Sample project COW
mercadopago/devsite-docs pull request #1014
Opened 2021-01-11 19:31 UTC by lamaralmp

## Description
Sumamos el [proyecto de ejemplo de COW](http://github.com/mercadopago/checkout-payment-sample) a la docu. Con nota introdutória y card de GitHub

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-01-11 19:52 UTC, abderossi approved these changes

2021-01-12 13:27 UTC, pamalv7 requested changes

2021-01-12 13:27 UTC, pamalv7 commented on guides/online-payments/checkout-pro/integration.es.md
> +> Te dejamos <a href="http://github.com/mercadopago/checkout-payment-sample" target="_blank">ejemplos completos de integración</a> en GitHub para PHP o NodeJS para que puedas descargar al instante.
```suggestion
> Te dejamos [ejemplos completos de integración](http://github.com/mercadopago/checkout-payment-sample) en GitHub para PHP o NodeJS para que puedas descargar al instante.
```

2021-01-12 13:27 UTC, pamalv7 commented on guides/online-payments/checkout-pro/integration.pt.md
> +> Disponibilizamos <a href="http://github.com/mercadopago/checkout-payment-sample" target="_blank">exemplos completos de integração</a> no GitHub para PHP ou NodeJS para que você possa fazer o downlo
```suggestion
> Disponibilizamos [exemplos completos de integração](http://github.com/mercadopago/checkout-payment-sample) no GitHub para PHP ou NodeJS para que você possa fazer o download imediatamente.
```

2021-01-12 13:27 UTC, pamalv7 commented on guides/online-payments/checkout-pro/integration.es.md
> +La integración del Checkout Pro de Mercado Pago te permite cobrar a través de nuestro formulario web desde cualquier dispositivo de manera simple, rápida y segura.
```suggestion
Integrar el Checkout Pro de Mercado Pago te permite cobrar a través de nuestro formulario web desde cualquier dispositivo de manera simple, rápida y segura.
```

2021-01-12 13:27 UTC, pamalv7 commented on guides/online-payments/checkout-pro/integration.pt.md
> +A integração por Checkout Pro do Mercado Pago te permite cobrar através do nosso formulário web de qualquer dispositivo de forma simples, rápida e segura.
```suggestion
Integrar Checkout Pro do Mercado Pago te permite cobrar através do nosso formulário web de qualquer dispositivo de forma simples, rápida e segura.
```

2021-01-12 13:27 UTC, pamalv7 commented on guides/online-payments/checkout-pro/integration.en.md
> +Integrating Mercado Pago's Checkout Pro allows you to charge your customers through our web form from any device in a simple, fast and secure way.
```suggestion
Integrate Mercado Pago's Checkout Pro allows you to charge your customers through our web form from any device in a simple, fast and secure way.
```

2021-01-12 14:55 UTC, abderossi approved these changes

2021-01-19 13:28 UTC, pamalv7 requested changes

2021-01-19 13:28 UTC, pamalv7 commented on guides/online-payments/checkout-pro/integration.es.md
> +Usa los [ejemplos descargables](#bookmark_ejemplos_descargables) para conocer la integración completa o para adaptarlos según lo que necesites.
```suggestion

Usa los [ejemplos descargables](#bookmark_ejemplos_descargables) para conocer la integración completa o para adaptarlos según lo que necesites.
```

2021-01-19 13:28 UTC, pamalv7 commented on guides/online-payments/checkout-pro/integration.pt.md
> +Use os [exemplos para download](#bookmark_exemplos_para_download) para conhecer a integração completa ou para adaptá-los de acordo com o que precisa.
```suggestion

Use os [exemplos para download](#bookmark_exemplos_para_download) para conhecer a integração completa ou para adaptá-los de acordo com o que precisa.
```

2021-01-19 15:06 UTC, abderossi approved these changes
Estoy de acuerdo con el comentario de agregar un espacio que hizo @pamalv7

2021-01-19 16:57 UTC, pamalv7 approved these changes

2021-01-19 20:34 UTC, merged