Feature/cambios q rdesatendido
mercadopago/devsite-docs pull request #1030
Opened 2021-01-19 15:18 UTC by juanseferrari2

## Description
Realizados algunos cambios en la documentacion del modelo desatendido.
Sacamos algunos valores que generaban errores en la App. Ordenamos las nomenclaturas.
Agregamos tambien un aviso de la API que no permite generar cajas sin sucursales asignadas. Dicen de agregarlo al Changelog? o como un aviso?

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-01-25 16:34 UTC, lamaralmp approved these changes

2021-01-25 16:38 UTC, lamaralmp commented
@juanseferrari2 sumé un par de ajustes de markdown y traducciones. Podrías validarlos?

2021-01-27 10:59 UTC, pamalv7 requested changes

2021-01-27 10:59 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.es.md
> +> A partir del 20 de Abril del 2021, no se podrán crear cajas sin una sucursal asignada.
```suggestion
> A partir del 20 de abril de 2021, no se podrán crear cajas sin una sucursal asignada. 
```

2021-01-27 10:59 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.en.md
> +> As of April 20, 2021, Point of sales can not be created without an assigned store.
```suggestion
> After April 20th, 2021, Point of Sales can not be created without an assigned store.
```

2021-01-27 10:59 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.en.md
> +> IMPORTANT
```suggestion
> Important
```

2021-01-27 10:59 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.es.md
> +> IMPORTANTE
```suggestion
> Importante
```

2021-01-27 10:59 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.pt.md
> +> IMPORTANTE
```suggestion
> Importante
```

2021-01-27 11:02 UTC, pamalv7 approved these changes

2021-01-27 12:15 UTC, merged