New version of Prestashop
mercadopago/devsite-docs pull request #1031
Opened 2021-01-20 14:54 UTC by katelucena-meli

## Description
New version of Prestashop

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [x] Requires translations.

2021-01-21 18:49 UTC, abderossi approved these changes

2021-01-27 11:11 UTC, pamalv7 requested changes

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +We have released the new version 4.4.2 for Prestashop.
```suggestion
We have released the new version 4.4.2 for PrestaShop.
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +[Go to Prestashop documentation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/prestashop/introduction)
```suggestion
[Go to PrestaShop documentation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/prestashop/introduction)
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> New Prestashop plugin version
```suggestion
> New PrestaShop plugin version
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +[Go to Prestashop documentation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/prestashop/introduction)
```suggestion
[Go to PrestaShop documentation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/prestashop/introduction)
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> Nueva versión Prestashop
```suggestion
> Nueva versión PrestaShop
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +[Ir a documentación de Prestashop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/prestashop/introduction)
```suggestion
[Ir a documentación de PrestaShop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/prestashop/introduction)
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +Lanzamos la nueva versión 4.4.2 para Prestashop.
```suggestion
Lanzamos la nueva versión 4.4.2 para PrestaShop.
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> Nueva versión Prestashop
```suggestion
> Nueva versión PrestaShop
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +[Ir a documentación de Prestashop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/prestashop/introduction)
```suggestion
[Ir a documentación de PrestaShop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/prestashop/introduction)
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +> Nova versão Prestashop
```suggestion
> Nova versão PrestaShop
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +Lançamos a nova versão 4.4.2 para Prestashop.
```suggestion
Lançamos a nova versão 4.4.2 para PrestaShop.
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +[Ir para a documentação de Prestashop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/prestashop/introduction)
```suggestion
[Ir para a documentação de PrestaShop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/prestashop/introduction)
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +Lançamos a nova versão 4.4.1 para Prestashop.
```suggestion
Lançamos a nova versão 4.4.1 para PrestaShop.
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +> Nova versão Prestashop
```suggestion
> Nova versão PrestaShop
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +[Ir para a documentação de Prestashop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/prestashop/introduction)
```suggestion
[Ir para a documentação de PrestaShop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/prestashop/introduction)
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> New Prestashop plugin version
```suggestion
> New PrestaShop plugin version
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +We have released the new version 4.4.1 for Prestashop.
```suggestion
We have released the new version 4.4.1 for PrestaShop.
```

2021-01-27 11:11 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +Lanzamos la nueva versión 4.4.1 para Prestashop.
```suggestion
Lanzamos la nueva versión 4.4.1 para PrestaShop.
```

2021-01-27 11:12 UTC, pamalv7 approved these changes

2021-01-27 12:15 UTC, merged