New version Prestashop 4.4.4
mercadopago/devsite-docs pull request #1043
Opened 2021-01-28 13:48 UTC by lira

## Description
New version of Mercado Pago Prestashop Module, version 4.4.4, with bug fixes.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [X] New features were communicated in changelog.
- [ ] Requires translations.

2021-01-28 14:57 UTC, pamalv7 requested changes

2021-01-28 14:57 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +We have released the new version 4.4.4 for PrestaShop.
```suggestion

We have released the new version 4.4.4 for PrestaShop.
```

2021-01-28 14:57 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +Lanzamos la nueva versión 4.4.4 para PrestaShop.
```suggestion

Lanzamos la nueva versión 4.4.4 para PrestaShop.
```

2021-01-28 14:57 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +Lançamos a nova versão 4.4.4 para PrestaShop.
```suggestion

Lançamos a nova versão 4.4.4 para PrestaShop.
```

2021-01-28 14:57 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> [Check GitHub](https://github.com/mercadopago/cart-prestashop-7/releases/tag/v4.4.4) fo
```suggestion
> [Check GitHub](https://github.com/mercadopago/cart-prestashop-7/releases/tag/v4.4.4) for further details regarding this release.
```

2021-01-28 14:57 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +### January 28nd
```suggestion
### January 28th
```

2021-01-28 19:18 UTC, abderossi approved these changes

2021-02-03 19:26 UTC, pamalv7 approved these changes

2021-02-03 19:46 UTC, merged