add note for device id management
mercadopago/devsite-docs pull request #1045
Opened 2021-02-01 23:25 UTC by diemartinezmeli

## Description
Se incorpora nota para comentar el uso de codigo de seguriad en la integracion de suscripciones. La misma se aplica en ES, EN y PT.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-02-02 18:26 UTC, abderossi commented on guides/online-payments/subscriptions/integration.es.md
> +> Con el código de seguridad, podrás proteger aún más tu sitio y obtener más pagos aprobados. Él te ayudará a prevenir el fraude y los pagos rechazados sin justificación.
> Con el código de seguridad, podrás proteger aún más tu sitio y obtener más pagos aprobados. **Este** te ayudará a prevenir el fraude y los pagos rechazados sin justificación.

2021-02-02 18:32 UTC, diemartinezmeli commented on guides/online-payments/subscriptions/integration.es.md
> +> Con el código de seguridad, podrás proteger aún más tu sitio y obtener más pagos aprobados. Él te ayudará a prevenir el fraude y los pagos rechazados sin justificación.
Hola @abderossi, ya esta subido el ajuste.

2021-02-03 19:38 UTC, pamalv7 requested changes

2021-02-03 19:38 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +>
```suggestion
```

2021-02-03 19:38 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +> Con el código de seguridad, podrás proteger aún más tu sitio y obtener más pagos aprobados. Este te ayudará a prevenir el fraude y los pagos rechazados sin justificación.
```suggestion
> Con el código de seguridad, podrás proteger aún más tu sitio y obtener más pagos aprobados. Este te ayudará a prevenir el fraude y los pagos rechazados sin justificación.<br><br>
```

2021-02-03 19:38 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +>
```suggestion
```

2021-02-03 19:38 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.pt.md
> +>
```suggestion
```

2021-02-03 19:38 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +> ¡Es fácil! [Agrega el código](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/account/payment-rejections#bookmark_recomendaciones_para_mejorar_tu_aprobacion) en simp
```suggestion
> ¡Es fácil! [Agrega el código](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/account/payment-rejections#bookmark_recomendaciones_para_mejorar_tu_aprobación) en simples pasos.
```

2021-02-03 19:42 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +> It's simple! [Add the code in easy steps](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/account/payment-rejections#bookmark_tips_to_improve_the_approval_process).
```suggestion
> It's simple! [Add the code](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/account/payment-rejections#bookmark_tips_to_improve_the_approval_process) in easy steps.
```

2021-02-03 19:43 UTC, pamalv7 approved these changes

2021-02-03 19:47 UTC, abderossi approved these changes

2021-02-03 19:51 UTC, merged