Se agrego curl para  point via API
mercadopago/devsite-docs pull request #1050
Opened 2021-02-08 18:46 UTC by SofiaMoralesGonzalez1992

## Description
Actualizamos los pasos para integrar  Point via API agregando el curl asi evitamos el contacto de support.

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [X] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-02-09 17:55 UTC, abderossi commented on guides/in-person-payments/mp-point/how-to-integrate.en.md
> +for
Eliminar

2021-02-09 17:56 UTC, abderossi commented on guides/in-person-payments/mp-point/how-to-integrate.en.md
> +for
Eliminar

2021-02-09 18:38 UTC, abderossi requested changes

2021-02-09 18:38 UTC, abderossi commented on guides/in-person-payments/mp-point/how-to-integrate.es.md
> +Para poder integrarte, tienes que habilitar las opciones de itegraciones  en la app de Mercado Pago. Ejecuta el siguiente curl para realizarlo:
- Hay un espacio extra luego de integraciones. 
- Falta la n en i**n**tegraciones

2021-02-09 18:38 UTC, abderossi commented on guides/in-person-payments/mp-point/how-to-integrate.es.md
> +```curl
El snippet no se visualiza correctamente. En español sí. 
![Captura de Pantalla 2021-02-09 a la(s) 15 11 01](https://user-images.githubusercontent.com/76011700/107407943-10fef280-6ae9-11eb-8900-1381319a8660.png)

2021-02-09 18:38 UTC, abderossi commented on guides/in-person-payments/mp-point/how-to-integrate.pt.md
> +`` `curl
El snippet no se visualiza correctamente 
![Captura de Pantalla 2021-02-09 a la(s) 15 10 52](https://user-images.githubusercontent.com/76011700/107408033-296f0d00-6ae9-11eb-99ee-abb03b19e417.png)

2021-02-09 20:12 UTC, abderossi approved these changes

2021-02-10 13:04 UTC, pamalv7 approved these changes

2021-02-11 01:02 UTC, merged