add trava recibibles description to account-money report
mercadopago/devsite-docs pull request #1052
Opened 2021-02-08 20:04 UTC by sanchezmauri

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-02-09 16:08 UTC, Matuteale commented on guides/manage-account/reports/account-money/glossary.en.md
> +| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Transaction type. It can
[q] - Se muestra sólo para Brasil, no? .com.br

2021-02-09 17:35 UTC, sanchezmauri commented on guides/manage-account/reports/account-money/glossary.en.md
> +| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Transaction type. It can
Tengo entendido que vos podes estar en `MLB` y tener la traducción en inglés, por eso también lo aplique en `.en` y en `.es`.

2021-02-09 18:44 UTC, Matuteale commented on guides/manage-account/reports/account-money/glossary.en.md
> +| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Transaction type. It can
Claro, pero también se puede filtrar por Site, es decir, para el site MLB tiene que estar en español, inglés y portugués. Para los demás sites, no tiene que aparecer.

2021-02-10 12:49 UTC, Matuteale approved these changes
Aprobado

2021-02-17 20:06 UTC, abderossi approved these changes

2021-02-18 14:13 UTC, pamalv7 requested changes

2021-02-18 14:13 UTC, pamalv7 commented on guides/manage-account/reports/account-money/glossary.en.md
> +| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Transaction type. It can
```suggestion
| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Transaction type. It can be:<br/><ul><li> *SETTLEMENT*: Approved payment. </li><li> *REFUND*: Payment returned in whole or in part. </li><li> *CHARGEBACK*: The buyer made a chargeback (unrecognized payment) on his credit card. </li><li> *DISPUTE*: The buyer initiated a claim for that payment. </li><li> *WITHDRAWAL*: Withdrawal to a bank account. </li><li> *WITHDRAWAL_CANCEL*: Canceled withdrawal to a bank account. </li><li>*PAYOUT*: Money withdrawal available at Mercado Pago.</li> ----[mlb]----  <br>*TRAVA_DE_RECEBIVEL*: Block receivable. ------------ </ul></td></tr></table> |
```

2021-02-18 14:13 UTC, pamalv7 commented on guides/manage-account/reports/account-money/glossary.es.md
> +| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Tipo de operación. Puede
```suggestion
| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Tipo de operación. Puede ser:<br/><ul><li> *SETTLEMENT*: Pago aprobado.</li><li>*REFUND*: Pago devuelto total o parcialmente.</li><li>*CHARGEBACK*: El comprador hizo un contracargo (desconocimiento del pago) en su tarjeta de crédito.</li><li>*DISPUTE*: El comprador inició un reclamo por ese pago.</li><li>*WITHDRAWAL*: Retiro a la cuenta bancaria.</li><li>*WITHDRAWAL_CANCEL*: Retiro a la cuenta bancaria que fue cancelado.</li><li>*PAYOUT*: Extracción en efectivo de dinero disponible en Mercado Pago.</li> ----[mlb]----  <br>*TRAVA_DE_RECEBIVEL*: Bloqueo por cobrar. ------------ </ul></td></tr></table> |
```

2021-02-18 14:13 UTC, pamalv7 commented on guides/manage-account/reports/account-money/glossary.pt.md
> +| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Tipo de operação. Pode s
```suggestion
| TRANSACTION_TYPE | <table style="border:none;background:none;font-size:16px;height:auto" ><tr style="border:none;background:none;"><td style="border:none;background:none;"> Tipo de operação. Pode ser:<br/><ul><li> *SETTLEMENT*: Pagamento aprovado.</li><li>*REFUND*: Pagamento devolvido total ou parcial.</li><li>*CHARGEBACK*: O comprador fez uma contestação (desconhece o pagamento) no seu cartão de crédito.</li><li>*DISPUTE*: O comprador iniciou uma reclamação por esse pagamento.</li><li>*WITHDRAWAL*: Retirada para a conta bancária.</li><li>*WITHDRAWAL_CANCEL*: Retirada para a conta bancária que foi cancelada.</li><li>*PAYOUT*: Saque em dinheiro disponível no Mercado Pago.</li> ----[mlb]---- <br>*TRAVA_DE_RECEBIVEL*: Trava de recebível. ------------ </ul></td></tr></table> |
```

2021-02-18 16:59 UTC, pamalv7 approved these changes

2021-02-18 19:08 UTC, merged