Feature/magento 2 update composer doc
mercadopago/devsite-docs pull request #1061
Opened 2021-02-17 17:18 UTC by lira

## Description

Updated the way to install the Magento 2 plugin, version 3 has been the default for some time. 🆙 

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [X] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-02-17 19:02 UTC, abderossi approved these changes

2021-02-17 21:06 UTC, mminestrelli commented on guides/plugins/official/magento-two.es.md
> +1) Ejecutar el comando para descargar el plugin via Composer:
```suggestion
1) Ejecutar el comando para descargar el plugin vía Composer: 
```

2021-02-18 12:50 UTC, pamalv7 requested changes

2021-02-18 12:50 UTC, pamalv7 commented on guides/plugins/official/magento-two.es.md
> +1) Ejecutar el comando para descargar el plugin vía Composer:
```suggestion
1) Ejecutar el comando para descargar el plugin vía Composer: 
```
```suggestion
1) Ejecutar el comando para descargar el plugin con Composer: 
```
Consistencia con inglés

2021-02-18 12:50 UTC, pamalv7 commented on guides/plugins/official/magento-two.pt.md
> +1) Execute o comando para baixar o plugin via Composer:
```suggestion
1) Execute o comando para baixar o plugin com Composer:
```
Consistencia con inglés.

2021-02-18 15:31 UTC, pamalv7 approved these changes

2021-02-18 19:25 UTC, merged