fix/atualizacao-lojaintegrada-q1
mercadopago/devsite-docs pull request #1066
Opened 2021-02-19 15:49 UTC by douglas-cruz

Olá Pessoal

Estamos criando esta PR com o intuito de deixarmos a mesma experiência junto a Loja Integrada com o DevSite do Mercado Pago.
Onde a Loja Integrada alterou o nome do botão em seu painel de “Instalar aplicativo do Mercado Pago” para "Sincronizar conta do Mercado Pago”

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-02-22 19:27 UTC, abderossi requested changes

2021-02-22 19:27 UTC, abderossi commented on guides/plugins/unofficial/lojaintegrada.es.md
> +Para **sincroniza tu cuenta de Mercado Pago a Loja Integrada**, sigue estos pasos:
```suggestion
Para **sincronizar tu cuenta de Mercado Pago a Loja Integrada**, sigue estos pasos:
```

2021-02-22 19:27 UTC, abderossi commented on guides/plugins/unofficial/lojaintegrada.es.md
> +¡Y listo! Mercado Pago ya está sincronizada en tu tienda y puedes empezar a cobrar.
```suggestion
¡Y listo! Mercado Pago ya está sincronizado en tu tienda para que empieces a cobrar.
```

2021-02-22 19:27 UTC, abderossi commented on guides/plugins/unofficial/lojaintegrada.es.md
> +> Si quieres cambiar la cuenta de Mercado Pago asociada a tu sitio, es necesario cerrar y sincronizar usando la nueva cuenta.
```suggestion
> Si quieres cambiar la cuenta de Mercado Pago asociada a tu sitio, es necesario salir de la cuenta activa y volver a sincronizar usando la nueva cuenta.
```

2021-02-22 19:27 UTC, abderossi commented on guides/plugins/unofficial/lojaintegrada.pt.md
> +> Se quiser alterar a conta do Mercado Pago do seu site, é necessário sair e sincronizar utilizando a nova conta.
```suggestion
> Se quiser alterar a conta do Mercado Pago do seu site, é necessário sair da conta ativa e sincronizar utilizando a nova conta.
```

2021-02-22 19:27 UTC, abderossi commented on guides/plugins/unofficial/lojaintegrada.en.md
> +Done! Mercado Pago account is Synchronize on your site and you can start charging.
```suggestion
Done! Mercado Pago account is synchronized with your site and you can start charging.
```

2021-02-22 19:27 UTC, abderossi commented on guides/plugins/unofficial/lojaintegrada.en.md
> +> If you wish to change the Mercado Pago account associated to your site, it is necessary to close and Synchronize the new account.
```suggestion
> If you wish to change the Mercado Pago account associated to your site, it is necessary to close the active account and synchronize again using the new account.
```

2021-02-22 21:59 UTC, elvisjhonataoliveira approved these changes

2021-02-23 14:19 UTC, abderossi approved these changes

2021-02-23 19:30 UTC, merged