[Feature] Add pix offline payment
mercadopago/devsite-docs pull request #1072
Opened 2021-02-25 17:52 UTC by SilvinaMorato

## Description

- Se agrego a PIX como medio de Pago, para Brasil unicamente, en Checkout API en la sección Otros medios de Pagos. 
- Se agregaron las traducciones de este nuevo contenido 
- Se agrego contenido en la sección Resources - Changelog y Localización

Dejo el [brief](https://docs.google.com/document/d/16YDGULCgBgubFF0IHKyC_JGABW5ukFNIaCXYybRcKZM/edit?ts=6022bad6#heading=h.7zlc4p88uqim) con el contenido que se genero y las traducciones [ingles](https://docs.google.com/document/d/1IpDuP_sOWci7efdgaG16oQ2EuvX5sAh2/edit) y [portugues](https://docs.google.com/document/d/1Q_wM8YWJFqQungnmEX11NSsdO1e7YT6B/edit#)

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [X] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-02-26 19:22 UTC, abderossi requested changes

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
A data usa o formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-02-26 19:22 UTC, abderossi commented on guides/resources/changelog/current-year.en.md
> +### March 04th
```suggestion
### March 4th
```

2021-02-26 19:22 UTC, abderossi commented on guides/resources/changelog/current-year.es.md
> +### 04 de Marzo
```suggestion
### 4 de marzo
```

2021-02-26 19:22 UTC, abderossi commented on guides/resources/changelog/current-year.pt.md
> +### 04 de Marzo
```suggestion
### 4 de março
```

2021-02-26 19:22 UTC, abderossi commented on guides/resources/changelog/current-year.pt.md
> +Agora, você pode adicionar Pix como meio de pagamento para começar a receber dinheiro no instante, todos os dias e de qualquer banco ou carteira. Você só deve ter sua chave e adicionar Pix no seu for
```suggestion
Agora, você pode adicionar Pix como meio de pagamento para começar a receber dinheiro no instante, todos os dias e de qualquer banco ou carteira. Você só deve ter sua chave e adicionar Pix no seu formulário de pagamento.
```

2021-03-01 20:42 UTC, abderossi approved these changes

2021-03-03 12:55 UTC, nicolassalvanes requested changes

2021-03-03 12:55 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +<label for="cvv">Copiar Hash:</label>
Acá debería ser for="copiar"

2021-03-03 12:55 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +            "application_data": {
Podemos mejorar la identacion de este json? Varios atributos dentro de application_data no están bien identados

2021-03-03 18:41 UTC, plovera commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +       .setDescription('Título do produto')
@SilvinaMorato, aquí podríamos poner comillas "" como los demás campos ?

2021-03-03 18:50 UTC, pamalv7 requested changes
@SilvinaMorato una vez que veamos estos cambios, pruebo de nuevo. 
Revisemos los datos falsos de los snippets para unificarlos.

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +        "external_resource_url": "https://www.mercadopago.com/mla/payments/ticket/helper?payment_id=123456789&payment_method_reference_id= 123456789&caller_id=123456",
¿Puede ser que esto sea un dato real? ¿Es correcto que diga `/mla`?

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +O resultado será uma lista com os meios de pagamento e suas propriedades. Por exemplo, os meios de pagamento do `payment_type_id` que tenham como valor `ticket` se referem aos meios de pagamento em d
```suggestion
O resultado será uma lista com os meios de pagamento e suas propriedades. Por exemplo, os meios de pagamento do `payment_type_id` que tenham como valor `ticket` se referem aos meios de pagamento em dinheiro e as de `bank_transfer` para transferências bancárias.
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +Luego de [capturar los datos](#bookmark_capture_os_dados_para_pagamento) con el formulario, para receber pagamentos em boleto ou pagamento em lotérica envie o e-mail e documento do seu cliente e a mé
```suggestion
Após [capturar os dados](#bookmark_capture_os_dados_para_pagamento) com o formulário, con el formulario, para receber pagamentos em boleto ou pagamento em lotérica envie o e-mail e documento do seu cliente e a método de pagamento e detalhe do valor.
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +[Conheça como criar uma chave Pix](https://www.mercadopago[FAKER][URL][DOMAIN]/ajuda/17843)
```suggestion
[Conheça como criar uma chave Pix](https://www.mercadopago.com.br/ajuda/17843)
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +| `qr_code` | Dato para armar un botón que permitirá copiar y pegar el código.|
```suggestion
| `qr_code` | Dato para armar un código de pago para copiar y pegar. |
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +                "qr_code": "00020126600014br.gov.bcb.pix0117test@testuser.com0217datos adicionales520400005303986540510.005802BR5913Maria Silva6008Brasilia62070503***6304E2CA",
```suggestion
                "qr_code": "00020126600014br.gov.bcb.pix0117test@testuser.com0217dados adicionais520400005303986540510.005802BR5913Maria Silva6008Brasilia62070503***6304E2CA",
```
¿Les parece quitar el nombre y dejar Test User y la ciudad de ejemplo en snipets?

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +You can receive immediate payment with Pix from any bank or digital wallet using QR or payment code.
```suggestion
You can receive payment immediately with Pix from any bank or digital wallet using QR code or payment code.
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +To make the payment, render the QR code to show it. You can also add an option to copy&paste payment code to make the transaction via web home banking.
```suggestion
To make the payment, render the QR code to show it. You can also add an option to copy and paste payment code to make the transaction via Internet Banking. 
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +To show the payment code for copy&paste, you can add `qr_code` like this:
```suggestion
To show the payment code for copy and paste, you can add `qr_code` like this:
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Voucher payment
```suggestion
### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Boleto payments
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +## Payment date of expiration
```suggestion
## Payments date of expiration
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +La fecha usa el formato ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```suggestion
The date uses the format ISO 8601: yyyy-MM-dd'T'HH:mm:ssz
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +> Nota
```suggestion
> Ten en cuenta
```

2021-03-03 18:50 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +Após [capturar os dados](#bookmark_capture_os_dados_para_pagamento) com o formulário, para poder receber pagamentos com Pix, você deve encaminhar o e-mail do comprador, o tipo e número de carteira de
```suggestion
Após [capturar os dados](#bookmark_capture_os_dados_para_pagamento) com o formulário, para poder receber pagamentos com Pix, você deve encaminhar o e-mail do comprador, o tipo e número de documento, o meio de pagamento e o detalhe do valor.
```

2021-03-03 18:53 UTC, SilvinaMorato commented
@pamalv7  ahi subi unos cambios en los snippets, faltan tus sugerencias, eso calculo que las aplican ustedes y estamos ok

2021-03-04 12:28 UTC, nicolassalvanes commented
> @pamalv7 ahi subi unos cambios en los snippets, faltan tus sugerencias, eso calculo que las aplican ustedes y estamos ok

Hola Silvi! Las sugerencias las podés confirmar vos también, no hay problema.
Veo que falta el comment que hice sobre corregir un poco la identación del JSON de ejemplo de la respuesta, podemos ver eso?

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +The `transaction_data` will provide data to make the payment available via QR code. These are the attributes:
```suggestion
The `transaction_data` will provide the data to make the payment available via QR code. These are the attributes: 
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +
```suggestion
```

2021-03-04 17:19 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +### 04 de Marzo
```suggestion
### 4 de Marzo

```

2021-03-04 17:19 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +### 4 de março
```suggestion
### 4 de março

```

2021-03-04 17:38 UTC, pamalv7 approved these changes

2021-03-04 17:44 UTC, abderossi approved these changes

2021-03-04 20:00 UTC, nicolassalvanes approved these changes

2021-03-04 20:02 UTC, abderossi approved these changes

2021-03-04 20:23 UTC, merged