Points suscripciones
mercadopago/devsite-docs pull request #1074
Opened 2021-02-26 14:29 UTC by adfonseca

## Description
That PR is about a small fix, some points to a better understanding of the minimum amount, time to the first charge and subscription status after the reattempt.

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-02-26 15:51 UTC, juliseewald approved these changes

2021-02-26 16:06 UTC, juanmanuele approved these changes

2021-03-03 19:53 UTC, pamalv7 requested changes
@adfonseca, ¿vemos los comentarios?
Cualquier duda, me avisas.

2021-03-03 19:53 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +> Validation Payment
```suggestion
> Validation payment
```

2021-03-03 19:53 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +> Pago de Validación
```suggestion
> Pago de validación
```

2021-03-03 19:53 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +> Realizamos un pago de validación de monto mínimo, esto difiere según cada país, y si el pago es exitoso, procedemos a realizar la devolución de ese pago. Esto nos sirve como medida para resguardar
```suggestion
> Para comprobar que la tarjeta sea válida, realizamos un pago de validación con un monto mínimo. Si el pago es exitoso, procedemos a realizar la devolución de ese pago. El monto puede diferir según cada país. 
```
Dejo sugerencia de versión para simplificar el contenido. 
Quitaría lo de aclarar los montos mínimos: o se ponen para todos los sites o no aplica. 
Mismo comentarios para el resto de idiomas.

2021-03-03 19:53 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.es.md
> +Luego de 3 cuotas con pagos rechazados se da de baja automáticamente la suscripción y la cuenta integrada será notificada del cancelamiento de la suscripción por email.
Esto queda contradictorio con lo anterior. Si a las tercera cuota se da de baja la suscripción, ¿por qué tendríamos un cuarto intento?

2021-03-03 19:53 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.es.md
> +La primera cuota se cobra hasta el periodo aproximado de una hora de suscribirse.
```suggestion
Luego de suscribirse, el pago de la la primera cuota se acreditará en 1 hora.
```
Sugerencia

2021-03-03 21:40 UTC, adfonseca commented on guides/online-payments/subscriptions/payment-retry.es.md
> +Luego de 3 cuotas con pagos rechazados se da de baja automáticamente la suscripción y la cuenta integrada será notificada del cancelamiento de la suscripción por email.
El paragrafo anterior refere-se a los reintentos para se cobrar la cuota. El ultimo paragrafo se refiere a la cantidade de cuotas con pagos rechazados. Son cosas diferentes.

4 tentativas para se cobrar una cuota, si no hay sucesso genera una cuota con pago rechazado.

2021-03-03 21:46 UTC, adfonseca commented on guides/online-payments/subscriptions/integration.pt.md
> +> Efetuamos um pagamento de validação de um valor mínimo, que difere de acordo com cada país, e se o pagamento for bem sucedido, procedemos com o reembolso desse pagamento. Isso serve como uma medida
```suggestion
>Para comprovar que o cartão seja válido, realizamos um pagamento de validação com um valor mínimo. Se o pagamento obter sucesso, procedemos com a realização da devolução desse pagamento. O valor pode diferir conforme cada país.
```

2021-03-03 21:52 UTC, adfonseca commented on guides/online-payments/subscriptions/integration.en.md
> +> We make a validation payment of a minimum amount, this differs according to each country, and if the payment is successful, we proceed to make the refund of that payment. This serves as a measure t
```suggestion
> To prove that the card is valid, we make a validation payment with a minimum amount. If the payment is successful, we proceed with the return of that payment. The amount may differ according to each country.
```

2021-03-04 12:29 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.es.md
> +Luego de 3 cuotas con pagos rechazados se da de baja automáticamente la suscripción y la cuenta integrada será notificada del cancelamiento de la suscripción por email.
Clarísimo. Con "la cuenta integrada", ¿a quién nos referimos?

2021-03-04 12:55 UTC, adfonseca commented on guides/online-payments/subscriptions/payment-retry.es.md
> +Luego de 3 cuotas con pagos rechazados se da de baja automáticamente la suscripción y la cuenta integrada será notificada del cancelamiento de la suscripción por email.
a la cuenta del seller, que esta integrada con MP.

2021-03-04 17:41 UTC, pamalv7 requested changes

2021-03-04 17:41 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.es.md
> +Luego de 3 cuotas con pagos rechazados se da de baja automáticamente la suscripción y la cuenta integrada será notificada del cancelamiento de la suscripción por email.
```suggestion
Luego de 3 cuotas con pagos rechazados se da de baja automáticamente la suscripción y la cuenta del vendedor será notificada de la cancelación de la suscripción por e-mail.
```

2021-03-04 17:41 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.en.md
> +After 3 installments with rejected payments, the subscription is automatically canceled and the integrated account will be notified of the cancellation of the subscription by email.
```suggestion
After 3 installments with rejected payments, the subscription is automatically canceled and the integrated account will be notified of the cancellation of the subscription by e-mail.
```

2021-03-04 17:41 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +Após 3 parcelas com pagamentos recusados a assinatura será automaticamente cancelada e a conta integrada será notificada do cancelamento da assinatura por email.
```suggestion
Após 3 parcelas com pagamentos recusados a assinatura será automaticamente cancelada e a conta integrada será notificada do cancelamento da assinatura por e-mail.
```

2021-03-04 17:47 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.en.md
> +After 3 installments with rejected payments, the subscription is automatically canceled and the integrated account will be notified of the cancellation of the subscription by email.
```suggestion
After 3 installments with rejected payments, the subscription is automatically canceled and the seller account will be notified of the cancellation of the subscription by email.
```

2021-03-04 17:47 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.en.md
> +After 3 installments with rejected payments, the subscription is automatically canceled and the integrated account will be notified of the cancellation of the subscription by e-mail.
```suggestion
After 3 installments with rejected payments, the subscription is automatically canceled and the seller account will be notified of the cancellation of the subscription by e-mail.
```

2021-03-04 17:47 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +Após 3 parcelas com pagamentos recusados a assinatura será automaticamente cancelada e a conta integrada será notificada do cancelamento da assinatura por e-mail.
```suggestion
Após 3 parcelas com pagamentos recusados a assinatura será automaticamente cancelada e a conta do vendedor será notificada do cancelamento da assinatura por e-mail.
```

2021-03-04 17:47 UTC, pamalv7 approved these changes

2021-03-04 17:48 UTC, merged