Adding new versions of SDKs Java and .NET in the changelog
mercadopago/devsite-docs pull request #1075
Opened 2021-03-01 13:09 UTC by delias-silva

## Description
Adding new versions of SDKs Java and .NET in the changelog.

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-01 15:09 UTC, lamaralmp requested changes

2021-03-01 15:09 UTC, lamaralmp commented on guides/resources/changelog/current-year.es.md
> +## March 2021
```suggestion
## Marzo 2021
```

2021-03-01 15:09 UTC, lamaralmp commented on guides/resources/changelog/current-year.es.md
> +### March 4th
```suggestion
### 4 de marzo
```

2021-03-01 15:11 UTC, lamaralmp requested changes

2021-03-01 15:11 UTC, lamaralmp commented on guides/resources/changelog/current-year.pt.md
> +## March 2021
```suggestion
## Março 2021
```

2021-03-01 15:11 UTC, lamaralmp commented on guides/resources/changelog/current-year.pt.md
> +### March 4th
```suggestion
### 4 de março
```

2021-03-01 18:07 UTC, abderossi approved these changes

2021-03-01 19:39 UTC, lamaralmp approved these changes

2021-03-04 11:44 UTC, closed without merging

2021-03-04 11:44 UTC, lamaralmp commented
Adicionei as alterações no PR #1083