Agregado SHOP YPF
mercadopago/devsite-docs pull request #1076
Opened 2021-03-01 14:16 UTC by juanseferrari2

## Description
YPF ahora soporta productos de Shop, por lo que agregamos la documentación relacionada con esto. 

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-01 18:58 UTC, abderossi requested changes
Hola! Dejé una sugerencia simple en una oración. De esta nueva manera evitamos hablar desde la negativa. Gracias!

2021-03-01 18:58 UTC, abderossi commented on guides/in-person-payments/qr-code/qr-unattended/qr-unattended-loyalty.es.md
> +4. El `transaction_id` debe ser único no solo para cada integrador, sino en todo el universo de operaciones de fidelización. Recomendamos concatenarlo con el `store_id` y la cara del surtidor.
```suggestion
4. El `transaction_id` debe ser único tanto para cada integrador como para todo el universo de operaciones de fidelización. Recomendamos concatenarlo con el `store_id` y la cara del surtidor.
```

2021-03-01 19:26 UTC, lamaralmp approved these changes

2021-03-01 19:43 UTC, abderossi approved these changes

2021-03-04 12:37 UTC, pamalv7 commented on guides/in-person-payments/qr-code/qr-unattended/qr-unattended-loyalty.es.md
> +2. Para productos *Shop*, se hace el cálculo de `quantity` multiplicado por `unit_price` para calcular los puntos a cargar. Es por esto que debe ponerse el número de código de *Shop*, `quantity = 1`
```suggestion
2. Para Producto shop, se hace el cálculo de `quantity` multiplicado por `unit_price` para calcular los puntos a cargar. Es por esto que debe ponerse el número de código de shop, `quantity = 1` y `unit_price` = monto total de los productos vendidos en shop.
```

2021-03-04 12:37 UTC, pamalv7 commented on guides/in-person-payments/qr-code/qr-unattended/qr-unattended-loyalty.es.md
> +2. Para productos *Shop*, se hace el cálculo de `quantity` multiplicado por `unit_price` para calcular los puntos a cargar. Es por esto que debe ponerse el número de código de *Shop*, `quantity = 1`
@juanseferrari2  ¿Damos por hecho que entienden que es "Producto Shop"?

2021-03-04 12:37 UTC, pamalv7 commented on guides/in-person-payments/qr-code/qr-unattended/qr-unattended-loyalty.es.md
> +3. La cantidad de puntos que se suman para combustibles, depende del código de producto (`code`) y la cantidad (`quantity`), validando la unidad en cuestión (`unit`). Cada producto suma una cantidad
```suggestion
3. La cantidad de puntos que se suman para combustibles depende del código de producto (`code`) y la cantidad (`quantity`), validando la unidad (`unit`). Cada producto suma una cantidad distinta en base a la cantidad cargada. Esta lógica la aplica directamente el programa de fidelización.
```

2021-03-04 14:27 UTC, juanseferrari2 commented on guides/in-person-payments/qr-code/qr-unattended/qr-unattended-loyalty.es.md
> +2. Para productos *Shop*, se hace el cálculo de `quantity` multiplicado por `unit_price` para calcular los puntos a cargar. Es por esto que debe ponerse el número de código de *Shop*, `quantity = 1`
mmm asumo que todos los integradores entienden que es producto Shop. Muchos lo tienen en YPF, asumo que deberian saberlo.

2021-03-04 15:11 UTC, pamalv7 approved these changes

2021-03-04 17:19 UTC, merged