Release/1.4.0 shopify cho
mercadopago/devsite-docs pull request #1077
Opened 2021-03-02 12:50 UTC by daniellferreira

## Description
Added discounts feature.

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [X] New features were communicated in changelog.
- [X] Requires translations.

2021-03-02 16:26 UTC, lamaralmp approved these changes

2021-03-03 14:51 UTC, abderossi requested changes
Realicé un pequeño ajuste en la versión en español para alinear el estilo a las descripciones que ya se encuentran en producción.

2021-03-03 14:51 UTC, abderossi commented on guides/plugins/official/shopify.es.md
> +| Descuentos | Ofrezca promociones a tus clientes creando cupones y descuentos automáticos. |
```suggestion
| Descuentos | Ofrece promociones a tus clientes creando cupones y descuentos automáticos. |
```

2021-03-03 15:02 UTC, abderossi approved these changes

2021-03-04 12:40 UTC, pamalv7 approved these changes

2021-03-04 17:19 UTC, merged