Iteraciones en Requisitos Previos en base a Overview
mercadopago/devsite-docs pull request #1084
Opened 2021-03-04 20:26 UTC by abderossi

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-09 16:47 UTC, pamalv7 requested changes

2021-03-09 16:47 UTC, pamalv7 commented on guides/in-person-payments/qr-code/pre-requisites.es.md
> +Puedes [Ingresar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview) a una cuenta de M
```suggestion

Puedes [Ingresar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/in-person-payments/qr-code/pre-requisites) a una cuenta de Mercado Pago o de Mercado Libre que ya exista o [Crear una cuenta nueva](https://www.mercadopago[FAKER][URL][DOMAIN]) en Mercado Pago.
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/in-person-payments/qr-code/pre-requisites.pt.md
> +Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview) uma conta existe
```suggestion

Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-person-payments/qr-code/pre-requisites) uma conta existente no Mercado Pago ou no Mercado Livre ou [Criar uma nova conta](https://www.mercadopago[FAKER][URL][DOMAIN]) no Mercado Pago.
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +### 2.  Instale do SDK do Mercado Pago
```suggestion
### 2. Instale do SDK do Mercado Pago
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/online-payments/checkout-pro/previous-requirements.en.md
> +You can [Sign in](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview) an existing Merca
```suggestion

You can [Sign in](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-pro/previous-requirements) an existing Mercado Pago or Mercado Libre account or [Create a new account](https://www.mercadopago[FAKER][URL][DOMAIN]) at Mercado Pago.
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/online-payments/checkout-pro/previous-requirements.es.md
> +Puedes [Ingresar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview) a una cuenta de M
```suggestion

Puedes [Ingresar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-pro/previous-requirements) a una cuenta de Mercado Pago o de Mercado Libre que ya exista o [Crear una cuenta nueva](https://www.mercadopago[FAKER][URL][DOMAIN]) en Mercado Pago.
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview) uma conta existe
```suggestion

Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/previous-requirements) uma conta existente no Mercado Pago ou no Mercado Livre ou [Criar uma nova conta](https://www.mercadopago[FAKER][URL][DOMAIN]) no Mercado Pago.
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.en.md
> +You can [Sign in](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview) an existing Merca
```suggestion
You can [Sign in](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/previous-requirements) an existing Mercado Pago or Mercado Libre account [Create a new account](https://www.mercadopago[FAKER][URL][DOMAIN]) at Mercado Pago.
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.es.md
> +Puedes [Ingresar]([https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview](https://www.merc
```suggestion
Puedes [Ingresar]([https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview](https://www.mercadolibre.com/jms/%5BFAKER%5D%5BGLOBALIZE%5D%5BSITE_ID%5D/lgz/login?platform_id=mp&go=https://www.mercadopago%5BFAKER%5D%5BURL%5D%5BDOMAIN%5D/developers/es/guides/online-payments/subscriptions/previous-requirements) a una cuenta de Mercado Pago o de Mercado Libre que ya exista o [Crear una cuenta nueva](https://www.mercadopago[FAKER][URL][DOMAIN]) en Mercado Pago.
```

2021-03-09 16:47 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.pt.md
> +Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/overview) uma conta existe
```suggestion
Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/previous-requirements) uma conta existente no Mercado Pago ou no Mercado Livre ou [Criar uma nova conta](https://www.mercadopago[FAKER][URL][DOMAIN]) no Mercado Pago.
```

2021-03-09 20:26 UTC, pamalv7 commented on guides/in-person-payments/qr-code/pre-requisites.pt.md
> +
```suggestion
```

2021-03-09 20:28 UTC, pamalv7 approved these changes

2021-03-09 20:36 UTC, lamaralmp commented on guides/in-person-payments/qr-code/pre-requisites.pt.md
> +Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-person-payments/qr-code
```suggestion
Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-person-payments/qr-code/pre-requisites) em uma conta existente no Mercado Pago ou no Mercado Livre ou [Criar uma nova conta](https://www.mercadopago[FAKER][URL][DOMAIN]) no Mercado Pago.
```

2021-03-09 20:36 UTC, lamaralmp commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-p
```suggestion
Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/previous-requirements) em uma conta existente no Mercado Pago ou no Mercado Livre ou [Criar uma nova conta](https://www.mercadopago[FAKER][URL][DOMAIN]) no Mercado Pago.
```

2021-03-09 20:36 UTC, lamaralmp commented on guides/online-payments/subscriptions/previous-requirements.pt.md
> +Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscripti
```suggestion
Você pode [Entrar](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/previous-requirements) em uma conta existente no Mercado Pago ou no Mercado Livre ou [Criar uma nova conta](https://www.mercadopago[FAKER][URL][DOMAIN]) no Mercado Pago.
```

2021-03-10 14:48 UTC, pamalv7 requested changes

2021-03-10 14:48 UTC, pamalv7 commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +**### 3. Obtenha suas credenciais**
```suggestion
### 3. Obtenha suas credenciais
```
¿Por qué le sumamos negritas? Por lo que recuerdo no funcionan con la nueva lib en los títulos.

2021-03-10 17:06 UTC, lamaralmp approved these changes

2021-03-11 15:17 UTC, pamalv7 approved these changes

2021-03-11 15:21 UTC, merged