Updating .NET SDK snippets
mercadopago/devsite-docs pull request #1090
Opened 2021-03-09 19:13 UTC by delias-silva

Update of the .NET SDK snippets to be compatible with the new version 2.0.0 of the SDK.

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-12 15:25 UTC, nicolassalvanes requested changes
Buen trabajo @delias-silva ! 💪  Dejé algunos comentarios y sugerencias, si algo no se entiende por favor me avisas.

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.en.md
>          Number = "12345678"
```suggestion
        Number = "12345678",
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.en.md
>          Number = "949 128 866"
```suggestion
        Number = "949 128 866",
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.es.md
>          Number = "949 128 866"
```suggestion
        Number = "949 128 866",
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.es.md
>          Number = "12345678"
```suggestion
        Number = "12345678",
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +        Number = "949 128 866"
```suggestion
        Number = "949 128 866",
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +        Number = "12345678"
```suggestion
        Number = "12345678",
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/shipments.en.md
> +            UnitPrice = [FAKER][COMMERCE][PRICE]m,
Excelente esto! Buen ojo! 😄

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.en.md
> +ResourcesList<CustomerCard> results = await customerClient.ListCardsAsync("CUSTOMER_ID");
```suggestion
ResourcesList<CustomerCard> customerCards = await customerClient.ListCardsAsync("CUSTOMER_ID");
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.en.md
> +ResourcesList<CustomerCard> results = await customerClient.ListCardsAsync("CUSTOMER_ID");
```suggestion
ResourcesList<CustomerCard> customerCards = await customerClient.ListCardsAsync("CUSTOMER_ID");
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +ResourcesList<CustomerCard> results = await customerClient.ListCardsAsync("CUSTOMER_ID");
```suggestion
ResourcesList<CustomerCard> customerCards = await customerClient.ListCardsAsync("CUSTOMER_ID");
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +ResourcesList<CustomerCard> results = await customerClient.ListCardsAsync("CUSTOMER_ID");
```suggestion
ResourcesList<CustomerCard> customerCards = await customerClient.ListCardsAsync("CUSTOMER_ID");
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.pt.md
> +ResourcesList<CustomerCard> results = await customerClient.ListCardsAsync("CUSTOMER_ID");
```suggestion
ResourcesList<CustomerCard> customerCards = await customerClient.ListCardsAsync("CUSTOMER_ID");
```

2021-03-12 15:25 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.pt.md
> +ResourcesList<CustomerCard> results = await customerClient.ListCardsAsync("CUSTOMER_ID");
```suggestion
ResourcesList<CustomerCard> customerCards = await customerClient.ListCardsAsync("CUSTOMER_ID");
```

2021-03-12 15:49 UTC, delias-silva commented on guides/online-payments/checkout-api/other-features.en.md
> +Payment payment = await client.CreateAsync(paymentRequest);
Sí, creo que es el mejor. Voy a cambiar donde no está así.

2021-03-12 15:50 UTC, delias-silva commented on guides/online-payments/checkout-api/other-features.en.md
> +var payment = await client.CaptureAsync(paymentId);
Sí, voy a cambiar.

2021-03-15 14:29 UTC, nicolassalvanes approved these changes
Excelente! Veo todo bien 👌

2021-03-22 13:57 UTC, nicolassalvanes approved these changes

2021-03-25 13:59 UTC, merged