cambio documentacion devsite
mercadopago/devsite-docs pull request #1091
Opened 2021-03-10 18:02 UTC by micheloliveiramarciano

## Description
Cambio del snippets para la version 2.0.0 del ruby

2021-03-11 20:14 UTC, nicolassalvanes requested changes
Marqué varios errores, y en general me gustaría que podamos unificar criterios de identación y sintaxis al momento de definir objetos.

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card.en.md
> +  "transaction_amount": request[:response]['transactionAmount.to_f'],
Acá porqué cambiamos de request.body.x a este formato? Es necesario? Lo que queremos es mostrar un ejemplo de cómo usamos los datos que recibimos mediante un POST HTTP

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.es.md
> + payment_object = {
Porqué ponemos payment_object y un array de items? No podemos mantener el ejemplo para un único item como en el resto de los lenguajes?

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/marketplace/checkout-api/create-marketplace.es.md
>  }
Acá también falta un `}` al final

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.en.md
> +      "notification_url" : "http://urlmarketplace.com/notification_ipn"
Esto no debería estar dentro de data? Está mal esta estructura me parece

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.en.md
> +	customer = sdk.customer.get(customer[:response]['id'])
```suggestion
customer = sdk.customer.get(customer[:response]['id'])
```

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.en.md
> +  customer_id = customer[:response]['id'],
Esto está mal, debería ser algo parecido a `"customer_id": customer[:response]['id']` no?

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/receiving-payment-by-card.en.md
> +token = sdk.payment().get("token")
Esto está mal, lo que hacemos acá es obtener el dato del request HTTP, no de la SDK

2021-03-11 20:14 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/receiving-payment-by-card.en.md
> +   "token" : "token",
Acá tenemos q usar las variables que se obtuvieron más arriba (token, installments, payment_method_id, issuer_id), no son strings constantes.

2021-03-15 20:46 UTC, delias-silva commented
@nicolassalvanes, estoy revisando todos los snippets, @michelmarciano está de vacaciones.

2021-03-23 20:23 UTC, nicolassalvanes approved these changes
@delias-silva excelente la revisión! Dejo el approve con unas sugerencias de fix menores para que puedan aplicar

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.es.md
> +    pending: 'http://www.tu-sitio/pendings'
```suggestion
    failure: 'https://www.tu-sitio/failure',
    pending: 'https://www.tu-sitio/pendings'
```

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +    pending: 'http://www.tu-sitio/pendings'
```suggestion
    failure: 'https://www.tu-sitio/failure',
    pending: 'https://www.tu-sitio/pendings'
```

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.en.md
> +card_response = sdk.card.create(card_data);
```suggestion
card_data = {
  token: '9b2d63e00d66a8c721607214cedaecda',
  customer_id: customer['id']
}
card_response = sdk.card.create(card_data)
```

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.en.md
> +card_response = sdk.card.create(card_data);
```suggestion
card_data = {
  token: '9b2d63e00d66a8c721607214cedaecda',
  customer_id: customer['id']
}
card_response = sdk.card.create(card_data)
```

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +card_response = sdk.card.create(card_data);
```suggestion
card_data = {
  token: '9b2d63e00d66a8c721607214cedaecda',
  customer_id: customer['id']
}
card_response = sdk.card.create(card_data)
```

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +card_response = sdk.card.create(card_data);
```suggestion
card_data = {
  token: '9b2d63e00d66a8c721607214cedaecda',
  customer_id: customer['id']
}
card_response = sdk.card.create(card_data)
```

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.pt.md
> +card_response = sdk.card.create(card_data);
```suggestion
card_data = {
  token: '9b2d63e00d66a8c721607214cedaecda',
  customer_id: customer['id']
}
card_response = sdk.card.create(card_data)
```

2021-03-23 20:23 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.pt.md
> +card_response = sdk.card.create(card_data);
```suggestion
card_data = {
  token: '9b2d63e00d66a8c721607214cedaecda',
  customer_id: customer['id']
}
card_response = sdk.card.create(card_data)
```

2021-03-25 14:05 UTC, mminestrelli commented
@delias-silva podrías actualizar el branch que hay conflictos?

2021-03-25 14:23 UTC, nicolassalvanes commented
> @delias-silva podrías actualizar el branch que hay conflictos?

Resueltos!

2021-03-25 14:27 UTC, merged