Add SDK Python V2 Snippets
mercadopago/devsite-docs pull request #1094
Opened 2021-03-11 16:26 UTC by dkarasawa

## Description
Add the snippets of the SDK Python Version 2.0.0.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [x] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-15 20:36 UTC, nicolassalvanes requested changes
Hola! Revisé solo los 3 primeros artículos del PR y hay muchos errores que detallé lo más que pude.
Se hacen llamados a métodos innecesarios, se definen objetos que no se utilizan, y no se respeta la firma de los métodos de la SDK (por lo que pude ver en el código [acá](https://github.com/mercadopago/sdk-python/tree/release/2.0.0/mercadopago/resources))

Antes de revisar todo el PR sumo a @delias-silva y @NicholasPedroso para ver si pueden dar una mano a @dkarasawa para hacer todas las correcciones que hacen falta.

2021-03-15 20:36 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/other-features.en.md
> +payment = self.sdk.advanced_payment().update(data=payment_object)
Acá entiendo que debería ser algo como lo siguiente:
```
capture_object = {
  "transaction_amount": 75,
  "capture": true,
}
payment = self.sdk.advanced_payment().update(payment_id, capture_object)
```

2021-03-15 20:36 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/other-features.en.md
> +payment = self.sdk.advanced_payment().update(data=payment_object)
Esto debería ser:
```
payment_object = {
  "status": "canceled"
}
payment = self.sdk.advanced_payment().update(payment_id, payment_object)
```

2021-03-15 20:43 UTC, nicolassalvanes commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +payment = self.sdk.payment().get(payment_id)
Sumo acá el comentario de que me parece que no se tiene que usar `self.sdk.`, eso está copiado del código interno de la SDK.
En este contexto hay que llamar directamente a `sdk.`

2021-03-23 21:18 UTC, nicolassalvanes requested changes

2021-03-23 21:18 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.es.md
> +        "pending": "http://www.tu-sitio/pendings"
```suggestion
        "failure": "https://www.tu-sitio/failure",
        "pending": "https://www.tu-sitio/pendings"
```

2021-03-23 21:18 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +        "pending": "http://www.tu-sitio/pendings"
```suggestion
        "failure": "https://www.tu-sitio/failure",
        "pending": "https://www.tu-sitio/pendings"
```

2021-03-23 21:18 UTC, nicolassalvanes commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +In order to receive notifications when your clients authorize your application, you can [configure the url](https://www.mercadopago.com/mla/account/webhooks) in your account.
```suggestion
In order to receive notifications when your clients authorize your application, you can [configure the url](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications) in your account.
```
La URL nueva es /developers/panel/notifications, creo que acá hubo algún problema de merge

2021-03-23 21:18 UTC, nicolassalvanes commented on guides/online-payments/marketplace/checkout-api/create-marketplace.es.md
> +Puedes recibir notificaciones cuando tus clientes autoricen o desautoricen tu aplicación, [configurando la URL](https://www.mercadopago.com/mla/account/webhooks) en tu cuenta.
```suggestion
Puedes recibir notificaciones cuando tus clientes autoricen o desautoricen tu aplicación, [configurando la URL](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications) en tu cuenta.
```

2021-03-23 21:18 UTC, nicolassalvanes commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Você pode receber notificações quando seus clientes autorizarem ou desautorizarem sua aplicação, [configurando a URL](https://www.mercadopago.com/mlb/account/webhooks) em sua conta.
```suggestion
Você pode receber notificações quando seus clientes autorizarem ou desautorizarem sua aplicação, [configurando a URL](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications) em sua conta.
```

2021-03-23 21:38 UTC, nicolassalvanes approved these changes

2021-03-25 14:06 UTC, mminestrelli commented
@dkarasawa podrías actualizar el branch que hay conflictos?

2021-03-25 14:40 UTC, nicolassalvanes commented
> @dkarasawa podrías actualizar el branch que hay conflictos?

Listo

2021-03-25 14:41 UTC, merged