Feature/mercadopago v2
mercadopago/devsite-docs pull request #1097
Opened 2021-03-21 22:48 UTC by NicholasPedroso

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/previous-requirements.es.md
> +> Utiliza la librería MercadoPago.js V2 para actualizarte a la última versión, autogenerar la lógica de negocio en tu formulario de pagos con tarjeta y mejorar la compatibilidad con los distintos nav
```suggestion
> Utiliza la librería MercadoPago.js V2 para actualizarte a la última versión, autogenerar la lógica de negocio en tu formulario de pagos con tarjeta y mejorar la compatibilidad con los distintos navegadores.<br><br>[Integrar Checkout Transparente con MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/previous-requirements-v2)
```

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/previous-requirements.es.md
> +> Utiliza la librería MercadoPago.js V2 para actualizarte a la última versión, autogenerar la lógica de negocio en tu formulario de pagos con tarjeta y mejorar la compatibilidad con los distintos nav
```suggestion
> Utiliza la librería MercadoPago.js V2 para actualizarte a la última versión, autogenerar la lógica de negocio en tu formulario de pagos con tarjeta y mejorar la compatibilidad con los distintos navegadores.<br><br>[Integrar Checkout API con MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/previous-requirements-v2)
```

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/receiving-payment-by-card.pt.md
> +> Utilize a biblioteca MercadoPago.js V2 para criar seu formulário de cartão com a funcionalidade CardForm e autogerar a lógica de negócio necessária para fazer o pagamento.<br><br>[Integrar Checkout
```suggestion
> Utilize a biblioteca MercadoPago.js V2 para criar seu formulário de cartão com a funcionalidade CardForm e autogerar a lógica de negócio necessária para fazer o pagamento.<br><br>[Integrar Checkout API com MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/receiving-payment-by-card-v2)
```

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/receiving-payment-by-card.pt.md
> +> Utilize a biblioteca MercadoPago.js V2 para criar seu formulário de cartão com a funcionalidade CardForm e autogerar a lógica de negócio necessária para fazer o pagamento.<br><br>[Integrar Checkout
```suggestion
> Utilize a biblioteca MercadoPago.js V2 para criar seu formulário de cartão com a funcionalidade CardForm e autogerar a lógica de negócio necessária para fazer o pagamento.<br><br>[Integrar Checkout Transparente com MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/receiving-payment-by-card-v2)
```

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/receiving-payment-by-card.es.md
> +> Utiliza la librería MercadoPago.js V2 para crear tu formulario de tarjeta con la funcionalidad CardForm y autogenerar la lógica de negocio necesaria para realizar el pago.<br><br>[Integrar Checkout
```suggestion
> Utiliza la librería MercadoPago.js V2 para crear tu formulario de tarjeta con la funcionalidad CardForm y autogenerar la lógica de negocio necesaria para realizar el pago.<br><br>[Integrar Checkout Transparente con MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/receiving-payment-by-card-v2)
```

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/receiving-payment-by-card.es.md
> +> Utiliza la librería MercadoPago.js V2 para crear tu formulario de tarjeta con la funcionalidad CardForm y autogenerar la lógica de negocio necesaria para realizar el pago.<br><br>[Integrar Checkout
```suggestion
> Utiliza la librería MercadoPago.js V2 para crear tu formulario de tarjeta con la funcionalidad CardForm y autogenerar la lógica de negocio necesaria para realizar el pago.<br><br>[Integrar Checkout API con MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/receiving-payment-by-card-v2)
```

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/receiving-payment-by-card.en.md
> +> Use MercadoPago.js V2 library to create your card form with CardForm functionality, which includes all business logic needed to make the payment.<br><br>[Integrate Checkout API with MercadoPago.js
```suggestion
> Use MercadoPago.js V2 library to create your card form with CardForm functionality, which includes all business logic needed to make the payment.<br><br>[Integrate Checkout API with MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/receiving-payment-by-card-v2)
```

2021-03-22 21:19 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +> Use MercadoPago.js V2 library to be updated to the latest version and to improve compatibility with different browsers.<br><br>[Integrate Checkout API with MercadoPago.js V2](https://www.mercadopag
```suggestion
> Use MercadoPago.js V2 library to be updated to the latest version and to improve compatibility with different browsers.<br><br>[Integrate Checkout API with MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/other-payment-ways)
```

2021-03-23 01:35 UTC, pamalv7 requested changes

2021-03-23 01:35 UTC, pamalv7 commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +![API-integration-flowchart](/images/api/api-integration-flowchart-coremethods-es.png)
Corregir contenidos en portugués en la imagen.

2021-03-23 01:35 UTC, pamalv7 commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.es.md
> +![API-integration-flowchart](/images/api/api-integration-flowchart-cardform-es.png)
Corregir contenido de imagen. 
"Formulario" va sin tilde.

2021-03-30 17:41 UTC, pamalv7 approved these changes

2021-03-30 17:42 UTC, nicolassalvanes approved these changes

2021-03-30 17:46 UTC, merged