[Feature] Add new info and beter code
mercadopago/devsite-docs pull request #1098
Opened 2021-03-22 19:32 UTC by SilvinaMorato

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-23 22:21 UTC, abderossi approved these changes

2021-03-25 16:13 UTC, pamalv7 requested changes

2021-03-25 16:13 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +> Recuerda que para poder generar pagos, antes debes [crear una llave Pix.](https://www.mercadopago.com.br/ajuda/1784)
```suggestion
> Recuerda que para poder generar pagos, antes debes [crear una llave Pix](https://www.mercadopago.com.br/ajuda/1784).
```

2021-03-25 16:13 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +> Lembre-se de que, para gerar pagamentos, você deve primeiro [criar uma chave Pix.](https://www.mercadopago.com.br/ajuda/1784)
```suggestion
> Lembre-se de que, para gerar pagamentos, você deve primeiro [criar uma chave Pix](https://www.mercadopago.com.br/ajuda/1784).
```

2021-03-25 16:13 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +> Importante
```suggestion
> Important
```

2021-03-25 16:13 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +> Leve em consideração que o registro da chave Pix pode levar alguns minutos.
```suggestion
> Considere que o registro da chave Pix pode levar alguns minutos.
```

2021-03-25 16:21 UTC, pamalv7 approved these changes

2021-03-25 16:36 UTC, merged