Changelog nodeJS 1.5.6
mercadopago/devsite-docs pull request #1099
Opened 2021-03-23 13:43 UTC by NicholasPedroso

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-23 19:52 UTC, nicolassalvanes approved these changes

2021-03-23 21:50 UTC, elvisjhonataoliveira requested changes

2021-03-23 21:50 UTC, elvisjhonataoliveira commented on guides/resources/changelog/current-year.pt.md
> +Lançamos uma nova versão do SDK NodeJS 1.5.6.
```suggestion
Lançamos a nova versão 1.5.6 do SDK NodeJS .
```

2021-03-25 14:07 UTC, mminestrelli commented
@NicholasPedroso podrías actualizar el branch que hay conflictos?

2021-03-25 16:37 UTC, pamalv7 approved these changes

2021-03-25 17:31 UTC, elvisjhonataoliveira approved these changes

2021-03-25 17:32 UTC, merged