Warning de uso de curls de industrias
mercadopago/devsite-docs pull request #1116
Opened 2021-03-30 19:20 UTC by lucasglanza1

Se agregó un warning del uso de curls para la API de preferencias.

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-03-30 19:41 UTC, adfonseca commented on guides/resources/industry-data/additional-info.pt.md
> +> Os curls a seguir funcionam apenas para a API de preferências.
```suggestion
> Os curls a seguir funcionam somente para a API de preferências.
```

2021-04-07 11:39 UTC, lamaralmp requested changes

2021-04-07 11:39 UTC, lamaralmp commented on guides/resources/industry-data/additional-info.en.md
> +> Using the examples
```suggestion
> Use of examples
```

2021-04-07 11:39 UTC, lamaralmp commented on guides/resources/industry-data/additional-info.en.md
> +> Using the examples
@pamalv7 en ingles seria "Use of examples"?

2021-04-07 11:39 UTC, lamaralmp commented on guides/resources/industry-data/additional-info.es.md
> +> Uso de Ejemplos
```suggestion
> Uso de ejemplos
```

2021-04-07 11:39 UTC, lamaralmp commented on guides/resources/industry-data/additional-info.es.md
> +> Los siguientes curls solo funcionan para la API de Preferencias.
```suggestion
> Los siguientes curls solo funcionan para la API de preferencias.
```

2021-04-07 11:42 UTC, lamaralmp commented
Bom dia @lucasglanza1,

sugeri algumas correções pequenas no seu PR.
Vi que você fez um PR desde um fork.
É necessário que você clone diretamente o repositório de `devsite-docs` e faça um PR contra `development`.
Poderia corrigir? Qualquer dúvida pode me chamar no Slack.

2021-04-08 12:45 UTC, lamaralmp commented
Hola @lucasglanza1 ,

estoy cerrando este PR y substituindo por el #1127 .
Para las próximas contribuiciones te pedimos que clone directamente el proyecto.
Cualquier duda estamos a disposición

2021-04-08 12:45 UTC, closed without merging