[Feature] Add note and change date of expiration pix
mercadopago/devsite-docs pull request #1126
Opened 2021-04-07 15:18 UTC by SilvinaMorato

## Description
Se cambio la fecha de expiración de PIX y además se agrego una nota para que en caso que se quiera devolver una transferencia, sepa que hacer y a donde debe ir. 

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [X ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-04-07 16:22 UTC, abderossi requested changes

2021-04-07 16:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +> Si necesitas devolver un pago realizado a través de una transferencia Pix, puedes encontrar esta información en [Devoluciones y cancelaciones](https://www.mercadopago.com.br/developers/es/guides/ma
```suggestion
> Si necesitas devolver un pago realizado a través de una transferencia Pix, puedes encontrar esta información en [Devoluciones y cancelaciones](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/account/cancellations-and-refunds).
```

2021-04-07 16:22 UTC, abderossi commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +> Se você precisar devolver um pagamento feito por transferência Pix, você pode encontrar essas informações em [Devoluções e cancelamentos](https://www.mercadopago.com.br/developers/pt/guides/manage-
```suggestion
> Se você precisar devolver um pagamento feito por transferência Pix, você pode encontrar essas informações em [Devoluções e cancelamentos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/manage-account/account/cancellations-and-refunds).
```

2021-04-07 19:50 UTC, abderossi approved these changes

2021-04-08 13:28 UTC, pamalv7 requested changes

2021-04-08 13:28 UTC, pamalv7 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +> If you need to refund a payment made by a Pix transfer, you can find this information in [Refunds and cancellations.](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account
```suggestion
> If you need to refund a payment made by a Pix transfer, you can find this information in [Refunds and cancellations](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/account/cancellations-and-refunds).
```

2021-04-08 13:29 UTC, pamalv7 approved these changes

2021-04-08 17:51 UTC, merged