fix/marketplaceapi
mercadopago/devsite-docs pull request #1166
Opened 2021-05-07 15:50 UTC by CandeGlikin

## Description
Actualice tambien la parte de cho api porque habia actualizado solo la de cho pro de marketplace

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [X] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-05-10 13:25 UTC, lamaralmp requested changes

2021-05-10 13:25 UTC, lamaralmp commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Para receber pagamentos em nome de seus vendedores, você deve integrar a [API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/introduction), gerando os
```suggestion
Para receber pagamentos em nome de seus vendedores, você deve integrar a [API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/introduction), gerando os pagamentos com o Access Token que você obteve vinculando cada vendedor ao seu aplicativo.
```

2021-05-11 12:40 UTC, lamaralmp approved these changes

2021-05-13 12:21 UTC, pamalv7 approved these changes

2021-05-13 12:31 UTC, abderossi approved these changes

2021-05-13 14:13 UTC, merged