Feature/add bin combo customers
mercadopago/devsite-docs pull request #1174
Opened 2021-05-18 19:05 UTC by brunoseba

## Agregar info sobre Bin Combo para Customers
Notificar a los usuarios, en el caso de haber bin compartido, deberán enviar campos adicionales

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-05-18 19:46 UTC, nicolassalvanes requested changes
Sumo además que este artículo no es el único donde se habla sobre Customers & Cards.
También en Checkout API:
https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-api/advanced-integration

2021-05-18 19:46 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +Cuando hay dos medios de pagos activos(tarjetas de credito y debito) con el "bin compartido" (primeros 6 digitos de las tarjetas), para estos casos se deberá adicionalmente enviar dos campos [issuer_
@brunoseba no sería mejor indicar en la documentación que siempre hay que enviar estos datos?
Me parece raro delegar en el integrador la responsabilidad de detectar la colisión de bines.

2021-05-18 19:59 UTC, brunoseba commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +Cuando hay dos medios de pagos activos(tarjetas de credito y debito) con el "bin compartido" (primeros 6 digitos de las tarjetas), para estos casos se deberá adicionalmente enviar dos campos [issuer_
coincido con ello @nicolassalvanes, gracias por la aclaración

2021-05-20 13:14 UTC, brunoseba reviewed
Archivos agregados y modificados.

2021-05-20 20:47 UTC, dmpenesi commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +Cuando hay dos medios de pagos activos(tarjetas de credito y debito) con el "bin compartido" (primeros 6 digitos de las tarjetas), por ello es necesario enviar siempre los campos [issuer_id] y [payme
```suggestion
Cuando hay dos medios de pagos activos(tarjetas de crédito y debito) con el "bin compartido" (primeros 6 dígitos de las tarjetas), es necesario enviar siempre los campos [issuer_id] y [payment_method_id]
```

2021-05-20 20:47 UTC, dmpenesi commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +En el caso de que actualize algún bin para que sea compartido y como no son posteados esos dos campos se devolvera un statuCode 4XX
Yo pondría algo como. 
"En caso de que el bin sea compartido y no se envíen los datos necesarios para identificar el medio de pago, retornaremos statuCode 4XX"

2021-05-20 20:47 UTC, dmpenesi commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +Cuando hay dos medios de pagos activos(tarjetas de credito y debito) con el "bin compartido" (primeros 6 digitos de las tarjetas), por ello es necesario enviar siempre estos dos campos [issuer_id] y
Esto deberías cambiarlo, porque es posible que existan más de 2 medio de pagos con el mismo bin.
yo pondría algo como :
"Cuando hay mas de un medios de pago activo con el "bin compartido" (primeros 6 dígitos de las tarjetas). Es necesario enviar siempre los campos [issuer_id] y [payment_method_id]. Caso contrario, se retornara un statusCode 4XX"
Con esto metería la linea de abajo también. 
¿Cuál es el statusdetail que se retorna en estos casos?

2021-05-20 20:47 UTC, dmpenesi commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +En el caso de que actualize algún bin para que sea compartido y como no son posteados esos dos campos se devolvera un statuCode 4XX
este quedaria agregado en la linea de arriba, porque esta hablando de lo mismo

2021-05-20 20:47 UTC, dmpenesi commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +Por ejemplo de dos pagos activos con bin compartidos:
```suggestion
Ejemplo de dos pagos con bin compartido pero distinto payment_type_id :
```

2021-05-20 20:47 UTC, dmpenesi commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +{
Estos ejemplos los dividiria en dos, porque al estar los dos juntos no se distingue donde empieza uno y termina el otro

2021-05-20 20:47 UTC, dmpenesi commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +      "payment_type_id": "credit_card"
En estos casos no debería variar el issuer y también el payment_method_id ?

2021-06-08 12:49 UTC, dmpenesi commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +Cuando hay mas de un medios de pago activo con el "bin compartido" (primeros 6 dígitos de las tarjetas). Es necesario enviar siempre los campos [issuer_id] y [payment_method_id]. Caso contrario, se r
```suggestion
Cuando hay mas de un medio de pago activo con el "bin compartido" (primeros 6 dígitos de la tarjeta). Es necesario enviar siempre los campos [issuer_id] y [payment_method_id]. Caso contrario, se retornara un statusCode 4XX 
```

2021-06-08 12:49 UTC, dmpenesi commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +Respuesta:
```suggestion
Respuesta-OK:
```

2021-06-09 19:02 UTC, nicolassalvanes requested changes
Es necesario confirmar con el equipo de SDK's cuáles soportan estos nuevos parámetros, y cuales no.

2021-06-09 19:02 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +> Si recibimos un mensaje de este tipo `"invalid parameter"` con statusCode 4XX es por falta de los campos `payment_method_id` y `issuer_id`
```suggestion
> Si recibes un mensaje de error del tipo `"invalid parameter"` con código de estado HTTP 400, asegúrate de estar completando correctamente los campos `payment_method_id` e `issuer_id` 
```

2021-06-09 19:02 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +> Si recibimos un mensaje de este tipo `"invalid parameter"` con statusCode 4XX es por falta de los campos `payment_method_id` y `issuer_id`
Te parece mejor @pamalv7 ?

2021-06-09 20:48 UTC, nicolassalvanes requested changes

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +  $card->payment_method array("id" => "debit_card");
```suggestion
  $card->payment_method = array("id" => "debit_card");
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +  $card->payment_method_id = "debit_card";
```suggestion
  $card->issuer = array("id" => "3245612");
  $card->payment_method = array("id" => "debit_card");
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +card.setIssuerId("3245612");
```suggestion
card.setIssuer(issuer);
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.es.md
>  Card card = new Card();
```suggestion
Issuer issuer = new Issuer();
issuer.setId("3245612");

Card card = new Card();
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.es.md
> +    PaymentMethodId = "debit_card"
```suggestion
    Token = "9b2d63e00d66a8c721607214cedaecda"
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +  $card->payment_method array("id" => "debit_card");
```suggestion
  $card->payment_method = array("id" => "debit_card");
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +  $card->payment_method_id = "debit_card";
```suggestion
  $card->issuer = array("id" => "3245612");
  $card->payment_method = array("id" => "debit_card");
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +card.setIssuerId("2332451");
```suggestion
card.setIssuer(issuer);
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
>  Card card = new Card();
```suggestion
Issuer issuer = new Issuer();
issuer.setId("3245612");

Card card = new Card();
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +    PaymentMethodId = "debit_card"
```suggestion
    Token = "9b2d63e00d66a8c721607214cedaecda"
```

2021-06-09 20:48 UTC, nicolassalvanes commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +> Si recibimos un mensaje de este tipo `"invalid parameter"` con statusCode 4XX es por falta de los campos `payment_method_id` y `issuer_id`
```suggestion
> Si recibes un mensaje de error del tipo `"invalid parameter"` con código de estado HTTP 400, asegúrate de estar completando correctamente los campos `payment_method_id` e `issuer_id`
```

2021-06-09 21:18 UTC, nicolassalvanes approved these changes

2021-06-10 00:08 UTC, pamalv7 commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.es.md
> +> Si recibes un mensaje de error del tipo `"invalid parameter"` con código de estado HTTP 400, asegúrate de estar completando correctamente los campos `payment_method_id` e `issuer_id`
```suggestion
> Si recibes un mensaje de error del tipo `"invalid parameter"` con código de estado HTTP 400, asegúrate de estar completando correctamente los campos `payment_method_id` e `issuer_id`. 
```

2021-06-10 00:08 UTC, pamalv7 commented on guides/online-payments/web-tokenize-checkout/customers-and-cards.pt.md
> +> Si recibes un mensaje de error del tipo `"invalid parameter"` con código de estado HTTP 400, asegúrate de estar completando correctamente los campos `payment_method_id` e `issuer_id`
```suggestion
> Se você receber uma mensagem de erro do tipo `"invalid parameter"` com código de estado HTTP 400, certifique-se de que está preenchendo corretamente os campos `payment_method_id` e `issuer_id`.
```

2021-06-10 00:35 UTC, pamalv7 approved these changes

2021-06-10 11:40 UTC, merged