Feature/mprc 6555 update report docs
mercadopago/devsite-docs pull request #1179
Opened 2021-05-21 16:23 UTC by OnnigPanossian

## Description
Se actualiza la documentación de la sección Reportes. 
Ésto incluye Changelog, Glosario y actualización en los snippets de código.
Se agregan nuevas secciones que corresponden a las carpetas V1 dentro de account-money y available-money que contienen la documentación de la versión antigua.
Todos los cambios incluyen sus correspondientes traducciones.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [x] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [x] New features were communicated in changelog.
- [ ] Requires translations.

2021-06-02 18:51 UTC, nicolassalvanes requested changes

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.en.md
> +}
```suggestion
```

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.en.md
> +                    "key": "EXTERNAL_REFERENCE"
Puede ser que esté mal esto? No puede haber múltiples atributos en un mismo objeto con el mismo nombre.

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.es.md
> +                    { \\"key\\": \\"EXTERNAL_REFERENCE\\" },
Falta el corchete de cierre ]

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.en.md
> +                    { \\"key\\": \\"EXTERNAL_REFERENCE\\" },
Falta el corchete de cierre ]

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.es.md
> +                    { \\"key\\": \\"EXTERNAL_REFERENCE\\" },
falta el corchete de cierre ]

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.pt.md
> +                    { \\"key\\": \\"EXTERNAL_REFERENCE\\" },
falta el corchete de cierre ]

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.pt.md
> +                    { \\"key\\": \\"EXTERNAL_REFERENCE\\" },
falta el corchete de cierre ]

2021-06-02 18:51 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.pt.md
> +| `columns` | <br/>Campo com os detalhes das colunas a serem incluídas no seu relatório. Encontre todos os valores possíveis na seção [Glossário](https://www.mercadopago[FAKER][URL][DOMAIN]/developer
```suggestion
| `columns` | <br/>Campo com os detalhes das colunas a serem incluídas no seu relatório. Encontre todos os valores possíveis na seção [Glossário](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/manage-account/reports/account-money/glossary).<br/><br/>|
```

2021-06-02 19:04 UTC, OnnigPanossian commented on guides/manage-account/reports/account-money/api.en.md
> +                    "key": "EXTERNAL_REFERENCE"
Ya lo reviso

2021-06-03 03:28 UTC, nicolassalvanes approved these changes

2021-06-03 03:28 UTC, nicolassalvanes commented on guides/manage-account/reports/account-money/api.pt.md
> +                        \\"columns\\": [
```suggestion
                    \\"columns\\": [
```

2021-06-03 14:33 UTC, OnnigPanossian commented on guides/resources/changelog/current-year.pt.md
> +### 3 de junho
Buenas, en mi caso lo repetí porque pensé que cada registro del changelog debía tener su fecha. Que Pame confirme pero creo que no sería necesario entonces.

2021-06-03 16:43 UTC, nicolassalvanes approved these changes

2021-06-03 20:46 UTC, pamalv7 commented on guides/manage-account/reports/account-money/api.es.md
> +> Esta documentación corresponde a la nueva versión de la API.
```suggestion
> Esta documentación corresponde a la nueva versión de la API
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/manage-account/reports/account-money/api.en.md
> +> This documentation corresponds to the new version of the API.
```suggestion
> This documentation corresponds to the new version of the API
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/manage-account/reports/account-money/api.pt.md
> +> Esta documentação corresponde à nova versão da API.
```suggestion
> Esta documentação corresponde à nova versão da API
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/manage-account/reports/available-money/api.en.md
> +> This documentation corresponds to the new version of the API.
```suggestion
> This documentation corresponds to the new version of the API
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/manage-account/reports/available-money/api.es.md
> +> Esta documentación corresponde a la nueva versión de la API.
```suggestion
> Esta documentación corresponde a la nueva versión de la API
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/manage-account/reports/available-money/api.pt.md
> +> Esta documentação corresponde à nova versão da API.
```suggestion
> Esta documentação corresponde à nova versão da API
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/manage-account/reports/available-money/v1/api.es.md
> +Ganá tiempo y automatizá la **frecuencia de generación** del reporte de Dinero retirado las veces que quieras, tanto de forma manual como de forma programada.
```suggestion
Gana tiempo y automatiza la **frecuencia de generación** del reporte de Dinero retirado las veces que quieras, tanto de forma manual como de forma programada. 
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +### 3 de junho
No, no es necesario. 

Al resolver los conflitos lo ajustamos.

2021-06-03 20:46 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> Product: REPORTES
```suggestion
> PRODUCT: REPORTES
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +> Product: RELATÓRIOS
```suggestion
> PRODUCT: RELATÓRIOS
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> Product: REPORTS
```suggestion
> PRODUCT: REPORTS
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> Product: REPORTS
```suggestion
> PRODUCT: REPORTS
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> Product: REPORTES
```suggestion
> PRODUCT: REPORTES
```

2021-06-03 20:46 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +> Product: RELATÓRIOS
```suggestion
> PRODUCT: RELATÓRIOS
```

2021-06-03 21:04 UTC, mminestrelli approved these changes

2021-06-03 21:37 UTC, pamalv7 approved these changes

2021-06-03 21:38 UTC, merged