Se tradujo el titulo de la pagina y una nota.
mercadopago/devsite-docs pull request #1184
Opened 2021-05-31 18:07 UTC by maperozo

## Description
Se tradujo el título de la página y una nota. También se cambió un curl que está erróneo en los tres idiomas.

### Checklist:
Before sending your contribution, please specify the following: 

- [ x] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-06-01 18:41 UTC, abderossi commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +# Cashback and Cancellations
@pamalv7 en el sidebar lo mencionamos como Cashback and cancellations, pero creo que el título Refunds iría mejor, porque el estado del pago queda en "refunded". ¿No sería conveniente dejar Refunds y unificar en el sidebar?

2021-06-03 14:21 UTC, pamalv7 requested changes

2021-06-03 14:21 UTC, pamalv7 commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +# Cashback and Cancellations
Sí, de acuerdo con esto. El término correcto es Refunds.

2021-06-03 14:21 UTC, pamalv7 commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +# Cashback and Cancellations
```suggestion
# Refunds and cancellations
```

2021-06-03 18:04 UTC, pamalv7 approved these changes

2021-06-03 18:54 UTC, merged