agregado oauth en API Ref
mercadopago/devsite-docs pull request #1194
Opened 2021-06-14 19:06 UTC by juanseferrari2

## Description
Agregado de la documentación de OAuth en API Ref. Debería ir desindexado.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-06-16 13:53 UTC, lamaralmp commented
Hice commit con ajustes en el `yaml` para que el devsite reconozca todos los campos del archivo:

- Sumé tags
- Cambie la sintaxis para el required
- Movi la descripción para los enums
- Sumé description a los campos de response
- Cambie la tag de error para errorKey
- Cambie el tipo de requestBody (estoy validando con @juanseferrari2 si la API acepta `application/json`)

La URL en la docu vá a ser:
`/developers/en/reference/oauth/_oauth_token/post`

2021-06-16 13:59 UTC, lamaralmp approved these changes

2021-06-16 14:34 UTC, elvisjhonataoliveira requested changes
Sugestões para adicionar -- nos enuns

2021-06-16 14:34 UTC, elvisjhonataoliveira commented on reference/api/oauth.yaml
> +                      - invalid_client
```suggestion
                      - invalid_client -- 
```

2021-06-16 14:34 UTC, elvisjhonataoliveira commented on reference/api/oauth.yaml
> +                      - invalid_grant
```suggestion
                      - invalid_grant -- 
```

2021-06-16 14:34 UTC, elvisjhonataoliveira commented on reference/api/oauth.yaml
> +                      - invalid_scope
```suggestion
                      - invalid_scope -- 
```

2021-06-16 14:34 UTC, elvisjhonataoliveira commented on reference/api/oauth.yaml
> +                      - invalid_request
```suggestion
                      - invalid_request -- 
```

2021-06-16 14:34 UTC, elvisjhonataoliveira commented on reference/api/oauth.yaml
> +                      - unsupported_grant_type
```suggestion
                      - unsupported_grant_type -- 
```

2021-06-16 14:34 UTC, elvisjhonataoliveira commented on reference/api/oauth.yaml
> +                      - forbidden
```suggestion
                      - forbidden -- 
```

2021-06-16 14:34 UTC, elvisjhonataoliveira commented on reference/api/oauth.yaml
> +                      - unauthorized_client
```suggestion
                      - unauthorized_client -- 
```

2021-06-16 15:16 UTC, elvisjhonataoliveira approved these changes

2021-06-22 16:01 UTC, abderossi commented on reference/api/oauth.yaml
> +      description: To create or refresh the necessary credentials to operate your application in the name of a seller
```suggestion
      description: To create or refresh the necessary credentials to allow your application to operate in the name of a seller
```

2021-06-22 16:05 UTC, abderossi commented on reference/api/oauth.yaml
> +                  description: Specify type of operation to perform to get your credentials.
```suggestion
                  description: Specifies the type of operation to perform to get your credentials.
```

2021-06-24 15:43 UTC, pamalv7 commented on reference/api/oauth.yaml
> +                    example: 'Error validating grant. Your authorization code or refresh token may be expired or it was already used'
```suggestion
                    example: 'Error validating grant. Your authorization code or refresh token may be expired or it was already used.'
```

2021-06-24 21:47 UTC, merged