Adjusted magento versions link
mercadopago/devsite-docs pull request #1196
Opened 2021-06-16 13:33 UTC by lira

## Description
Fixed Magento 2 link, set to Magento Marketplace releases

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-06-16 14:02 UTC, lamaralmp approved these changes

2021-06-16 14:56 UTC, abderossi requested changes
@pamalv7 sumé estos ajustes porque el link no lleva a descargar la última versión, sino a las release notes en donde se listan las últimas versiones. ¿Qué opinás?

2021-06-16 14:56 UTC, abderossi commented on guides/plugins/official/magento-two.es.md
> +> - [Descarga la última versión](https://marketplace.magento.com/mercadopago-core.html#product.info.details.release_notes) para actualizar tu plugin de Mercado Pago.<br>
```suggestion
> - [Verifica la última versión](https://marketplace.magento.com/mercadopago-core.html#product.info.details.release_notes) y actualiza tu plugin de Mercado Pago.<br>
```

2021-06-16 14:56 UTC, abderossi commented on guides/plugins/official/magento-two.en.md
> +> - [Download the latest version](https://marketplace.magento.com/mercadopago-core.html#product.info.details.release_notes) to update your Mercado Pago plugin.<br>
```suggestion
> - [Verify the latest version](https://marketplace.magento.com/mercadopago-core.html#product.info.details.release_notes) and update your Mercado Pago plugin.<br>
```

2021-06-16 14:56 UTC, abderossi commented on guides/plugins/official/magento-two.pt.md
> +> - [Baixar a última versão](https://marketplace.magento.com/mercadopago-core.html#product.info.details.release_notes) para atualizar seu plugin do Mercado Pago.<br>
```suggestion
> - [Verifique a última versão](https://marketplace.magento.com/mercadopago-core.html#product.info.details.release_notes) e atualize seu plugin do Mercado Pago.<br>
```

2021-06-16 17:51 UTC, abderossi approved these changes

2021-06-17 14:44 UTC, pamalv7 commented on guides/plugins/official/magento-two.es.md
>  > Antes de configurar el Pix como medio de pago, ten en cuenta:<br><br>
```suggestion
> Antes de configurar Pix como medio de pago, ten en cuenta:<br><br>
```

2021-06-17 14:44 UTC, pamalv7 approved these changes

2021-06-17 16:26 UTC, merged