fix-nuvemshop-pix
mercadopago/devsite-docs pull request #1197
Opened 2021-06-17 15:36 UTC by douglas-cruz

> Contexto
Se incluyó Pix como medio de pago en Nuvemshop nueva condición del pago
para recibir pagos a través de Pix.

> Objetivo
Comunicar en Devsite el nuevo método de pago en Nuvemshop para Brasil, que incluye Pix como método de pago.

> Qué tenemos que hacer
Integrar este nuevo medio de pago a la documentación de Nuvemshop para MLB.

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-06-22 20:30 UTC, abderossi commented on guides/plugins/unofficial/nuvemshop.es.md
> +Permite que el **cliente finalice la compra en tu tienda**, sin ser redireccionado para otro sitio ----[mlb]---- , y donde posibilita recibir pagos con tarjeta de crédito, boleto bancario, Pix y Chec
```suggestion
Permite que el **cliente finalice la compra en tu tienda**, sin ser redireccionado para otro sitio----[mlb]----, y donde posibilita recibir pagos con tarjeta de crédito, boleto bancario, Pix y Checkout Pro------------.
```

2021-06-22 20:31 UTC, abderossi commented on guides/plugins/unofficial/nuvemshop.es.md
> +**El comprador será redireccionado a Mercado Pago** para realizar el pago y terminar la compra ----[mlb]---- utilizando medios de pago como Pix, boleto parcelado, débito virtual de Caixa y dinero en
```suggestion
**El comprador será redireccionado a Mercado Pago** para realizar el pago y terminar la compra ----[mlb]---- utilizando medios de pago como Pix, boleto parcelado, débito virtual de Caixa y dinero en cuenta de Mercado Pago. Una vez finalizado el pago, el comprador regresará a su tienda------------. 
```

2021-06-22 21:31 UTC, abderossi commented on guides/resources/changelog/current-year.es.md
> +Ahora puedes incluir Pix como método de pago para Nuvemshop.
```suggestion
Ahora puedes incluir Pix como método de pago para Tiendanube.
```

2021-06-22 21:32 UTC, abderossi commented on guides/resources/changelog/current-year.es.md
> +[Ir para a documentação Nuvemshop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/nuvemshop)
```suggestion
[Ir a documentación de Tiendanube](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/nuvemshop)
```

2021-06-22 21:34 UTC, abderossi commented on guides/resources/changelog/current-year.en.md
> +[Ir para a documentação Nuvemshop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/nuvemshop)
```suggestion
[Ir para a documentação Nuvemshop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/nuvemshop)
```
```suggestion
[Ir para a documentação Nuvemshop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/nuvemshop)
```
```suggestion
[Go to Nuvemshop documentation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/nuvemshop)
```

2021-06-22 21:34 UTC, abderossi commented on guides/resources/changelog/current-year.en.md
> +[Ir para a documentação Nuvemshop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/nuvemshop)
```suggestion
[Go to Nuvemshop documentation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/nuvemshop)
```

2021-06-22 21:37 UTC, abderossi approved these changes

2021-06-24 16:33 UTC, pamalv7 requested changes

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.pt.md
> +> Ao instalar o Mercado Pago, as modalidades de pagamento "Cartão de crédito", "Boleto bancário" e "Pix" estarão habilitadas por padrão em sua loja.
@abderossi ¿Por qué en este caso les dejamos las comillas y arribas en el paso a paso no? 
Unificaría ambas formas. Si queremos mantener fidelidad a la experiencia, pondría todo en comillas y Pix en mayúsculas acá también.

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.es.md
> +Permite que el **cliente finalice la compra en tu tienda**, sin ser redireccionado para otro sitio----[mlb]----, y donde posibilita recibir pagos con tarjeta de crédito, boleto bancario, Pix y Checko
```suggestion
Permite que el **cliente finalice la compra en tu tienda**, sin ser redireccionado para otro sitio----[mlb]----, y recibe pagos con tarjeta de crédito, boleto bancario, Pix y Checkout Pro------------.
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.es.md
> +3. Selecciona las opciones de pago que deseas ofrecer en tu tienda. Estos pueden ser Tarjeta de crédito, Boleto Bancario y PIX.
```suggestion
3. Selecciona las opciones de pago que deseas ofrecer en tu tienda. Estas pueden ser Tarjeta de crédito, Boleto Bancario y PIX.
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.es.md
>  > Luego de instalar Mercado Pago, todos los medios de pago estarán activos por defecto.
@abderossi  ¿Y si llevamos este mensaje a portugués también?

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.es.md
> +Si deseas sincronizar tus configuraciones manualmente  o aplicar un monto mínimo de cuotas, realiza los siguientes pasos: ------------
```suggestion
Si deseas **sincronizar tus configuraciones manualmente** o aplicar un monto mínimo de cuotas, realiza los siguientes pasos: ------------
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.en.md
> +If you want to manually sync your settings or apply a minimum amount of installments, please follow these steps: ------------
```suggestion
If you want to **manually sync your settings** or apply a minimum amount of installments, please follow these steps: ------------
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.en.md
>  1. Access the payment ----[mlb]---- [methods settings](https://lojavirtualnuvem.com.br/admin/payments/) ------------ ----[mla, mlm, mlc, mlu, mpe, mco]---- [methods settings](https://mitiendanube.com
```suggestion
1. Access the payment ----[mlb]---- [methods settings](https://lojavirtualnuvem.com.br/admin/payments/) ------------ ----[mla, mlm, mlc, mlu, mpe, mco]---- [methods settings](https://mitiendanube.com/admin/payments/) ------------ on your site menu, look for "Mercado Pago" and select "Edit".
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.en.md
>  2. In the installments section, click on "Show now".
@abderossi El paso 2 es: 

If you want to apply a minimum amount of installments for payments with Transparent Checkout, inform the amount in the "Installments" field.

Como está en español.

2021-06-24 16:33 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> New Pix payment method for ----[mlb]----Nuvemshop------------ ----[mla, mlm, mlc, mco]----Tiendanube------------
```suggestion
> New Pix payment method for Nuvemshop
```
No es necesario localizar esta instancia, solamente se va a ver en BR esta información.

2021-06-24 16:33 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +Ahora puedes incluir Pix como método de pago para Tiendanube.
```suggestion
Ahora puedes incluir Pix como método de pago para Nuvemshop.
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +[Ir a documentación de Tiendanube](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/nuvemshop)
```suggestion
[Ir a documentación de Nuvemshop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/nuvemshop)
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.es.md
> +2. En la sección de mensualidades, haz clic en "Reflejar ahora".
```suggestion
2. En la sección de meses, haz clic en "Reflejar ahora".
```

2021-06-24 16:33 UTC, pamalv7 commented on guides/plugins/unofficial/nuvemshop.en.md
> +**The buyer will be redirected to Mercado Pago** to make the payment and complete the purchase ----[mlb]---- using payment methods such as Pix, boleto parcelado, Caixa’s virtual debit and money from
```suggestion
**The buyer will be redirected to Mercado Pago** to make the payment and complete the purchase----[mlb]---- using payment methods such as Pix, boleto parcelado, Caixa’s virtual debit and money from a Mercado Pago account. Once the payment is complete, the buyer will return to your site ------------.
```

2021-06-24 16:47 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
>  ### 3 de junio
@abderossi Si la fecha va a ser la misma, deberían estar agrupados.

2021-06-24 16:56 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
>  ### 3 de junio
¿No debería tener fecha actual?

2021-06-24 21:21 UTC, pamalv7 approved these changes

2021-06-24 21:26 UTC, merged