Feature/cambiar v2 default
mercadopago/devsite-docs pull request #1204
Opened 2021-06-23 21:31 UTC by eltinMeli

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-07-21 18:54 UTC, eltinMeli commented
@nicolassalvanes y @pamalv7 hice merge de la development con esta branch, resolví el conflicto y migré los cambios de v2 a root, podrían verificar si falta algo? Gracias

2021-07-21 19:42 UTC, nicolassalvanes requested changes
@pamalv7 @abderossi en "other-payment-ways" de v1 PIX está antes que Boleto, pero en v2 está al revés.
Creo que estaría bueno dejarlo igual el orden en los dos lados, no? Dejamos primero PIX en v2?

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
> +> For an automated payment flow, [use MercadoPago.js V2 CardForm functionality](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/v2/receiving-payment-by-c
```suggestion
> For an automated payment flow, [use MercadoPago.js V2 CardForm functionality](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/receiving-payment-by-card).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
> +Both for frontend and backend, we recommend [our libraries](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/v2/previous-requirements#bookmark_always_use_
```suggestion
Both for frontend and backend, we recommend [our libraries](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/previous-requirements#bookmark_always_use_our_libraries) to collect user sensitive data securely.
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
> +> This documentation uses the new library version. To see the previous version, go to [integrate payment for cards with MercadoPago.js V1 section](https://www.mercadopago[FAKER][URL][DOMAIN]/develope
```suggestion
> This documentation uses the new library version. To see the previous version, go to [integrate payment for cards with MercadoPago.js V1 section](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/v1/receiving-payment-by-card).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
> +For this to work, you should configure your [private key]([FAKER][CREDENTIALS][URL]). Also, to interact with our APIs, you should use [Mercado Pago official SDK](https://www.mercadopago[FAKER][URL][D
```suggestion
For this to work, you should configure your [private key]([FAKER][CREDENTIALS][URL]). Also, to interact with our APIs, you should use [Mercado Pago official SDK](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/previous-requirements#bookmark__install_mercado_pago_sdk).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
> +We recommend using [response handling](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/v2/handling-responses) and the suggested communication in each cas
```suggestion
We recommend using [response handling](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/handling-responses) and the suggested communication in each case.
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
> +> [Test your integration](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/v2/testing)
```suggestion
> [Test your integration](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/testing)
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
> +> [Integrate other payment methods](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/v2/other-payment-ways)
```suggestion
> [Integrate other payment methods](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/other-payment-ways)
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
> +> Si quieres realizar un flujo automatizado del pago, te recomendamos [utilizar la funcionalidad CardForm de MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online
```suggestion
> Si quieres realizar un flujo automatizado del pago, te recomendamos [utilizar la funcionalidad CardForm de MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/receiving-payment-by-card).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
> +Tanto para el frontend como para el backend, recomendamos utilizar [nuestras librerías](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/v2/previous-requi
```suggestion
Tanto para el frontend como para el backend, recomendamos utilizar [nuestras librerías](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/previous-requirements#bookmark_utiliza_nuestras_librerías_siempre) para poder recolectar los datos sensibles de tus usuarios de manera segura.
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
> +> Esta documentación utiliza la nueva versión de la librería. Para ver la versión anterior, ve a la [sección de integrar pagos con tarjeta con MercadoPago.js V1](https://www.mercadopago[FAKER][URL][D
```suggestion
> Esta documentación utiliza la nueva versión de la librería. Para ver la versión anterior, ve a la [sección de integrar pagos con tarjeta con MercadoPago.js V1](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/v1/receiving-payment-by-card).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
> +Ten en cuenta que para que este paso funcione es necesario que configures tu [clave privada]([FAKER][CREDENTIALS][URL]) y que para interactuar con nuestras APIs recomendamos utilizar la [SDK oficial
```suggestion
Ten en cuenta que para que este paso funcione es necesario que configures tu [clave privada]([FAKER][CREDENTIALS][URL]) y que para interactuar con nuestras APIs recomendamos utilizar la [SDK oficial de Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/previous-requirements#bookmark__instala_la_sdk_de_mercado_pago).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
> +Te recomendamos usar los [mensajes de respuesta](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/v2/handling-responses) y utilizar la comunicación sugeri
```suggestion
Te recomendamos usar los [mensajes de respuesta](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/handling-responses) y utilizar la comunicación sugerida en cada uno de los casos.
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
> +> [Prueba tu integración](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/v2/testing)
```suggestion
> [Prueba tu integración](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/testing)
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
> +> [Integra otros medios de pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/v2/other-payment-ways)
```suggestion
> [Integra otros medios de pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/other-payment-ways)
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +> Caso deseje realizar um fluxo de pagamento automatizado, recomendamos você [utilizar a funcionalidade CardForm de MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides
```suggestion
> Caso deseje realizar um fluxo de pagamento automatizado, recomendamos você [utilizar a funcionalidade CardForm de MercadoPago.js V2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/receiving-payment-by-card).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +Tanto para o frontend como para o backend, recomendamos utilizar [nossos SDKs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/previous-requirements#b
```suggestion
Tanto para o frontend como para o backend, recomendamos utilizar [nossos SDKs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/previous-requirements#bookmark_sempre_utilize_nossas_bibliotecas) para poder coletar os dados sensíveis dos seus usuários de maneira segura.
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +> Esta documentação utiliza a nova versão da biblioteca. Para ver a versão anterior, vá para a [seção de integrar pagamentos com cartão com MercadoPago.js V1](https://www.mercadopago[FAKER][URL][DOMA
```suggestion
> Esta documentação utiliza a nova versão da biblioteca. Para ver a versão anterior, vá para a [seção de integrar pagamentos com cartão com MercadoPago.js V1](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v1/receiving-payment-by-card).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +Tenha em conta que para que esse passo funcione é necessário que configure sua [chave privada]([FAKER][CREDENTIALS][URL]) e que para interagir com nossas APIs recomendamos utilizar o [SDK oficial do
```suggestion
Tenha em conta que para que esse passo funcione é necessário que configure sua [chave privada]([FAKER][CREDENTIALS][URL]) e que para interagir com nossas APIs recomendamos utilizar o [SDK oficial do Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/previous-requirements#bookmark__instale_o_sdk_do_mercado_pago).
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +Te recomendamos usar as [mensagens de respostas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/handling-responses) e utilizar a comunicação sugerida
```suggestion
Te recomendamos usar as [mensagens de respostas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/handling-responses) e utilizar a comunicação sugerida em cada um dos casos.
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +> [Teste sua integração](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/testing)
```suggestion
> [Teste sua integração](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/testing)
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +> [Integrar outros meios de pagamento](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/other-payment-ways)
```suggestion
> [Integrar outros meios de pagamento](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/other-payment-ways)
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/testing.es.md
> +| Mastercard |  5808 8877 7464 1586| 123 | 11/25 |
```suggestion
| Mastercard |  5808 8877 7464 1586 | 123 | 11/25 |
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/testing.pt.md
> +| Mastercard |  5808 8877 7464 1586| 123 | 11/25 |
```suggestion
| Mastercard |  5808 8877 7464 1586 | 123 | 11/25 |
```

2021-07-21 19:42 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/receiving-payment-by-card.pt.md
> +Tanto para o frontend como para o backend, recomendamos utilizar [nossos SDKs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/previous-requirements#b
```suggestion
Tanto para o frontend como para o backend, recomendamos utilizar [nossos SDKs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/previous-requirements#bookmark_sempre_utilize_nossas_bibliotecas) para poder coletar os dados sensíveis dos seus usuários de maneira segura.
```

2021-07-22 17:34 UTC, eltinMeli commented on guides/online-payments/checkout-api/testing.es.md
> +| Mastercard |  5808 8877 7464 1586| 123 | 11/25 |
Cambió!

2021-07-22 17:35 UTC, eltinMeli commented on guides/online-payments/checkout-api/testing.pt.md
> +| Mastercard |  5808 8877 7464 1586| 123 | 11/25 |
Cambió!

2021-07-22 17:45 UTC, eltinMeli commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +> [Teste sua integração](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/testing)
Cambió

2021-07-22 17:45 UTC, eltinMeli commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
> +> [Integrar outros meios de pagamento](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/other-payment-ways)
Cambió

2021-07-22 17:48 UTC, eltinMeli commented on guides/online-payments/checkout-api/receiving-payment-by-card.pt.md
> +Tanto para o frontend como para o backend, recomendamos utilizar [nossos SDKs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/v2/previous-requirements#b
Cambió

2021-07-26 16:08 UTC, nicolassalvanes commented
> @pamalv7 @abderossi en "other-payment-ways" de v1 PIX está antes que Boleto, pero en v2 está al revés.
> Creo que estaría bueno dejarlo igual el orden en los dos lados, no? Dejamos primero PIX en v2?

Veo todo bien, pero queda resolver esta duda. @pamalv7 @abderossi les dejo a ustedes el approve

2021-07-28 16:57 UTC, elvisjhonataoliveira requested changes

2021-07-28 16:57 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/advanced-integration.en.md
> -```
Não deveríamos remover essa parte. Sem esse fechamento, não será exibido corretamente o componente.

2021-07-28 16:57 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/other-features.en.md
> -```
Não deveríamos remover essa parte. Sem esse fechamento, não será exibido corretamente o componente.

2021-07-28 16:57 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/other-features.es.md
> -```
Não deveríamos remover essa parte. Sem esse fechamento, não será exibido corretamente o componente.

2021-07-28 16:57 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/other-features.pt.md
> -```
Não deveríamos remover essa parte. Sem esse fechamento, não será exibido corretamente o componente.

2021-07-29 12:40 UTC, nicolassalvanes requested changes

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/advanced-integration.en.md
> -```
Hola Elvito! Está bien, está removiendo todo el snippet:
```
```javascript
doSubmit = false;
addEvent(document.querySelector('#pay'),'submit', doPay);function doPay(event){
    event.preventDefault();
    if(!doSubmit){
        var $form = document.querySelector('#pay');

        Mercadopago.createToken($form, sdkResponseHandler);
        return false;
    }
};
```
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.en.md
> +1. [Log in](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/pre
Este cambio quedó mal, puede ser que se haya hecho por error?
```suggestion
1. [Log in](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/wix) to a Mercado Pago account or [create a new account](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) if you don't have one yet.
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.en.md
> +3. Select the maximum number of interest free instalments you want to offer.
```suggestion
1. Log in [your Mercado Libre account](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp), and go to "Your business".
2. Go to "Costs" section.
3. Browse up to "interest free instalments" and click on the activation switch.
4. Select the maximum number of interest free instalments you want to offer.
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.es.md
> +1. [Ingresa](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/pr
```suggestion
1. [Ingresa](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/wix) a una cuenta de Mercado Pago o ----[mla, mlb, mlm, mlc]----[crea una nueva](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing)------------ ----[mco, mpe]----[crea una nueva](https://www.mercadopago[FAKER][URL][DOMAIN]/registration-mp)------------ si todavía no tienes una.
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.es.md
> +----[mla, mlb, mlc, mlu, mpe]----
```suggestion
----[mla, mlb, mlc, mlu, mpe, mco]----
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.es.md
> +3. Selecciona la cantidad máxima de mensualidades sin intereses que deseas ofrecer.
```suggestion
1. Ingresa a [tu cuenta de Mercado Pago](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp) y ve a "Tu negocio".
2. Accede en la sección "Costos".
3. Navega hasta "mensualidades sin intereses" y haz clic en el switch para activarlos.
4. Selecciona la cantidad máxima de mensualidades sin intereses que deseas ofrecer.
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.pt.md
> +1. [Entre](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/prev
```suggestion
1. [Acesse](https://www.mercadolibre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp&go=https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/unofficial/wix) sua conta Mercado Pago ou [crie uma](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) caso ainda não tenha.
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.pt.md
> +----[mla, mlc, mlu, mpe]----
```suggestion
----[mla, mlc, mlu, mpe, mco]----
```

2021-07-29 12:40 UTC, nicolassalvanes commented on guides/plugins/unofficial/wix.pt.md
> +3. Selecione o valor máximo de parcelas sem acréscimo que você deseja oferecer.
```suggestion
1. Acesse sua [conta do Mercado Pago](https://www.mercadolivre.com/jms/[FAKER][GLOBALIZE][SITE_ID]/lgz/login?platform_id=mp) e clique em "Seu negócio".
2. Acesse a seção "Custos".
3. Navegue até "Parcelas sem acréscimo" e clique no botão para ativá-las.
4. Selecione o valor máximo de parcelas sem acréscimo que você deseja oferecer.
```

2021-07-29 14:11 UTC, eltinMeli commented on guides/online-payments/checkout-api/other-features.en.md
> -```
Cambió

2021-07-29 14:11 UTC, eltinMeli commented on guides/online-payments/checkout-api/other-features.pt.md
> -```
Cambió

2021-07-29 15:31 UTC, nicolassalvanes approved these changes

2021-07-29 16:56 UTC, elvisjhonataoliveira approved these changes

2021-07-29 16:56 UTC, merged