wording changes for subscription section
mercadopago/devsite-docs pull request #1213
Opened 2021-07-06 17:15 UTC by rcrespillio-ml

## Description
Wording changes to keep clear the differences between "subscriptions" and "subscription plans" for english and spanish languages.
Brief from Content: [https://docs.google.com/document/d/1QzsOboz8hQAVJ5Oxx8jHLHylt2LLRN_o5SzO39nJB9s/edit#](https://docs.google.com/document/d/1QzsOboz8hQAVJ5Oxx8jHLHylt2LLRN_o5SzO39nJB9s/edit#
)

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-07-08 03:21 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.es.md
> +> ¿Quieres ofrecer suscripciones de forma rápida y simple?
¿En inglés no deberíamos alinear a _offer_?

2021-07-08 03:22 UTC, pamalv7 commented
@rcrespillio-ml ¿Por qué no estamos sumando cambios en los contenidos de portugués? Según el documento compartido, existen.

2021-07-08 12:29 UTC, rcrespillio-ml commented on guides/online-payments/subscriptions/introduction.es.md
> +> ¿Quieres ofrecer suscripciones de forma rápida y simple?
Tomé e apliqué esta sugerencia

2021-07-08 12:30 UTC, rcrespillio-ml commented
> @rcrespillio-ml ¿Por qué no estamos sumando cambios en los contenidos de portugués? Según el documento compartido, existen.

Se agregaron luego de realizado en PR. Gracias por levantarlo, ya agregué ahora si esas modificaciones en portugués también.

2021-07-14 16:04 UTC, abderossi commented on guides/online-payments/subscriptions/introduction.es.md
> +> Ingresa en la sección de [Planes de suscripción](https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans) en el panel de tu cuenta de Mercado Pago, configura tus datos ¡y listo!
Entiendo que la URL sea Suscription Plans y por eso el cambio, pero al entrar al link la sección se sigue llamando Suscripciones. ¿No deberíamos alinearlo tal cual se ve al hacer clic?

2021-07-14 16:06 UTC, abderossi reviewed
Hola @rcrespillio-ml ! Dejé una sugerencia de cambio para el link a Suscripciones. En caso de aplicarlo, habría que replicarlo en los tres idiomas.

2021-07-14 16:38 UTC, rcrespillio-ml commented on guides/online-payments/subscriptions/introduction.es.md
> +> Ingresa en la sección de [Planes de suscripción](https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans) en el panel de tu cuenta de Mercado Pago, configura tus datos ¡y listo!
Si, pero se va a alinear del lado de la app. El cambio ya está tomado y en poco queda productivo. 
Los nombres van a quedar como detalla la img de abajo
![Screen Shot 2021-07-14 at 13 37 32](https://user-images.githubusercontent.com/58994852/125659525-4e9375d6-001f-4649-ae49-1a62b38324d6.png)

2021-07-14 16:43 UTC, rcrespillio-ml commented
> Hola @rcrespillio-ml ! Dejé una sugerencia de cambio para el link a Suscripciones. En caso de aplicarlo, habría que replicarlo en los tres idiomas.

Buenas, en la app el cambio ya está tomado y en poco queda productivo. Así que acá debería quedar como Planes de suscripción para que queden igual de los dos lados. 

Antes (En prod ahora pero se va a reemplazar)
![Screen Shot 2021-07-14 at 13 42 24](https://user-images.githubusercontent.com/58994852/125660203-53cb6432-0c31-4eff-9f4e-7ae93d56ecc0.png)

Con los cambios nuevos:
![image](https://user-images.githubusercontent.com/58994852/125660140-6fcfd9a8-078f-4a32-9b14-363265156cbc.png)

2021-07-14 16:49 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.es.md
> +> Ingresa en la sección de [Planes de suscripción](https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans) en el panel de tu cuenta de Mercado Pago, configura tus datos ¡y listo!
¡Gracias por la explicación Rodri! ☺️

2021-07-14 17:25 UTC, pamalv7 requested changes

2021-07-14 17:25 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.en.md
>  > Enter the [Subscriptions](https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans) section on your Mercado Pago account panel, set the data you need and that's it!
```suggestion
> Enter the [Subscriptions plan](https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans) section on your Mercado Pago account panel, set the data you need and that's it!
```

2021-07-14 17:54 UTC, abderossi approved these changes

2021-07-14 19:05 UTC, abderossi commented on guides/online-payments/subscriptions/introduction.es.md
> +> Ingresa en la sección de [Planes de suscripción](https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans) en el panel de tu cuenta de Mercado Pago, configura tus datos ¡y listo!
Perfecto, gracias @rcrespillio-ml !

2021-07-14 19:05 UTC, abderossi approved these changes

2021-07-14 21:02 UTC, pamalv7 approved these changes

2021-07-15 13:37 UTC, merged