Disponibilizada la documentacion de Wix para hispanos y fue actualiza…
mercadopago/devsite-docs pull request #1217
Opened 2021-07-14 14:20 UTC by etellez-MeLi

Disponibilizada la documentacion de Wix para hispanos y fue actualizada para BR, se añadieron las novedades al changelog

2021-07-14 17:49 UTC, pamalv7 requested changes

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +## 15 de Julho
```suggestion
## 15 de julho
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> + CHANGELOG
```suggestion
> CHANGELOG
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +> NEWS: NUEVA VERSIÓN
```suggestion
> NEW_VERSION: NOVA VERSÃO
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +> PRODUCT: MERCADO PAGO
```suggestion
> PRODUCT: WIX

```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> + CHANGELOG
```suggestion
> CHANGELOG
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> Disponibilizamos Wix como medio de pago.
```suggestion
> Disponibilizamos Wix como medio de pago
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +Ahora puedes integrar Mercado Pago en tu comercio Wix. Con ella, puedes ofrecer a tus clientes la posibilidad de pagar directamente en el sitio de Mercado Pago.
@abderossi  Gosti, ¿con ella que? No me queda muy claro

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> NEWS: NOVEDADES
```suggestion
> NEW_VERSION: NUEVA VERSIÓN
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +[Ir a la documentación de Wix] (https://www.mercadopago[FAKER][URL][DOMAIN]/ developers/es/guides/plugins/unofficial/wix)
```suggestion
[Ir a la documentación de Wix](https://www.mercadopago[FAKER][URL][DOMAIN]/ developers/es/guides/plugins/unofficial/wix)
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +### 15 de Julio
```suggestion
### 15 de julio
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> PRODUCTO: WIX
```suggestion
> PRODUCT: WIX

```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> PRODUCT: WIX
```suggestion
> PRODUCT: WIX

```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +> PRODUCT: WIX
```suggestion
> PRODUCT: WIX

```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +----[mla,mlc,mco,mpe,mlu]----
```suggestion
----[mla, mlc, mco, mpe, mlu]----
```
Siempre van con espacios.

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +---- [mlb] ----
```suggestion
----[mlb]----
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +----[mla,mlc,mco,mpe,mlu]----
```suggestion
----[mla, mlc, mco, mpe, mlu]----
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +----[mla,mlc,mco,mpe,mlu]----
```suggestion
----[mla, mlc, mco, mpe, mlu]----
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> + CHANGELOG
```suggestion
> CHANGELOG
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> PRODUCT: WIX
```suggestion
> PRODUCT: WIX

```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> NEWS: NEWS
```suggestion
> NEW_VERSION: NEW VERSION
```

2021-07-14 17:49 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +> PRODUCT: WIX
```suggestion
> PRODUCT: WIX

```

2021-07-14 17:51 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +> Disponibilizamos Wix como medio de pago.
¿No alineamos el título al resto que menciona Checkout Pro?

2021-07-19 21:30 UTC, abderossi commented on guides/plugins/unofficial/wix.pt.md
> +Com ela você poderá, oferecer aos seus clientes a possibilidade de pagar diretamente no site do Mercado Pago.
```suggestion
Com ela você poderá oferecer aos seus clientes a possibilidade de pagar diretamente no site do Mercado Pago.
```

2021-07-19 21:52 UTC, abderossi commented on guides/plugins/unofficial/wix.es.md
> +1. En la lista de medios de pago, da clic en 'Conectar' en Mercado Pago.
```suggestion
1. En la lista de medios de pago, da clic en "Conectar" en Mercado Pago.
```

2021-07-19 21:55 UTC, abderossi commented on guides/plugins/unofficial/wix.es.md
> +1. Completa los campos Client ID y Client Secret con las [credenciales de producción]([FAKER][CREDENTIALS][URL]) de tu cuenta de Mercado Pago.
```suggestion
1. En la sección "Información de la cuenta", completa los campos Client ID y Client Secret con las [credenciales de producción]([FAKER][CREDENTIALS][URL]) de tu cuenta de Mercado Pago.
```

2021-07-19 23:24 UTC, abderossi commented on guides/plugins/unofficial/wix.es.md
> +1. Completa los campos Client ID y Client Secret con las [credenciales de producción]([FAKER][CREDENTIALS][URL]) de tu cuenta de Mercado Pago.
```suggestion
1. En la sección "Información de la cuenta", completa los campos Client ID y Client Secret con las [credenciales de producción]([FAKER][CREDENTIALS][URL]) de tu cuenta de Mercado Pago.
```

2021-07-19 23:25 UTC, abderossi commented on guides/plugins/unofficial/wix.es.md
> +1. En la lista de medios de pago, da clic en 'Conectar' en Mercado Pago.
```suggestion
1. En la lista de medios de pago, busca a Mercado Pago y haz clic en "Conectar".
```

2021-07-20 15:28 UTC, abderossi commented on guides/resources/changelog/current-year.en.md
> +Now you can integrate Mercado Pago into your Wix store. With it, you can offer your customers the possibility to pay directly on the Mercado Pago site.
```suggestion
Now you can integrate Mercado Pago into your Wix store. With this virtual platform, you can offer your customers the possibility to pay directly on the Mercado Pago site.
```

2021-07-20 15:29 UTC, abderossi commented on guides/resources/changelog/current-year.es.md
> +Ahora puedes integrar Mercado Pago en tu comercio Wix. Con ella, puedes ofrecer a tus clientes la posibilidad de pagar directamente en el sitio de Mercado Pago.
```suggestion
Ahora puedes integrar Mercado Pago en tu comercio Wix. Con esta plataforma virtual puedes ofrecer a tus clientes la posibilidad de pagar directamente en el sitio de Mercado Pago.
```

2021-07-20 15:30 UTC, abderossi commented on guides/resources/changelog/current-year.pt.md
> +Agora você pode integrar o Mercado Pago em sua loja Wix. Com ele, você pode oferecer aos seus clientes a possibilidade de pagar diretamente no site do Mercado Pago.
```suggestion
Agora você pode integrar o Mercado Pago em sua loja Wix. Com esta plataforma virtual, você pode oferecer aos seus clientes a possibilidade de pagar diretamente no site do Mercado Pago.
```

2021-07-20 16:16 UTC, closed without merging

2021-07-20 16:16 UTC, abderossi commented
Cerramos este PR porque lo trasladamos a este: https://github.com/mercadopago/devsite-docs/pull/1225