docs(wallet button): explain new feature wallet button for woocommerce
mercadopago/devsite-docs pull request #1220
Opened 2021-07-16 12:32 UTC by lira

## Description
New feature for WooCommerce, the buyer can use blue money with Wallet Button

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-07-16 13:24 UTC, SalehKhalilMP approved these changes

2021-07-28 16:02 UTC, abderossi commented on guides/plugins/woocommerce/introduction.es.md
> +| Pago con tarjetas guardadas en Mercado Pago | Función de Pago con tarjeta guardada en Mercado Pago, para que los clientes de Mercado Pago puedan comprar sin tener que rellenar los datos de tarjeta
```suggestion
| Pago con tarjetas guardadas en Mercado Pago | Permite que los clientes de Mercado Pago puedan comprar con los datos guardados de su tarjeta, sin tener que rellenar los datos en el checkout de la tienda. |
```

2021-07-28 18:45 UTC, abderossi commented on guides/plugins/woocommerce/introduction.pt.md
> +| Pagamento com cartões salvos no Mercado Pago  | Função Pagamento com cartão salvo no Mercado Pago, para clientes do Mercado Pago comprarem sem precisar preencher dados do cartão no checkout da loja
```suggestion
| Pagamento com cartões salvos no Mercado Pago  | Permite que os clientes do Mercado Pago comprem com os dados do cartão, sem precisar preencher dados do cartão no checkout da loja. |
```

2021-07-28 18:50 UTC, abderossi commented on guides/plugins/woocommerce/preferences.en.md
> +| Payment with stored cards | Payment with card stored in Mercado Pago function, for Mercado Pago customers to buy without having to fill in card data at the store's checkout. |
```suggestion
| Payment with stored cards | Allows customers to use their card data saved in Mercado Pago without having to fill in card data at the store's checkout. |
```

2021-07-28 18:52 UTC, abderossi commented on guides/plugins/woocommerce/preferences.es.md
> +| Pago con tarjetas guardadas | Función de Pago con tarjeta guardada en Mercado Pago, para que los clientes de Mercado Pago puedan comprar sin tener que rellenar los datos de tarjeta en el checkout d
```suggestion
| Pago con tarjetas guardadas | Permite que los clientes puedan comprar con los datos guardados de su tarjeta en Mercado Pago, sin tener que rellenar los datos en el checkout de la tienda. |
```

2021-07-28 18:52 UTC, abderossi commented on guides/plugins/woocommerce/preferences.pt.md
> +| Pagamento com cartões salvos | Função Pagamento com cartão salvo no Mercado Pago, para clientes do Mercado Pago comprarem sem precisar preencher dados do cartão no checkout da loja |
```suggestion
| Pagamento com cartões salvos | Permite que os clientes comprem com os dados do cartão guardados no Mercado Pago, sem precisar preencher dados do cartão no checkout da loja. |
```

2021-07-28 18:54 UTC, abderossi commented on guides/plugins/woocommerce/introduction.en.md
> +| Payment with card stored in Mercado Pago  | Payment with card stored in Mercado Pago function, for Mercado Pago customers to buy without having to fill in card data at the store's checkout. |
```suggestion
| Payment with card stored in Mercado Pago  | Allows customers to use their card data saved in Mercado Pago without having to fill in card data at the store's checkout. |
```

2021-07-28 18:55 UTC, abderossi requested changes
Ajuste de wording para alinear la descripción con la tabla.

2021-07-29 11:37 UTC, elvisjhonataoliveira approved these changes

2021-07-29 11:39 UTC, merged