fix/vtex/nuevos-medios-pago-v2
mercadopago/devsite-docs pull request #1244
Opened 2021-07-30 22:34 UTC by douglas-cruz

Hola Gosti y Pame

Estoy enviando el PR sobre la nueva versión del gateway MercadoPagoV2 en VTEX para MLB, que incluye Boleto Bancario, Checkout Pro, Checkout WalletButton y Medios Off como medio de pago disponible. 

Contexto
Se incluyó Boleto Bancario, Checkout Pro, Checkout WalletButton y Medios Off como medio de pago en VTEX a través de la afiliación del gateway MercadoPagoV2. Esta nueva versión de gateway permite nuevas features que ofrece Mercado Pago, mientras que MercadoPagoV1 te permite aceptar pagos con tarjeta de crédito

## Description

In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-08-05 19:44 UTC, pamalv7 requested changes

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +> Lembre-se que o gateway MercadoPagoV1 adiciona apenas a condição de pagamento Cartão de Crédito.
```suggestion
> Lembre-se que o gateway MercadoPagoV1 adiciona apenas a condição de pagamento cartão de crédito.
```

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +> Lembre-se que o gateway MercadoPagoV2 por enquanto adiciona apenas as condições de pagamento Boleto Bancário, Pix, Mercado Pago Offline e Checkout Pro.
```suggestion
> Lembre-se que o gateway MercadoPagoV2 por enquanto adiciona apenas as condições de pagamento boleto bancário, Pix, Mercado Pago Offline e Checkout Pro.
```

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
>  1. No painel de administração de sua loja, acesse "Configurações" do módulo de pagamentos.
```suggestion
1. No painel de administração de sua loja, acesse “Configurações do módulo de pagamentos”.
```

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +4. Preencha os campos correspondentes.
```suggestion
4. Preencha os campos correspondentes:
```

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +| Métodos de pagamento excluídos - Métodos de pago excluídos (visa, paypal, bolbradesco, oxxo...) | Métodos de pagamento a serem excluídos no momento da compra. |
```suggestion
| Métodos de pagamento excluídos - Métodos de pago excluídos (Visa, Paypal, Bolbradesco, OXXO e outros) | Métodos de pagamento a serem excluídos no momento da compra. |
```

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +| Tipos de pagamento excluídos - Tipos de pago excluidos (credit_card, bank_transfer, ticket...) | Tipos de pagamento a serem excluídos no momento da compra. |
```suggestion
| Tipos de pagamento excluídos - Tipos de pago excluidos (credit_card, bank_transfer, ticket e outros) | Tipos de pagamento a serem excluídos no momento da compra. |
```

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +> Certifique em sua loja de aplicativos da VTEX se o App **Mercado Pago Payment APP** esteja instalado para utilização das condições de pagamento **MercadoPagoOff, MercadoPagoPro e MercadoPagoWallet*
```suggestion
> Certifique em sua loja de aplicativos da VTEX se o app **Mercado Pago Payment APP** esteja instalado para utilização das condições de pagamento **MercadoPagoOff, MercadoPagoPro e MercadoPagoWallet** ou solicite a instalação pela equipe VTEX sob demanda através de ticket no [Support VTEX](https://support.vtex.com). <br>
```

2021-08-05 19:44 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +Para criar uma **condição de pagamento Mercado Pago Offline, onde poderá contar com Boleto Bancário e Pagamentos com PEC (em lotéricas), utilizando sua afiliação com o MercadoPagoV2**, siga os passos
```suggestion
Para criar uma **condição de pagamento Mercado Pago Offline, onde poderá contar com boleto bancário e pagamentos com PEC (em lotéricas), utilizando sua afiliação com o MercadoPagoV2**, siga os passos abaixo:
```

2021-08-05 20:50 UTC, douglas-cruz commented on guides/plugins/unofficial/vtex.pt.md
> +| Métodos de pagamento excluídos - Métodos de pago excluídos (visa, paypal, bolbradesco, oxxo...) | Métodos de pagamento a serem excluídos no momento da compra. |
Pame,
Una duda, tiene sentido agregar estos ajustes, pregunto porque el panel en Vtex está como (visa, paypal, bolbradesco, oxxo...)

2021-08-05 20:50 UTC, douglas-cruz commented on guides/plugins/unofficial/vtex.pt.md
> +| Tipos de pagamento excluídos - Tipos de pago excluidos (credit_card, bank_transfer, ticket...) | Tipos de pagamento a serem excluídos no momento da compra. |
Pame,
Una duda, tiene sentido agregar estos ajustes, pregunto porque el panel en Vtex está como (credit_card, bank_transfer, ticket...)

2021-08-05 20:53 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +| Métodos de pagamento excluídos - Métodos de pago excluídos (visa, paypal, bolbradesco, oxxo...) | Métodos de pagamento a serem excluídos no momento da compra. |
En realidad, deberían ir con mayúscula porque son marcas. En el caso que quieras tomar algo literal que está en VTEX, le podemos poner comillas ("").

2021-08-05 20:53 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +| Tipos de pagamento excluídos - Tipos de pago excluidos (credit_card, bank_transfer, ticket...) | Tipos de pagamento a serem excluídos no momento da compra. |
En realidad, así debería ir por manual; los tres puntos dejan más dudas que certezas. En el caso que quieras tomar algo literal que está en VTEX, le podemos poner comillas ("").

2021-08-05 20:53 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +| Métodos de pagamento excluídos - Métodos de pago excluídos (visa, paypal, bolbradesco, oxxo...) | Métodos de pagamento a serem excluídos no momento da compra. |
Sumo a la duda a @abderossi

2021-08-05 22:50 UTC, douglas-cruz commented on guides/plugins/unofficial/vtex.pt.md
> +| Métodos de pagamento excluídos - Métodos de pago excluídos (visa, paypal, bolbradesco, oxxo...) | Métodos de pagamento a serem excluídos no momento da compra. |
Se ve muy bien, podríamos seguir así?

2021-08-05 22:51 UTC, douglas-cruz commented on guides/plugins/unofficial/vtex.pt.md
> +| Tipos de pagamento excluídos - Tipos de pago excluidos (credit_card, bank_transfer, ticket...) | Tipos de pagamento a serem excluídos no momento da compra. |
Se ve muy bien, podríamos seguir así también ?

2021-08-09 21:17 UTC, abderossi commented on guides/plugins/unofficial/vtex.pt.md
> +5. e clique em "Salvar".
```suggestion
5. Clique em "Salvar".
```

2021-08-09 21:32 UTC, abderossi commented on guides/plugins/unofficial/vtex.pt.md
>  #### Configuração do meio de pagamento Mercado Pago Wallet
```suggestion
### Configuração do meio de pagamento Mercado Pago Wallet
```

2021-08-09 21:33 UTC, abderossi commented on guides/plugins/unofficial/vtex.pt.md
>  #### Configuração do meio de pagamento Mercado Pago Wallet
@douglas-cruz Puede ser que Mercado Pago Wallet tenga que tener la misma jerarquía que los otros medios de pago?

2021-08-09 21:33 UTC, abderossi commented on guides/plugins/unofficial/vtex.pt.md
>  #### Configuração do meio de pagamento Mercado Pago PRO
```suggestion
### Condição de pagamento Mercado Pago PRO
```

2021-08-09 21:34 UTC, abderossi commented on guides/plugins/unofficial/vtex.pt.md
>  #### Configuração do meio de pagamento Mercado Pago PRO
@douglas-cruz Cambié Configuração do meio por Condiçao porque así mencionamos los otros medios de pago en la documentación.
También, puede ser que tengan que ser un ### como Pix y otros medios de pago?

2021-08-09 21:39 UTC, abderossi commented on guides/plugins/unofficial/vtex.pt.md
> +> Certifique em sua loja de aplicativos da VTEX se o app **Mercado Pago Payment APP** esteja instalado para utilização das condições de pagamento **MercadoPagoOff, MercadoPagoPro e MercadoPagoWallet*
@douglas-cruz Consulta: "Mercado Pago Payment APP" es el nombre del producto? Queda una repetición de la palabra APP en la misma oración. Podemos mencionarla como Mercado Pago Payment? Gracias!

2021-08-09 21:40 UTC, abderossi requested changes
@douglas-cruz dejé algunos ajustes y algunas dudas sobre la jerarquía de los títulos para los nuevos medios de pago. 
Falta sumar changelog. Dejé algunos ajustes en el brief. ¿Podrías adicionarlo a este pr? ¡Gracias!

2021-08-10 19:05 UTC, abderossi commented on guides/plugins/unofficial/vtex.pt.md
> +> Certifique em sua loja de aplicativos da VTEX se o app **Mercado Pago Payment APP** esteja instalado para utilização das condições de pagamento **MercadoPagoOff, MercadoPagoPro e MercadoPagoWallet*
```suggestion
> Certifique em sua loja de aplicativos da VTEX se o **Mercado Pago Payment APP** esteja instalado para utilização das condições de pagamento **MercadoPagoOff, MercadoPagoPro e MercadoPagoWallet** ou solicite a instalação pela equipe VTEX sob demanda através de ticket no [Support VTEX](https://support.vtex.com). <br>
```

2021-08-10 21:04 UTC, abderossi approved these changes

2021-08-11 20:05 UTC, pamalv7 approved these changes

2021-08-11 20:05 UTC, merged