Warning WooCommerce vulnerability
mercadopago/devsite-docs pull request #1247
Opened 2021-08-05 14:37 UTC by FaraboliniMeli

## Description
Adding Warning box about WooCommerce vulnerability

### Checklist:
- [ ] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.
- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-08-05 19:54 UTC, pamalv7 reviewed
Dejo sugerencias de contenido.

2021-08-05 19:54 UTC, pamalv7 commented on guides/plugins/woocommerce/introduction.es.md
> +> Aviso: El 13/07/21, WooCommerce notificó a sus clientes que algunas de sus versiones resultan vulnerables. Las correcciones necesarias ya se han realizado en la última actualización. Por lo tanto,
```suggestion
> El 13 de julio del 2021, WooCommerce notificó a sus clientes que algunas de sus versiones resultan vulnerables. Las correcciones necesarias ya se han realizado en la última actualización. Por lo tanto, es **muy importante que tu tienda tenga la última versión de WooCommerce actualizada** para evitar la exposición de información sensible. Más información en el [WooCommerce blog](https://woocommerce.com/pt-br/posts/critical-vulnerability-detected-july-2021).
```

2021-08-05 19:54 UTC, pamalv7 commented on guides/plugins/woocommerce/introduction.es.md
> +> Importante
```suggestion
> Aviso importante
```

2021-08-05 21:39 UTC, pbracale commented on guides/plugins/woocommerce/introduction.es.md
> +> Aviso: El 13/07/21, WooCommerce notificó a sus clientes que algunas de sus versiones resultan vulnerables. Las correcciones necesarias ya se han realizado en la última actualización. Por lo tanto,
Não. O link está escrito em inglês e é a única versão existente.

2021-08-05 21:49 UTC, pamalv7 requested changes
Falta alinear contenidos entre idiomas.

2021-08-09 21:44 UTC, abderossi commented on guides/plugins/woocommerce/introduction.en.md
> +> Important
```suggestion
> Important announcement
```

2021-08-09 21:46 UTC, abderossi commented on guides/plugins/woocommerce/introduction.en.md
> +> Attention: On 7/13/21, WooCommerce notified its customers that some of its versions are vulnerable. The necessary fixes were already made in the last update. Therefore, it is **very important that
```suggestion
> On July 13th 2021, WooCommerce notified its customers that some of its versions were vulnerable. The necessary fixes were already made in the last update. Therefore, it is **very important that your store has the latest version of WooCommerce updated** to prevent exposure of sensitive information. For more information, see the [WooCommerce blog.](https://woocommerce.com/pt-br/posts/critical-vulnerability-detected-july-2021/)
```

2021-08-09 21:46 UTC, abderossi commented on guides/plugins/woocommerce/introduction.pt.md
> +> Importante
```suggestion
> Aviso importante
```

2021-08-09 21:47 UTC, abderossi commented on guides/plugins/woocommerce/introduction.pt.md
> +> Atenção: Em 13/07/21, o WooCommerce notificou seus clientes de que algumas de suas versões estão vulneráveis. As correções necessárias já foram feitas na última atualização. Por isso, é **muito imp
```suggestion
> Em 13 de julho de 2021, o WooCommerce notificou seus clientes de que algumas de suas versões são vulneráveis. As correções necessárias já foram feitas na última atualização. Por isso, é **muito importante que sua loja esteja com a última versão do WooCommerce atualizada** para prevenir a exposição de informações sensíveis. Para obter mais informações, consulte o [blog do Woocommerce](https://woocommerce.com/pt-br/posts/critical-vulnerability-detected-july-2021/).
```

2021-08-09 21:49 UTC, abderossi requested changes
Consulté los cambios de wording con Lucas Felisberto Dos Reis. Aprobó las modificaciones, por lo que las repliqué en los otros dos idiomas.

2021-08-11 18:18 UTC, abderossi approved these changes

2021-08-11 18:18 UTC, pbracale approved these changes

2021-08-11 18:18 UTC, abderossi approved these changes

2021-08-11 18:19 UTC, pamalv7 approved these changes

2021-08-11 18:19 UTC, merged