Major doc update para seller behavior
mercadopago/devsite-docs pull request #1258
Opened 2021-08-13 15:47 UTC by pbracale

Foram realizadas as seguintes alterações:

- Atualização da doc de perguntas frequentes de credenciais (foram excluídas as perguntas e foi criado um texto explicativo).

- Criação de nova página com documentação do. DevPanel

- Atualização de todas as referencias à credenciais nas documentações dos plugins e plataformas (e outras) de forma que estas fossem enviadas para a nova doc de credenciais.

2021-08-16 17:23 UTC, rwaetemann commented on guides/in-person-payments/qr-code/pre-requisites.pt.md
> +> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 17:24 UTC, rwaetemann commented on guides/in-person-payments/qr-code/pre-requisites.pt.md
> +> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
Pri, como aqui estamos falando de "informações", acredito que o ideal seja usarmos "mais". O que acha?

2021-08-16 17:25 UTC, rwaetemann commented on guides/online-payments/checkout-api/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 17:25 UTC, rwaetemann commented on guides/online-payments/checkout-api/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
@pbracale mesma coisa aqui :)

2021-08-16 17:25 UTC, pbracale commented on guides/in-person-payments/qr-code/pre-requisites.pt.md
> +> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
Perfeito! Se quiser alterar tudo, manda ver!!!

2021-08-16 17:26 UTC, rwaetemann commented on guides/online-payments/checkout-api/v1/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 17:26 UTC, rwaetemann commented on guides/online-payments/checkout-api/v1/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
@pbracale - o mesmo nessa aqui.

2021-08-16 17:27 UTC, rwaetemann commented on guides/online-payments/checkout-api/v2/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 17:27 UTC, rwaetemann commented on guides/online-payments/checkout-api/v2/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
@pbracale +1

2021-08-16 17:28 UTC, rwaetemann commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 17:28 UTC, rwaetemann commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
+1

2021-08-16 17:59 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-api/introduction.pt.md
> +> Possui alguma dúvida? Consulte nossas Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Possui alguma dúvida? Consulte nossas Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações.
```

2021-08-16 18:00 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/introduction.pt.md
> +> Possui alguma dúvida? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Possui alguma dúvida? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações.
```

2021-08-16 18:02 UTC, rwaetemann commented on guides/online-payments/mobile-checkout/latest/introduction.pt.md
> +> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 18:02 UTC, rwaetemann commented on guides/online-payments/subscriptions/previous-requirements.pt.md
> +>Dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
>Dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 18:03 UTC, rwaetemann commented on guides/online-payments/web-tokenize-checkout/receiving-payment-by-card.pt.md
> +> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 18:04 UTC, rwaetemann commented on guides/online-payments/web-tokenize-checkout/v1/receiving-payment-by-card.pt.md
> +> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 18:04 UTC, rwaetemann commented on guides/plugins/official/magento-two.pt.md
> +> * Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para maiores informações.
```suggestion
> * Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações. 
```

2021-08-16 18:05 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +To start receiving payments, you must activate your credentials.
@pbracale - Pri, aqui deveria ter o link para direcionar para a página de credenciais?

2021-08-16 18:05 UTC, rwaetemann commented on guides/plugins/official/shopify.es.md
> +Para empezar a cobrar debes activar tus credenciales.
@pbracale - mesma coisa aqui.

2021-08-16 18:06 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +Para começar a receber pagamentos, você deve ativar suas credenciais.
@pbracale - +1

2021-08-16 18:07 UTC, pbracale commented on guides/plugins/official/shopify.en.md
> +To start receiving payments, you must activate your credentials.
Não, aí deveria ser um link para um documento de passo a passo para ir à produção. Mas, esse doc não existe (ainda). E, como é a doc do Shopify que vamos melhorar ainda nesse Q, podemos deixar passar por enquanto.

2021-08-16 18:08 UTC, pbracale commented on guides/plugins/official/shopify.es.md
> +Para empezar a cobrar debes activar tus credenciales.
Mesmo comentário do anterior.

2021-08-16 18:08 UTC, pbracale commented on guides/plugins/official/shopify.pt.md
> +Para começar a receber pagamentos, você deve ativar suas credenciais.
Idem anterior.

2021-08-16 18:23 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +To start receiving payments, you must activate your credentials.
Boa, obrigado, Pri!

2021-08-16 18:27 UTC, rwaetemann commented on guides/plugins/prestashop/integration.en.md
> +> The [credentials]() are the keys that uniquely identify you within the platform. To operate in a **test environment** with which to simulate online payments, use the test credentials. Use **product
```suggestion
> The [credentials]() are the keys that uniquely identify you within the platform. To operate in a **test environment** in order to simulate online payments, use the test credentials. To receive real payments, use **production** credentials.
```

2021-08-16 18:31 UTC, rwaetemann commented on guides/plugins/prestashop/integration.es.md
> +> Las  [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/credentials/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en
```suggestion
> Las  [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/credentials/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en un **entorno de pruebas** y simular pagos online, utiliza las credenciales de prueba. Para recibir pagos reales, usa las credenciales de **producción**.
```

2021-08-16 18:32 UTC, rwaetemann commented on guides/plugins/prestashop/integration.pt.md
> +> As [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) são a senhas que te identificam de forma única dentro da plataforma. Para operar em um **a
```suggestion
> As [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) são a senhas que te identificam de forma única dentro da plataforma. Para operar em um **ambiente de testes** e simular pagamentos on-line, utilize as credenciais de teste. Para receber pagamentos reais, use as credenciais de **produção**.
```

2021-08-16 18:34 UTC, rwaetemann commented on guides/plugins/unofficial/iset.pt.md
> +5. Complete os campos Client ID e Client Secret que são as [credenciais]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/pt/guides/resources/faqs/credentials)) da sua conta do Mercado Pago.
```suggestion
5. Complete os campos Client ID e Client Secret com as [credenciais]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/pt/guides/resources/faqs/credentials)) da sua conta do Mercado Pago.
```

2021-08-16 18:37 UTC, pbracale commented on guides/plugins/unofficial/iset.pt.md
> +5. Complete os campos Client ID e Client Secret que são as [credenciais]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/pt/guides/resources/faqs/credentials)) da sua conta do Mercado Pago.
Rods, por definição as credenciais são um conjunto de chaves. Então credenciais = client ID + Client Secret. Achei melhor simplificar e tirar o link.

2021-08-16 18:48 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.en.md
> +> The [credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/credentials/credentials) are the keys that uniquely identify you within the platform. To operate in a **test envir
```suggestion
> The [credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/credentials/credentials) are the keys that uniquely identify you within the platform. To operate in a **test environment** in order to simulate online payments, use the test credentials. To receive real payments, use **production** credentials.
```

2021-08-16 18:48 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +> Las [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/credentials/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en
```suggestion
> Las [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/credentials/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en un **entorno de pruebas** con el que simular pagos online, utiliza las credenciales de prueba. Pare recibir pagos reales, usa las credenciales de **producción**.
```

2021-08-16 18:51 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +> Las [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/credentials/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en
```suggestion
> Las [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/credentials/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en un **entorno de pruebas** con el que simular pagos online, utiliza las credenciales de prueba. Para recibir pagos reales, usa las credenciales de **producción**.
```

2021-08-16 18:52 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.pt.md
> +> As [credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) são a senhas que te identificam de forma única dentro da plataforma. Para operar em um **a
```suggestion
> As [credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) são a senhas que te identificam de forma única dentro da plataforma. Para operar em um **ambiente de testes** e simular pagamentos on-line, utilize as credenciais de teste. Para receber pagamentos reais, use as credenciais de **produção**.
```

2021-08-16 19:25 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.en.md
> +Applications are nothing more than the different integrations one or more stores have. You can create an application for each solution implemented to have everything organized and maintain control to
```suggestion
Applications are nothing more than different integrations that one or more stores have. You can create an application for each solution implemented, so you have everything organized and maintain control to facilitate your management. 
```

2021-08-16 19:31 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.en.md
> +To every application created, a new card is also automatically created on the Developer Panel's homepage, containing the application's name, description, and ID.
```suggestion
To every application created, a new card is automatically created on the Developer Panel's homepage, containing the application's name, description, and ID.
```

2021-08-16 19:34 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.en.md
> +By clicking on an application card, you will have access to application details, including:
```suggestion
By clicking on an application card, you will have access to it's details, including:
```

2021-08-16 19:47 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +Cada aplicação possui um conjunto de credenciais e a possibilidade de configurar suas próprias notificações. Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/creden
```suggestion
Cada aplicação possui um conjunto de credenciais e a possibilidade de configurar suas próprias notificações. Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) e [Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/webhooks) para mais informações.
```

2021-08-16 19:47 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +> Se você não é desenvolvedor, recomendamos que você integre o Mercado Pago à sua loja através de [plugins e plataformas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins) e r
```suggestion
> Se você não é desenvolvedor, recomendamos que  integre o Mercado Pago à sua loja através de [plugins e plataformas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins) e recupere suas credenciais através da sua conta Mercado Pago em [Seu negócio > Configurações > Gestão e Administração > Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/settings/account/credentials). Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações.
```

2021-08-16 19:48 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +A cada aplicação criada, um card novo é automaticamente criado na página inicial do painel do desenvolvedor que contém o nome, descrição e o ID da aplicação.
```suggestion
A cada aplicação criada, um card novo contendo o nome, descrição e ID da aplicação é automaticamente criado na página inicial do painel do desenvolvedor.
```

2021-08-16 19:49 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +Ao clicar no card de uma aplicação, você terá acesso aos detalhes da aplicação, incluindo:
```suggestion
Ao clicar no card de uma aplicação, você terá acesso aos seus detalhes, incluindo:
```

2021-08-16 19:49 UTC, pbracale commented on guides/resources/devpanel/devpanel.pt.md
> +> Se você não é desenvolvedor, recomendamos que você integre o Mercado Pago à sua loja através de [plugins e plataformas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins) e r
@rwaetemann a gente usa "você" pra se comunicar com o leitor para manter aproximação!

2021-08-16 19:50 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +- **Minhas credenciais**. Senhas únicas com as quais identificamos uma integração na sua conta. Servem para capturar pagamentos em lojas online e outras aplicações. Leia [Credenciais](https://www.mer
```suggestion
- **Minhas credenciais**. Senhas únicas com as quais identificamos uma integração na sua conta. Servem para capturar pagamentos em lojas online e outras aplicações. Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/credentials/credentials) para mais informações.
```

2021-08-16 20:00 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +- **Notificações webhook**. Eventos que você pode receber através chamadas POST HTTP toda vez que houver um evento relacionado à transações na sua aplicação. Leia [Webhooks](https://www.mercadopago[F
```suggestion
- **Notificações webhook**. Eventos que você pode receber através chamadas POST HTTP toda vez que houver um evento relacionado a transações na sua aplicação. Leia [Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/webhooks) para maiores informações para maiores informações.
```

2021-08-16 20:02 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +  - **Permissões da aplicação**. Este campo apresenta as opções de acesso da sua aplicação. Por padrão, sua aplicação é criada com todas as permissões ativadas. Mas, você pode desativar uma permissão
```suggestion
  - **Permissões da aplicação**. Este campo apresenta as opções de acesso da sua aplicação. Por padrão, sua aplicação é criada com todas as permissões ativadas, mas você pode desativar uma permissão clicando na caixa de seleção referente à permissão que você deseja alterar. 
```

2021-08-16 20:03 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +  - **Redirect URL**. Este campo define a URL na qual você deseja receber o código de autorização quando sua integração for configurada como Marketplace ou for realizada através de OAuth.
```suggestion
  - **Redirect URL**. Este campo define a URL na qual você deseja receber o código de autorização quando sua integração for configurada como Marketplace ou realizada através de OAuth.
```

2021-08-16 20:04 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +- **Produto a ser integrado**. Esta seção define o produto a ser integrado na sua aplicação. O campo "Produtos disponíveis" apresenta a lista de produtos disponíveis a serem integrados. Por padrão, o
```suggestion
- **Produto a ser integrado**. Esta seção define o produto a ser integrado na sua aplicação. O campo "Produtos disponíveis" apresenta a lista de produtos disponíveis a serem integrados. Por padrão, o valor deste campo é preenchido com o valor inserido no momento da criação da aplicação, mas você pode alterar o produto escolhido sem a necessidade de reconfigurar a integração. Este campo serve como um informativo do produto ao qual a aplicação se refere.
```

2021-08-16 20:06 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.pt.md
> +Você pode integrar soluções para outras contas além da sua própria. Quando estiver integrando soluções para outras contas, você pode solicitar acesso às credenciais desta conta de forma a manter a se
```suggestion
Você pode integrar soluções para outras contas além da sua própria. Quando estiver integrando soluções para outras contas, você pode solicitar acesso às credenciais desta conta de forma a manter a segurança dos dados. Nesta seção, constam as credenciais dessas outras contas. Para solicitar acesso, basta:
```

2021-08-16 20:19 UTC, rwaetemann commented on guides/resources/devpanel/devpanel.es.md
> +Puedes integrar soluciones para cuentas distintas a la tuya. Al integrar soluciones para otras cuentas, puedes solicitar acceso a las credenciales de estas cuentas para mantener la seguridad de los d
```suggestion
Puedes integrar soluciones para cuentas distintas a la tuya. Al integrar soluciones para otras cuentas, puedes solicitar acceso a las credenciales de estas cuentas para mantener la seguridad de los datos. Esta sección contiene las credenciales de estas otras cuentas. Para solicitar acceso, se necesita:
```

2021-08-16 20:39 UTC, rwaetemann commented on guides/credentials/credentials.pt.md
> +Ambos tipos de credenciais são compostas por dois pares de chaves que você deve utilizar de acordo com o produto escolhido (veja a documentação de cada produto para detalhes de quais chaves utilizar)
```suggestion
Ambos os tipos de credenciais são compostas por dois pares de chaves que você deve utilizar de acordo com o produto escolhido (veja a documentação de cada produto para detalhes de quais chaves utilizar).
```

2021-08-16 20:39 UTC, rwaetemann commented on guides/credentials/credentials.pt.md
> +   <td>Chave pública da aplicação que normalmente será usada no frontend e permitirá, por exemplo, conhecer os meios de pagamento e criptografar os dados do cartão.
```suggestion
   <td>Chave pública da aplicação, que normalmente será usada no frontend e permitirá, por exemplo, conhecer os meios de pagamento e criptografar os dados do cartão.
```

2021-08-16 20:39 UTC, rwaetemann commented on guides/credentials/credentials.pt.md
> +   <td>Chave privada da aplicação que sempre será usada no backend para gerar pagamentos. É muito importante que este dado fique protegido em seus servidores e não seja acessível por nenhum usuário d
```suggestion
   <td>Chave privada da aplicação, que sempre será usada no backend para gerar pagamentos. É muito importante que este dado fique protegido em seus servidores e não seja acessível por nenhum usuário do sistema ou invasor.
```

2021-08-16 20:40 UTC, rwaetemann commented on guides/credentials/credentials.pt.md
> +>Você tem a opção de renovar suas credenciais por motivos de segurança ou quaisquer que sejam. Para renová-las basta clicar clicar em Mais opções > Renovar.
```suggestion
>Você tem a opção de renovar suas credenciais por motivos de segurança ou quaisquer que sejam. Para renová-las, basta clicar clicar em Mais opções > Renovar.
```

2021-08-17 12:25 UTC, nicolassalvanes requested changes
@pbracale porqué creamos carpetas `credentials` y `devpanel` dentro de `/resources`?
Queda muy raro el path repetido "/credentials/credentials" y "/devpanel/devpanel"

Me parece que tenemos que mover los archivos credentials.md y devpanel.md directamente al raíz de la carpeta /resources

2021-08-17 13:51 UTC, rwaetemann commented on guides/credentials/credentials.es.md
> +Comparte tus credenciales de forma segura con quien te ayude a integrar o configurar tus canales de pago. Para hacerlo, ven a tu cuenta de Mercado Pago y en [Tu negocio> Configuraciones> Gestión y Ad
```suggestion
Comparte tus credenciales de forma segura con quien te ayude a integrar o configurar tus canales de pago. Para hacerlo, acceda a tu cuenta de Mercado Pago y en [Tu negocio> Configuraciones> Gestión y Administración> Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/settings/account/credentials), elige la opción “Compartir mis credenciales” e ingresa el correo electrónico de la persona a la que quieres darle acceso. 
```

2021-08-17 13:54 UTC, pbracale commented
> @pbracale porqué creamos carpetas `credentials` y `devpanel` dentro de `/resources`?
> Queda muy raro el path repetido "/credentials/credentials" y "/devpanel/devpanel"
> 
> Me parece que tenemos que mover los archivos credentials.md y devpanel.md directamente al raíz de la carpeta /resources

@nicolassalvanes a priori pensei que fosse um padrão manter todos os arquivos dentro de pastas mas, concordo que fica estranho mesmo. Porém, estou com um item no backlog para rever o local do menu (e consequentemente o local dos arquivos) desses itens (e de mais outros). No resumo, coloquei eles dentro de resources temporariamente, mas a curto prazo (espero que já em Q4) eles sejam removidos e colocados no local adequado. Dito isso, acha que podemos manter assim por algumas semanas?

2021-08-17 14:02 UTC, nicolassalvanes commented
> > @pbracale porqué creamos carpetas `credentials` y `devpanel` dentro de `/resources`?
> 
> > Queda muy raro el path repetido "/credentials/credentials" y "/devpanel/devpanel"
> 
> > 
> 
> > Me parece que tenemos que mover los archivos credentials.md y devpanel.md directamente al raíz de la carpeta /resources
> 
> 
> 
> @nicolassalvanes a priori pensei que fosse um padrão manter todos os arquivos dentro de pastas mas, concordo que fica estranho mesmo. Porém, estou com um item no backlog para rever o local do menu (e consequentemente o local dos arquivos) desses itens (e de mais outros). No resumo, coloquei eles dentro de resources temporariamente, mas a curto prazo (espero que já em Q4) eles sejam removidos e colocados no local adequado. Dito isso, acha que podemos manter assim por algumas semanas?

Me parece bien que por ahora estén dentro de resources, es lo mejor hasta que puedan revisar toda la estructura del menú más adelante.👌🏻

Pero movería ahora /guides/resources/credentials/credentials.md a /guides/resources/credentials.md, y lo mismo con devpanel.md. Para evitar el path duplicado.

Puedo ayudar a hacerlo rápido con un search & replace 😄

2021-08-17 14:07 UTC, pbracale commented
> > > @pbracale porqué creamos carpetas `credentials` y `devpanel` dentro de `/resources`?
> > 
> > 
> > > Queda muy raro el path repetido "/credentials/credentials" y "/devpanel/devpanel"
> > 
> > 
> > > 
> > 
> > 
> > > Me parece que tenemos que mover los archivos credentials.md y devpanel.md directamente al raíz de la carpeta /resources
> > 
> > 
> > @nicolassalvanes a priori pensei que fosse um padrão manter todos os arquivos dentro de pastas mas, concordo que fica estranho mesmo. Porém, estou com um item no backlog para rever o local do menu (e consequentemente o local dos arquivos) desses itens (e de mais outros). No resumo, coloquei eles dentro de resources temporariamente, mas a curto prazo (espero que já em Q4) eles sejam removidos e colocados no local adequado. Dito isso, acha que podemos manter assim por algumas semanas?
> 
> Me parece bien que por ahora estén dentro de resources, es lo mejor hasta que puedan revisar toda la estructura del menú más adelante.👌🏻
> 
> Pero movería ahora /guides/resources/credentials/credentials.md a /guides/resources/credentials.md, y lo mismo con devpanel.md. Para evitar el path duplicado.
> 
> Puedo ayudar a hacerlo rápido con un search & replace 😄

@nicolassalvanes Tem razão Nico, vou alterar a pasta agora!! Pode deixar que eu faço, acabei de descobrir uma outra mudança necessária, daí já faço tudo junto!

2021-08-17 15:03 UTC, rwaetemann commented on guides/credentials/credentials.en.md
> +> If you are not a developer, we recommend you verify your credentials in your Mercado Pago account. And, if someone is helping you set up your store's integrations, you can share your credentials wi
```suggestion
> If you are not a developer, we recommend you to verify your credentials in your Mercado Pago account. And, if someone is helping you set up your store's integrations, you can share your credentials with them.
```

2021-08-17 15:11 UTC, rwaetemann commented on guides/credentials/credentials.pt.md
> +# Credenciais
@pbracale - Pri, percebi que o path está /credentials/credentials. É isso mesmo ou deveria ter outra palavra após o primeiro credentials?

2021-08-17 16:48 UTC, pbracale commented on guides/credentials/credentials.pt.md
> +# Credenciais
Acabei de fazer uma alteração para simplificar isso.

2021-08-17 16:56 UTC, pbracale commented
@nicolassalvanes fiz as alterações dos links por um commit, consegue dar uma olhada e ver se está ok?

2021-08-17 17:57 UTC, rwaetemann commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações.
```suggestion
> Tem dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações. 
```

2021-08-17 17:58 UTC, rwaetemann commented on guides/online-payments/checkout-api/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações.
```suggestion
> Tem dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações. 
```

2021-08-17 17:58 UTC, rwaetemann commented on guides/online-payments/checkout-api/v1/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações.
```suggestion
> Tem dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações. 
```

2021-08-17 17:58 UTC, rwaetemann commented on guides/online-payments/checkout-api/v2/previous-requirements.pt.md
> +> Têm dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações.
```suggestion
> Tem dúvidas sobre credenciais? Leia [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações. 
```

2021-08-17 18:44 UTC, rwaetemann approved these changes

2021-08-17 18:50 UTC, rwaetemann commented
@pbracale - reviews finalizados e aprovados, Pri!

2021-08-17 20:42 UTC, abderossi commented on guides/online-payments/checkout-api/v1/previous-requirements.en.md
> +> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 20:42 UTC, abderossi commented on guides/online-payments/checkout-api/v2/previous-requirements.en.md
> +> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 20:43 UTC, abderossi commented on guides/online-payments/checkout-pro/previous-requirements.en.md
> +> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 20:43 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/introduction.en.md
> +> Do you have any questions? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Do you have any questions? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 20:43 UTC, abderossi commented on guides/online-payments/marketplace/checkout-pro/introduction.en.md
> +> Do you have any questions? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Do you have any questions? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 20:44 UTC, abderossi commented on guides/online-payments/web-tokenize-checkout/receiving-payment-by-card.en.md
> +> Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 20:44 UTC, abderossi commented on guides/online-payments/web-tokenize-checkout/v1/receiving-payment-by-card.en.md
> +> Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 20:45 UTC, abderossi commented on guides/plugins/prestashop/integration.es.md
> +2. Obtén el par de [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) Access Token y Public Key y pégalas en los campos de Producción y Pruebas que
```suggestion
2. Obtén el par de [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) Access Token y Public Key y pégalas en los campos de Producción y Pruebas que encontrarás en la configuración del módulo.
```

2021-08-17 20:50 UTC, abderossi commented on guides/plugins/prestashop/integration.es.md
> +> Las  [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en
Sugerencia en el uso de bold. Destacaría en ambos casos el mismo elemento, ya sea el entorno y función o las credenciales. En este caso, destacamos primero **entorno de pruebas** y luego **producción**. Sugiero destacar **credenciales de prueba** y **credenciales de producción**, o sino **entorno de pruebas** y **recibir pagos reales**.

2021-08-17 20:52 UTC, abderossi commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields Client ID and Client Secret with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/credentials)).
En este caso no cambiaría el faker llevándolo a las FAQs, porque en este paso le estamos indicando al desarrollador que complete con sus credenciales. Utilizando ([FAKER][CREDENTIALS][URL]) llega directamente a sus credenciales.
Si lo enviamos a las FAQs, estaría resolviendo dudas, pero no estamos invitándolo a esto.

2021-08-17 20:53 UTC, abderossi commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields Client ID, Client Secret and Public Key with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/cred
Mismo comentario que arriba :)

2021-08-17 20:53 UTC, abderossi commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields “Client ID, Client Secret and Public Key” with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/cr
Mismo comentario que arriba :)

2021-08-17 20:54 UTC, abderossi commented on guides/plugins/unofficial/iset.pt.md
> +5. Complete os campos Client ID e Client Secret da sua conta do Mercado Pago.
¿Por qué eliminamos esta instancia de link a sus credenciales acá y en otras documentaciones lo mantenemos?

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/prestashop/integration.en.md
> +2. Obtain the Access Token and Public Key [credentials]() and paste them into the Production and Testing fields that you will find in the module configuration.
```suggestion
2. Obtain the Access Token and Public Key [credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) and paste them into the Production and Testing fields that you will find in the module configuration.
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/prestashop/integration.es.md
> +2. Obtén el par de [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) Access Token y Public Key y pégalas en los campos de Producción y Pruebas que
```suggestion
2. Obtén el par de [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) Access Token y Public Key y pégalas en los campos de Producción y Pruebas que encontrarás en la configuración del módulo.
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/prestashop/integration.es.md
> +> Las  [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en
```suggestion
> Las [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en un **entorno de pruebas** y simular pagos online, utiliza las credenciales de prueba. Para recibir pagos reales, usa las credenciales de **producción**.
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields Client ID and Client Secret with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/credentials)).
```suggestion
1. Complete the fields Client ID and Client Secret with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/credentials)).
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields Client ID, Client Secret and Public Key with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/cred
```suggestion
1. Complete the fields Client ID, Client Secret and Public Key with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/credentials)).
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields “Client ID, Client Secret and Public Key” with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/cr
```suggestion
1. Complete the fields “Client ID, Client Secret and Public Key” with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/credentials)).
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.es.md
> +1. Completa los campos Client ID y Client Secret con las [credenciales]([(https://www.mercadopago[FAKER][URL][DOMAIN]developers/es/guides/resources/faqs/credentials)) de tu cuenta de Mercado Pago.
```suggestion
1. Completa los campos Client ID y Client Secret con las [credenciales]([(https://www.mercadopago[FAKER][URL][DOMAIN]developers/es/guides/resources/credentials)) de tu cuenta de Mercado Pago.
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.es.md
> +1. Completa en los campos Client ID, Client Secret y Public Key, las [credenciales]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/es/guides/resources/faqs/credentials)) de tu cuenta de Merca
```suggestion
1. Completa en los campos Client ID, Client Secret y Public Key, las [credenciales]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/es/guides/resources/credentials)) de tu cuenta de Mercado Pago.
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.es.md
> +1. Completa los campos “Cliend ID, Clien Secret y Public Key” con las [credenciales de tu cuenta de Mercado Pago]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/es/guides/resources/faqs/crede
```suggestion
1. Completa los campos “Cliend ID, Clien Secret y Public Key” con las [credenciales de tu cuenta de Mercado Pago]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/es/guides/resources/credentials)).
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.pt.md
> +5. Complete os campos Client ID, Client Secret e Public Key que são as [credenciais da sua conta do Mercado Pago]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/pt/guides/resources/faqs/crede
```suggestion
5. Complete os campos Client ID, Client Secret e Public Key que são as [credenciais da sua conta do Mercado Pago]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/pt/guides/resources/credentials)).
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/iset.pt.md
> +5. Complete os campos Client ID, Client Secret e Public Key que são as [credenciais da sua conta do Mercado Pago]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/pt/guides/resources/faqs/crede
```suggestion
5. Complete os campos Client ID, Client Secret e Public Key que são as [credenciais da sua conta do Mercado Pago]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/pt/guides/resources/credentials)).
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/plugins/unofficial/linx.es.md
> +1. Si quieres probar tus pagos, en la sección Modo de prueba, selecciona la opción “Sí”. Luego, completa los campos Public Key y Access Token key con las  [Credenciais](https://www.mercadopago[FAKER]
```suggestion
1. Si quieres probar tus pagos, en la sección Modo de prueba, selecciona la opción “Sí”. Luego, completa los campos Public Key y Access Token key con las [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) de prueba de tu cuenta de Mercado Pago. 
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/resources/credentials.en.md
> +Credentials are unique passwords responsible for capturing payments in online stores and other applications securely with which we identify an integration in your account. They can be found on the [D
Me parece un poco rara esta frase:
> Credentials are unique passwords responsible for capturing payments in online stores and other applications securely with which we identify an integration in your account.

Viendo como está escrito en español, no debería ser algo como:
> Credentials are unique passwords that identify an integration in your account. They allow to capture payments in online stores and other applications securely.

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/resources/credentials.en.md
> +* **Test credentials**. Test credentials test your integrations and can be used together with test credit cards to simulate card receipts. We recommend you to use them before production credentials t
```suggestion
* **Test credentials**. Test credentials check your integrations and can be used together with test users and test credit cards to simulate card receipts. We recommend you to use them before production credentials to ensure that integrations work properly.
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/resources/credentials.en.md
> +</table>
No podemos usar el formato de tabla de Markdown?
Se empieza poniendo código HTML para cosas sencillas y bien rápido se termina usando más de lo debido 😅 

```suggestion
| Type | Description |
| :--- | :--- |
| Public key | Application's public key that will usually be used in the frontend. It allows you to know the means of payment and to encrypt card data. |
| Access token | Application's private key that will always be used in the backend to generate payments. It is very important that this data is protected in your servers and is not accessible for any system user or attacker. |
```

2021-08-17 20:54 UTC, nicolassalvanes commented on guides/resources/devpanel.en.md
> +The [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) is your application management environment. It is automatically created with a user ID for you when you open a Mercado Pago a
Y si hablamos de "integrations management enviroment"?
Para que esté más alineado con el acceso:
<img width="194" alt="Captura de Pantalla 2021-08-17 a la(s) 17 54 37" src="https://user-images.githubusercontent.com/13139782/129799227-653d2b07-ae88-480a-a29a-90c00d2a8408.png">

2021-08-17 21:05 UTC, pbracale commented on guides/plugins/prestashop/integration.es.md
> +> Las  [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) son las claves que te identifican de forma única dentro de la plataforma. Para operar en
Faz sentido.

2021-08-17 21:07 UTC, pbracale commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields Client ID and Client Secret with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/credentials)).
A FAQ de credenciais foi substituída por um artigo. E sim, concordo que faz mais sentido fazer o link para o artigo. Alterei.

2021-08-17 21:09 UTC, abderossi commented on guides/resources/changelog/last-year.es.md
> +Lee [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) para obtener más información.
En inglés y portugués se mantuvo el "Conoce más sobre cómo solicitar credenciales". No deberíamos mantenerlo también en español?

2021-08-17 21:13 UTC, pbracale commented on guides/resources/credentials.en.md
> +Credentials are unique passwords responsible for capturing payments in online stores and other applications securely with which we identify an integration in your account. They can be found on the [D
Sim! Usei sua sugestão em um commit! ☺️

2021-08-17 21:13 UTC, pbracale commented on guides/resources/credentials.en.md
> +</table>
Podemos... eu não me atentei... sorry, foi o costume!

2021-08-17 21:15 UTC, pbracale commented on guides/resources/devpanel.en.md
> +The [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) is your application management environment. It is automatically created with a user ID for you when you open a Mercado Pago a
Sim. Perfeito! Alterei em commit.

2021-08-17 21:18 UTC, pbracale commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields Client ID, Client Secret and Public Key with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/cred
mesmo comentário acima

2021-08-17 21:18 UTC, pbracale commented on guides/plugins/unofficial/iset.en.md
> +1. Complete the fields “Client ID, Client Secret and Public Key” with the [credentials of your Mercado Pago account]((https://www.mercadopago[FAKER][URL][DOMAIN]developers/en/guides/resources/faqs/cr
mesmo comentário acima

2021-08-17 21:20 UTC, pbracale commented on guides/plugins/prestashop/integration.es.md
> +2. Obtén el par de [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) Access Token y Public Key y pégalas en los campos de Producción y Pruebas que
outdated

2021-08-17 21:21 UTC, abderossi commented on guides/resources/credentials.es.md
> +Ambos tipos de credenciales se componen de dos pares de llaves que debes usar según el producto que elijas (consulta la documentación de cada producto para obtener detalles sobre qué llaves usar).
```suggestion
Ambos tipos de credenciales se componen de dos pares de llaves que debes usar según el producto que elijas. 
 Te recomendamos consultar la documentación de cada producto para obtener detalles sobre qué llaves usar.
```

2021-08-17 21:21 UTC, pbracale commented on guides/resources/changelog/last-year.es.md
> +Lee [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) para obtener más información.
Sim. Vou alterar em commit.

2021-08-17 21:21 UTC, abderossi commented on guides/resources/credentials.es.md
> +Ambos tipos de credenciales se componen de dos pares de llaves que debes usar según el producto que elijas (consulta la documentación de cada producto para obtener detalles sobre qué llaves usar).
Dejo sugerencia!

2021-08-17 21:25 UTC, pbracale commented on guides/plugins/unofficial/iset.pt.md
> +5. Complete os campos Client ID e Client Secret da sua conta do Mercado Pago.
Porque esse texto em específico continha um erro dizendo que Client ID e Client Secret são as credenciais. Essa frase vai contra o que está escrito na documentação de credenciais, que diz que as credenciais são um par de chaves. Daí, visto que aqui é um passo a passo, achei melhor tirar o link e simplificar a explicação. Mas, vou adicionar a chamada "leia credenciais para maior informação".

2021-08-17 21:29 UTC, abderossi commented on guides/resources/credentials.es.md
> +   <td>Chave privada para ser utilizada em alguns plugins para gerar pagamentos. É muito importante que este dado fique protegido em seus servidores e não seja acessível por nenhum usuário do sistema
```suggestion
   <td>Llave privada que se utiliza en algunos plugins para generar pagos. Es muy importante que estos datos estén protegidos en tus servidores y no sean accesibles por ningún usuario o atacante.
```

2021-08-17 21:29 UTC, abderossi commented on guides/resources/credentials.es.md
> +   <td>Llave privada de la aplicación que siempre se utiliza en el backend para generar pagos. Es muy importante que estos datos estén protegidos en tus servidores y no sean accesibles por ningún usu
```suggestion
   <td>Llave privada de la aplicación que siempre se utiliza en el backend para generar pagos. Es muy importante que estos datos estén protegidos en tus servidores y no sean accesibles por ningún usuario o atacante.
```

2021-08-17 21:38 UTC, abderossi commented on guides/resources/devpanel.en.md
> +4. Accept our Terms and Conditions.
Consulta: por cuestiones legales no sería necesario linkear los Terminos y Condiciones acá o indicar donde encontrarlos?

2021-08-17 21:43 UTC, abderossi commented on guides/in-person-payments/qr-code/pre-requisites.en.md
> +> Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 21:43 UTC, abderossi commented on guides/online-payments/checkout-api/previous-requirements.en.md
> +> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) fore more information.
```suggestion
> Do you have any questions about credentials? Read [Credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) for more information.
```

2021-08-17 21:44 UTC, pbracale reviewed
Alteração de tabelas (de HTML para MD) e alteração da intro sobre o dashboard.

2021-08-17 22:28 UTC, nicolassalvanes approved these changes
@mminestrelli en dx-devsite tenemos que actualizar el link al artículo de credenciales de la landing de soporte y, por las dudas, sumar el redirect de la url vieja (/faqs/credentials) a la nueva

2021-08-17 22:28 UTC, nicolassalvanes commented on guides/resources/devpanel.en.md
> +The [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) is your integration management environment automatically created with a user ID for you when you open a Mercado Pago account.
```suggestion
The [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) is your integration management environment automatically created with an user ID for you when you open a Mercado Pago account. In it you can create, edit and delete applications.
```

2021-08-18 13:39 UTC, merged