Improve snippet
mercadopago/devsite-docs pull request #1261
Opened 2021-08-16 20:33 UTC by lucmantovani

## Description
Improving NodeJs snippet to get payment_methods. The previous snippet ignored that the method return a Promise, which could cause integration issues.

### Checklist:
Before sending your contribution, please specify the following: 

- [X] This request modifies code snippets. 
- [X] The contribution aligns with the information stated in the repository wiki.

2021-08-31 12:00 UTC, elvisjhonataoliveira requested changes
Acho que precisa adicionar o `var` antes de declarar a variável.

2021-08-31 12:00 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/v2/other-payment-ways.pt.md
> +response = await mercadopago.get("/v1/payment_methods");
```suggestion
var response = await mercadopago.get("/v1/payment_methods");
```

2021-08-31 12:00 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/v2/other-payment-ways.pt.md
> +response = await mercadopago.get("/v1/payment_methods");
```suggestion
var response = await mercadopago.get("/v1/payment_methods");
```

2021-08-31 12:00 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/v2/other-payment-ways.pt.md
> +response = await mercadopago.get("/v1/payment_methods");
```suggestion
var response = await mercadopago.get("/v1/payment_methods");
```

2021-08-31 12:00 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/v2/other-payment-ways.pt.md
> +response = await mercadopago.get("/v1/payment_methods");
```suggestion
var response = await mercadopago.get("/v1/payment_methods");
```

2021-08-31 12:00 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/v2/other-payment-ways.pt.md
> +response = await mercadopago.get("/v1/payment_methods");
```suggestion
var response = await mercadopago.get("/v1/payment_methods");
```

2021-08-31 12:00 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/v2/other-payment-ways.pt.md
> +response = await mercadopago.get("/v1/payment_methods");
```suggestion
var response = await mercadopago.get("/v1/payment_methods");
```

2021-08-31 12:00 UTC, elvisjhonataoliveira commented on guides/online-payments/checkout-api/v2/other-payment-ways.pt.md
> +response = await mercadopago.get("/v1/payment_methods");
```suggestion
var response = await mercadopago.get("/v1/payment_methods");
```

2021-08-31 12:59 UTC, lucmantovani commented
> Acho que precisa adicionar o `var` antes de declarar a variável.

Ajustado!

2021-09-13 15:13 UTC, nicolassalvanes approved these changes

2021-09-15 18:22 UTC, merged