[ADD] new doc for release report
mercadopago/devsite-docs pull request #1272
Opened 2021-08-25 15:16 UTC by NaNieto

## Description
create  new documentation for release report

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-08-30 22:21 UTC, biaguerreiromeli reviewed
Partial review. waiting on meeting (31/08) to finish it.

2021-08-30 22:21 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +## Generar de forma programada
```suggestion
## Generar reporte automaticamente
```

2021-08-30 22:21 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +Recibirás como respuesta un `HTTP STATUS 200 (Ok)`
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)` si no se encuentra ningún error en la generación.

El objeto de respuesta con los datos del reporte tendrá una estructura similar al ejemplo siguiente:
```

2021-08-30 22:21 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +Ejecuta el curl que necesites para cancelar la generación programada de tus reportes.
```suggestion
Ejecuta el curl para cancelar la generación programada de tus reportes:
```

2021-08-30 22:21 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +Recibirás como respuesta un `HTTP STATUS 200 (Ok)`
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)` si no se encuentra ningún error para cancelar.

El objeto de respuesta con los datos de la cancelación tendrá una estructura similar al ejemplo siguiente:
```

2021-08-30 22:21 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +Descarga el archivo con este comando:
```suggestion
Descarga el archivo generado con el siguiente comando:
```

2021-08-30 22:21 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +Recibirás como respuesta un `HTTP STATUS 200 (Ok)`
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)` si no se encuentra ningún error en la descarga.

El objeto de respuesta con los datos del archivo tendrá una estructura similar al ejemplo siguiente:
```

2021-08-31 20:48 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +## Generar de forma programada
```suggestion
## Genera tus reportes de forma programada
```

2021-08-31 20:48 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Genera tus reportes de forma programada configurando tres instancias: generación, configuración y descarga.
```suggestion
Puedes programar la creación de tus reportes. Solo debes configurar tres instancias: generación, configuración y descarga.
```

2021-09-01 21:57 UTC, NaNieto reviewed
ok

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/available-money/withdrawal.en.md
>  > You can use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the
```suggestion
> The Available Balance report will be disabled from next March 1st, 2022.
>
> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/available-money/withdrawal.es.md
>  > Puedes usar el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/ma
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
>
> Usa el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) para conciliar las transacciones del dinero disponible en tu cuenta, incluidos tus retiros bancarios.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/available-money/withdrawal.pt.md
>  > Você pode usar o [relatório de ----[mla]----Liquidações------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberações------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/ma
```suggestion
> O relatório de Dinheiro disponível será desabilitado a partir de 1º de março de 2022.
>
> Use o [relatório de ----[mla]----Liquidações------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberações------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/manage-account/reports/released-money/introduction) para fazer a reconciliação das transações que afetem o saldo disponível na sua conta, incluindo seus saques bancários.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 22 de marzo de 2022
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +> You can use the [Release report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the b
```suggestion
> WARNING
>
> The Available Balance report will be disabled from next March 1st, 2022.
>
> Use the [Release report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
## Set up your reports

Execute the curl you need to check, create and update your reports.

```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive an `HTTP STATUS 200 (OK)` in response.
```suggestion
You will receive an `HTTP STATUS 200 (OK)` in response if no error is found.

The response object will have a similar structure to the following example:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +Create your API generation preferences to export columns, name your files and configure other settings:
```suggestion
Create your generation preferences through API to export columns, name your files and configure other settings:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive an `HTTP STATUS 201 (Created)` in response.
```suggestion
You will receive an `HTTP STATUS 201 (Created)` in response if no error is found.

The response object will have a similar structure to the following example:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive an `HTTP STATUS 200 (OK)` in response.
```suggestion
You will receive an `HTTP STATUS 200 (OK)` in response if no error is found.

The response object will have a similar structure to the following example:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +> Have the [Glossary](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/release-money/glossary) of the Available Balance report on hand to review it when needed
```suggestion
> NOTE
>
> Note
>
> Have the [Glossary](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/release-money/glossary) at hand to review technical terms when managing your reports.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +## Generating manually
```suggestion
## Generating your reports manually 
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +Post to the API by specifying the start and end dates as follows:
```suggestion
Perform a POST to the API by specifying the start and end dates as follows:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive an `HTTP STATUS 202 (Accepted)` in response, and the report will be generated asynchronously.
```suggestion
You will receive an `HTTP STATUS 202 (Accepted)` in response if no error is found, and the report will be generated asynchronously.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +Check the API this way to see if the report generation is ready:
```suggestion
Check the API according to the snippet below to see if the report generation is ready:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive `HTTP STATUS 200 (OK)` in response:
```suggestion
You will receive `HTTP STATUS 200 (OK)` in response if no error is found.

The response object will have a similar structure to the following example:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive an `HTTP STATUS 200 (OK)` in response.
```suggestion
You will receive an `HTTP STATUS 200 (OK)` in response if no error is found.

The response object will have a similar structure to the following example:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +## Generating on a scheduled basis
```suggestion
## Generating your reports automatically
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +Schedule the automatic report generation using the frequency in the configuration resource. Update the *`scheduled`* attribute in the configuration to *`true`*:
```suggestion
Schedule the automatic generation of your report using the desired frequency in the configuration resource. 

Keep in mind to update the *`scheduled`* attribute in the configuration to *`true`*:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +Execute the curl you need to start and cancel the scheduled generation of your reports.
```suggestion
Execute the following curls to respectively start and cancel the scheduled generation of your reports, according to your desired scenario.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +Download the file with this command:
```suggestion
Download the generated file with the following command:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +El objeto de respuesta con los datos de la consulta tendrá una estructura similar al ejemplo siguiente:
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)` si no se encuentra ningún error. 

El objeto de respuesta tendrá una estructura similar al ejemplo siguiente:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +El objeto de respuesta con los datos del nuevo reporte tendrá una estructura similar al ejemplo siguiente:
```suggestion
Recibirás como respuesta un `HTTP STATUS 201 (Created)` si no se encuentra ningún error. 

El objeto de respuesta tendrá una estructura similar al ejemplo siguiente:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +La respuesta con los datos de la alteración tendrá una estructura similar al ejemplo siguiente:
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)` si no se encuentra ningún error. 

El objeto de respuesta tendrá una estructura similar al ejemplo siguiente:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +## Atributos configurables
```suggestion
#### Atributos configurables
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +
```suggestion
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +
```suggestion

> NOTE
>
> Nota
>
> Ten a mano el [Glosario](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/glossary) para consultar algún término técnico durante la generacion de tus reportes.
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +La respuesta con los datos de la consulta tendrá una estructura similar al ejemplo siguiente:
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)` si no se encuentra ningún error.

El objeto de respuesta tendrá una estructura similar al ejemplo siguiente:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +Recibirás como respuesta un `HTTP STATUS 200 (Ok)`
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)` si no se encuentra ningún error.

El objeto de respuesta tendrá una estructura similar al ejemplo siguiente:
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +## Configurable attributes
```suggestion
#### Configurable attributes
```

2021-09-02 04:48 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.es.md
> +Puedes programar la creación de tus reportes. Solo debes configurar tres instancias: generación, configuración y descarga.
```suggestion
Programa la creación de tus reportes. Solo debes configurar tres instancias: generación, configuración y descarga.
```

2021-09-10 02:09 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +
```suggestion
Generate your reports manually by configuring three instances: creation, query, and download.

### 1. Creation

Perform a POST to the API by specifying the desired start and end dates as follows:

```

2021-09-10 02:09 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +### 2. Search
```suggestion
### 2. Query
```

2021-09-10 02:09 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +Check the API according to the snippet below to see if the report generation is ready:
```suggestion
Check the API according to the snippet below to see if the report creation is ready:
```

2021-09-10 02:09 UTC, biaguerreiromeli commented on guides/manage-account/reports/released-money/api.en.md
> +### 1. Generation
```suggestion
Generate your reports on a scheduled basis by configuring three instances: creation, configuration, and download.

### 1. Creation
```

2021-09-22 13:18 UTC, abderossi commented on guides/manage-account/reports/available-money/api.en.md
> +> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance
```suggestion
> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-09-22 15:43 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-22 15:43 UTC, abderossi commented on guides/manage-account/reports/available-money/generate.en.md
> +> The Available Balance report will be disabled from next March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022.
```

2021-09-22 15:43 UTC, abderossi commented on guides/manage-account/reports/available-money/generate.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-22 15:43 UTC, abderossi commented on guides/manage-account/reports/available-money/glossary.en.md
> +> The Available Balance report will be disabled from next March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022.
```

2021-09-22 15:44 UTC, abderossi commented on guides/manage-account/reports/available-money/glossary.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-22 15:44 UTC, abderossi commented on guides/manage-account/reports/available-money/how-to-use.en.md
> +> The Available Balance report will be disabled from next March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022.
```

2021-09-22 15:44 UTC, abderossi commented on guides/manage-account/reports/available-money/how-to-use.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-22 15:44 UTC, abderossi commented on guides/manage-account/reports/available-money/introduction.en.md
> +> The Available Balance report will be disabled from next March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022.
```

2021-09-22 15:44 UTC, abderossi commented on guides/manage-account/reports/available-money/introduction.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-22 15:45 UTC, abderossi commented on guides/manage-account/reports/available-money/panel.en.md
> +> The Available Balance report will be disabled from next March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022.
```

2021-09-22 15:45 UTC, abderossi commented on guides/manage-account/reports/available-money/panel.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-22 15:45 UTC, abderossi commented on guides/manage-account/reports/available-money/withdrawal.en.md
> +> The Available Balance report will be disabled from next March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022.
```

2021-09-22 15:45 UTC, abderossi commented on guides/manage-account/reports/available-money/withdrawal.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 01 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```

2021-09-22 15:46 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +> The Available Balance report will be disabled from next March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022.
```

2021-09-22 15:48 UTC, abderossi approved these changes

2021-11-01 20:00 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
>  Ganá tiempo y automatizá la **frecuencia de generación** del reporte de Dinero retirado las veces que quieras, tanto de forma manual como de forma programada.
```suggestion
Gana tiempo y automatiza la **frecuencia de generación** del reporte de Dinero retirado las veces que quieras, tanto de forma manual como de forma programada. 
```

2021-11-04 19:19 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
> +>El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022
```

2021-11-04 19:21 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
>  Ganá tiempo y automatizá la **frecuencia de generación** del reporte de Dinero retirado las veces que quieras, tanto de forma manual como de forma programada.
```suggestion
Genera el informe de dinero liberado manualmente tantas veces como desees o prográmalo de acuerdo con la frecuencia deseada a través de nuestra API.
```

2021-11-04 19:23 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
>  ## Configurar tus reportes
```suggestion
## Configura tus reportes
```

2021-11-04 19:42 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
> +Ejecuta el curl que necesites para crear, consultar y actualizar tus reportes.
```suggestion
Puedes configurar tus reportes según lo que necesites. A continuación, te mencionamos cuáles son las llamadas a la API que puedes hacer para crear, consultar y actualizar tus reportes.
```

2021-11-04 19:43 UTC, abderossi commented on guides/manage-account/reports/available-money/api.en.md
> +Execute the curl you need to create, review and update your reports.
```suggestion
You can configure your reports according to your preferences. Up next, you'll find the API calls you can make to create, consult and update your reports.
```

2021-11-04 19:48 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
>  Recibirás como respuesta un `HTTP STATUS 200 (Ok)`
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)`.
```

2021-11-04 19:50 UTC, abderossi commented on guides/manage-account/reports/available-money/api.pt.md
>  Você pode gerar seu relatório via API, tanto de forma manual quanto programada.
```suggestion
```

2021-11-04 19:50 UTC, abderossi commented on guides/manage-account/reports/available-money/api.pt.md
>  Ganhe tempo e automatize a **frequência de geração** do relatório de Dinheiro disponível sempre que quiser.
```suggestion
Gere manualmente o relatório de dinheiro liberado quantas vezes quiser ou programe-o de acordo com a frequência que você escolher por meio de nossa API.```

2021-11-04 19:52 UTC, abderossi commented on guides/manage-account/reports/available-money/api.pt.md
> +> O relatório de Dinheiro disponível será desabilitado a partir de 1o de março de 2022.
```suggestion
> O relatório de Dinheiro disponível será desabilitado a partir de 1° de março de 2022.
```

2021-11-05 15:52 UTC, abderossi commented on guides/manage-account/reports/available-money/api.pt.md
> +Execute o curl que você precisa para gerar, consultar e atualizar seus relatórios.
```suggestion
Você pode configurar seus relatórios de acordo com o que você precisa. A seguir, mencionamos quais são as chamadas de API que você pode fazer para criar, consultar e atualizar seus relatórios.
```

2021-11-05 16:38 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
>  ### Crear configuración
```suggestion
### Crea tus configuraciones
```

2021-11-05 16:39 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
> +### Consultar configuración
```suggestion
### Consulta tus configuraciones
```

2021-11-05 16:39 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
> +Recibirás como respuesta un `HTTP STATUS 200 (Ok)`
```suggestion
Recibirás como respuesta un `HTTP STATUS 200 (Ok)`:
```

2021-11-05 16:40 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
>  ### Actualizar configuración
```suggestion
### Actualiza tu configuración
```

2021-11-05 16:42 UTC, abderossi commented on guides/manage-account/reports/available-money/api.pt.md
> +Como resposta, você receberá um `HTTP STATUS 200 (Ok)`
```suggestion
Como resposta, você receberá um `HTTP STATUS 200 (Ok)`:
```

2021-11-05 16:42 UTC, abderossi commented on guides/manage-account/reports/available-money/api.pt.md
> +Como resposta, você receberá um `HTTP STATUS 200 (Ok)`
```suggestion
Como resposta, você receberá `HTTP STATUS 200 (Ok)`:
```

2021-11-05 16:50 UTC, abderossi commented on guides/manage-account/reports/available-money/generate.en.md
> +> The Available Balance report will be disabled next March 01, 2022
```suggestion
> The Available Balance report will be disabled next March 1st, 2022
```

2021-11-05 16:50 UTC, abderossi commented on guides/manage-account/reports/available-money/generate.es.md
> +> El reporte de Dinero retirado será deshabilitado el próximo 01 marzo, 2022
```suggestion
> El reporte de Dinero retirado será deshabilitado el 1 marzo de 2022
```

2021-11-05 16:51 UTC, abderossi commented on guides/manage-account/reports/available-money/api.en.md
> +> Use the [Release report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance a
```suggestion
> You can use the [Release report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-11-05 16:51 UTC, abderossi commented on guides/manage-account/reports/available-money/generate.en.md
> +> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance
```suggestion
> You can use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-11-05 16:52 UTC, abderossi commented on guides/manage-account/reports/available-money/generate.es.md
> +> Usa el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-acc
```suggestion
> Puedes usar el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) para conciliar las transacciones del dinero disponible en tu cuenta, incluidos tus retiros bancarios.
```

2021-11-05 16:52 UTC, abderossi commented on guides/manage-account/reports/available-money/generate.pt.md
> +> O relatório de Dinheiro disponível será desabilitado em 01 de março, 2022
```suggestion
> O relatório de Dinheiro disponível será desabilitado em 1 de março de 2022
```

2021-11-05 16:54 UTC, abderossi commented on guides/manage-account/reports/available-money/glossary.en.md
> +> The Available Balance report will be disabled next March 01, 2022
```suggestion
> The Available Balance report will be disabled on March 1st, 2022
```

2021-11-05 16:55 UTC, abderossi commented on guides/manage-account/reports/available-money/glossary.es.md
> +> El reporte de Dinero retirado será deshabilitado el próximo 01 marzo, 2022
```suggestion
> El reporte de Dinero retirado será deshabilitado el 1 marzo de 2022
```

2021-11-05 16:55 UTC, abderossi commented on guides/manage-account/reports/available-money/glossary.pt.md
> +> O relatório de Dinheiro disponível será desabilitado em 01 de março, 2022
```suggestion
> O relatório de Dinheiro disponível será desabilitado desde o 1° de março de 2022
```

2021-11-05 16:55 UTC, abderossi commented on guides/manage-account/reports/available-money/how-to-use.en.md
> +> TThe Available Balance report will be disabled from March 01, 2022
```suggestion
> The Available Balance report will be disabled on March 1st, 2022
```

2021-11-05 16:56 UTC, abderossi commented on guides/manage-account/reports/available-money/how-to-use.en.md
> +> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance
```suggestion
> You can use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-11-05 16:56 UTC, abderossi commented on guides/manage-account/reports/available-money/glossary.es.md
> +> Usa el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-acc
```suggestion
> Puedes usar el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) para conciliar las transacciones del dinero disponible en tu cuenta, incluidos tus retiros bancarios.
```

2021-11-05 16:56 UTC, abderossi commented on guides/manage-account/reports/available-money/glossary.en.md
> +> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance
```suggestion
> You can use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-11-05 16:56 UTC, abderossi commented on guides/manage-account/reports/available-money/how-to-use.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado el 1 de marzo de 2022.
```

2021-11-05 16:57 UTC, abderossi commented on guides/manage-account/reports/available-money/how-to-use.es.md
> +> Usa el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-acc
```suggestion
> Puedes usar el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) para conciliar las transacciones del dinero disponible en tu cuenta, incluidos tus retiros bancarios.
```

2021-11-05 16:57 UTC, abderossi commented on guides/manage-account/reports/available-money/how-to-use.pt.md
> +> O relatório de Dinheiro disponível será desabilitado a partir de 1º de março de 2022.
```suggestion
> O relatório de Dinheiro disponível será desabilitado desde o 1° de março de 2022
```

2021-11-05 16:57 UTC, abderossi commented on guides/manage-account/reports/available-money/introduction.en.md
> +> The Available Balance report will be disabled from March 1st, 2022.
```suggestion
> The Available Balance report will be disabled on March 1st, 2022.
```

2021-11-05 17:00 UTC, abderossi commented on guides/manage-account/reports/available-money/introduction.en.md
> +> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance
```suggestion
> You can use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-11-05 17:01 UTC, abderossi commented on guides/manage-account/reports/available-money/introduction.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado desde el 1 de marzo de 2022.
```

2021-11-05 17:04 UTC, abderossi commented on guides/manage-account/reports/available-money/panel.en.md
> +> The Available Balance report will be disabled from March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022
```

2021-11-05 17:04 UTC, abderossi commented on guides/manage-account/reports/available-money/panel.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado desde el 1 de marzo de 2022
```

2021-11-05 17:04 UTC, abderossi commented on guides/manage-account/reports/available-money/panel.es.md
> +> Usa el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-acc
```suggestion
> Puedes usar el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) para conciliar las transacciones del dinero disponible en tu cuenta, incluidos tus retiros bancarios.
```

2021-11-05 17:04 UTC, abderossi commented on guides/manage-account/reports/available-money/withdrawal.en.md
> +> The Available Balance report will be disabled from March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022
```

2021-11-05 17:05 UTC, abderossi commented on guides/manage-account/reports/available-money/withdrawal.en.md
> +> Use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance
```suggestion
> You can use the [Releases report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-11-05 17:05 UTC, abderossi commented on guides/manage-account/reports/available-money/withdrawal.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022
```

2021-11-05 17:05 UTC, abderossi commented on guides/manage-account/reports/available-money/withdrawal.es.md
> +> Usa el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-acc
```suggestion
> Puedes usar el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) para conciliar las transacciones del dinero disponible en tu cuenta, incluidos tus retiros bancarios.
```

2021-11-05 17:05 UTC, abderossi commented on guides/manage-account/reports/general-considerations/reconciliation-reports.en.md
> +> The Available Balance report will be disabled next March O1, 2022
```suggestion
> The Available Balance report will be disabled from March 1st, 2022
```

2021-11-05 17:06 UTC, abderossi commented on guides/manage-account/reports/general-considerations/reconciliation-reports.es.md
> +> El reporte de Dinero retirado será deshabilitado el próximo 01 marzo, 2022
```suggestion
> El reporte de Dinero retirado será deshabilitado desde el 1 de marzo de 2022
```

2021-11-05 17:06 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +> The Available Balance report will be disabled from March 1st, 2022.
```suggestion
> The Available Balance report will be disabled from March 1st, 2022
```

2021-11-05 17:07 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +> Use the [Release report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance a
```suggestion
> You can use the [Release report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/introduction) to reconcile the transactions that affect the balance available in your account, including your bank withdrawals.
```

2021-11-05 17:08 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +Execute the curl you need to check, create and update your reports.
```suggestion
You can configure your reports according to your preferences. Up next, you'll find the API calls you can make to create, consult and update your reports.
```

2021-11-05 17:08 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +### Check configuration
```suggestion
### Check your configuration 
```

2021-11-05 17:09 UTC, abderossi commented on guides/manage-account/reports/available-money/api.en.md
> +### Check configuration
```suggestion
### Check the configuration 
```

2021-11-05 17:10 UTC, abderossi commented on guides/manage-account/reports/available-money/api.en.md
>  ### Create configuration
```suggestion
### Create the configuration
```

2021-11-05 18:26 UTC, abderossi commented on guides/manage-account/reports/available-money/introduction.pt.md
> +> O relatório de Dinheiro disponível será desabilitado a partir de 1º de março de 2022.
```suggestion
> A partir do dia 1º de março de 2022, o relatório Dinheiro disponível será desabilitado
```

2021-11-05 18:27 UTC, abderossi commented on guides/manage-account/reports/available-money/withdrawal.pt.md
> +> O relatório de Dinheiro disponível será desabilitado a partir de 1º de março de 2022.
```suggestion
> A partir do dia 1º de março de 2022, o relatório Dinheiro disponível será desabilitado
```

2021-11-05 18:27 UTC, abderossi commented on guides/manage-account/reports/general-considerations/reconciliation-reports.pt.md
> +> O relatório de Dinheiro disponível será desabilitado em 01 de março, 2022
```suggestion
> A partir do dia 1º de março de 2022, o relatório Dinheiro disponível será desabilitado
```

2021-11-05 18:28 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +Check the configuration of your reports by API in this way:
```suggestion
You can check the configuration of your reports by API using these commands:
```

2021-11-05 18:29 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +### Check configuration
```suggestion
### Check the configuration 
```

2021-11-05 18:30 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +Check the configuration of your reports by API in this way:
```suggestion
To check the configuration of your reports by API using with these codes:
```

2021-11-05 18:32 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +### Create configuration
```suggestion
### Create your configuration
```

2021-11-05 18:32 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive an `HTTP STATUS 200 (OK)` in response.
```suggestion
You will receive an `HTTP STATUS 200 (OK)` in response:
```

2021-11-05 18:33 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +You will receive an  `HTTP STATUS 200 (Ok)` in response.
```suggestion
You will receive an  `HTTP STATUS 200 (Ok)` in response:
```

2021-11-05 18:35 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +#### Start scheduled generation
```suggestion
```

2021-11-05 18:36 UTC, abderossi commented on guides/manage-account/reports/released-money/api.en.md
> +### 2. Cancel scheduled generation
```suggestion
#### Cancel scheduled generation
```

2021-11-05 18:54 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Genere el reporte de Liberaciones de forma manual las veces que quieras o prográmalo según tus necesidades de frecuencia a través de nuestra API.
```suggestion
Genera el reporte de  [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) de forma manual las veces que quieras o prográmalo según tus necesidades de frecuencia a través de nuestra API. 
```

2021-11-05 18:55 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Genere el reporte de Liberaciones de forma manual las veces que quieras o prográmalo según tus necesidades de frecuencia a través de nuestra API.
```suggestion
Genera el reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------ de forma manual las veces que quieras o prográmalo según tus necesidades de frecuencia a través de nuestra API. 
```

2021-11-05 19:00 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +> Usa el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-acc
```suggestion
> Puedes usar el [reporte de ----[mla]----Liquidaciones------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberaciones------------](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/introduction) para conciliar las transacciones del dinero disponible en tu cuenta, incluidos tus retiros bancarios.
```

2021-11-05 19:00 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +> El reporte de Dinero retirado será deshabilitado a partir del 1 de marzo de 2022.
```suggestion
> El reporte de Dinero retirado será deshabilitado desde el 1 de marzo de 2022
```

2021-11-05 19:01 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +## Configurar tus reportes
```suggestion
## Configura tus reportes
```

2021-11-05 19:02 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Ejecuta el curl que necesites para consultar, crear y actualizar tus reportes.
```suggestion
Puedes configurar tus reportes según lo que necesites. A continuación, te mencionamos cuáles son las llamadas a la API que puedes hacer para crear, consultar y actualizar tus reportes.
```

2021-11-05 19:03 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +### Consultar configuraciones
```suggestion
### Consulta tu configuración
```

2021-11-05 19:04 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Ejecuta el curl que necesites para crear, consultar y actualizar tus reportes.
```suggestion
```

2021-11-05 19:12 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +### Crear configuraciones
```suggestion
### Crea tus configuraciones
```

2021-11-05 19:13 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +### Actualizar configuraciones
```suggestion
### Actualiza tus configuraciones
```

2021-11-05 19:13 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +## Generar tu reporte de forma manual
```suggestion
## Genera tu reporte de forma manual 
```

2021-11-05 19:13 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Haz el POST a la API especificando las fechas deseadas para inicio y fin del reporte de la siguiente manera:
```suggestion
Haz el llamado POST a la API especificando las fechas deseadas para inicio y fin del reporte de la siguiente manera:
```

2021-11-05 19:14 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Consulta la API para ver si la generación de reportes quedó lista:
```suggestion
Consulta a la API para ver si la generación de reportes quedó lista:
```

2021-11-05 19:14 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +El objeto de respuesta tendrá una estructura similar al ejemplo siguiente:
```suggestion
El objeto de respuesta tendrá una estructura similar a este ejemplo:
```

2021-11-05 19:17 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +Programa la generación de tu reporte configurando tres instancias: creación, configuración y descarga.
@NaNieto aquí se mencionan los pasos "creación, configuración y descarga", pero a continuación se describen creación, **eliminación** y descarga. Cuál es el correcto? En caso de ser eliminación, no creo que deberíamos contarlo dentro de este item sino aparte.

2021-11-05 19:18 UTC, abderossi commented on guides/manage-account/reports/available-money/api.es.md
> +### 2. Eliminación
@NaNieto arriba se mencionan los pasos "creación, configuración y descarga", pero aquí se describen creación, **eliminación** y descarga. Cuál es el correcto? En caso de ser eliminación, no creo que deberíamos contarlo dentro de este item sino aparte.

2021-11-05 19:20 UTC, abderossi commented on guides/manage-account/reports/released-money/api.es.md
> +> Puedes generar tus reportes de Dinero retirado desde el panel de Mercado Pago en tres simples pasos.
@NaNieto no recomendaría aquí el reporte de dinero retirado ya que es el que será deshabilitado. Podremos reemplazarlo por el de Liberaciones

2021-11-05 19:20 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +Gere o relatório de Liquidações manualmente quantas vezes quiser ou programe-o de acordo com a frequência desejada por meio de nossa API.
```suggestion

```

2021-11-05 19:21 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +Gere o relatório de Dinheiro disponível manualmente quantas vezes quiser ou programe-o de acordo com a frequência desejada por meio de nossa API.
```suggestion
```

2021-11-05 19:22 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +Gere o relatório de Liquidações manualmente quantas vezes quiser ou programe-o de acordo com a frequência desejada por meio de nossa API.
```suggestion
Gere o relatório de ----[mla]----Liquidações------------ ----[mlm, mlb, mlc, mco, mlu, mpe]----Liberações------------ manualmente quantas vezes quiser ou programe-o de acordo com a frequência desejada por meio de nossa API.
```

2021-11-05 19:22 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +> O relatório de Dinheiro disponível será desabilitado a partir de 1o de março de 2022.
```suggestion
> A partir do dia 1º de março de 2022, o relatório Dinheiro disponível será desabilitado
```

2021-11-05 19:23 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +## Configurar os seus relatórios
```suggestion
## Configure seus relatórios
```

2021-11-05 19:23 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +### Consultando configurações
```suggestion
### Consulte seus configurações
```

2021-11-05 19:24 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +### Criando configurações
```suggestion
### Crie as configurações
```

2021-11-05 19:24 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +Crie as suas preferências de geração de relatório via API para exportar colunas, nomear seus arquivos e configurar outros ajustes:
```suggestion
Crie suas preferências de geração de relatório via API para exportar colunas, nomear seus arquivos e configurar outros ajustes:
```

2021-11-05 19:28 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +    "include_withdrawal_at_end": triue,
```suggestion
    "include_withdrawal_at_end": true,
```

2021-11-05 19:28 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +## Gerando os seus relatórios manualmente
```suggestion
## Gerando seus relatórios manualmente 
```

2021-11-05 19:28 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +Faça o POST à API especificando as datas de início e fim desejadas, assim:
```suggestion
Faça uma chamada POST à API especificando as datas de início e fim desejadas, assim:
```

2021-11-05 19:31 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +### 3. *Download*
```suggestion
### 3. Download
```

2021-11-05 19:31 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +xxxxxxxx
@NaNieto aquí falta texto, puede ser?

2021-11-05 19:33 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +De acordo com o cenário desejado, execute os *curls* abaixo para iniciar e cancelar, respectivamente, a geração programada do seu relatório:
```suggestion
É possível configurar seus relatórios de acordo com o que você precisa. A seguir, mostramos quais as chamadas de API necessárias para iniciar e cancelar a geração programada do seu relatório:
```

2021-11-05 19:33 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +#### Cancelar geração automática
```suggestion
#### Cancele a geração automática
```

2021-11-05 19:46 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +        "user_id": USER-ID,
```suggestion
        "user_id": "USER_ID",
```

2021-11-05 19:46 UTC, abderossi commented on guides/manage-account/reports/available-money/api.pt.md
> +    "user_id": "USER-ID",
```suggestion
    "user_id": "USER_ID",
```

2021-11-05 19:48 UTC, abderossi commented on guides/manage-account/reports/released-money/api.pt.md
> +### 3. *Download*
```suggestion
### 3. Download
```

2021-11-05 19:49 UTC, abderossi requested changes
Hola @NaNieto! Dejé varios ajustes y algunas consultas. Gracias!

2021-11-10 02:00 UTC, NaNieto commented on guides/manage-account/reports/available-money/api.es.md
> +### 2. Eliminación
@abderossi lo que pasa es que esa configuración en si lo que hace es Ejecutar el curl que necesites para cancelar la generación programada de tus reportes. y su metodo es un delete. decidimos dejarlo asi. me apoyo en @ccamargov-meli

2021-11-10 02:02 UTC, NaNieto commented on guides/manage-account/reports/available-money/api.es.md
>  ### Crear configuración
falta un espacio luego de tus !

2021-11-11 23:13 UTC, abderossi approved these changes

2021-11-11 23:16 UTC, merged