WooCommerce new documentation
mercadopago/devsite-docs pull request #1299
Opened 2021-09-13 17:20 UTC by rwaetemann

## Description

WooCommerce documentation needed to be rewritten with some new sections and informations. Furthermore, new technical writing concepts were applied to the documentation, making it clearer and easier to understand.

### Issue involved

### Checklist:

- [x] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features.

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/introduction.en.md
> +For more information about the benefits, taxes, terms and types of checkout available, access the [WooCommerce with Mercado Pago page](https://www.mercadopago.com.br/ferramentas-para-vender/link-de-p
```suggestion
For more information about the benefits, taxes, terms, and types of checkout available, access the [WooCommerce with Mercado Pago page](https://www.mercadopago.com.br/ferramentas-para-vender/link-de-pagamento-plugins-checkout/plugins/vender-woocommerce?utm_experiment=optimize&matt_tool=10047855&matt_word=MLB_MP_G_AO_OP_COW_SEARCH_SELL_TXS_Checkout-WooCommerce-Branded&gclid=Cj0KCQjw6s2IBhCnARIsAP8RfAjJHJVBE0is6oJv5K3_v9qiv44mYs52j7TlFtAMe2AVWKoJ-DAga_4aAuH7EALw_wcB).
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/introduction.en.md
> +> On July 13th 2021, WooCommerce notified its customers that some of its versions were vulnerable. The necessary fixes were already made in the last update. Therefore, it is very important that your
```suggestion
> On July 13th, 2021, WooCommerce notified its customers that some of its versions were vulnerable. The necessary fixes were already made in the last update. Therefore, it is very important that your store has the latest version of WooCommerce updated to prevent exposing sensitive information. For more information, see the [WooCommerce blog](https://woocommerce.com/pt-br/posts/critical-vulnerability-detected-july-2021).
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| WordPress | Online tool for stores, websites and blog creation. [Click here](https://br.wordpress.org/about/) for more information. | Installation version required 4.9.10 or higher. Tested up to 5.
```suggestion
| WordPress | Online tool for stores, websites, and blog creation. [Click here](https://br.wordpress.org/about/) for more information. | Installation version required 4.9.10 or higher. Tested up to 5.8.x |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| Environment | Hosting service. | MySQL, PHP or equivalent service that supports WordPress installation. |
```suggestion
| Environment | Hosting service. | MySQL, PHP, or equivalent service that supports WordPress installation. |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| Operational system | System responsible for managing the computer's hardware. | Linux x86, Windows x86-64 |
```suggestion
| Operational system | System that is responsible for managing the computer's hardware. | Linux x86, Windows x86-64 |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| PHP Version | PHP is a widely used programming language for web application development. For more information, [click here](https://www.php.net/). | PHP 5.6 and 7.x |
```suggestion
| PHP Version | PHP is a widely-used programming language for web application development. For more information, [click here](https://www.php.net/). | PHP 5.6 and 7.x |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| Database | Sets of files related to each other with records about people, places or things. | MySQL 5.6 or higher (Oracle or Percona), MariaDB 10.0 or higher.|
```suggestion
| Database | Sets of files related to each other with records about people, places, or things. | MySQL 5.6 or higher (Oracle or Percona), MariaDB 10.0 or higher.|
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| Additional configuration | Recommended settings for better performance and proper functioning of Wordpress, WooCommerce and Mercado Pago plugin. | [safe_mode](https://wordpress.org/plugins/safe-mod
```suggestion
| Additional configuration | Recommended settings for better performance and proper functioning of WordPress, WooCommerce, and Mercado Pago plugin. | [safe_mode](https://wordpress.org/plugins/safe-mode/) off* [memory_limit](https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/) greater than 256MB (512MB recommended). |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| Backup copy **(optional)**| Copy all your information in order to guarantee a version without any changes if necessary. | We advise you to back up the online store before making any changes. When c
```suggestion
| Backup copy **(optional)**| Copy all your information to guarantee a version without any changes if necessary. | We advise you to back up the online store before making any changes. When copying is complete, delete all files related to the previous version of the module. |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/sales-processing.en.md
> +With all steps completed, your customers will be able to make purchases from your store. When performing a transaction, it is commom for some messages to return with specific information about the pu
```suggestion
With all steps completed, your customers will be able to make purchases from your store. When performing a transaction, it is common for some messages to return with specific information about the purchase. This information is available in the **Notas do Pedido** section of the WooCommerce panel.
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/sales-processing.en.md
> +Every sale generates a payment status that shows the status of the sale including confirmation, pending or denial of payment and other important information about the transaction.
```suggestion
Every sale generates a payment status that shows the condition of the purchase, including confirmation, pending, or denial of payment and other important information about the transaction.
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/sales-processing.en.md
> +There are two statuses in a WooCommerce sale: _status do pedido_ and _status do pagamento_. In the table below you can check the details on how this information correlates.
```suggestion
There are two statuses in a WooCommerce sale: _status do pedido_ and _status do pagamento_. In the following table, you can check the details on how this information correlates.
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/sales-processing.en.md
> +Regarding the **approval of payments** in your store, there are three main reasons that can directly impact these results.
```suggestion
Regarding the **approval of payments** in your store, three main reasons can directly impact these results.  
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/sales-processing.en.md
> +| Buyer's mistakes | Errors in filling in address, CPF or card details. | Checkout with clear information in step-by-step purchase. |
```suggestion
| Buyer's mistakes | Errors in filling in address, CPF, or card details. | Checkout with clear information in the step-by-step purchase. |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/sales-processing.en.md
> +| Banking refusals | Cards with expiration date, lack of limit, insufficient funds or disabled for online purchases. | Offer alternatives to other methods and/or payment terms. |
```suggestion
| Banking refusals | Cards with an expiration date, lack of limit, insufficient funds, or disabled for online purchases. | Offer alternatives to other methods and/or payment terms. |
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/testing.en.md
> +With the store in test mode, you can test a purchase before enabling it for the public. To do this, perform the entire purchase flow until completion at checkout and select the option **credit card p
```suggestion
With the store in test mode, you can test purchases before enabling them for the public. To do this, perform the entire purchase flow until completion at checkout and select the option **credit card payment**, as shown in the instructions below.
```

2021-09-15 14:51 UTC, biaguerreiromeli commented on guides/plugins/woocommerce/testing.en.md
> +If the test runs without errors, it means your store is ready to sell. However, we recommend you to perform additional tests so that you can view the different payment results.
```suggestion
If the test runs without errors, it means your store is ready to sell. However, we recommend you perform additional tests so that you can view the different payment results.
```

2021-09-15 16:59 UTC, biaguerreiromeli approved these changes

2021-09-15 17:21 UTC, pbracale commented on guides/plugins/woocommerce/faq.pt.md
> +O WooCommerce permite que seus usuários configurem por quanto tempo um pedido permanecerá como pendente. Essa funcionalidade pode ser acessada através do **menu de configurações** do WooCommerce, em
Esse menu é em minúscula mesmo?

2021-09-15 17:37 UTC, pbracale approved these changes

2021-09-15 17:37 UTC, pbracale commented on guides/plugins/woocommerce/goto-production.pt.md
> +Pronto! Sua loja está em Produção e habilitada para transacionar suas vendas.
```suggestion
Pronto! Sua loja está em Produção e habilitada para realizar suas vendas.
```

2021-09-15 17:37 UTC, pbracale commented on guides/plugins/woocommerce/instalation.pt.md
> +> Acesse o passo a passo para configurar a integração do plugin.
```suggestion
> Acesse o passo-a-passo para configurar a integração do plugin.
```

2021-09-15 17:37 UTC, pbracale commented on guides/plugins/woocommerce/testing.pt.md
> +1. Deslogue-se da sua conta do Mercado Pago para que consiga simular a compra como um cliente não associado ao Mercado pago.
```suggestion
1. Desconecte-se da sua conta do Mercado Pago para que consiga simular a compra como um cliente não associado ao Mercado pago.
```

2021-09-15 19:43 UTC, rwaetemann commented on guides/plugins/woocommerce/faq.pt.md
> +O WooCommerce permite que seus usuários configurem por quanto tempo um pedido permanecerá como pendente. Essa funcionalidade pode ser acessada através do **menu de configurações** do WooCommerce, em
O FAQ você diz, Pri? FAQ será maiúscula no menu do DevSite.

2021-09-15 20:02 UTC, pbracale commented on guides/plugins/woocommerce/faq.pt.md
> +O WooCommerce permite que seus usuários configurem por quanto tempo um pedido permanecerá como pendente. Essa funcionalidade pode ser acessada através do **menu de configurações** do WooCommerce, em
não... **produtos > inventário** na UI... está em minúscula mesmo?

2021-09-15 20:37 UTC, abderossi commented on guides/plugins/woocommerce/faq.es.md
> +Si deseas ser un asociado, [haz clic aquí](https://www.mercadopago.com.br/developers/es/developer-program#dev-program-benefits) para obtener más información.
El link al dev program es únicamente de Brasil. ¿No deberíamos localizarlo para todos los países?

2021-09-15 20:37 UTC, abderossi commented on guides/plugins/woocommerce/faq.es.md
> +WooCommerce permite a sus usuarios configurar cuánto tiempo permanecerá pendiente un pedido. Se puede acceder a esta funcionalidad a través del menú **Ajustes** de WooCommerce, en ß**Productos > Inve
```suggestion
WooCommerce permite a sus usuarios configurar cuánto tiempo permanecerá pendiente un pedido. Se puede acceder a esta funcionalidad a través del menú **Ajustes** de WooCommerce, en **Productos > Inventario**. 
```

2021-09-15 20:38 UTC, abderossi commented on guides/plugins/woocommerce/faq.es.md
> +Para obtener más información, accede a **inventario** en [el manual de la plataforma](https://docs.woocommerce.com/document/perguntas-frequentes-sobre-reservas/).
```suggestion
Para obtener más información, accede a **inventario** en el [manual de la plataforma](https://docs.woocommerce.com/document/perguntas-frequentes-sobre-reservas/).
```

2021-09-15 20:38 UTC, abderossi commented on guides/plugins/woocommerce/faq.es.md
> +Para obtener más información, accede a **inventario** en [el manual de la plataforma](https://docs.woocommerce.com/document/perguntas-frequentes-sobre-reservas/).
Opcional!

2021-09-15 20:39 UTC, abderossi commented on guides/plugins/woocommerce/goto-production.es.md
> +Para obtener más información, visita nuestra documentación [Requisitos para salir a producción](https://www.mercadopago.com.br/developers/es/guides/online-payments/checkout-api/goto-production).
```suggestion
Para obtener más información, visita nuestra documentación [Requisitos para salir a producción](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/goto-production).
```

2021-09-15 20:41 UTC, abderossi commented on guides/plugins/woocommerce/goto-production.es.md
> +4. En _¿Como quieres operar los checkouts de tu tienda?_, selecciona la opción _Activar Modo Producción para checkouts Mercado Pago_.
Actualmente no utilizamos _italic_ en las documentaciones del devsite. Lo ideal, para mantener el estilo general, sería reemplazarlas por "" o continuar con el uso de bold.

2021-09-15 20:42 UTC, abderossi commented on guides/plugins/woocommerce/instalation.es.md
> +> Si tienes problemas para instalar el complemento y necesitas ponerte en contacto con nuestro soporte, es posible que te soliciten que lo instales manualmente. Consulta las preguntas frecuentes para
Aquí, en "Consulta las preguntas frecuentes", podríamos linkearlo con las FAQs.

2021-09-15 20:45 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +Credenciales de producción, porque al finalizar las pruebas iniciales habilitaremos la tienda para procesar las ventas reales y es a través de estas credenciales que se realiza la activación.
En general creo que esta descripción de por qué se piden las credenciales está rara. Dejo una sugerencia de cómo podríamos contarlo para que la historia tenga más sentido:

En la sección "Ingresa las credenciales para el Modo Test o el Modo Producción", se te pedirá que ingreses tus credenciales de **producción** y **test**.

Necesitarás las **credenciales de producción**  porque al finalizar las pruebas iniciales habilitaremos la tienda para procesar las ventas reales y es a través de estas credenciales que se realiza la activación.

Las **credenciales de prueba** serán necesarias para realizar pruebas para asegurar el correcto funcionamiento del flujo de compra y pago.

2021-09-15 20:45 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +En la sección _Ingresa las credenciales para el Modo Test o el Modo Producción_, se te pedirá que ingreses tus credenciales de **producción** y **test**.
```suggestion
En la sección _Ingresa las credenciales para el Modo Test o el Modo Producción_, se te pedirá que ingreses tus credenciales de **producción** y **prueba**.
```

2021-09-15 20:46 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +2. En **Configura los pagos de la tienda para el modo Test o Producción**, selecciona la opción **Activar Modo Test para checkouts Mercado Pago**. Al mantener este campo habilitado, tu tienda estará
```suggestion
2. En **Configura los pagos de la tienda para el modo Prueba o Producción**, selecciona la opción **Activar Modo Test para checkouts Mercado Pago**. Al mantener este campo habilitado, tu tienda estará en **modo test**, lo que te permitirá probar el funcionamiento del plugin antes de habilitar la tienda para producción.
```

2021-09-15 20:46 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +En la sección _Ingresa las credenciales para el Modo Test o el Modo Producción_, se te pedirá que ingreses tus credenciales de **producción** y **test**.
Les decimos "credenciales test" porque así lo menciona el plugin? O estamos hablando de las credenciales de prueba de Mercado Pago?

2021-09-15 20:47 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +En *Ajustes avançados*, configura las opciones relacionadas con el almacenamiento de información en un archivo para depurar problemas técnicos, así como para configurar las [notificaciones de IPN](ht
```suggestion
En *Ajustes avançados*, configura las opciones relacionadas con el almacenamiento de información en un archivo para depurar problemas técnicos, así como para configurar las [notificaciones de IPN](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/notifications/ipn).
```

2021-09-15 20:47 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +3. Ingresa tus credenciales de **test** y **producción** en los campos obligatorios. Si aún no tienes esta información, accede a nuestra documentación [Credenciales](https://www.mercadopago.com.br/de
```suggestion
3. Ingresa tus credenciales de **prueba** y **producción** en los campos obligatorios. Si aún no tienes esta información, accede a nuestra documentación [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) y sigue el paso a paso para obtenerlas. 
```

2021-09-15 20:49 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +1. **Ativar o checkout:** selecciona _Sim_ para habilitar la experiencia de Mercado Pago en el checkout de tu tienda.
@rwaetemann Consulta: creés necesario que estas diferentes opciones aparezcan enumeradas? Podrían ir en bullets ya que no son un paso a paso? Qué opinas?

2021-09-15 20:51 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +14. **Pix:** si deseas ofrecer pagos de Pix, debes activar el **pago personalizado - Paga con Pix** y seguir los pasos descritos en pantalla para completar la integración. **(Solo para Brasil)**
```suggestion
----[mlb]----
14. **Pix:** si deseas ofrecer pagos de Pix, debes activar el **pago personalizado - Paga con Pix** y seguir los pasos descritos en pantalla para completar la integración. **(Solo para Brasil)**
15. **Vencimento do Pix:** elige un período de validez del código enviado al cliente después de realizar el pedido. Este será el período que el cliente deberá pagar por la compra. **(Solo para Brasil)**
16. **Pagamento com cartões salvos:** permite a los clientes comprar con los datos de su tarjeta guardados en Mercado Pago, sin tener que completar los datos de la tarjeta al momento de pagar en la tienda.
------------
```

2021-09-15 20:51 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +15. **Vencimento do Pix:** elige un período de validez del código enviado al cliente después de realizar el pedido. Este será el período que el cliente deberá pagar por la compra. **(Solo para Brasil
```suggestion

```

2021-09-15 20:52 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +16. **Pagamento com cartões salvos:** permite a los clientes comprar con los datos de su tarjeta guardados en Mercado Pago, sin tener que completar los datos de la tarjeta al momento de pagar en la t
```suggestion
```

2021-09-15 20:53 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +1. **Ativar o checkout:** selecciona _Sim_ para habilitar la experiencia de Mercado Pago en el checkout de tu tienda.
```suggestion
----[mla, mlu, mlc, mco, mpe, mlm]----
1. **Ativar o checkout:** selecciona _Sim_ para habilitar la experiencia de Mercado Pago en el checkout de tu tienda.
```

2021-09-15 20:54 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +13. **Comissão por compra com Mercado Pago:** elige un porcentaje adicional que desees cobrar como tarifa a sus clientes por pagar con Mercado Pago.
```suggestion
13. **Comissão por compra com Mercado Pago:** elige un porcentaje adicional que desees cobrar como tarifa a sus clientes por pagar con Mercado Pago.
14. **Pagamento com cartões salvos:** permite a los clientes comprar con los datos de su tarjeta guardados en Mercado Pago, sin tener que completar los datos de la tarjeta al momento de pagar en la tienda.
```

2021-09-15 20:55 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +13. **Comissão por compra com Mercado Pago:** elige un porcentaje adicional que desees cobrar como tarifa a sus clientes por pagar con Mercado Pago.
Coloqué **Pagamento com cartões salvos** como número 14, de esta manera podemos localizar ambos items relacionados con Pix unicamente para Brasil.

2021-09-15 20:56 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +15. **Vencimento do Pix:** elige un período de validez del código enviado al cliente después de realizar el pedido. Este será el período que el cliente deberá pagar por la compra. **(Solo para Brasil
Incluido arriba solo para Brasil.

2021-09-15 20:56 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +16. **Pagamento com cartões salvos:** permite a los clientes comprar con los datos de su tarjeta guardados en Mercado Pago, sin tener que completar los datos de la tarjeta al momento de pagar en la t
Incluido arriba solo para Brasil.

2021-09-15 20:57 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +> WARNING
```suggestion
----[mlb]----
> WARNING
```

2021-09-15 20:57 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +> Antes de configurar Pix como método de pago, te recomendamos descargar la última versión del plugin Mercado Pago para WooCommerce y registrar tu clave Pix en Mercado Pago. **(Solo para Brasil)**
```suggestion
> Antes de configurar Pix como método de pago, te recomendamos descargar la última versión del plugin Mercado Pago para WooCommerce y registrar tu clave Pix en Mercado Pago. **(Solo para Brasil)**
------------

```

2021-09-15 21:04 UTC, abderossi commented on guides/plugins/woocommerce/introduction.es.md
> +[WooCommerce](https://woocommerce.com/) es un complemento que te permite habilitar tu sitio web / blog de [WordPress](https://wordpress.com/pt-br/create/?utm_source=google&utm_campaign=google_wpcom_s
```suggestion
[WooCommerce](https://woocommerce.com/) es un complemento que te permite habilitar tu sitio web/blog de [WordPress](https://wordpress.com/pt-br/create/?utm_source=google&utm_campaign=google_wpcom_search_brand_desktop_br_pt&utm_medium=paid_search&keyword=wordpress&creative=405409862800&campaignid=662299893&adgroupid=55904101192&matchtype=e&device=c&network=g&targetid=kwd-313411415&gclsrc=aw.ds&gclid=Cj0KCQjw6s2IBhCnARIsAP8RfAjJw-W6L7Lm5t3QdPwg8oRXUA783ncsLK4sSYBaU5ObfjUylCwwi20aAgLXEALw_wcB) para que funcione como una tienda virtual con la tranquilidad de ofrecer a los compradores la posibilidad de realizar pagos utilizando Mercado Pago a través de una integración.
```

2021-09-15 21:05 UTC, abderossi commented on guides/plugins/woocommerce/introduction.es.md
> +Para obtener más información sobre los beneficios, tarifas, términos y tipos de pago disponibles, visita la página [WooCommerce com Mercado Pago](https://www.mercadopago.com.br/ferramentas-para-vende
```suggestion
Para obtener más información sobre los beneficios, tarifas, términos y tipos de pago disponibles, visita la página [WooCommerce con Mercado Pago](https://www.mercadopago.com.br/ferramentas-para-vender/link-de-pagamento-plugins-checkout/plugins/vender-woocommerce?utm_experiment=optimize&matt_tool=10047855&matt_word=MLB_MP_G_AO_OP_COW_SEARCH_SELL_TXS_Checkout-WooCommerce-Branded&gclid=Cj0KCQjw6s2IBhCnARIsAP8RfAjJHJVBE0is6oJv5K3_v9qiv44mYs52j7TlFtAMe2AVWKoJ-DAga_4aAuH7EALw_wcB). 
```

2021-09-15 21:07 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.es.md
> +Para utilizar la integración de Mercado Pago con WooCommerce en tu WordPress, debe cumplir con los requisitos a continuación.
```suggestion
Para utilizar la integración de Mercado Pago con WooCommerce en tu WordPress, debes cumplir con los requisitos a continuación.
```

2021-09-15 21:07 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.es.md
> +| Cuenta de vendedor Mercado Pago | Para realizar ventas se necesita una cuenta de vendedor en Mercado Pago. Si aún no tienes una, [haz clic aquí](https://www.mercadopago.com.br/hub/registration/land
la URL es de Brasil. Hay versiones de otros países para poder localizarla?

2021-09-15 21:08 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.es.md
> +| WooCommerce | WordPress Plugin que permite crear tiendas virtuales desde código abierto. [Haz clic aquí](https://woocommerce.com/pt-br/woocommerce-features/) para obtener más información. | Requeri
Hay versión en español de esta URL?

2021-09-15 21:09 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.es.md
> +| Copia de seguridad **(opcional)** | Copie toda su información para asegurar una versión sin cambios si es necesario. | Le recomendamos que haga una copia de seguridad de la tienda online antes de r
Más que "opcional", yo le diría "recomendado" ya que si bien no es obligatorio, es importante. Qué te parece?

2021-09-15 21:09 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.es.md
> +> Siga los pasos a continuación para instalar el complemento de Mercado Pago con WooCommerce.
```suggestion
> Sigue los pasos a continuación para instalar el complemento de Mercado Pago con WooCommerce.
```

2021-09-15 21:09 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.es.md
> +> [Instalación del complemento](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/woocommerce/installation)
```suggestion
> [Instalación del complemento](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/woocommerce/installation)
```

2021-09-15 21:11 UTC, abderossi commented on guides/plugins/woocommerce/sales-processing.es.md
> +Para obtener más información, accede a la sección [Actividades](https://www.mercadopago.com.br/activities) de tu cuenta de Mercado Pago y al [manual de pedidos de WooCommerce](https://docs.woocommerc
hay versión de otros países para esta URL? Faltaría localizarla

2021-09-15 21:12 UTC, abderossi commented on guides/plugins/woocommerce/sales-processing.es.md
> +* [Rechazos de pago](https://conteudo.mercadopago.com.br/entenda-como-funcionam-as-recusas-de-aprovacao-de-pagamentos-no-mercado-pago)
hay versión de otros países para la URL de Mercado Pago? Faltaría localizarla

2021-09-15 21:12 UTC, abderossi commented on guides/plugins/woocommerce/sales-processing.es.md
> +* [Manejar las denegaciones de pago](https://conteudo.mercadopago.com.br/como-lidar-com-as-recusas-de-pagamento-do-cartao-de-credito-no-seu-e-commerce)
hay versión de otros países para la URL de Mercado Pago? Faltaría localizarla

2021-09-15 21:13 UTC, abderossi commented on guides/plugins/woocommerce/testing.es.md
> +6. Selecciona el pago con tarjeta de crédito y usa la información de tarjeta disponible en nuestra página [Tarjetas locales de prueba](https://www.mercadopago.com.br/developers/es/guides/resources/lo
```suggestion
6. Selecciona el pago con tarjeta de crédito y usa la información de tarjeta disponible en nuestra página [Tarjetas locales de prueba](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/localization/local-cards).
```

2021-09-15 21:14 UTC, abderossi requested changes
@rwaetemann comparto ajustes de traducciones y localizaciones de links y contenido, sugerencias de estilo y algunas dudas. Gracias!

2021-09-16 13:08 UTC, rwaetemann commented on guides/plugins/woocommerce/goto-production.es.md
> +4. En _¿Como quieres operar los checkouts de tu tienda?_, selecciona la opción _Activar Modo Producción para checkouts Mercado Pago_.
```suggestion
4. En **¿Como quieres operar los checkouts de tu tienda?**, selecciona la opción **Activar Modo Producción para checkouts Mercado Pago**. 
```

2021-09-16 13:39 UTC, rwaetemann commented on guides/plugins/woocommerce/instalation.es.md
> +> Si tienes problemas para instalar el complemento y necesitas ponerte en contacto con nuestro soporte, es posible que te soliciten que lo instales manualmente. Consulta las preguntas frecuentes para
@abderossi - Gosti, é possível fazer isso por aqui mesmo?

2021-09-16 13:42 UTC, rwaetemann commented on guides/plugins/woocommerce/faq.es.md
> +Si deseas ser un asociado, [haz clic aquí](https://www.mercadopago.com.br/developers/es/developer-program#dev-program-benefits) para obtener más información.
@abderossi - Gosti, aqui não sei exatamente como faríamos para localizar para todos os países. Pode me ajudar?

2021-09-16 13:43 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +Credenciales de producción, porque al finalizar las pruebas iniciales habilitaremos la tienda para procesar las ventas reales y es a través de estas credenciales que se realiza la activación.
Bueníssimo, Gosti! Gracias :)

2021-09-16 13:44 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +Credenciales de producción, porque al finalizar las pruebas iniciales habilitaremos la tienda para procesar las ventas reales y es a través de estas credenciales que se realiza la activación.
```suggestion
Necesitarás las **credenciales de producción** porque al finalizar las pruebas iniciales habilitaremos la tienda para procesar las ventas reales y es a través de estas credenciales que se realiza la activación.
```

2021-09-16 13:45 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +Credenciales de test, porque en un primer momento será necesario realizar pruebas para asegurar el correcto funcionamiento del flujo de compra y pago.
```suggestion
Las **credenciales de test** serán necesarias para realizar pruebas para asegurar el correcto funcionamiento del flujo de compra y pago.
```

2021-09-16 13:51 UTC, rwaetemann commented on guides/plugins/woocommerce/previous-requirements.es.md
> +| Copia de seguridad **(opcional)** | Copie toda su información para asegurar una versión sin cambios si es necesario. | Le recomendamos que haga una copia de seguridad de la tienda online antes de r
Bueníssimo!!!

2021-09-16 13:52 UTC, rwaetemann commented on guides/plugins/woocommerce/previous-requirements.es.md
> +| Copia de seguridad **(opcional)** | Copie toda su información para asegurar una versión sin cambios si es necesario. | Le recomendamos que haga una copia de seguridad de la tienda online antes de r
```suggestion
| Copia de seguridad **(recomendado)** | Copie toda su información para asegurar una versión sin cambios si es necesario. | Le recomendamos que haga una copia de seguridad de la tienda online antes de realizar cualquier cambio. Cuando finalice la copia, elimine todos los archivos relacionados con la versión anterior del módulo.|
```

2021-09-16 14:23 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +2. En **Configura los pagos de la tienda para el modo Test o Producción**, selecciona la opción **Activar Modo Test para checkouts Mercado Pago**. Al mantener este campo habilitado, tu tienda estará
Mesmo caso aqui, Gosti! Na UI, dizemos test mesmo, e não prueba, por isso deixamos assim.

2021-09-16 15:32 UTC, abderossi commented on guides/plugins/woocommerce/faq.es.md
> +Si deseas ser un asociado, [haz clic aquí](https://www.mercadopago.com.br/developers/es/developer-program#dev-program-benefits) para obtener más información.
```suggestion
Si deseas ser un asociado, [haz clic aquí](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/developer-program) para obtener más información.
```

2021-09-16 15:34 UTC, abderossi commented on guides/plugins/woocommerce/instalation.es.md
> +> Si tienes problemas para instalar el complemento y necesitas ponerte en contacto con nuestro soporte, es posible que te soliciten que lo instales manualmente. Consulta las preguntas frecuentes para
```suggestion
> Si tienes problemas para instalar el complemento y necesitas ponerte en contacto con nuestro soporte, es posible que te soliciten que lo instales manualmente. Consulta las [Preguntas frecuentes](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/woocommerce/faq) para obtener detalles sobre cómo hacerlo.
```

2021-09-16 15:36 UTC, abderossi commented on guides/plugins/woocommerce/faq.pt.md
> +Quer ser um parceiro, [clique aqui](https://www.mercadopago.com.br/developers/pt/developer-program#dev-program-benefits) para mais informações
```suggestion
Quer ser um parceiro, [clique aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/developer-program) para mais informações
```

2021-09-16 15:37 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +4. **Integrator ID:** ingresa tu *integrator_id* como asociado de Mercado Pago. Si aún no eres un asociado, [haz clic aquí](https://www.mercadopago.com.br/developers/es/developer-program#dev-program-
```suggestion
4. **Integrator ID:** ingresa tu *integrator_id* como asociado de Mercado Pago. Si aún no eres un asociado, [haz clic aquí](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/developer-program) para obtener más información.
```

2021-09-16 15:37 UTC, abderossi commented on guides/plugins/woocommerce/integration.pt.md
> +4. **Integrator ID:** Insira seu *integrator_id* como parceiro do Mercado Pago. Caso ainda não seja um parceiro, [clique aqui](https://www.mercadopago.com.br/developers/pt/developer-program#dev-progr
```suggestion
4. **Integrator ID:** Insira seu *integrator_id* como parceiro do Mercado Pago. Caso ainda não seja um parceiro, [clique aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/developer-program) para mais informações.
```

2021-09-16 15:39 UTC, abderossi commented on guides/plugins/woocommerce/instalation.en.md
> +> If you experience any problems during the plugin installation and need to contact our support, you may have to install it manually. See the FAQ for details on how to do this.
```suggestion
> If you experience any problems during the plugin installation and need to contact our support, you may have to install it manually. See the [FAQ]((https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/woocommerce/faq) for details on how to do this.
```

2021-09-16 15:39 UTC, abderossi commented on guides/plugins/woocommerce/instalation.pt.md
> +> Caso você tenha problemas durante a instalação do plugin e precise entrar em contato com nosso suporte, é possível que você seja solicitado a realizar a instalação de forma manual. Veja a FAQ para
```suggestion
> Caso você tenha problemas durante a instalação do plugin e precise entrar em contato com nosso suporte, é possível que você seja solicitado a realizar a instalação de forma manual. Veja a [FAQ](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/woocommerce/faq)  para detalhes de como fazê-lo.
```

2021-09-16 15:41 UTC, abderossi commented on guides/plugins/woocommerce/faq.en.md
> +Do you want to be a partner? [Click here](https://www.mercadopago.com.br/developers/pt/developer-program#dev-program-benefits) for more information.
```suggestion
Do you want to be a partner? [Click here](https://www.mercadopago[FAKER][DOMAIN][URL]/developers/en/developer-program) for more information.
```

2021-09-16 15:41 UTC, abderossi commented on guides/plugins/woocommerce/integration.en.md
> +3. Enter your **test** and **production** credentials in the required fields. If you don't have this information, access the [Credentials](https://www.mercadopago.com.br/developers/en/guides/resource
```suggestion
3. Enter your **test** and **production** credentials in the required fields. If you don't have this information, access the [Credentials](https://www.mercadopago.[FAKER][DOMAIN][URL]/developers/en/guides/resources/credentials) documentation and follow the required steps. 
```

2021-09-16 15:42 UTC, abderossi commented on guides/plugins/woocommerce/integration.en.md
> +In _Ajustes avançados_, you can configure options related to saving information to a file for debugging technical issues, as well as configuring [IPN notifications](https://www.mercadopago.com.br/dev
```suggestion
In _Ajustes avançados_, you can configure options related to saving information to a file for debugging technical issues, as well as configuring [IPN notifications](https://www.mercadopago[FAKER][DOMAIN][URL]/developers/en/guides/notifications/ipn).
```

2021-09-16 15:42 UTC, abderossi commented on guides/plugins/woocommerce/integration.pt.md
> +3. Insira suas credenciais de **teste** e **produção** nos campos solicitados. Caso ainda não tenha essas informações, acesse nossa documentação [Credenciais](https://www.mercadopago.com.br/developer
```suggestion
3. Insira suas credenciais de **teste** e **produção** nos campos solicitados. Caso ainda não tenha essas informações, acesse nossa documentação [Credenciais](https://www.mercadopago[FAKER][DOMAIN][URL]/developers/pt/guides/resources/credentials) e siga o passo a passo para obtê-las. 
```

2021-09-16 15:43 UTC, abderossi commented on guides/plugins/woocommerce/integration.pt.md
> +Em **Ajustes avançados**, você configura opções relativas ao salvamento de informações em um arquivo para depurar problemas técnicos, além de configurar as [notificações IPN](https://www.mercadopago.
```suggestion
Em **Ajustes avançados**, você configura opções relativas ao salvamento de informações em um arquivo para depurar problemas técnicos, além de configurar as [notificações IPN](https://www.mercadopago[FAKER][DOMAIN][URL]/developers/pt/guides/notifications/ipn). 
```

2021-09-16 15:44 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| Mercado Pago Seller account | To make sales, you need a seller account in Mercado Pago. If you don't have one, [click here](https://www.mercadopago.com.br/hub/registration/landing) to create. | Sel
```suggestion
| Mercado Pago Seller account | To make sales, you need a seller account in Mercado Pago. If you don't have one, [click here](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) to create. | Seller account on Mercado Pago|
```

2021-09-16 15:44 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.es.md
> +| Cuenta de vendedor Mercado Pago | Para realizar ventas se necesita una cuenta de vendedor en Mercado Pago. Si aún no tienes una, [haz clic aquí](https://www.mercadopago.com.br/hub/registration/land
```suggestion
| Cuenta de vendedor Mercado Pago | Para realizar ventas se necesita una cuenta de vendedor en Mercado Pago. Si aún no tienes una, [haz clic aquí](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) para crearla. | Cuenta de vendedor en Mercado Pago. |
```

2021-09-16 15:44 UTC, abderossi commented on guides/plugins/woocommerce/previous-requirements.pt.md
> +| Conta de vendedor Mercado Pago | Para realizar vendas, é preciso uma conta vendedor no Mercado Pago. Caso não tenha, [clique aqui](https://www.mercadopago.com.br/hub/registration/landing) para cria
```suggestion
| Conta de vendedor Mercado Pago | Para realizar vendas, é preciso uma conta vendedor no Mercado Pago. Caso não tenha, [clique aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) para criar.| Conta de vendedor no Mercado Pago |
```

2021-09-16 15:45 UTC, abderossi commented on guides/plugins/woocommerce/sales-processing.en.md
> +For more information, access the [Activities](https://www.mercadopago.com.br/activities) section of your Mercado Pago account and the [WooCommerce order manual](https://docs.woocommerce.com/document/
```suggestion
For more information, access the [Activities](https://www.mercadopago[FAKER][URL][DOMAIN]/activities) section of your Mercado Pago account and the [WooCommerce order manual](https://docs.woocommerce.com/document/como-gerenciar-pedidos/).
```

2021-09-16 15:45 UTC, abderossi commented on guides/plugins/woocommerce/sales-processing.es.md
> +Para obtener más información, accede a la sección [Actividades](https://www.mercadopago.com.br/activities) de tu cuenta de Mercado Pago y al [manual de pedidos de WooCommerce](https://docs.woocommerc
```suggestion
Para obtener más información, accede a la sección [Actividades](https://www.mercadopago[FAKER][URL][DOMAIN]/activities) de tu cuenta de Mercado Pago y al [manual de pedidos de WooCommerce](https://docs.woocommerce.com/document/gestion-de-pedidos/).
```

2021-09-16 15:46 UTC, abderossi commented on guides/plugins/woocommerce/sales-processing.pt.md
> +Para mais informações, acesse a seção [Atividades](https://www.mercadopago.com.br/activities) da sua conta do Mercado Pago e o [manual de pedidos do WooCommerce]( https://docs.woocommerce.com/documen
```suggestion
Para mais informações, acesse a seção [Atividades](https://www.mercadopago[FAKER][URL][DOMAIN]/activities) da sua conta do Mercado Pago e o [manual de pedidos do WooCommerce]( https://docs.woocommerce.com/document/como-gerenciar-pedidos/).
```

2021-09-16 15:46 UTC, abderossi commented on guides/plugins/woocommerce/testing.en.md
> +6. Select **credit card payment** and use the credit card information available on our page [Test local credit cards](https://www.mercadopago.com.br/developers/en/guides/resources/localization/local-
```suggestion
6. Select **credit card payment** and use the credit card information available on our page [Test local credit cards](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/localization/local-cards).
```

2021-09-16 15:46 UTC, abderossi commented on guides/plugins/woocommerce/testing.pt.md
> +6. Selecione o pagamento com cartão de crédito e utilize as informações de cartão disponíveis na nossa página [Cartões nacionais de teste](https://www.mercadopago.com.br/developers/pt/guides/resource
```suggestion
6. Selecione o pagamento com cartão de crédito e utilize as informações de cartão disponíveis na nossa página [Cartões nacionais de teste](https://www.mercadopago.[FAKER][URL][DOMAIN]/developers/pt/guides/resources/localization/local-cards).
```

2021-09-16 17:47 UTC, rwaetemann commented on guides/plugins/woocommerce/faq.pt.md
> +O WooCommerce permite que seus usuários configurem por quanto tempo um pedido permanecerá como pendente. Essa funcionalidade pode ser acessada através do **menu de configurações** do WooCommerce, em
Não, Pri! Maiúsculo mesmo. Já alterei :)

2021-09-16 17:48 UTC, rwaetemann commented on guides/plugins/woocommerce/faq.pt.md
> +O WooCommerce permite que seus usuários configurem por quanto tempo um pedido permanecerá como pendente. Essa funcionalidade pode ser acessada através do **menu de configurações** do WooCommerce, em
```suggestion
O WooCommerce permite que seus usuários configurem por quanto tempo um pedido permanecerá como pendente. Essa funcionalidade pode ser acessada através do **menu de configurações** do WooCommerce, em  **Produtos > Inventário**.
```

2021-09-16 17:53 UTC, rwaetemann commented on guides/plugins/woocommerce/goto-production.es.md
> +Con el certificado activado y la prueba completada, puedes sacar su tienda del modo de prueba y habilitar el modo de **producción**. Esto te permitirá realizar ventas reales.
```suggestion
Con el certificado activado y la prueba completada, puedes sacar su tienda del modo test y habilitar el modo de **producción**. Esto te permitirá realizar ventas reales.
```

2021-09-16 17:54 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +3. Ingresa tus credenciales de **prueba** y **producción** en los campos obligatorios. Si aún no tienes esta información, accede a nuestra documentación [Credenciales](https://www.mercadopago[FAKER][
```suggestion
3. Ingresa tus credenciales de **test** y **producción** en los campos obligatorios. Si aún no tienes esta información, accede a nuestra documentación [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) y sigue el paso a paso para obtenerlas. 
```

2021-09-16 17:57 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +1. **Ativar o checkout:** selecciona _Sim_ para habilitar la experiencia de Mercado Pago en el checkout de tu tienda.
Gosti, acredito que dessa forma possa ficar mais visual. Te explico o porquê: essas etapas são sim um "passo-a-passo", só que dependerão do tipo de checkout que o cliente escolher. Por isso, se ele escolher um que tenha todas as opções (ou não), poderá seguir por cada etapa enumerada sem se confundir, entende? :)

2021-09-16 18:06 UTC, rwaetemann commented on guides/plugins/woocommerce/previous-requirements.es.md
> +| WooCommerce | WordPress Plugin que permite crear tiendas virtuales desde código abierto. [Haz clic aquí](https://woocommerce.com/pt-br/woocommerce-features/) para obtener más información. | Requeri
```suggestion
| WooCommerce | WordPress Plugin que permite crear tiendas virtuales desde código abierto. [Haz clic aquí](https://woocommerce.com/es-es/woocommerce-features/) para obtener más información. | Requerido 3.xo superior. Probado hasta 5.6.x |
```

2021-09-16 18:07 UTC, rwaetemann commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| WooCommerce | WordPress Plugin that allows the creation of virtual stores from open source. [Click here](https://woocommerce.com/pt-br/woocommerce-features/) for more information. | Required 3.x or
```suggestion
| WooCommerce | WordPress Plugin that allows the creation of virtual stores from open source. [Click here](https://woocommerce.com/woocommerce-features/) for more information. | Required 3.x or higher. Tested up to 5.6.x |
```

2021-09-16 18:19 UTC, rwaetemann commented on guides/plugins/woocommerce/goto-production.en.md
> +4. In _Add credentials to "Test Mode" or "Production Mode"_, choose _Activate Production Mode for Mercado Pago checkouts_.
```suggestion
4. In **Add credentials to "Test Mode" or "Production Mode"**, choose **Activate Production Mode for Mercado Pago checkouts**. 
```

2021-09-16 18:20 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.en.md
> +In the *Add credentials to "Test Mode" or "Production Mode"* section, you must fill in your **production** and **test** credentials.
```suggestion
In the **Add credentials to "Test Mode" or "Production Mode"** section, you must fill in your **production** and **test** credentials.
```

2021-09-16 18:23 UTC, rwaetemann commented on guides/plugins/woocommerce/previous-requirements.en.md
> +| Backup copy **(optional)**| Copy all your information to guarantee a version without any changes if necessary. | We advise you to back up the online store before making any changes. When copying is
```suggestion
| Backup copy **(recommended)**| Copy all your information to guarantee a version without any changes if necessary. | We advise you to back up the online store before making any changes. When copying is complete, delete all files related to the previous version of the module. |
```

2021-09-16 18:24 UTC, rwaetemann commented on guides/plugins/woocommerce/previous-requirements.pt.md
> +| Cópia de segurança **(opcional)** | Cópia de todas as informações da sua a fim de garantir uma versão sem qualquer alteração caso seja necessário. | Aconselhamos que você faça uma cópia de seguranç
```suggestion
| Cópia de segurança **(recomendado)** | Cópia de todas as informações da sua a fim de garantir uma versão sem qualquer alteração caso seja necessário. | Aconselhamos que você faça uma cópia de segurança da loja online antes de fazer qualquer alteração. Ao finalizar a cópia, exclua todos os arquivos relacionados à versão anterior do módulo. |
```

2021-09-16 18:25 UTC, rwaetemann commented on guides/plugins/woocommerce/testing.en.md
> +7. When you finish completing the fields, click _Finalizar compra_.
```suggestion
7. When you finish completing the fields, click on _Finalizar compra_.
```

2021-09-16 18:37 UTC, rwaetemann commented on guides/plugins/woocommerce/introduction.pt.md
> +> Em 13 de julho de 2021, o WooCommerce notificou seus clientes de que algumas de suas versões são vulneráveis. As correções necessárias já foram feitas na última atualização. Por isso, é muito impor
```suggestion
> Em 13 de julho de 2021, o WooCommerce notificou seus clientes de que algumas de suas versões são vulneráveis. As correções necessárias já foram feitas na última atualização. Por isso, é muito importante que sua loja esteja com a última versão do WooCommerce atualizada para prevenir a exposição de informações sensíveis. Para obter mais informações, consulte o [blog do WooCommerce](https://woocommerce.com/pt-br/posts/critical-vulnerability-detected-july-2021).
```

2021-09-16 22:06 UTC, abderossi commented on guides/plugins/woocommerce/integration.en.md
> +13. **Comissão por compra com Mercado Pago:** Set an additional percentage amount that you want to charge as a fee to your customers for paying with Mercado Pago.
```suggestion
13. **Comissão por compra com Mercado Pago:** Set an additional percentage amount that you want to charge as a fee to your customers for paying with Mercado Pago.
14. **Pagamento com cartões salvos**: Allows customers to buy with their card details saved at Mercado Pago, without having to fill in card details at the store checkout.
```

2021-09-16 22:06 UTC, abderossi commented on guides/plugins/woocommerce/integration.en.md
> +14. **Pix:** If you want to offer Pix payments, you need to activate **Custom Checkout** **- Pay with Pix** and follow the steps described on the screen to complete the integration. **(Brazil only)**
```suggestion
15. **Pix:** If you want to offer Pix payments, you need to activate **Custom Checkout** **- Pay with Pix** and follow the steps described on the screen to complete the integration. **(Brazil only)**
```

2021-09-16 22:06 UTC, abderossi commented on guides/plugins/woocommerce/integration.en.md
> +15. **Vencimento do Pix:** The validity period of the code sent to the customer after placing the order. This will be the period the customer will have to pay for the purchase. **(Brazil only)**
```suggestion
16. **Vencimento do Pix:** The validity period of the code sent to the customer after placing the order. This will be the period the customer will have to pay for the purchase. **(Brazil only)**
```

2021-09-16 22:06 UTC, abderossi commented on guides/plugins/woocommerce/integration.en.md
> +16. **Pagamento com cartões salvos**: Allows customers to buy with their card details saved at Mercado Pago, without having to fill in card details at the store checkout.
```suggestion

```

2021-09-16 22:07 UTC, abderossi commented on guides/plugins/woocommerce/integration.pt.md
> +13. **Comissão por compra com Mercado Pago:** defina um valor percentual adicional que quiser cobrar como tarifa dos seus clientes por pagar com Mercado Pago.
```suggestion
13. **Comissão por compra com Mercado Pago:** defina um valor percentual adicional que quiser cobrar como tarifa dos seus clientes por pagar com Mercado Pago.
14. **Pagamento com cartões salvos**: permite que os clientes comprem com os dados do cartão guardados no Mercado Pago, sem precisar preencher dados do cartão no checkout da loja.
```

2021-09-16 22:07 UTC, abderossi commented on guides/plugins/woocommerce/integration.pt.md
> +14. **Pix:** caso queira oferecer pagamentos por Pix, é preciso ativar o **Checkout Personalizado** **- Pague com Pix** e seguir os passos descritos na tela para concluir a integração.
```suggestion
15. **Pix:** caso queira oferecer pagamentos por Pix, é preciso ativar o **Checkout Personalizado** **- Pague com Pix** e seguir os passos descritos na tela para concluir a integração.
```

2021-09-16 22:08 UTC, abderossi commented on guides/plugins/woocommerce/integration.pt.md
> +15. **Vencimento do Pix:** defina o prazo de validade do código enviado ao cliente após a realização do pedido. Este será o período que o cliente terá para pagar a compra.
```suggestion
16. **Vencimento do Pix:** defina o prazo de validade do código enviado ao cliente após a realização do pedido. Este será o período que o cliente terá para pagar a compra.
```

2021-09-16 22:08 UTC, abderossi commented on guides/plugins/woocommerce/integration.pt.md
> +16. **Pagamento com cartões salvos**: permite que os clientes comprem com os dados do cartão guardados no Mercado Pago, sem precisar preencher dados do cartão no checkout da loja.
```suggestion

```

2021-09-16 22:10 UTC, abderossi commented on guides/plugins/woocommerce/integration.en.md
> +>Before configuring Pix as a payment method, we recommend [downloading the latest version](https://br.wordpress.org/plugins/woocommerce-mercadopago/#description) of the Mercado Pago plugin for WooCom
```suggestion
>Before configuring Pix as a payment method, we recommend [downloading the latest version](https://br.wordpress.org/plugins/woocommerce-mercadopago/#description) of the Mercado Pago plugin for WooCommerce and [registering your Pix key](https://www.mercadopago.com.br/stop/pix?url=https%3A%2F%2Fwww.mercadopago.com.br%2Fadmin-pix-keys%2Fmy-keys&authentication_mode=required) in Mercado Pago.
```

2021-09-16 22:10 UTC, abderossi commented on guides/plugins/woocommerce/integration.es.md
> +> Antes de configurar Pix como método de pago, te recomendamos descargar la última versión del plugin Mercado Pago para WooCommerce y registrar tu clave Pix en Mercado Pago. **(Solo para Brasil)**
```suggestion
> Antes de configurar Pix como método de pago, te recomendamos descargar la última versión del plugin Mercado Pago para WooCommerce y registrar tu clave Pix en Mercado Pago. 
```

2021-09-16 22:16 UTC, abderossi approved these changes

2021-09-16 22:17 UTC, abderossi commented
@rwaetemann, deberíamos comunicar esto en Changelog. Sumas un pr con entrada de Changelog para la semana siguiente?
Gracias!

2021-09-17 14:19 UTC, rwaetemann commented on guides/plugins/woocommerce/integration.es.md
> +En la sección _Ingresa las credenciales para el Modo Test o el Modo Producción_, se te pedirá que ingreses tus credenciales de **producción** y **test**.
```suggestion
En la sección **Ingresa las credenciales para el Modo Test o el Modo Producción**, se te pedirá que ingreses tus credenciales de **producción** y **test**.
```

2021-09-17 16:31 UTC, SalehKhalilMP approved these changes

2021-09-17 18:46 UTC, rwaetemann commented on guides/plugins/woocommerce/previous-requirements.en.md
> +> [Plugin installation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/woocommerce/installation)
```suggestion
> [Plugin installation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/woocommerce/instalation)
```

2021-09-20 18:30 UTC, merged