agregado de taxes en dinamico, atendido y api reference para MCO
mercadopago/devsite-docs pull request #1300
Opened 2021-09-13 17:48 UTC by raul-crisostomo

## Description

1. Adjust in guides for making available QR dynamic for MCO. Actually this documentation (QRD) is not visible for MCO. Its important modifying the menu for making the documentation visible in this site with this modifications.

2. QR attended  v2 was updated adding taxes attribute allowing update v1 to v2 documentation for MCO.

3. minor changes to api reference v1 and v2 adding taxes array and modifying descriptions to external ids

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [x] New features were communicated in changelog.
- [x] Requires translations.

2021-09-22 16:20 UTC, abderossi commented
Se agrega el PR [#522](https://github.com/mercadolibre/fury_dx-devsite/pull/522) en dx-devsite para disponibilizar QR Dinámico en el menú de Colombia.

2021-09-22 16:26 UTC, abderossi approved these changes

2021-09-22 21:18 UTC, nicolassalvanes requested changes

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders.yaml
> +      example: COP
```suggestion
      example: ARS
```
Esta documentación no puede localizarse, por lo cual ponemos como ejemplo el currency_id de un site con mas share, como MLA (aunque podría ser de MLB también)

El valor para Colombia se especifica más abajo en toda la lista de valores posibles (enum)

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders_v2.yaml
> +                  description: custom id of the purchase.
```suggestion
                  description: Custom order id you can synchronize with your sale system.
```

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders_v2.yaml
> +          description: custom id of the POS asosiated to the purchase
```suggestion
          description: Custom POS Id associated to the order.
```

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders_v2.yaml
> +          description: custom id of the store asosiated to the purchase
```suggestion
          description: Custom Store Id associated to the order.
```

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders_v2.yaml
> +          description: Last digits after '-' symbol in seller's access token
```suggestion
          description: Find the User Id in your developer dashboard at our devsite
```
El ID de usuario está disponible en la parte superior derecha del [panel de desarrollador](https://www.mercadopago.com/developers/panel)

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders_v2.yaml
> +                        description: total amount of tax payed (this amount is not involved in the sum of order's total amount).
```suggestion
                        description: total amount of tax payed (this amount is not included in the sum of order's total amount).
```

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders_v2.yaml
> +                        example: IVA
Tenemos el listado de todos los valores posibles?

2021-09-22 21:18 UTC, nicolassalvanes commented on reference/api/instore_orders_v2.yaml
> +                        type: number
Se pueden usar valores decimales?

2021-09-23 00:05 UTC, biaguerreiromeli commented on reference/api/instore_orders_v2.yaml
> +                        description: total amount of tax payed (this amount is not involved in the sum of order's total amount).
```suggestion
                        description: the total amount of paid taxes (this amount is not included in the sum of the order's total amount).
```

2021-09-23 00:05 UTC, biaguerreiromeli commented on reference/api/instore_orders_v2.yaml
> +                  description: Information about the taxes payed.
```suggestion
                  description: Information about the paid taxes.
```

2021-09-23 00:05 UTC, biaguerreiromeli commented on reference/api/instore_orders_v2.yaml
> +                  description: custom id of the purchase.
```suggestion
                  description: Custom order ID in sync with your sale system. 
```

2021-09-23 00:05 UTC, biaguerreiromeli commented on reference/api/instore_orders_v2.yaml
> +          description: Last digits after '-' symbol in seller's access token
```suggestion
          description: Find the User Id on your Mercado Pago account's Developer Dashboard. 
```

2021-09-23 14:15 UTC, raul-crisostomo commented on reference/api/instore_orders.yaml
> +      example: COP
Nosotros decidimos cambiar a COP el ejemplo debido a que es el unico site con esta version activa, los demas sites no tienen esta version de la api, todas se actualizaron ya. si aun asi, no lo ven viable, lo dejamos en ARS

2021-09-23 14:19 UTC, raul-crisostomo commented on reference/api/instore_orders_v2.yaml
> +                        example: IVA
Por ahora solo se puede IVA

2021-09-23 14:19 UTC, raul-crisostomo commented on reference/api/instore_orders_v2.yaml
> +                        type: number
Si nico, se pueden usar decimales

2021-09-23 17:10 UTC, raul-crisostomo commented on guides/in-person-payments/qr-code/qr-attended/integrations.en.md
> +curl -X PUT \
Listo Nico

2021-09-23 17:11 UTC, raul-crisostomo commented on guides/in-person-payments/qr-code/qr-dynamic/integrations.en.md
> +   "description": "Compra y retiro",
Cambié los snippets chicos

2021-09-27 18:34 UTC, lamaralmp approved these changes

2021-09-27 19:29 UTC, abderossi commented on reference/api/instore_orders.yaml
> +      example: COP
Hola @raul-crisostomo ! ¿Cómo es que esta versión está solo activa en Colombia? Los cambios que se sugieren aquí serían visibles para todos los sites, no solo para Colombia. No me queda claro esto. ¡Gracias!

2021-09-27 22:01 UTC, raul-crisostomo commented on reference/api/instore_orders.yaml
> +      example: COP
Esa version de producto solo esta productivo en colombia @abderossi a pesar de ser visibles en todos los sites, solo colombia usa "orders" v1

2021-09-28 21:10 UTC, abderossi approved these changes

2021-09-28 21:21 UTC, abderossi commented on reference/api/instore_orders_v2.yaml
> +          description: Find the User Id in your developer dashboard at our devsite
```suggestion
          description: Find the User ID in your developer dashboard at our devsite
```

2021-09-28 21:21 UTC, abderossi commented on reference/api/instore_orders_v2.yaml
> +          description: Custom Store Id associated to the order.
```suggestion
          description: Custom Store ID associated to the order.
```

2021-09-28 21:21 UTC, abderossi commented on reference/api/instore_orders_v2.yaml
> +          description: Custom POS Id associated to the order.
```suggestion
          description: Custom POS ID associated to the order.
```

2021-09-28 21:22 UTC, abderossi commented on reference/api/instore_orders_v2.yaml
> +                  description: Custom order id you can synchronize with your sale system.
```suggestion
                  description: Custom order ID you can synchronize with your sale system.
```

2021-09-28 21:29 UTC, abderossi commented on reference/api/instore_orders_v2.yaml
> +                        description: total amount of tax payed (this amount is not included in the sum of order's total amount).
```suggestion
                        description: Total amount of tax payed. This amount is not included in the total sum of the order
```

2021-09-28 21:38 UTC, abderossi commented
Adicionamos [PR #536](https://github.com/mercadolibre/fury_dx-devsite/pull/536) en fury_dx-devsite con las traducciones de las definiciones para API Reference

2021-09-29 12:16 UTC, nicolassalvanes approved these changes

2021-09-29 18:18 UTC, merged