Update introduction.pt.md
mercadopago/devsite-docs pull request #1301
Opened 2021-09-14 09:44 UTC by biaguerreiromeli

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-09-22 14:07 UTC, biaguerreiromeli commented on guides/online-payments/checkout-pro/advanced-integration.es.md
> +Optimice su integración con funciones adicionales que le permitirán administrar mejor sus pagos de ventas con Checkout Pro.
Bia, o que acha de escrever: ubdeudvbcueiwfvie

2021-09-22 14:09 UTC, biaguerreiromeli commented on guides/online-payments/checkout-pro/advanced-integration.es.md
> +Optimice su integración con funciones adicionales que le permitirán administrar mejor sus pagos de ventas con Checkout Pro.
```suggestion
Optimiza su integración con funciones adicionales que le permitirán administrar mejor tus pagos de ventas con Checkout Pro.
```

2021-09-22 15:21 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +Otimize a sua integração com funcionalidades extras que te permitirão melhor gerenciar os pagamentos de suas vendas com o Checkout Pro.
```suggestion
O **Checkout Pro** dispõe de funcionalidades extras que permitem otimizar sua integração e melhorar a gestão dos pagamentos de suas vendas.
```

2021-09-22 15:27 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +As notificações IPN (_Instant Payment Notification_) são uma forma automática de aviso da criação de novos pagamentos e as atualizações de seus _status_, isto é, se eles foram aprovados, recusados ou
```suggestion
As notificações IPN (_Instant Payment Notification_) são notificações automáticas sobre a criação de novos pagamentos e atualizações de status, informando se as transações foram aprovadas, recusadas ou estão pendentes.
```

2021-09-22 15:28 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +Os avisos automáticas permitem que você administre seu estoque e mantenha seu sistema sincronizado com os fluxos de pagamento do seu negócio. Aprenda como receber as notificações IPN [aqui](https://w
```suggestion
Os avisos automáticos permitem que você administre seu estoque e mantenha seu sistema sincronizado com os fluxos de pagamento do seu negócio. Aprenda como receber as notificações IPN [aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn)
```

2021-09-22 15:28 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +## Adicione informações adicionais à preferência
```suggestion
## Insira informações adicionais à preferência
```

2021-09-22 15:44 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +Melhore a aprovação dos pagamentos e a experiência dos seus compradores no Checkout Pro adicionando informações às suas preferências que possam detalhar sobre o item comprado e o usuário comprador.
```suggestion
Melhore a aprovação dos pagamentos e a experiência dos seus compradores no Checkout Pro adicionando informações às suas preferências que possam detalhar sobre o item comprado e o usuário comprador.
```
```suggestion
Melhore a aprovação dos pagamentos e a experiência de compra no Checkout Pro adicionando informações às suas preferências que detalhem o item comprado e o usuário comprador.
```

2021-09-22 15:46 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +As informações adicionais passíveis de serem adicionadas por você nas preferências são:
```suggestion
Em Preferências, você pode inserir as seguintes informações adicionais:
```

2021-09-22 15:48 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +Se quer que o redirecionamento seja automático para os pagamentos aprovados, sem a renderização de um botão de retorno, é preciso adicionar também o atributo `auto_return` com valor `approved`.
```suggestion
Se deseja que o redirecionamento para os pagamentos aprovados seja automático, sem a renderização de um botão de retorno, é preciso adicionar também o atributo `auto_return` com valor `approved`. 
```

2021-09-22 15:59 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +| `auto_return` | Redireciona automaticamente compradores para o _site_ quando o pagamento é finalizado como aprovado. O valor padrão é `approved`. |
```suggestion
| `auto_return` | Os compradores são redirecionados automaticamente para o  _site_ quando o pagamento é aprovado. O valor padrão é `approved`. |
```

2021-09-22 18:02 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +| ------------ 	|	-------- |
```suggestion
| --- | --- | 
```

2021-09-22 18:46 UTC, romisoto requested changes

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/configurations.es.md
> +Sabemos que es importante maximizar la efectividad y la capacidad de búsqueda de sus anuncios.
```suggestion
Sabemos que es importante maximizar la efectividad y la capacidad de búsqueda de tus anuncios.
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/configurations.es.md
> +Al crear una preferencia, puede asociarla con un _pixel_ (identificador) para rastrear las conversiones de anuncios de Facebook:
```suggestion
Al crear una preferencia, puedes asociarla con un _pixel_ (identificador) para rastrear las conversiones de anuncios de Facebook:
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/configurations.es.md
> +Una vez completada la configuración, se asociará un evento de `purchase` con el _píxel_ especificado cuando se apruebe un pago reenviado por su anuncio.
```suggestion
Una vez completada la configuración, se asociará un evento de `purchase` con el _píxel_ especificado cuando se apruebe un pago reenviado por tu anuncio.
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/configurations.es.md
> +Al crear una preferencia, puede asociarla con una _tag_ (identificador) para realizar un seguimiento de las conversiones de Google Ads:
```suggestion
Al crear una preferencia, puedes asociarla con una _tag_ (identificador) para realizar un seguimiento de las conversiones de Google Ads:
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/integration.es.md
> +> No te olvides de acceder al Checkout Pro desde otro navegador o cerrar la sesión de tu cuenta de Mercado Pago antes de probarlo, ya que no puedes pagar con la misma cuenta que creaste el formulario
```suggestion
> No te olvides de acceder al Checkout Pro desde otro navegador o cerrar la sesión de tu cuenta de Mercado Pago antes de probarlo, ya que no puedes pagar con la misma cuenta con la que creaste el formulario de pago.<br/>
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/integration.es.md
> +Implemente la solución Checkout Pro en su sitio con nuestro video tutorial sobre la integración:
```suggestion
Implementa la solución Checkout Pro en tu sitio con nuestro video tutorial sobre la integración:
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/integration.es.md
> +Consulte el [ejemplo de integración completa](http://github.com/mercadopago/checkout-payment-sample) en GitHub para PHP o NodeJS para descargar un proyecto básico de implementación rápida de Checkout
```suggestion
Consulta el [ejemplo de integración completa](http://github.com/mercadopago/checkout-payment-sample) en GitHub para PHP o NodeJS para descargar un proyecto básico de implementación rápida de Checkout Pro en tu sitio.
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/previous-requirements.es.md
> +Siga estos pasos antes de comenzar su integración:
```suggestion
Sigue estos pasos antes de comenzar tu integración:
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/previous-requirements.es.md
> +Para encontrarlas, consulte la sección [Credenciales]([FAKER][CREDENTIALS][URL]) en el Panel de desarrollador de tu cuenta Mercado Pago
```suggestion
Para encontrarlas, consulta la sección [Credenciales]([FAKER][CREDENTIALS][URL]) en el panel de desarrollador de tu cuenta Mercado Pago
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/previous-requirements.es.md
> +> ¿Aún tienes dudas sobre? Lee nuestra documentación de [Credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) para obtener más información.
```suggestion
> ¿Aún tienes dudas sobre credenciales? Lee [nuestra documentación](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) para obtener más información.
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/test-integration.es.md
> +La respuesta tendrá una estructura similar al ejemplo siguiente:
```suggestion
La respuesta tendrá una estructura similar al siguiente ejemplo:
```

2021-09-22 18:46 UTC, romisoto commented on guides/online-payments/checkout-pro/test-integration.es.md
> +## Reciba los pagos
```suggestion
## Recibe los pagos
```

2021-09-22 18:59 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +Encontre todas as informações necessárias para melhor gerenciar os cancelamentos e estornos dos seus pagamentos na documentação [Devoluções e cancelamentos](https://www.mercadopago[FAKER][URL][DOMAIN
```suggestion
Para mais informações sobre como gerenciar os cancelamentos e estornos dos seus pagamentos, acesse a documentação [Devoluções e cancelamentos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/manage-account/account/cancellations-and-refunds) do Mercado Pago.
```

2021-09-22 19:02 UTC, rwaetemann commented on guides/online-payments/checkout-pro/advanced-integration.pt.md
> +Uma contestação (ou *chargeback*) acontece quando o comprador entra em contato com a entidade emissora do cartão e desconhece o pagamento. Na prática, isso significa que o dinheiro desse pagamento se
```suggestion
Uma contestação (ou *chargeback*) acontece quando o comprador entra em contato com a entidade emissora do cartão e desconhece o pagamento. Na prática, isso significa que o dinheiro desse pagamento será retido da sua conta Mercado Pago até que a situação seja solucionada.
```

2021-09-22 19:12 UTC, rwaetemann commented on guides/online-payments/checkout-pro/customizations.pt.md
> +| `type` (opcional) | `string` | Define o tipo de botão desejado. Atualmente, aceita apenas o valor `wallet, que mostra um botão de pagamento com a marca do Mercado Pago. |
```suggestion
| `type` (opcional) | `string` | Define o tipo de botão desejado. Atualmente, aceita apenas o valor `wallet`, que mostra um botão de pagamento com a marca do Mercado Pago. |
```

2021-09-22 19:20 UTC, rwaetemann commented on guides/online-payments/checkout-pro/customizations.pt.md
> +- Invocando a função `render` posteriormente, do lugar que você preferir dentro de seu código, com seus respectivos parâmetros.
@biaguerreiromeli, Bião, a palavra é "invocando" mesmo? kkkk. Tem alguma outra?

2021-09-22 19:22 UTC, rwaetemann commented on guides/online-payments/checkout-pro/customizations.pt.md
> +Adicione o parâmetro `autoOpen` nas opções de inicialização do Checkout para exibir automaticamente o Checkout Pro, sem precisar que seus compradores interajam com um botão ou qualquer outro elemento
```suggestion
Adicione o parâmetro `autoOpen` nas opções de inicialização do Checkout para exibir automaticamente o Checkout Pro, sem precisar que seus compradores interajam com um botão ou qualquer outro elemento para abri-lo
```

2021-09-22 19:22 UTC, rwaetemann commented on guides/online-payments/checkout-pro/customizations.pt.md
> +Para integrar o esquema de redirecionamento à sua integração, substitua o botão de pagamento configurado na implementação básica e adicione o link do Web Checkout ao seu _site_ no local em que deseja
```suggestion
Para integrar o esquema de redirecionamento à sua integração, substitua o botão de pagamento configurado na implementação básica e adicione o link do Web Checkout ao seu _site_ no local em que deseja exibi-lo, como mostra o exemplo abaixo:
```

2021-09-22 19:26 UTC, rwaetemann commented on guides/online-payments/checkout-pro/integration.pt.md
> +A integracão com a solução Checkout Pro do Mercado Pago te permite cobrar através do nosso formulário _web_ a partir qualquer dispositivo de forma simples, rápida e segura.
```suggestion
A integração com o Checkout Pro do Mercado Pago te permite cobrar através do nosso formulário _web_ a partir qualquer dispositivo de forma simples, rápida e segura.
```

2021-09-22 19:37 UTC, rwaetemann commented on guides/online-payments/checkout-pro/integration.pt.md
> +Instalar o Checkout Pro requer duas principais etapas:
```suggestion
Instalar o Checkout Pro requer duas etapas principais:
```

2021-09-22 19:41 UTC, rwaetemann commented on guides/online-payments/checkout-pro/integration.pt.md
> +Implemente a solução Checkout Pro em seu *site* com o nosso vídeo tutorial sobre a integração completa:
```suggestion
Saiba como implementar a solução Checkout Pro em seu *site* com o nosso vídeo tutorial:
```

2021-09-22 20:18 UTC, rwaetemann commented on guides/online-payments/checkout-pro/introduction.pt.md
>  |                                       | Checkout Pro | Web Tokenize Checkout | API |
```suggestion
| Checkout Pro | Web Tokenize Checkout | API |
```

2021-09-22 20:19 UTC, rwaetemann commented on guides/online-payments/checkout-pro/introduction.pt.md
> +> Para realizar a integração com o Checkout Pro, você deve cumprir com alguns requisitos necessários.
```suggestion
> Para realizar a integração com o Checkout Pro, você deve cumprir alguns requisitos.
```

2021-09-22 20:22 UTC, rwaetemann commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +| Credenciais (`credentials`) | Suas credenciais são as **chaves únicas que te fornecemos para que você possa configurar as suas integrações.** Existem dois tipos de credenciais: Public key e Access
```suggestion
| Credenciais (`credentials`) | Suas credenciais são as **chaves únicas que fornecemos para que você possa configurar as suas integrações.** Existem dois tipos de credenciais: Public key e Access Token. <br/><br/>**Public key é a chave pública da aplicação** para saber os meios de pagamento e criptografar os dados do cartão, por exemplo. Você deve usá-la somente para as suas integrações.<br/><br/>**Access token é a chave privada da aplicação** para gerar pagamentos. Você deve usá-la somente para suas integrações.<br/><br/>Para encontrá-las, confira a [seção de Credenciais]([FAKER][CREDENTIALS][URL]) no Painel de desenvolvedor da sua conta Mercado Pago e selecione as produtivas. |
```

2021-09-22 20:34 UTC, rwaetemann commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +Para poder começar a integração, é necessário ter uma conta do Mercado Pago ou do Mercado Livre.
```suggestion
Para começar a integração, é necessário ter uma conta do Mercado Pago ou do Mercado Livre.
```

2021-09-22 20:35 UTC, rwaetemann commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +As credenciais são chaves únicas que te fornecemos para que você possa configurar as suas integrações.
```suggestion
As credenciais são chaves únicas que fornecemos para que você possa configurar as suas integrações.
```

2021-09-22 20:35 UTC, rwaetemann commented on guides/online-payments/checkout-pro/previous-requirements.pt.md
> +> Ainda tem dúvidas sobre? Leia a nossa documentação de [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações.
```suggestion
> Ainda tem dúvidas? Leia a nossa documentação de [Credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações. 
```

2021-09-23 20:24 UTC, rwaetemann approved these changes

2021-09-23 20:31 UTC, romisoto requested changes

2021-09-23 20:31 UTC, romisoto commented on guides/online-payments/checkout-pro/advanced-integration.es.md
> +Evita pagos rechazados con nuestras mejores práticas y [mejora la aprobación de tus pagos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/account/payment-rejections).
```suggestion
Evita pagos rechazados con nuestras mejores prácticas y [mejora la aprobación de tus pagos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/account/payment-rejections).
```

2021-09-23 20:31 UTC, romisoto commented on guides/online-payments/checkout-pro/test-integration.es.md
> +| Comprador | Es la cuenta que usas para **probar el proceso de compra.**<br/><br/>Existen dos formas de hacer el pago: como **usuario invitado**, completando la dirección de correo electrónico desea
```suggestion
| Comprador | Es la cuenta que usas para **probar el proceso de compra.**<br/><br/>Existen dos formas de hacer el pago: como **usuario invitado**, completando la dirección de correo electrónico deseado, y como **usuario registrado**, accediendo a una cuenta de Mercado Pago con usuario y clave. En este último escenario se habilitarán como medio de pago las tarjetas previamente guardadas y el saldo disponible en la cuenta. |
```

2021-09-23 20:31 UTC, romisoto commented on guides/online-payments/checkout-pro/test-integration.es.md
> +Antes de activarlas, verifica si las credenciales utlizadas en tu integración son las de la cuenta que debería recibir el dinero de las ventas.
```suggestion
Antes de activarlas, verifica si las credenciales utilizadas en tu integración son las de la cuenta que debería recibir el dinero de las ventas.
```

2021-09-23 20:38 UTC, romisoto approved these changes

2021-09-27 20:54 UTC, pbracale approved these changes

2021-09-27 20:54 UTC, pbracale commented on guides/online-payments/checkout-pro/advanced-integration.en.md
> +Checkout Pro has extra features that allow you to optimize its integration and improve the management of your sales payments.
```suggestion
Checkout Pro has features that allow you to improve the management of your sales payments through an optimized integration.
```

2021-09-27 20:54 UTC, pbracale commented on guides/online-payments/checkout-pro/advanced-integration.en.md
> +IPN notifications (_Instant Payment Notification_) are automatic notifications about creating new payments and status updates, letting you know if transactions have been approved, declined, or are pe
```suggestion
IPN notifications (_Instant Payment Notification_) are automatic notifications that can be sent when there are payments and/or status updates, letting you know if transactions have been approved, declined, or are pending.
```

2021-09-27 20:54 UTC, pbracale commented on guides/online-payments/checkout-pro/advanced-integration.en.md
> +Improve the payment approval and shopping experience in Checkout Pro by adding information to your preferences that details the item purchased and the purchasing user.
```suggestion
Improve the payment approval and shopping experience in Checkout Pro by adding information that details the item purchased and the purchasing user to your preferences.
```

2021-09-27 20:54 UTC, pbracale commented on guides/online-payments/checkout-pro/advanced-integration.en.md
> +Cancellations are made when payment has not been completed before the due date and the seller then decides to cancel it. Returns, in turn, happen when the buyer completes the payment, but the seller
```suggestion
Cancellations happen when a payment has not been completed before the due date and the seller then decides to cancel it. Returns, in turn, happen when the buyer completes the payment, but the seller decides to cancel it totally or partially.
```

2021-09-27 20:54 UTC, pbracale commented on guides/online-payments/checkout-pro/advanced-integration.en.md
> +Cancellations are made when payment has not been completed before the due date, and the seller then decides to cancel it. Returns, in turn, happen when the buyer completes the payment, but the seller
```suggestion
Cancellations happen when payment has not been completed before the due date, and the seller then decides to cancel it. Returns, in turn, happen when the buyer completes the payment, but the seller decides to cancel it totally.
```

2021-09-29 17:00 UTC, nicolassalvanes reviewed
Excelente trabajo! 
Solo tuve tiempo de revisar los archivos en inglés, así que dejo algunos comentarios o sugerencias solo en esos archivos

2021-09-29 17:00 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/introduction.en.md
>  ------------
Podríamos simplificar toda esta localización así no?:
```
----[mlb]----
* **Integration with the most popular [payment methods](https://www.mercadopago.com.br/ajuda/meios-de-pagamento-parcelamento_265)** in the country.
------------
----[mla, mlm, mlc, mpe, mco, mlu]----
* **Integration with the most popular [payment methods](https://www.mercadopago[FAKER][URL][DOMAIN]/ayuda/medios-de-pago-cuotas-promociones_264)** in the country.
------------
```

2021-09-29 17:00 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/introduction.en.md
> +* **Split payments** with two cards. A useful feature in scenarios with high amount transactions, for example.
```suggestion
* **Split payments** with two cards. An useful feature in scenarios with high amount transactions, for example.
```

2021-09-29 17:00 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/previous-requirements.en.md
> +Follow the following steps before starting your integration:
También podríamos usar "pay attention to"

2021-09-29 17:00 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/test-integration.en.md
> +> LEFT_BUTTON_REQUIRED_EN
No queremos que esto sea RECOMMENDED?

2021-09-29 17:40 UTC, biaguerreiromeli commented on guides/online-payments/checkout-pro/test-integration.en.md
> +> LEFT_BUTTON_REQUIRED_EN
Como é uma trilha, o passo seguinte é required mesmo para completar o objetivo final proposto pela doc!

2021-09-29 17:54 UTC, biaguerreiromeli commented on guides/online-payments/checkout-pro/configurations.en.md
> +Add the identification codes and replace the values according to the desired scenario: <code>CORPORATION\_ID</code>, <code>INTEGRATOR\_ID</code> and <code>PLATFORM_ID</code>.
Antes os valores estavam soltos, sem identificação de código. Para melhorar a renderização do texto, seria interessante adicionarmos a tag. Poderíamos também adicionar ``, mas como estamos falando de um snippet em HTML, preferi as tags mesmo.

2021-09-29 18:32 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/advanced-integration.en.md
> +> LEFT_BUTTON_REQUIRED_EN
Ahhhh, sabemos que es opcional pero si no lo ponemos como requiired el usuario nunca va a llegar a "test integration" por ejemplo no? Está bien entonces :D

2021-09-29 18:33 UTC, nicolassalvanes commented on guides/online-payments/checkout-pro/introduction.en.md
> +* **Split payments** with two cards. A useful feature in scenarios with high amount transactions, for example.
Necesito volver a tomar clases kkkkk 😄

2021-09-29 19:20 UTC, merged