Feature/Oauth public and Marketplace update
mercadopago/devsite-docs pull request #1309
Opened 2021-09-17 19:20 UTC by abderossi

## Description

- Nueva documentación de OAuth dentro de la sección de Seguridad
- Actualización de la información relacionada a Marketplace para CHO Pro y CHO API
- Entradas de changelog en los tres idiomas comunicando la nueva sección

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [x] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [x] New features were communicated in changelog.
- [ ] Requires translations.

2021-09-22 20:58 UTC, romisoto requested changes

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +| `state` | Identify who the code to be received belongs to; so replace `RANDOM_ID` value with a unique ID for each attempt without sensitive data. |
```suggestion
| `state` | Identify who the code to be received belongs to. In order to do this, replace `RANDOM_ID` value with a unique ID for each attempt without sensitive data. |
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +When entering this URL, the seller will be redirected to Mercado Pago to log in their account and authorize the link to your application.
```suggestion
When entering this URL, the seller will be redirected to Mercado Pago to log into their account and authorize the link to your application.
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +**Your sellers' data that you received last 180 days**. After that, you need to request the seller's authorization again.
```suggestion
**Your sellers' data that you received lasts 180 days**. After that, you need to request the seller's authorization again.
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +> In case of errors when refreshing your credentials, remember that you can query them in the [error code reference](https://developers.mercadolibre[FAKER][URL][DOMAIN]/en_us/authentication-and-autho
```suggestion
>  In case of errors when refreshing your credentials, remember that you can query them in the [error code reference](https://developers.mercadolibre[FAKER][URL][DOMAIN]/en_us/authentication-and-authorization#Error-codes-reference).
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +These are some of the data that you can find within the notifications:
```suggestion
This is some of the data that you can find within the notifications:
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.es.md
> +> En caso de encontrar algún error a la hora de renovar las credenciales, recuerda que puedes consultarlo en la [referencia de códigos de error](https://developers.mercadolibre[FAKER][URL][DOMAIN]/es
```suggestion
>  En caso de encontrar algún error a la hora de renovar las credenciales, recuerda que puedes consultarlo en la [referencia de códigos de error](https://developers.mercadolibre[FAKER][URL][DOMAIN]/es_ar/autenticacion-y-autorizacion#Referencia-de-codigos-de-error).
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.es.md
> +[Probá tu integración](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/testing)
```suggestion
[Prueba tu integración](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/testing)
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +| `action` | `application.authorized` | Reports that seller linked to application. |
```suggestion
| `action` | `application.authorized` | Reports that the seller has been linked to the application. |
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +| `action` | `application.deauthorized` | Confirms that seller unlinked from application. |
```suggestion
| `action` | `application.deauthorized` | Confirms that the seller has been unlinked from the application. |
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +| `data.id`| `string`| ID of seller linked to application. |
```suggestion
| `data.id`| `string`| ID of the seller linked to the application. |
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.en.md
> +**Your sellers' data that you received last 180 days**. After that, you need to request the seller's authorization again.
```suggestion
**Your sellers' data that you received lasts 180 days**. After that, you need to request the seller's authorization again.
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.en.md
> +> In case of errors when refreshing your credentials, remember that you can query them in the [error code reference](https://developers.mercadolibre[FAKER][URL][DOMAIN]/en_us/authentication-and-autho
```suggestion
>  In case of errors when refreshing your credentials, remember that you can query them in the [error code reference](https://developers.mercadolibre[FAKER][URL][DOMAIN]/en_us/authentication-and-authorization#Error-codes-reference).
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.en.md
>  > The more information you send us in the preference, the better our fraude prevention system will perform when it comes to payment approval.
```suggestion
> The more information you send us in the preference, the better our fraud prevention system will perform when it comes to payment approval.  
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.en.md
> +2. Go to "Webhooks Notifications" tab. In this section, go to "Production Mode" and add the URL to receive notifications. If you want, you can click on "Test" button to test that the assigned URL wil
```suggestion
2. Go to "Webhooks Notifications" tab. In this section, go to "Production Mode" and add the URL to receive notifications. If you want, you can click on the "Test" button to test that the assigned URL will receive Webhooks Notifications correctly.
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.en.md
> +These are some of the data that you can find within the notifications:
```suggestion
This is some of the data that you can find within the notifications:
```

2021-09-22 20:58 UTC, romisoto commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.es.md
> +> En caso de encontrar algún error a la hora de renovar las credenciales, recuerda que puedes consultarlo en la [referencia de códigos de error](https://developers.mercadolibre[FAKER][URL][DOMAIN]/es
```suggestion
>  En caso de encontrar algún error a la hora de renovar las credenciales, recuerda que puedes consultarlo en la [referencia de códigos de error](https://developers.mercadolibre[FAKER][URL][DOMAIN]/es_ar/autenticacion-y-autorizacion#Referencia-de-codigos-de-error).
```

2021-09-22 21:09 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +> Caso haja algum erro na hora de renovar as credenciais, lembre que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Refe
```suggestion
>  Caso haja algum erro na hora de renovar as credenciais, lembre que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Referencia-de-codigos-de-erro).
```

2021-09-22 21:10 UTC, abderossi commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +> Caso haja algum erro na hora de renovar as credenciais, lembre que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Refe
```suggestion
>  Caso haja algum erro na hora de renovar as credenciais, lembre que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Referencia-de-codigos-de-erro).
```

2021-09-23 14:41 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Para começar, siga estes passos:
```suggestion
Para começar, siga os passos abaixo:
```

2021-09-23 14:42 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +1. Crie ou configure sua aplicação.
```suggestion
1. Crie ou configure seu aplicativo.
```

2021-09-23 14:43 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +3. Crie as credenciais para operar.
@abderossi - Gosti, aqui não entendi muito bem! "Operar" acaba ficando um pouquinho estranho. As credenciais, nesse caso, seria para que exatamente?

2021-09-23 14:43 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +## Crie ou configure sua aplicação.
```suggestion
## Crie ou configure seu aplicativo.
```

2021-09-23 14:44 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +[Primeiramente, você deve ter criado [sua aplicação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/applications/create-app) com um nome único que o identifique.
```suggestion
[Primeiramente, você deve ter criado [seu aplicação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/applications/create-app) com um nome de identificação único.
```

2021-09-23 14:46 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Depois, você terá que **configurar um Redirect URL para sua aplicação**. Para isso, vá para [Suas Aplicações](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel), clique no menu de opções d
```suggestion
Depois, é preciso **configurar um Redirect URL para sua aplicação**. Para isso, acesse [Suas Aplicações](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel), clique no menu de opções da sua aplicação e selecione Editar. 
```

2021-09-23 14:51 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +No campo Redirect URL, adicione o endereço ao qual você quer encaminhar os vendedores após tê-los vinculado corretamente. Lembre que no endereço que você adicionar você vai receber os códigos de auto
```suggestion
No campo Redirect URL, adicione o endereço para onde você deseja encaminhar os vendedores após tê-los vinculado corretamente. Lembre-se que os códigos de autorização para a criação das credenciais serão enviados para o endereço cadastrado.
```

2021-09-23 14:51 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +## 2. Vincule seu aplicação à conta de seus vendedores.
```suggestion
## 2. Vincule sua aplicação à conta de seus vendedores.
```

2021-09-23 14:53 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Para operar em nome dos seus vendedores através de suas contas do Mercado Pago, primeiramente, você deve solicitar sua autorização. Para gerenciar mais de uma conta do Mercado Pago ao mesmo tempo em
```suggestion
Para operar em nome dos seus vendedores através de suas contas do Mercado Pago, primeiramente, você deve solicitar uma autorização. É possível gerenciar mais de uma conta do Mercado Pago simultaneamente em sua integração através do OAuth, um um protocolo de autenticação que permite ao vendedor acessar sua conta do Mercado Pago, realizar a autenticação  e habilitar seu aplicativo para funcionar utilizando seu nome.
```

2021-09-23 14:53 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Para isso, deve incluir em sua aplicação uma URL que encaminhe o vendedor para o site de autorização.
```suggestion
Para isso, é preciso incluir em sua aplicação uma URL que encaminhe o vendedor para o site de autorização. 
```

2021-09-23 14:54 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Para começar, siga estes passos:
```suggestion
Para começar, siga os passos abaixo:
```

2021-09-23 14:54 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Compartilhamos a URL base que você deve utilizar e o detalhe dos parâmetros com os quais tem que completá-la.
```suggestion
Compartilhamos a URL base que você deve utilizar e o detalhe dos parâmetros com os quais deverá completá-la.
```

2021-09-23 14:55 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +| `client_id` | Substitua o valor `APP_ID` com a ID do sua aplicação. |
```suggestion
| `client_id` | Substitua o valor `APP_ID` com a ID da sua aplicação. |
```

2021-09-23 14:55 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Ao acessar essa URL, o vendedor será encaminhado para o Mercado Pago, onde deverá fazer o login com sua conta e autorizar a vinculação com sua aplicação.
```suggestion
Ao acessar essa URL, o vendedor será encaminhado para o Mercado Pago, onde deverá fazer o login com sua conta e autorizar o vínculo com sua aplicação.
```

2021-09-23 14:56 UTC, abderossi commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +3. Crie as credenciais para operar.
Las credenciales serían para comenzar a utilizar la función de OAuth

2021-09-23 14:57 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +2. Vincule seu aplicação à conta de seus vendedores.
```suggestion
2. Vincule sua aplicação à conta dos seus vendedores.
```

2021-09-23 14:58 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Primeiramente, você deve ter criado [sua aplicação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/applications/create-app) com um nome único que o identifique.
```suggestion
Primeiramente, você deve ter criado [sua aplicação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/applications/create-app) com um nome de identificação único.
```

2021-09-23 14:58 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Depois, você terá que **configurar um Redirect URL para sua aplicação**. Para isso, vá para [Suas Aplicações](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel), clique no menu de opções d
```suggestion
é preciso **configurar um Redirect URL para sua aplicação**. Para isso, acesse [Suas Aplicações](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel), clique no menu de opções da sua aplicação e selecione Editar.
```

2021-09-23 14:58 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Quando o vendedor tenha autorizado a vinculação do sua aplicação à sua conta do Mercado Pago, você vai receber no seu servidor o código de autorização na Redirect URL especificada. Você verá o seguin
```suggestion
Quando o vendedor autorizar o vínculo da aplicação à sua conta do Mercado Pago, você receberá em seu servidor o código de autorização na Redirect URL especificada, conforme mostrado abaixo.  
```

2021-09-23 14:58 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +No campo Redirect URL, adicione o endereço ao qual você quer encaminhar os vendedores após tê-los vinculado corretamente. Lembre que no endereço que você adicionar você vai receber os códigos de auto
```suggestion
No campo Redirect URL, adicione o endereço para onde você deseja encaminhar os vendedores após tê-los vinculado corretamente. Lembre-se que os códigos de autorização para a criação das credenciais serão enviados para o endereço cadastrado.
```

2021-09-23 14:59 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +> Lembre que o valor `code` tem um período de validade de 10 minutos.
```suggestion
> Lembre-se que o valor `code` tem um período de validade de 10 minutos.
```

2021-09-23 14:59 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +## Vincule seu aplicação à conta de seus vendedores.
```suggestion
## Vincule sua aplicação à conta de seus vendedores.
```

2021-09-23 14:59 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Para operar em nome dos seus vendedores através de suas contas do Mercado Pago, primeiramente, você deve solicitar sua autorização. Para gerenciar mais de uma conta do Mercado Pago ao mesmo tempo em
```suggestion
Para operar em nome dos seus vendedores através de suas contas do Mercado Pago, primeiramente, você deve solicitar uma autorização. É possível gerenciar mais de uma conta do Mercado Pago simultaneamente em sua integração através do OAuth, um um protocolo de autenticação que permite ao vendedor acessar sua conta do Mercado Pago, realizar a autenticação  e habilitar seu aplicativo para funcionar utilizando seu nome.
```

2021-09-23 14:59 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Para isso, deve incluir em sua aplicação uma URL que encaminhe o vendedor para o site de autorização.
```suggestion
Para isso, é preciso incluir em sua aplicação uma URL que encaminhe o vendedor para o site de autorização.  
```

2021-09-23 15:00 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Você também vai receber o `refresh_token`, que mais a frente servirá para renovar as credenciais dos seus vendedores.
```suggestion
Você também vai receber o `refresh_token`, que servirá para renovar as credenciais dos seus vendedores. 
```

2021-09-23 15:01 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Além disso, você vai receber a `public_key` do vendedor, que é a credencial ou chave pública que você vai usar para identificar a conta em seu frontend.
```suggestion
Além disso, você vai receber a `public_key` do vendedor, que é a credencial ou chave pública necessária para identificar a conta em seu frontend. 
```

2021-09-23 15:01 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Compartilhamos a URL base que você deve utilizar e o detalhe dos parâmetros com os quais tem que completá-la.
```suggestion
Compartilhamos a URL base que você deve utilizar e o detalhe dos parâmetros com os quais deverá completá-la.
```

2021-09-23 15:01 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +| `client_id` | Substitua o valor `APP_ID` com a ID do sua aplicação. |
```suggestion
| `client_id` | Substitua o valor `APP_ID` com a ID da sua aplicação. |
```

2021-09-23 15:01 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Ao acessar essa URL, o vendedor será encaminhado para o Mercado Pago, onde deverá fazer o login com sua conta e autorizar a vinculação com sua aplicação.
```suggestion
Ao acessar essa URL, o vendedor será encaminhado para o Mercado Pago, onde deverá fazer o login com sua conta e autorizar o vínculo com sua aplicação.
```

2021-09-23 15:02 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Além disso, você vai receber a `public_key` do vendedor, que é a credencial ou chave pública que você vai usar para identificar a conta em seu frontend.
@abderossi talvez seria bacana pensarmos em outra palavra para "Frontend", Gosti! Se partirmos do princípio que talvez nem todos conheçam esses termos, pode ser que confunda. O que acha?

2021-09-23 15:02 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Quando o vendedor tenha autorizado a vinculação do sua aplicação à sua conta do Mercado Pago, você vai receber no seu servidor o código de autorização na Redirect URL especificada. Você verá o seguin
```suggestion
Quando o vendedor autorizar o vínculo da aplicação à sua conta do Mercado Pago, você receberá em seu servidor o código de autorização na Redirect URL especificada, conforme mostrado abaixo.  
```

2021-09-23 15:02 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +> Lembre que o valor `code` tem um período de validade de 10 minutos.
```suggestion
> Lembre-se que o valor `code` tem um período de validade de 10 minutos.
```

2021-09-23 15:02 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +> Lembre que você vai utilizar informações sensíveis dos seus vendedores. Certifique-se de resguardá-las de maneira segura, não incorpore nas suas URL de vinculação e gerencie somente do seu servidor
```suggestion
> Lembre-se que você vai utilizar informações sensíveis dos seus vendedores. Garanta que serão armazenadas de maneira segura, não incorpore nas suas URL de vinculação e gerencie somente do seu servidor.
```

2021-09-23 15:02 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Para criar as credenciais necessárias para que sua aplicação possa operar em nome de um vendedor, você terá que enviar o `CODE` obtido no passo anterior através da API de OAuth.
```suggestion
Para criar as credenciais necessárias para sua aplicação operar em nome de um vendedor, você terá que enviar o `CODE` obtido no passo anterior através da API de OAuth.
```

2021-09-23 15:03 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +**As informações que você recebe dos seus vendedores têm validade durante 180 dias**. Passado esse tempo, você deverá solicitar novamente a autorização ao vendedor.
```suggestion
**As informações que você recebe dos seus vendedores são válidas por 180 dias**. Passado esse tempo, você deverá solicitar novamente a autorização ao vendedor.
```

2021-09-23 15:03 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Para evitar isso, renove os dados antes desse período para garantir que estejam sempre vigentes.
```suggestion
Para evitar isso, renove os dados antes desse período e garanta que estejam sempre vigentes. 
```

2021-09-23 15:04 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Além disso, você vai receber a `public_key` do vendedor, que é a credencial ou chave pública que você vai usar para identificar a conta em seu frontend.
```suggestion
Além disso, você vai receber a `public_key` do vendedor, que é a credencial ou chave pública necessária para identificar a conta em seu frontend. 
```

2021-09-23 15:04 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +> Lembre que, a cada vez que você renovar as credenciais, o `refresh_token` também vai mudar, porquanto, você deverá armazená-lo novamente.
```suggestion
> Lembre-se que, a cada vez que você renovar as credenciais, o `refresh_token` também mudará, por isso, você deverá armazená-lo novamente.
```

2021-09-23 15:05 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +> Lembre que você vai utilizar informações sensíveis dos seus vendedores. Certifique-se de resguardá-las de maneira segura, não incorpore nas suas URL de vinculação e gerencie somente do seu servidor
```suggestion
> Lembre-se que você vai utilizar informações sensíveis dos seus vendedores. Garanta que serão armazenadas de maneira segura, não incorpore nas suas URL de vinculação e gerencie somente do seu servidor.
```

2021-09-23 15:05 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +>  Caso haja algum erro na hora de renovar as credenciais, lembre que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Ref
```suggestion
>  Caso haja algum erro na hora de renovar as credenciais, lembre-se que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Referencia-de-codigos-de-erro).
```

2021-09-23 15:05 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
>  Para realizar a cobrança em nome de seus vendedores, você deve integrar o [Checkout](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/introduction), geran
```suggestion
Para realizar a cobrança em nome de seus vendedores, você deve integrar o [Checkout](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/introduction), gerando as preferências de pagamento com o Access Token obtido ao vincular cada vendedor ao seu aplicativo.
```

2021-09-23 15:06 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Você pode receber notificações sempre que um vendedor se vincule ou desvincule do sua aplicação. Para configurá-las, siga estes passos:
```suggestion
Você pode receber notificações sempre que um vendedor se vincular ou desvincular da sua aplicação. Para configurá-las, siga os passos abaixo.
```

2021-09-23 15:07 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +>  Caso haja algum erro na hora de renovar as credenciais, lembre que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Ref
```suggestion
>  Caso haja algum erro na hora de renovar as credenciais, lembre-se que você pode consultar a [referência de códigos de erro](https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Referencia-de-codigos-de-erro).
```

2021-09-23 15:07 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +> Lembre que, a cada vez que você renovar as credenciais, o `refresh_token` também vai mudar, porquanto, você deverá armazená-lo novamente.
```suggestion
> > Lembre-se que, a cada vez que você renovar as credenciais, o `refresh_token` também mudará, por isso, você deverá armazená-lo novamente.
```

2021-09-23 15:08 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +Pronto! A cada vez que um vendedor se vincule ou desvincule, você vai receber uma notificação na URL escolhida.
```suggestion
Pronto! A cada vez que um vendedor se vincular ou desvincular, você receberá uma notificação na URL escolhida.
```

2021-09-23 15:09 UTC, rwaetemann commented on guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md
> +| `action` | `application.authorized` | Informa que o vendedor se vinculou ao aplicação. |
```suggestion
| `action` | `application.authorized` | Informa que o vendedor se vinculou a aplicação. |
```

2021-09-23 15:09 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Você pode receber notificações sempre que um vendedor se vincule ou desvincule do sua aplicação. Para configurá-las, siga estes passos:
```suggestion
Você pode receber notificações sempre que um vendedor se vincular ou desvincular da sua aplicação. Para configurá-las, siga os passos abaixo.
```

2021-09-23 15:09 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +1. Acesse [Suas aplicações](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel) e selecione o aplicação que você utiliza para o fluxo de OAuth.
```suggestion
1. Acesse [Suas aplicações](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel) e selecione a aplicação que você utiliza para o fluxo de OAuth.
```

2021-09-23 15:10 UTC, rwaetemann commented on guides/resources/changelog/current-year.pt.md
> +Aprenda a gerenciar várias contas do Mercado Pago ao mesmo tempo em sua integração e com segurança através do OAuth. Essa funcionalidade de vinculação permite que o vendedor acesse sua conta do Merca
```suggestion
Aprenda a gerenciar várias contas do Mercado Pago simultaneamente e de forma segura através do OAuth. Essa funcionalidade de vinculação permite que o vendedor acesse sua conta do Mercado Pago, autorize a vinculação e habilite sua aplicação para operar em seu nome.
```

2021-09-23 15:11 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md
> +Pronto! A cada vez que um vendedor se vincule ou desvincule, você vai receber uma notificação na URL escolhida.
```suggestion
Pronto! A cada vez que um vendedor se vincular ou desvincular, você receberá uma notificação na URL escolhida.
```

2021-09-23 15:13 UTC, rwaetemann approved these changes

2021-09-23 15:20 UTC, abderossi commented on guides/online-payments/marketplace/checkout-api/create-marketplace.en.md
> +**Your sellers' data that you received last 180 days**. After that, you need to request the seller's authorization again.
```suggestion
**Your sellers' data that you received lasts 180 days**. After that, you need to request the seller's authorization again.
```

2021-09-23 15:23 UTC, merged