Aclaración del uso de las credenciales
mercadopago/devsite-docs pull request #1312
Opened 2021-09-21 19:07 UTC by SofiaMoralesGonzalez1992

Realizamos la aclaración del uso de credenciales para realizar pruebas en suscripciones.

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [X] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-09-22 19:03 UTC, hgaldino requested changes

2021-09-22 19:03 UTC, hgaldino commented on guides/online-payments/subscriptions/testing.pt.md
Use a [chave pública de produção](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/resources/credentials) do seu usuário vendedor de teste na hora de criar a assinatura que quiser testar.<br>

2021-09-27 19:39 UTC, SofiaMoralesGonzalez1992 commented
Hola, quería saber si hay algun bloqueo con este PR?, desde ya gracias.

2021-09-27 20:56 UTC, abderossi commented on guides/online-payments/subscriptions/testing.es.md
> +Utiliza la  [clave pública de producción](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) de tu usuario de prueba vendedor “.<br>
@SofiaMoralesGonzalez1992 No queda claro qué credenciales necesita utilizar el integrador. Se refiere a la public key de las **credenciales de prueba**?
De ser así deberíamos mencionarlas como public key, ya que no las traducimos, y explicar que las encuentran dentro de la opción Credenciales de prueba.

2021-09-28 19:01 UTC, abderossi commented on guides/online-payments/subscriptions/testing.en.md
> +Use the [production public key](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) of your user seller test.<br>
```suggestion
Use the [production open key](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) of your user seller test.<br>
```

2021-09-28 19:21 UTC, SofiaMoralesGonzalez1992 commented
Gracias chicos, disculpen que no quedo claro desde el inicio. Lo tengo en cuenta para la próxima.

2021-09-28 21:42 UTC, abderossi commented on guides/online-payments/subscriptions/testing.es.md
> +Utiliza la  [clave pública de producción](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) de tu usuario de prueba vendedor “.<br>
```suggestion
Utiliza el `access_token` de las [credenciales productivas]((https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) de tu usuario de prueba. 
<br>
```

2021-09-28 21:43 UTC, abderossi commented on guides/online-payments/subscriptions/testing.en.md
> +Use the [production public key](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) of your user seller test.<br>
```suggestion
Use the `access_token` of the [productive credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) of your test user.
<br>
```

2021-09-28 21:45 UTC, abderossi commented on guides/online-payments/subscriptions/testing.pt.md
> +Use a [chave pública de produção](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) do seu usuário vendedor de teste na hora de criar a assinatura que quiser testar.<br>
```suggestion
Use o `access_token` das [credenciais produtivas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/credentials) do seu usuário de teste. 
<br>
```

2021-09-28 21:46 UTC, abderossi approved these changes

2021-09-30 14:01 UTC, hgaldino approved these changes

2021-09-30 14:02 UTC, merged