Nueva documentación de VTEX
mercadopago/devsite-docs pull request #1384
Opened 2021-10-28 20:46 UTC by romisoto

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-11-23 14:51 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/common-errors.pt.md
> +|`Cannot infer Payment Method`|Você está tentando pagar com um cartão que não seja o tipo de cartão selecionado (por exemplo, um número de cartão de crédito foi inserido na opção de cartão de débito)
```suggestion
|`Cannot infer Payment Method`|Você está tentando pagar com um cartão diferente do tipo de cartão selecionado (por exemplo, um número de cartão de crédito foi inserido na opção de cartão de débito).|
```

2021-11-23 14:54 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/common-errors.pt.md
> +|`Invalid users involved`|Ocorre quando é utilizado as credencias produtivas em ambiente de teste ou vice-versa. **Exemplo:** Utilizar um email de teste no nó "payer" quando se está utilizando a cred
```suggestion
|`Invalid users involved`|Ocorre quando as credenciais de produção são utilizadas em ambiente de teste ou vice-versa. **Exemplo:** Utilizar um email de teste no "payer" quando se está utilizando a credencial de produção em um usuário real.|
```

2021-11-23 16:10 UTC, hgaldino requested changes

2021-11-23 16:10 UTC, hgaldino commented on guides/plugins/unofficial/vtex/configure-payment-conditions.en.md
> +* **Pix:** This refers to transactions with Pix via **QR Code** or **Copy and Paste**. To configure this payment condition, you must have a Pix key registered in your Mercado Pago account. For more i
Dúvida: o Pix tem só para o Brasil...vai ter um jeito de deixar essa informação aparecendo só para os brasileiros ou vai ser geral? Fiquei me perguntando isso com a Presta, Romi...mas como não lançaram nesse Q eu não precisei colocar.

2021-11-23 16:10 UTC, hgaldino commented on guides/plugins/unofficial/vtex/prerequisites.en.md
> +|Mercado Pago Payment APP installed|Verify that the App **Mercado Pago Payment APP** is has been installed  in your VTEX application store, in order to use the payment conditions **MercadoPagoPro, Me
Como faz para a URL ficar curtinha assim, Romi? hahaha

2021-11-23 16:15 UTC, romisoto commented on guides/plugins/unofficial/vtex/configure-payment-conditions.en.md
> +* **Pix:** This refers to transactions with Pix via **QR Code** or **Copy and Paste**. To configure this payment condition, you must have a Pix key registered in your Mercado Pago account. For more i
los stakeholders me pidieron que Pix y Boleto Bancário fuesen solo visibles para MLB, por eso le hice la localización (si te fijas, tiene ----[mlb]---- antes de Boleto y ------------ despues de Pix)

2021-11-23 16:16 UTC, romisoto commented on guides/plugins/unofficial/vtex/prerequisites.en.md
> +|Mercado Pago Payment APP installed|Verify that the App **Mercado Pago Payment APP** is has been installed  in your VTEX application store, in order to use the payment conditions **MercadoPagoPro, Me
no se! hahaha lo vi utilizado en otra documentacion y funciona! asi que lo copie!

2021-11-23 17:13 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +**Condições de pagamento** são as formas de pagamento exibidas no site para a finalização de compra. Permitem a configuração de parcelamento, juros, condições especiais etc.
```suggestion
**Condições de pagamento** são as formas de pagamento exibidas no site para a finalização de compra. Permitem a configuração de parcelamento, juros, condições especiais e etc.
```

2021-11-23 17:14 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +Após ter criado sua afiliação com o **MercadoPagoV2**, você deverá configurar as **condições de pagamento** que serão oferecidas aos compradores.
```suggestion
Após criar sua afiliação com o **MercadoPagoV2**, você deverá configurar as **condições de pagamento** que serão oferecidas aos compradores.
```

2021-11-23 17:14 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +> Certifique em sua loja de aplicativos da VTEX se o App **Mercado Pago Payment APP** está instalado para utilização das condições de pagamento **MercadoPagoPro, MercadoPagoWallet e MercadoPagoOff**
```suggestion
> Certifique em sua loja de aplicativos da VTEX se o App **Mercado Pago Payment APP** está instalado para utilização das condições de pagamento **MercadoPagoPro, MercadoPagoWallet e MercadoPagoOff**. Caso não esteja, solicite a instalação para a equipe de VTEX através do [Support VTEX](https://help.vtex.com/es/support).
```

2021-11-23 17:21 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +* **Cartão de Crédito:** refere-se a transações com cartões de crédito diretamente no site da sua loja. Este configuração requer que você selecione cada bandeira de cartão de crédito que deseja em su
```suggestion
* **Cartão de Crédito:** refere-se a transações com cartões de crédito que serão realizadas em sua loja. Esta configuração permite selecionar as bandeiras de cartão que deseja oferecer. [Clique aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/unofficial/vtex/payment-methods) para mais informações sobre as bandeiras disponíveis. Além disso, dependendo das condições de pagamento que selecionar (À vista ou Parcelado), sua configuração pode exigir o preenchimento de campos adicionais. Para mais informações sobre como configurar parcelas na VTEX, clique [aqui](https://help.vtex.com/pt/tutorial/condicoes-de-pagamento--tutorials_455#parcelado-sem-juros). ----[mla, mlu, mlc, mlm, mpe, mco]----
```

2021-11-23 17:22 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +* **Outro:** refere-se à transações com **MercadoPagoOff**, **MercadoPagoWallet**, ou **MercadoPagoPro**.
```suggestion
* **Outro:** refere-se às transações com **MercadoPagoOff**, **MercadoPagoWallet**, ou **MercadoPagoPro**.
```

2021-11-23 17:23 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +  * Se você configurar **MercadoPagoPro**, o comprador realizará o pagamento no ambiente do Mercado Pago, via formulário apresentado diretamente em sua loja e terá acesso a todos os meios de pagament
```suggestion
  * Se você configurar **MercadoPagoPro**, o comprador será direcionado para o ambiente do Mercado Pago onde deverá concluir o pagamento de sua compra utilizando qualquer um dos meios de pagamento disponíveis na plataforma.
```

2021-11-23 17:24 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +* **Pix:** refere-se a transações com Pix através de **QR Code** ou de **Copia e Cola**. Para configurar esta condição de pagamento é necessário que tenha uma chave Pix cadastrada na sua conta do Mer
```suggestion
* **Pix:** refere-se a transações com Pix através de **QR Code** ou **Copia e Cola**. Para configurar esta condição de pagamento é necessário que tenha uma chave Pix cadastrada na sua conta do Mercado Pago. Para obter mais informações sobre como criar sua chave Pix, clique [aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/stop/pix?url=https%3A%2F%2Fwww.mercadopago.com.br%2Fadmin-pix-keys%2Fmy-keys&authentication_mode=required). ------------
```

2021-11-23 17:25 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +> Nota
```suggestion
> Importante
```

2021-11-23 17:25 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +> Você também pode configurar **condições especiais** de pagamento. Clique [aqui](https://help.vtex.com/pt/tutorial/condicoes-especiais--tutorials_456?&utm_source=admin) para obter mais informações.
```suggestion
> Você também pode configurar **condições especiais** de pagamento. Clique [aqui](https://help.vtex.com/pt/tutorial/condicoes-especiais--tutorials_456?&utm_source=admin) para mais informações.
```

2021-11-23 17:26 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +> Nota
```suggestion
> Importante
```

2021-11-23 17:27 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +> Se você tiver dificuldades durante sua integração, verifique nosso [lista de erros](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/unofficial/vtex/common-errors) e nosso d
```suggestion
> Caso tenha alguma dúvida durante a integração, acesse nossa [lista de erros](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/unofficial/vtex/common-errors) e nosso documento sobre [logs do VTEX](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/unofficial/vtex/logs).
```

2021-11-23 17:27 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +> Conheça como configurar o fingerprint.
```suggestion
> Saiba como configurar o Device Fingerprint.
```

2021-11-23 17:32 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/device-fingerprint.pt.md
> +Sempre que possível, recomendamos que envie informações sobre o comportamento do cliente para detectar movimentos incomuns e evitar transações fraudulentas. Não se preocupe, cuidamos dos dados de seu
```suggestion
Sempre que possível, recomendamos que envie informações sobre o comportamento do cliente para detectar movimentos incomuns e evitar transações fraudulentas. Os dados recebidos são analisados de forma segura e não os compartilhamos com ninguém.
```

2021-11-23 17:33 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/device-fingerprint.pt.md
> +**Para configurar o device fingerprint**, siga os passos abaixo:
```suggestion
Para configurar o **Device Fingerprint**, siga os passos abaixo:
```

2021-11-23 17:33 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/device-fingerprint.pt.md
> +1. No painel de administração de sua loja, acesse **Checkout** del módulo **Configurações da Loja**.
```suggestion
1. No painel de administração de sua loja, acesse **Checkout > Configurações da Loja**.
```

2021-11-23 17:34 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/device-fingerprint.pt.md
> +3. Acessar a aba **Código** e clique em **checkout6-custom.js** no módulo **Arquivos**.
```suggestion
3. No módulo **Arquivos**, acesse a aba **Código** e clique em **checkout6-custom.js**.
```

2021-11-23 17:35 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/device-fingerprint.pt.md
> +4. Copiar e colar o seguinte código e clique em **Salvar**.
```suggestion
4. Copie e cole o seguinte código e clique em **Salvar**.
```

2021-11-23 21:17 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +Uma **afiliação de gateway** é um conjunto de configurações que representam o processamento de seus pagamentos com um gateway de pagamento de sua escolha, neste caso **Mercado Pago**.
```suggestion
Uma **afiliação de gateway** é um conjunto de configurações que representam o processamento de seus pagamentos com um gateway de pagamento de sua escolha, neste caso o **Mercado Pago**. 
```

2021-11-23 21:17 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +Com isso, é possível decidir por qual gateway de pagamento serão processados os diferentes tipos de transações da sua loja VTEX, podendo a **afiliação de gateway MercadoPagoV2** para o processamento
```suggestion
Com isso, é possível decidir por qual gateway de pagamento serão processados os diferentes tipos de transações da sua loja VTEX, podendo a **afiliação de gateway MercadoPagoV2** processar pagamentos com Cartão de Crédito, Cartão de Débito, Mercado Pago Offline e Checkout Pro.
```

2021-11-23 21:18 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +A afliliação MercadoPagoV2 processa as condições de pagamento Cartão de Crédito, Boleto Bancário, Pix, Mercado Pago Offline e Checkout Pro.
```suggestion
A afiliação MercadoPagoV2 processa as condições de pagamento Cartão de Crédito, Boleto Bancário, Pix, Mercado Pago Offline e Checkout Pro.
```

2021-11-23 21:18 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +A afliliação MercadoPagoV2 processa as condições de pagamento Cartão de Crédito, Cartão de Débito, Mercado Pago Offline e Checkout Pro.
```suggestion
A afiliação MercadoPagoV2 processa as condições de pagamento Cartão de Crédito, Cartão de Débito, Mercado Pago Offline e Checkout Pro.
```

2021-11-23 21:19 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +A afliliação MercadoPagoV2 processa as condições de pagamento Cartão de Crédito, Cartão de Débito e Checkout Pro.
```suggestion
A afiliação MercadoPagoV2 processa as condições de pagamento Cartão de Crédito, Cartão de Débito e Checkout Pro.
```

2021-11-23 21:20 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +> Se você tem uma afiliação de gateway do MercadoPagoV1, por motivos de segurança, recomendamos [migrar para o MercadoPagoV2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/
```suggestion
> Por motivos de segurança, caso você tenha uma afiliação de gateway do MercadoPagoV1, recomendamos [migrar para o MercadoPagoV2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/unofficial/vtex/mp1-mp2-migration).
```

2021-11-23 21:23 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Nome da loja - Nombre para resúmenes:** Nome da loja. O valor deste campo aparecerá na fatura do cartão do cliente
@romisoto - Romi, na UI aparece assim mesmo? Em PT e ES?

2021-11-23 21:23 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Parcelamento máximo - Cuotas máximas** Número máximo de parcelas disponíveis.
```suggestion
   * **Parcelamento máximo - Cuotas máximas:** Número máximo de parcelas disponíveis.
```

2021-11-23 21:24 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Modo binário - binário:** Configura se o pagamento poderá passar por revisão manual ou não.
```suggestion
   * **Modo binário - binário:** Escolha se o pagamento poderá passar por revisão manual ou não.
```

2021-11-25 13:00 UTC, romisoto commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Nome da loja - Nombre para resúmenes:** Nome da loja. O valor deste campo aparecerá na fatura do cartão do cliente
si! incluso en la version en EN de VTEX esta solo en ES y PT

2021-11-25 13:47 UTC, romisoto commented on guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
> +* **Cartão de Crédito:** refere-se a transações com cartões de crédito diretamente no site da sua loja. Este configuração requer que você selecione cada bandeira de cartão de crédito que deseja em su
```suggestion
* **Cartão de Crédito:** refere-se a transações com cartões de crédito que serão realizadas em sua loja. Este configuração requer que você selecione cada bandeira de cartão de crédito que deseja em sua loja. [Clique aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins/unofficial/vtex/payment-methods) para mais informações sobre as bandeiras disponíveis. Além disso, dependendo das condições de pagamento que selecionar (À vista ou Parcelado), sua configuração pode exigir o preenchimento de campos adicionais. Para mais informações sobre como configurar parcelas na VTEX, clique [aqui](https://help.vtex.com/pt/tutorial/condicoes-de-pagamento--tutorials_455#parcelado-sem-juros). ----[mla, mlu, mlc, mlm, mpe, mco]----
```

2021-11-25 14:16 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +Uma **afiliação de gateway** é um conjunto de configurações que representam o processamento de seus pagamentos com um gateway de pagamento de sua escolha, neste caso o **Mercado Pago**.
```suggestion
Uma **afiliação de gateway** é um conjunto de configurações que representam o processamento de seus pagamentos com um gateway de sua escolha, neste caso o **Mercado Pago**. 
```

2021-11-25 14:23 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Application Key:** Refere-se às suas [credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) do Mercado Pago. Complete com sua Public Key.
@romisoto - Romi, talvez valha deixar claro que são as credencias de produção ou teste, né?

2021-11-25 14:24 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Modo de processamento - Modo de procesamiento** Configura se o pagamento será gateway ou agregador. Para processar pagamentos em modo Gateway contate o seu Assessor do Mercado Pago.
```suggestion
   * **Modo de processamento - Modo de procesamiento:** Selecione se o pagamento será gateway ou agregador. Para processar pagamentos em modo Gateway contate o seu Assessor do Mercado Pago.
```

2021-11-25 14:25 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Modo de processamento - Modo de procesamiento** Configura se o pagamento será gateway ou agregador. Para processar pagamentos em modo Gateway contate o seu Assessor do Mercado Pago.
@romisoto - O que seria agregador?

2021-11-25 14:29 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Integrator ID:** Para programadores ou agências que realizam a integração.
@romisoto - Romi, esse integrator ID não é o ID de integração que os membros do dev program usam? Ou é diferente?

2021-11-25 14:29 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +E pronto! Sua afiliação com MercadoPagoV2 já está ativa!
```suggestion
Pronto! Sua afiliação com MercadoPagoV2 já está ativa!
```

2021-11-25 14:31 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/introduction.pt.md
> +VTEX é uma **plataforma e-commerce de lojas virtuais que permite processar pagamentos através do Mercado Pago**.
```suggestion
VTEX é uma **plataforma de e-commerce que permite processar pagamentos através do Mercado Pago**.
```

2021-11-25 14:32 UTC, romisoto commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Application Key:** Refere-se às suas [credenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) do Mercado Pago. Complete com sua Public Key.
ok!

2021-11-25 14:33 UTC, romisoto commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Modo de processamento - Modo de procesamiento** Configura se o pagamento será gateway ou agregador. Para processar pagamentos em modo Gateway contate o seu Assessor do Mercado Pago.
es el nombre de uno de los modos de procesamiento. hay dos: gateway & agregador

2021-11-25 14:34 UTC, romisoto commented on guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
> +   * **Integrator ID:** Para programadores ou agências que realizam a integração.
No lo se, se lo pregunto a la gente de VTEX!

2021-11-25 14:40 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Os logs provêm um maior entendimento às equipes para que possam ter um melhor suporte em uma primeira instância, pois permitem revisar a informação retornada na integração do Mercado Pago com a VTEX
```suggestion
Os logs são conjuntos de informações que reúnem todas as ocorrências dentro de determinada transação. A partir da análise dos dados, o usuário poderá identificar se houve ou não algum erro e como corrigi-lo.
```

2021-11-25 14:41 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Os logs provêm um maior entendimento às equipes para que possam ter um melhor suporte em uma primeira instância, pois permitem revisar a informação retornada na integração do Mercado Pago com a VTEX
@romisoto - Romi, aqui eu reescrevi todo o parágrafo porque estava bem confuso em PT. Pelo que entendi, acho que fica melhor se reescrevermos dessa forma. O que você acha?

2021-11-25 14:46 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Também em caso de modificação ou ativação de novos meios de pagamento, nos dão a possibilidade de poder validar se tudo está funcionando conforme o previsto.
```suggestion
Além disso, caso seja necessário modificar ou ativar novos meios de pagamento, é possível validar se tudo está funcionando conforme o previsto.
```

2021-11-25 14:47 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Para ter acesso aos logs, acesse o menu **Transações** do módulo **Pagamentos** do painel de administração de sua loja VTEX, então busque pelo LOG que contenha o `status response` e clique em **"+ In
```suggestion
Para ter acesso aos logs, acesse o painel de administração de sua loja VTEX e clique em  **Transações > Pagamentos**, então busque pelo LOG que contenha o `status response` e clique em **"+ Informações"**. Os dados mais significativos são os seguintes:
```

2021-11-25 14:48 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Quando confrontado com uma rejeição, é muito importante rever o `status_detail` que especifica o motivo do mesmo.
```suggestion
Caso um pagamento seja rejeitado, é  importante rever o `status_detail` que especifica o motivo da recusa.
```

2021-11-25 14:48 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Para mais informações acesse o link [Resultados da criação de uma cobrança](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/handling-responses).
```suggestion
Para mais informações, acesse o link [Resultados da criação de uma cobrança](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/handling-responses).
```

2021-11-25 14:50 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/mp1-mp2-migration.pt.md
> +As afiliações **MercadoPago** e **MercadoPagoV1** serão descontinuadas. As mesmas processavam apenas a condição de pagamento Cartão de Crédito e Débito e agora essas mesmas condições já estão disponí
```suggestion
As afiliações **MercadoPago** e **MercadoPagoV1** serão descontinuadas. Essas afiliações processavam apenas a condição de pagamento Cartão de Crédito e Débito e agora essas mesmas condições já estão disponíveis no **MercadoPagoV2**.
```

2021-11-25 14:51 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/mp1-mp2-migration.pt.md
> +Se você cadastrou uma afiliação MercadoPagoV1, você pode **migrar de MercadoPagoV1 para MercadoPagoV2**, realizando os seguintes passos:
```suggestion
Se você cadastrou uma afiliação MercadoPagoV1, siga os passos abaixo para **migrar de MercadoPagoV1 para MercadoPagoV2**.
```

2021-11-25 14:53 UTC, rwaetemann commented on guides/plugins/unofficial/vtex/prerequisites.pt.md
> +> Conheça como cadastrar uma afiliação.
```suggestion
> Saiba como cadastrar uma afiliação.
```

2021-11-25 15:03 UTC, romisoto commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Os logs provêm um maior entendimento às equipes para que possam ter um melhor suporte em uma primeira instância, pois permitem revisar a informação retornada na integração do Mercado Pago com a VTEX
perfeito! obrigada!

2021-11-25 20:05 UTC, abderossi commented on guides/plugins/unofficial/vtex/configure-payment-conditions.es.md
> +  * Si configuras **MercadoPagoOff**, puedes contar con medios de pago en efectivo, como Boleto Bancário y PEC (pagos en puntos de venta de loterías). ----[mlb]----
Los ejemplos de medios de pago en efectivo que se dan acá no están disponibles en todos los países. Normalmente solo los mencionamos para cada país. En este caso, Boleto Bancário sería solo para Brasil, por ejemplo. Podríamos no dar ejemplos y eso lo resuelve.  Sino también como algo opcional, podríamos sugerirles visitar la sección de Medios de pago por país en caso que tengan dudas de cuál les corresponde: https://www.mercadopago.com.ar/developers/es/guides/resources/localization/payment-methods#bookmark_medios_de_pago_por_pa%C3%ADs

2021-11-25 20:18 UTC, abderossi commented on guides/plugins/unofficial/vtex/gateway-affiliations.es.md
> +   * **Métodos de pagamento excluídos - Métodos de pago excluídos (visa, paypal, bolbradesco, oxxo...):** Métodos de pago que se excluirán en el momento de la compra. [Mira las opciones aquí](https:/
Acá sucede lo mismo que comenté arriba: damos ejemplos de medios de pago que no están disponibles en todos los países. Usualmente en el devsite no los mostramos.

2021-11-25 20:19 UTC, abderossi commented on guides/plugins/unofficial/vtex/introduction.en.md
> +1. [Verify all prerequisites.](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/unofficial/vtex/prerequisites)
OPCIONALÍSIMO: pueden ir sin punto porque es una enumeración de pasos.

2021-11-25 20:20 UTC, abderossi commented on guides/plugins/unofficial/vtex/introduction.es.md
> +1. [Verifica todos los prerrequisitos.](hhttps://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/vtex/prerequisites)
```suggestion
1. [Verifica todos los prerrequisitos.](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/vtex/prerequisites)
```

2021-11-25 20:20 UTC, abderossi commented on guides/plugins/unofficial/vtex/introduction.es.md
> +1. [Verifica todos los prerrequisitos.](hhttps://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/unofficial/vtex/prerequisites)
Si bien prerrequisitos es correcto, "requisitos previos" no sería un poco más común?

2021-11-25 20:21 UTC, romisoto commented on guides/plugins/unofficial/vtex/gateway-affiliations.es.md
> +   * **Métodos de pagamento excluídos - Métodos de pago excluídos (visa, paypal, bolbradesco, oxxo...):** Métodos de pago que se excluirán en el momento de la compra. [Mira las opciones aquí](https:/
@abderossi en el otro caso voy a aplicar la sugerencia, pero aca no puedo porque es el texto de los campos tal como estan en la pagina de VTEX, ejemplos incluídos

2021-11-25 20:22 UTC, abderossi commented on guides/plugins/unofficial/vtex/logs.es.md
> +Para acceder a los logs, accede al panel de administración de tu tienda VTEX y haz clic en **Pagos > Transacciones**. Luego busca el LOG que contiene el `status response` y haz clic en **"+ Informaci
LOG está en mayúscula por algo en particular?

2021-11-25 20:23 UTC, romisoto commented on guides/plugins/unofficial/vtex/logs.es.md
> +Para acceder a los logs, accede al panel de administración de tu tienda VTEX y haz clic en **Pagos > Transacciones**. Luego busca el LOG que contiene el `status response` y haz clic en **"+ Informaci
lo pasaron asi ellos, lo puedo cambiar

2021-11-25 20:25 UTC, abderossi commented on guides/plugins/unofficial/vtex/prerequisites.es.md
> +# Prerrequisitos
En general en las docus en español, esta sección se llama Requisitos Previos. Igual es correcto llamarlo así! Lo menciono como sugerencia.

2021-11-25 20:32 UTC, romisoto commented on guides/plugins/unofficial/vtex/logs.es.md
> +Para acceder a los logs, accede al panel de administración de tu tienda VTEX y haz clic en **Pagos > Transacciones**. Luego busca el LOG que contiene el `status response` y haz clic en **"+ Informaci
```suggestion
Para acceder a los logs, accede al panel de administración de tu tienda VTEX y haz clic en **Pagos > Transacciones**. Luego busca el log que contiene el `status response` y haz clic en **"+ Información"**. Los datos más significativos son los siguientes:
```

2021-11-25 20:34 UTC, romisoto commented on guides/plugins/unofficial/vtex/logs.pt.md
> +Para ter acesso aos logs, acesse o painel de administração de sua loja VTEX e clique em  **Pagamentos > Transações**, então busque pelo LOG que contenha o `status response` e clique em **"+ Informaçõ
```suggestion
Para ter acesso aos logs, acesse o painel de administração de sua loja VTEX e clique em  **Pagamentos > Transações**, então busque pelo log que contenha o `status response` e clique em **"+ Informações"**. Os dados mais significativos são os seguintes:
```

2021-11-25 20:34 UTC, romisoto commented on guides/plugins/unofficial/vtex/logs.en.md
> +To access the logs, access the administration panel of your VTEX store, and click on **Payments > Transactions**, then look for the LOG that contains the `status response` and click on **"+ Informati
```suggestion
To access the logs, access the administration panel of your VTEX store, and click on **Payments > Transactions**, then look for the log that contains the `status response` and click on **"+ Information"**. The most significant data is the following:
```

2021-11-29 18:34 UTC, hgaldino approved these changes

2021-11-30 13:28 UTC, rwaetemann approved these changes

2021-11-30 17:58 UTC, abderossi approved these changes

2021-12-01 13:57 UTC, merged