Reescrevendo a documentação de Notifications
mercadopago/devsite-docs pull request #1407
Opened 2021-11-10 18:36 UTC by hgaldino

## Description
PR relacionado aos ajustes na documentação de Notifications, incluindo a criação do menu de introdução.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [x] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [x] Requires translations.

2021-11-22 15:11 UTC, lamaralmp requested changes

2021-11-22 15:11 UTC, lamaralmp commented on guides/notifications/Introduction.pt.md
> +Uma vez instalado, o Webhook será enviado cada vez que ocorrer um ou mais eventos assinados, evitando que haja um trabalho de pesquisa a cada minuto em busca de uma resposta e, por consequência, impe
- `Uma vez instalado`
Acho que **configurado** ficaria melhor, não se **instala** exatamente o webhook

- `um ou mais eventos assinados`
Precisa ver a melhor forma de não ficar redundante, mas acho que eventos configurados/cadastrados ficaria melhor

- `evitando que haja um trabalho de pesquisa a cada minuto em busca de uma resposta e, por consequência, impede que aconteça uma sobrecarga do sistema e a perda de dados sempre que ocorrer alguma situação.`
É exatamente isso, mas também achei confuso assim em uma frase corrida.

2021-11-22 15:11 UTC, lamaralmp commented on guides/notifications/Introduction.pt.md
> +O [IPN](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn) (_Instant Payment Notification_) é um mecanismo que permite que sua loja receba notificações de um servidor
- `permite que sua loja receba notificações de um servidor do Mercado Pago`
Trocaria loja por aplicação e diria diretamente receba notificações do Mercado Pago

- `informando o estado de um determinado pagamento`
Não só pagamentos, também vale para chargebacks e merchant_orders

- `as notificações por IPN poderão ser configuradas para uma única aplicação por vez`
Na verdade é possível configurar apenas uma url de notificação IPN por conta (mais de uma aplicação pode usar essa url dependendo da aplicação)
E há também a possibilidade de utilizar notificação ipn por meio do campo notification_url do objeto. Dessa forma a url pode ser diferente pra cada objeto ou aplicação.

2021-11-22 16:52 UTC, lamaralmp requested changes

2021-11-22 16:52 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +Depois de dar um retorno à notificação, você obterá as informações completas do recurso notificado acessando o terminal correspondente da [API](https://api.mercadopago.com/):
Acho que poderia tirar esse link da API

2021-11-22 16:52 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +| merchant_orders | `https://api.mercadopago.com/merchant\_orders/[ID]` | [ver documentação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/merchant_orders/_merchant_orders_id/ge
```suggestion
| merchant_orders | `https://api.mercadopago.com/merchant_orders/[ID]` | [ver documentação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/merchant_orders/_merchant_orders_id/get) |
```

2021-11-22 16:52 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +
Senti falta de um exemplo de notificação, com uma tabela explicando o que é cada campo. Parecido ao que temos em Webhooks

2021-11-22 19:19 UTC, lamaralmp requested changes

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +===
Ficou sobrando esse `===`

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +Encontre o estado do pagamento no campo _status_.
Ficou sobrando esse comentário

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +    Notification_url = Request["http://requestbin.fullcontact.com/1ogudgk1"],
```suggestion
    NotificationUrl = "http://requestbin.fullcontact.com/1ogudgk1",
```

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +    Notification_url = Request["http://requestbin.fullcontact.com/1ogudgk1"],
Fiz essa alteração baseado na lógica do snippet, mas validaria com o time de SDKs

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +Encontre o estado do pagamento no campo _status_.
Ficou sobrando esse comentário

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +notification_url =  "http://requestbin.fullcontact.com/1ogudgk1"
```suggestion
```

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +    "payment_method_id": request.POST.get("payment_method_id"),
```suggestion
    "payment_method_id": request.POST.get("payment_method_id"),
    "notification_url" =  "http://requestbin.fullcontact.com/1ogudgk1",
```

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +    "payment_method_id": request.POST.get("payment_method_id"),
Validaria com SDKs

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +===
Ficou sobrando esse `===`

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +```php
Não conseguimos para outras linguagens?

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +Isso indica que foi criado o pagamento **999999999** para o usuário **44444** em modo de produção com a versão V1 da API e que esse evento ocorreu na data **2016-03-25T10:04:58.396-04:00**.
Acho que aqui seria interessante uma tabela com todos os campos explicando o que é cada um

2021-11-22 19:19 UTC, lamaralmp commented on guides/notifications/webhooks.pt.md
> +Depois de dar um retorno à notificação, você obterá as informações completas do recurso notificado acessando o terminal correspondente da [API](https://api.mercadopago.com/):
Acho que pode remover esse link

2021-11-29 12:20 UTC, romisoto commented on guides/notifications/Introduction.en.md
> +Notifications are messages sent by the Mercado Pago server from events carried out in your application, and these events are updates to the reported object, such as the creation/update of payments, l
```suggestion
Notifications are messages sent by the Mercado Pago server from events carried out in your application, and these events are updates to the reported object, such as the creation/update of payments, linking to a subscription plan, among other types of internal updates in the application.
```

2021-11-29 12:22 UTC, romisoto commented on guides/notifications/Introduction.en.md
> +With the notifications configured, you will have a real-time information about the changes produced in the different features of the Mercado Pago APIs.
```suggestion
With the notifications configured, you will have real-time information about the changes produced in the different features of the Mercado Pago APIs.
```

2021-11-29 12:24 UTC, romisoto commented on guides/notifications/Introduction.en.md
> +Currently, notifications are available for configuration:
```suggestion
Currently, the following notifications are available for configuration:
```

2021-11-29 12:26 UTC, romisoto commented on guides/notifications/Introduction.es.md
> +Las notificaciones son mensajes enviados por el servidor de Mercado Pago de eventos que se realizan en su aplicación, y estos eventos son actualizaciones al objeto reportado, como la creación / actua
```suggestion
Las notificaciones son mensajes enviados por el servidor de Mercado Pago sobre eventos que se realizan en su aplicación. Estos eventos son actualizaciones al objeto reportado, tales como la creación / actualización de pagos, vinculación a un plan de suscripción, entre otros tipos de actualización interna en la aplicación. .
```

2021-11-29 12:27 UTC, romisoto commented on guides/notifications/Introduction.es.md
> +Actualmente, las notificaciones están disponibles para configuración:
```suggestion
Actualmente, las siguientes notificaciones están disponibles para configuración:
```

2021-11-29 12:28 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +# IPN notifications for in personal payments
```suggestion
# IPN notifications for in-person payments
```

2021-11-29 12:29 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +If you are integrating in-person payments with QR code, below we will provide information about IPN notifications in this type of payment for each status (opened and closed). In addition, we will ind
```suggestion
If you are integrating in-person payments with QR code, below we will provide information about IPN notifications in this type of payment for each status (opened and closed). In addition, we will indicate how to consult the order with the external reference and what you will need to do if the customer scans the QR code twice (leaving an order always open).
```

2021-11-29 12:32 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +* The `status` field of the `merchant_order` will remain in **opened** when it doesn't have associated payments yet or has rejected/approved payments for an amount less than the order total.
```suggestion
* The `status` field of the `merchant_order` will remain as **opened** when it doesn't have associated payments yet or has rejected/approved payments for an amount that is less than the order total.
```

2021-11-29 12:33 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +Inside the order, in the payments object, you will find all its payments. It is important to obtain the ID of payments with **approved** status in order to [can make refunds](https://www.mercadopago[
```suggestion
Inside the order, in the payments object, you will find all its payments. It is important to obtain the ID of payments with **approved** status in order to [make refunds](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/account/cancellations-and-refunds). When the `status` of `merchant_order` is **closed**, make sure that the sum of payments with `status` **approved** is equal to or greater than the order total.
```

2021-11-29 12:33 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +For each QR scan a different `merchant_order` is generated. Remember that if the customer does more than one scan, an order will be **open** indefinitely and, to close the transaction, the `merchant_
```suggestion
For each QR scan a different `merchant_order` is generated. Remember that if the customer does more than one scan, an order will remain **open** indefinitely and, to close the transaction, the `merchant_order` must have `status` = **closed**.
```

2021-11-29 12:34 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +If notifications are not received, it will be necessary to apply as a contingency method the **order search** using its `external_reference` as search criteria. The **search** can be performed by `ex
```suggestion
If notifications are not received, it will be necessary to apply the **order search** as a contingency method using its `external_reference` as search criteria. The **search** can be performed by `external_reference` in two ways:
```

2021-11-29 12:36 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +| **Automatic** | After a reasonable amount of time without receiving any notification, an order search is started at every interval of, for example, 5 seconds. |
"After a reasonable amount of time" - un periodo de tiempo razonable es algo que puede ser subjetivo dependiendo de quien lo lea, hay forma de explicar esto de forma mas exacta o menos ambigua?

2021-11-29 12:37 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +Si está integrando pagos presenciales con código QR, a continuación le proporcionaremos información sobre las notificaciones de IPN en este tipo de pago para cada estado (opened e closed). Además, in
```suggestion
Si estas integrando pagos presenciales con código QR, a continuación te proporcionaremos información sobre las notificaciones de IPN en este tipo de pago para cada estado (opened y closed). Además, indicaremos cómo consultar el pedido con la referencia externa y qué será necesario hacer si el cliente escanea el código QR dos veces (dejando un pedido siempre abierto).
```

2021-11-29 12:37 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +La integración de pago con código QR utiliza el objeto `merchant_order`, que es básicamente un pedido con 1 o más artículos. Por lo tanto, para las notificaciones de IPN en pagos presenciales recuerd
```suggestion
La integración de pago con código QR utiliza el objeto `merchant_order`, que es básicamente un pedido con 1 o más artículos. Por lo tanto, para las notificaciones de IPN en pagos presenciales recuerda las siguientes reglas:
```

2021-11-29 12:39 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +Dentro del pedido, en el objeto de pagos, encontrará todos sus pagos. Es importante obtener el ID de los pagos con estado **approved** para [puede hacer reembolsos](https://www.mercadopago[FAKER][URL
```suggestion
Dentro del pedido, en el objeto de pagos, encontrarás todos tus pagos. Es importante obtener el ID de los pagos con estado **approved** para [hacer reembolsos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/account/cancellations-and-refunds). Cuando el `status` de `merchant_order` sea **closed**, asegúrate de que la suma de los pagos con estado  **approved** sea igual o mayor que el total del pedido.
```

2021-11-29 12:45 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +Para cada escaneo QR, se genera un "comerciante_orden" diferente. Recuerde que si el cliente hace más de un escaneo, un pedido será **opened** indefinidamente y, para cerrar la transacción, el `merch
"comerciante_orden" = merchant_order??

2021-11-29 12:46 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +Si no se reciben notificaciones, será necesario aplicar como método de contingencia la ** búsqueda de pedidos ** utilizando su `external_reference` como criterio de búsqueda. La ** búsqueda ** se pue
```suggestion
Si no se reciben notificaciones, será necesario aplicar como método de contingencia la **búsqueda de pedidos** utilizando su `external_reference` como criterio de búsqueda. La **búsqueda** se puede realizar mediante `external_reference` de dos formas:
```

2021-11-29 12:47 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +| **Automático** | Después de un período de tiempo razonable sin recibir ninguna notificación, se inicia una búsqueda de pedidos en cada intervalo de, por ejemplo, 5 segundos. |
sobre lo de "razonable", aplica el mismo comentario que hice en el documento en inglés

2021-11-29 12:48 UTC, romisoto commented on guides/snippets/test-integration/notification-response.en.md
> +When you receive a notification on your platform, Mercado Pago waits for a response to validate that you received it correctly. For that, you must return an `HTTP STATUS 200 (OK)` or `201 (CREATED)`.
```suggestion
When you receive a notification on your platform, Mercado Pago waits for a response to validate that you received it correctly. For that, you must return an `HTTP STATUS 200 (OK)` or `201 (CREATED)`. If this response is not sent, it will be understood that you have not received the notification and a further attempt to send it will be made until you submit the response.
```

2021-11-29 12:49 UTC, romisoto commented on guides/snippets/test-integration/notification-response.en.md
> +| Event | Deadline after the first shipment | Confirmation waiting time |
Shipment se refiere e envío de cosas físicas, si te referis al envío de la notificación tal vez sería mejor cambiar la palabra por "envío"

2021-11-29 12:49 UTC, romisoto commented on guides/snippets/test-integration/notification-response.es.md
> +Cuando recibes una notificación en tu plataforma, Mercado Pago espera una respuesta para validar que la recibiste correctamente. Para eso, debe devolver un `HTTP STATUS 200 (OK)` o `201 (CREATED)`. S
```suggestion
Cuando recibes una notificación en tu plataforma, Mercado Pago espera una respuesta para validar que la recibiste correctamente. Para eso, debe devolver un `HTTP STATUS 200 (OK)` o `201 (CREATED)`. Si no se envía esta respuesta, se entenderá que no ha recibido la notificación y se realizará un nuevo intento de envío hasta que reciba la respuesta.
```

2021-11-29 12:50 UTC, romisoto commented on guides/snippets/test-integration/notification-response.es.md
> +En la siguiente tabla puede encontrar los principales eventos, plazos y tiempo de espera para recibir nuevos intentos de notificación.
```suggestion
En la siguiente tabla puedes encontrar los principales eventos, plazos y tiempo de espera para recibir nuevos intentos de notificación.
```

2021-12-13 12:04 UTC, romisoto commented on guides/notifications/Introduction.en.md
> +There are **two types** of notifications available for configuration, which once configured, allow you to program your store's backend to, for example, update the status of orders when a payment is c
```suggestion
There are **two types** of notifications available for configuration which ,once configured, allow you to program your store's backend to, for example, update the status of orders when a payment is created, send an order confirmation email from store when an order is updated on Mercado Pago, updating a customer's record when a subscription plan is linked, or any other actions arising from the events listed above.
```

2021-12-13 12:07 UTC, romisoto commented on guides/notifications/Introduction.es.md
> +* Desvincular cuentas mp-connect
```suggestion
* Desvinculación de cuentas mp-connect
```

2021-12-13 12:08 UTC, romisoto commented on guides/notifications/Introduction.es.md
> +Hay **dos tipos** de notificaciones disponibles para la configuración, que una vez configuradas, le permiten programar el backend de su tienda para, por ejemplo, actualizar el estado de los pedidos c
```suggestion
Hay **dos tipos** de notificaciones disponibles para la configuración, que una vez configuradas, te permiten programar el backend de tu tienda para, por ejemplo, actualizar el estado de los pedidos cuando se crea un pago, enviar un correo electrónico de confirmación del pedido desde la tienda cuando un pedido se actualiza en Mercado Pago, actualizar el registro de un cliente cuando se vincula un plan de suscripción, o cualquier otra acción derivada de los eventos enumerados anteriormente.
```

2021-12-13 12:12 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +Si está integrando pagos presenciales con código QR, a continuación le brindaremos información sobre las notificaciones de IPN en este tipo de pago para cada estado (abierto y cerrado). Además, indic
```suggestion
Si estás integrando pagos presenciales con código QR, a continuación te brindaremos información sobre las notificaciones de IPN en este tipo de pago para cada estado (abierto y cerrado). Además, indicaremos cómo consultar el pedido con la referencia externa y qué será necesario hacer si el cliente escanea el código QR dos veces (dejando un pedido siempre abierto).
```

2021-12-13 12:13 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +Dentro del pedido, en el objeto de pagos, encontrará todos los pagos realizados, ya sean aprobados o rechazados. Es importante obtener el ID de los pagos con estado ** aprobado ** para poder realizar
```suggestion
Dentro del pedido, en el objeto de pagos, encontrarás todos los pagos realizados, ya sean aprobados o rechazados. Es importante obtener el ID de los pagos con estado **aprobado** para poder realizar devoluciones/devoluciones.
```

2021-12-13 12:13 UTC, romisoto commented on guides/notifications/ipn-personal-payment.es.md
> +Dentro del pedido, en el objeto de pagos, encontrará todos los pagos realizados, ya sean aprobados o rechazados. Es importante obtener el ID de los pagos con estado ** aprobado ** para poder realizar
"devoluciones/devoluciones" esto es correcto?

2021-12-13 12:14 UTC, romisoto commented on guides/notifications/ipn-personal-payment.en.md
> +Within the order, in the payments object, you will find all payments made, whether approved or rejected. It is important to obtain the ID of payments with **approved** status in order to carry out re
"refunds/refunds": esto es correcto?

2021-12-13 12:17 UTC, romisoto commented on guides/snippets/test-integration/notification-response.es.md
> +Cuando recibes una notificación en tu plataforma, Mercado Pago espera una respuesta para validar que la recibiste correctamente. Para eso, debe devolver un `HTTP STATUS 200 (OK)` o `201 (CREATED)`. S
```suggestion
Cuando recibes una notificación en tu plataforma, Mercado Pago espera una respuesta para validar que la recibiste correctamente. Para eso, debes devolver un `HTTP STATUS 200 (OK)` o `201 (CREATED)`. Si no se envía esta respuesta, se entenderá que no ha recibido la notificación y se realizará un nuevo intento de envío hasta que reciba la respuesta.
```

2021-12-13 12:22 UTC, romisoto commented on guides/notifications/ipn.en.md
> +It is possible to configure the notification url more specifically for each payment using the `notification_url` field. See below how to do this using the SDKs.
```suggestion
It is possible to configure the notification URL more specifically for each payment using the `notification_url` field. See below how to do this using the SDKs.
```

2021-12-13 12:24 UTC, romisoto commented on guides/notifications/ipn.es.md
> +**IPN (_Instant Payment Notification_)** es un mecanismo que permite que tu aplicación reciba notificaciones de Mercado Pago. informando el estado de un determinado pago, contracargo y comerciante_or
```suggestion
**IPN (_Instant Payment Notification_)** es un mecanismo que permite que tu aplicación reciba notificaciones de Mercado Pago, informando el estado de un determinado pago, contracargo y merchant_order, a través de una llamada `HTTP POST` para informar sobre sus transacciones.
```

2021-12-13 12:25 UTC, romisoto commented on guides/notifications/ipn.es.md
> +En esta documentación te explicaremos la configuración necesaria para recibir notificaciones de IPN (a través del Dashboard o al momento de crear pagos), así como mostrar las acciones necesarias que
```suggestion
En esta documentación te explicaremos la configuración necesaria para recibir notificaciones de IPN (a través del Dashboard o al momento de crear pagos), y te mostraremos las acciones necesarias que debes realizar para que Mercado Pago valide que los mensajes fueron recibidos correctamente.
```

2021-12-13 12:25 UTC, romisoto commented on guides/notifications/ipn.es.md
> +1. Acceda a la pantalla [Notificaciones IPN](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications/ipn).
```suggestion
1. Accede a la pantalla [Notificaciones IPN](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications/ipn).
```

2021-12-13 12:26 UTC, romisoto commented on guides/notifications/ipn.es.md
> +2. A continuación, configure la **URL** de **producción** donde se recibirán las notificaciones.
```suggestion
2. A continuación, configura la **URL** de **producción** donde se recibirán las notificaciones.
```

2021-12-13 12:26 UTC, romisoto commented on guides/notifications/ipn.es.md
> +4. Si necesita identificar varias cuentas, al final de la URL indicada puede especificar el parámetro `?cliente=(nombredelvendedor) endpoint` para identificar a los vendedores.
```suggestion
4. Si necesitas identificar varias cuentas, al final de la URL indicada puedes especificar el parámetro `?cliente=(nombredelvendedor) endpoint` para identificar a los vendedores.
```

2021-12-13 12:27 UTC, romisoto commented on guides/notifications/ipn.es.md
> +5. Seleccione los ** eventos ** de los que recibirá notificaciones en formato `json` usando` HTTP POST` a la URL especificada anteriormente. Le notificamos de los eventos relacionados con sus pedidos
```suggestion
5. Selecciona los **eventos** de los que recibirás notificaciones en formato `json` usando `HTTP POST` a la URL especificada anteriormente. Te notificamos de los eventos relacionados con tus pedidos (`merchant_orders`), devoluciones de cargo recibidas (`chargebacks`), pagos recibidos (`payment`) o intentos de pago (`point_integration_ipn`).
```

2021-12-13 12:27 UTC, romisoto commented on guides/notifications/ipn.es.md
> +Es posible configurar el URL de notificación de forma más específica para cada pago utilizando el campo `notification_url`. Vea a continuación cómo hacer esto usando los SDK.
```suggestion
Es posible configurar la URL de notificación de forma más específica para cada pago utilizando el campo `notification_url`. Ve a continuación cómo hacer esto usando los SDK.
```

2021-12-13 12:28 UTC, romisoto commented on guides/notifications/ipn.es.md
> +1. En el campo `notification_url`, indique la URL desde la que se recibirán las notificaciones, como se muestra abajo.
```suggestion
1. En el campo `notification_url`, indica la URL desde la que se recibirán las notificaciones, como se muestra abajo.
```

2021-12-13 12:28 UTC, romisoto commented on guides/notifications/ipn.es.md
> +2. Implemente el receptor de notificaciones usando el siguiente código como ejemplo:
```suggestion
2. Implementa el receptor de notificaciones usando el siguiente código como ejemplo:
```

2021-12-13 12:29 UTC, romisoto commented on guides/notifications/ipn.es.md
> +Por ejemplo, si configura la URL: `https://www.yoursite.com/notifications`, recibirá notificaciones de pago como esta:` https://www.yoursite.com/notifications?topic=payment&id=123456789`.
```suggestion
Por ejemplo, si configuras la URL: `https://www.yoursite.com/notifications`, recibirás notificaciones de pago como esta:` https://www.yoursite.com/notifications?topic=payment&id=123456789`.
```

2021-12-13 12:29 UTC, romisoto commented on guides/notifications/ipn.es.md
> +4. Si desea recibir notificaciones solo de IPN y no de Webhooks, puede agregar en el `notification_url` el parámetro`source_news=ipn`. Por ejemplo: https://www.yourserver.com/notifications?source_new
```suggestion
4. Si deseas recibir notificaciones solo de IPN y no de Webhooks, puedes agregar en el `notification_url` el parámetro `source_news=ipn`. Por ejemplo: https://www.yourserver.com/notifications?source_news=ipn
```

2021-12-13 12:30 UTC, romisoto commented on guides/notifications/ipn.es.md
> +Después de devolver la notificación, obtendrá la información completa del recurso notificado yendo al punto final de la API correspondiente:
```suggestion
Después de devolver la notificación, obtendrás la información completa del recurso notificado yendo al punto final de la API correspondiente:
```

2021-12-13 12:30 UTC, romisoto commented on guides/notifications/webhooks.en.md
> +# Webhook
es webhook o webhooks?

2021-12-13 12:33 UTC, romisoto commented on guides/notifications/webhooks.en.md
> +1. First, an application must be created on the home page of your [Dashboard](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel).
es "webhook notifications" o "webhooks notifications"? esta de las dos formas en el mismo documento

2021-12-13 12:33 UTC, romisoto commented on guides/notifications/webhooks.en.md
> +2. With the application created, go to the Webhooks Notifications tab in your Dashboard and configure the [URLs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications) of **produ
es "webhook notifications" o "webhooks notifications"? esta de las dos formas en el mismo documento

2021-12-13 12:34 UTC, romisoto commented on guides/notifications/webhooks.en.md
> +3. También podrás experimentar y probar si la URL indicada está recibiendo notificaciones correctamente, pudiendo verificar la solicitud, la respuesta dada por el servidor y la descripción del evento
este texto está en español en el documento en inglés

2021-12-13 12:34 UTC, romisoto commented on guides/notifications/webhooks.en.md
> +It is possible to configure the notification url more specifically for each payment using the `notification_url` field. See below how to do this using the SDKs.
```suggestion
It is possible to configure the notification URL more specifically for each payment using the `notification_url` field. See below how to do this using the SDKs.
```

2021-12-13 12:35 UTC, romisoto commented on guides/notifications/webhooks.en.md
> +> For the event type point_integration_wh the notification format changes. [Click here](https://www.mercadopago[FAKER][URL][DOMÍNIO]/developers/en/guides/in-person-payments/mp-point/introduction) to
```suggestion
> For the event type `point_integration_wh` the notification format changes. [Click here](https://www.mercadopago[FAKER][URL][DOMÍNIO]/developers/en/guides/in-person-payments/mp-point/introduction) to consult the documentation of **Mercado Pago Point**.
```

2021-12-13 12:37 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +2. Con la aplicación creada, vaya a la pestaña Notificaciones de Webhooks en su Panel de control y configure las [URLs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications) de
```suggestion
2. Con la aplicación creada, ve a la pestaña Notificaciones de Webhooks en tu Panel de control y configura las [URLs](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/notifications) de **producción** y **prueba** de las que se recibirán notificaciones. 
```

2021-12-13 12:37 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +4. Si necesita identificar varias cuentas, al final de la URL indicada puede indicar el parámetro `?cliente=(nommbredelvendedor) endpoint` para identificar a los vendedores.
```suggestion
4. Si necesitas identificar varias cuentas, al final de la URL indicada puedes indicar el parámetro `?cliente=(nommbredelvendedor) endpoint` para identificar a los vendedores.
```

2021-12-13 12:38 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +5. A continuación, seleccione los **eventos** de los que recibirá notificaciones en formato `json` a través de un `HTTP POST` a la URL especificada anteriormente. Un evento es cualquier tipo de actua
```suggestion
5. A continuación, selecciona los **eventos** de los que recibirás notificaciones en formato `json` a través de un `HTTP POST` a la URL especificada anteriormente. Un evento es cualquier tipo de actualización del objeto informado, incluidos los cambios de estado o atributos. Vea los eventos que se pueden configurar en la siguiente tabla.
```

2021-12-13 12:38 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +Es posible configurar la URL de notificación de forma más específica para cada pago utilizando el campo `notification_url`. Vea a continuación cómo hacer esto usando los SDK.
```suggestion
Es posible configurar la URL de notificación de forma más específica para cada pago utilizando el campo `notification_url`. Ve a continuación cómo hacer esto usando los SDK.
```

2021-12-13 12:38 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +1. En el campo `notification_url`, indique la URL desde la que se recibirán las notificaciones, como se muestra a continuación.
```suggestion
1. En el campo `notification_url`, indica la URL desde la que se recibirán las notificaciones, como se muestra a continuación.
```

2021-12-13 12:39 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +> NOTE
```suggestion
> NOTA
```

2021-12-13 12:39 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +| **type** | Tipo de notificacion recebida (paymentes, merchant_order, subscription, preapproval, etc) |
```suggestion
| **type** | Tipo de notificacion recebida (payments, merchant_order, subscription, preapproval, etc) |
```

2021-12-13 12:40 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +| **action** | Tipo de notificación recebida, indicando si es la actualización de un pago o bien la creación de un pago nuevo |
```suggestion
| **action** | Tipo de notificación recibida, indicando si es la actualización de un pago o bien la creación de un pago nuevo |
```

2021-12-13 12:40 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +4. Si desea recibir notificaciones solo de Webhook y no de IPN, puede agregar en el `notification_url` el parámetro`source_news=webhook`. Por ejemplo: https://www.yourserver.com/notifications?source_
```suggestion
4. Si deseas recibir notificaciones solo de Webhook y no de IPN, puedes agregar en el `notification_url` el parámetro`source_news=webhook`. Por ejemplo: https://www.yourserver.com/notifications?source_news=webhook
```

2021-12-13 12:40 UTC, romisoto commented on guides/notifications/webhooks.es.md
> +Luego de devolver la notificación y confirmar su recepción, obtendrá la información completa del recurso notificado accediendo al punto final de la API correspondiente:
```suggestion
Luego de devolver la notificación y confirmar su recepción, obtendrás la información completa del recurso notificado accediendo al punto final de la API correspondiente:
```

2021-12-13 17:34 UTC, romisoto requested changes
Heitor! dejo algunas sugerencias. Muy buena documentación, muy tecnica!
Un detalle: en el scope veo que la siguiente documentación  tiene mal el indice/menu:

https://docs06.mercadopago.com.br/developers/es/guides/notifications/ipn-personal-payment 

https://docs06.mercadopago.com.br/developers/es/guides/notifications/ipn

(dice "nuevo item" en lugar de los nombres de los documentos)

2021-12-15 14:02 UTC, romisoto approved these changes

2021-12-16 18:20 UTC, lamaralmp requested changes

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +3. Você também poderá experimentar e testar se a URL indicada está recebendo as notificações corretamente, podendo verificar a solicitação, a resposta dada pelo servidor e a descrição do evento.
```suggestion
3. Você também poderá experimentar e testar se o URL indicado está recebendo as notificações corretamente, podendo verificar a solicitação, a resposta dada pelo servidor e a descrição do evento.
```

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +4. Caso seja necessário indentificar múltiplas contas, no final da URL indicada você poderá indicar o parâmetro `?cliente=(nomedovendedor) endpoint` para indentificar os vendedores.
```suggestion
4. Caso seja necessário identificar múltiplas contas, no final da URL indicada você poderá indicar o parâmetro `?cliente=(nomedovendedor) endpoint` para identificar os vendedores.
```

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +5. Selecione os **eventos** dos quais você receberá notificações em formato `json` utilizando `HTTP POST` para a URL especificada anteriormente. Notificamos eventos relacionados aos seus pedidos (`me
```suggestion
5. Selecione os **eventos** dos quais você receberá notificações em formato `json` utilizando `HTTP POST` para a URL especificada anteriormente. Notificamos eventos relacionados aos seus pedidos (`merchant_orders`), estornos recebidos (`chargebacks`), pagamentos recebidos (`payment`) ou tentativas de pagamento (`point_integration_ipn`).
```

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +1. No campo `notificaction_url`, indique a URL da qual serão recebidas as notificações como exemplificado abaixo.
```suggestion
1. No campo `notificaction_url`, indique o URL do qual serão recebidas as notificações como exemplificado abaixo.
```

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +    $payment->notification_url = `"http://requestbin.fullcontact.com/1ogudgk1"`;
```suggestion
    $payment->notification_url = 'http://requestbin.fullcontact.com/1ogudgk1';
```

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +       .setNotificationUrl: "http://requestbin.fullcontact.com/1ogudgk1";
```suggestion
       .setNotificationUrl("http://requestbin.fullcontact.com/1ogudgk1");
```

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn.pt.md
> +    "notification_url" =  "http://requestbin.fullcontact.com/1ogudgk1",
```suggestion
    "notification_url":  "http://requestbin.fullcontact.com/1ogudgk1",
```

2021-12-16 18:20 UTC, lamaralmp commented on guides/notifications/ipn-personal-payment.pt.md
> +Dentro da ordem, no objeto de payments, você encontrará todos os pagamentos realizados, seja ele aprovado ou rejeitado. É importante obter a ID dos pagamentos com status **approved** para poder reali
```suggestion
Dentro da ordem, no objeto de payments, você encontrará todos os pagamentos realizados, seja ele aprovado ou rejeitado. É importante obter o ID dos pagamentos com status **approved** para poder realizar estornos/devoluções.
```

2021-12-17 17:22 UTC, lamaralmp approved these changes

2021-12-17 19:08 UTC, merged