feature/api-integraciones-documentation
mercadopago/devsite-docs pull request #1417
Opened 2021-11-16 00:29 UTC by abderossi

## Description
Nueva documentación oculta de API de Integraciones.

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [x] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [x] Requires translations.

2021-12-28 17:04 UTC, romisoto commented on guides/in-person-payments/integration-api/create-payment-intent.es.md
> +Antes de crear una intención de pago, debes obtener los dispositivos Point asociados a tu cuenta. Pueden hacerlo de esta manera:
```suggestion
Antes de crear una intención de pago, debes obtener los dispositivos Point asociados a tu cuenta. Puedes hacerlo de esta manera:
```

2021-12-28 17:14 UTC, romisoto commented on guides/in-person-payments/integration-api/introduction.es.md
> +> Si quieres conocer más detalles acerca de la API de Integraciones y los pedidos de información que puedes hacer, ingresa a [Referencia de API](https://www.mercadopago.com.ar/developers/es/reference
esta url no deberia ser faker? no veo que el texto este localizado

2021-12-28 17:15 UTC, romisoto commented on guides/in-person-payments/integration-api/introduction.es.md
> +> Para realizar la integración, primero debes obtener las credenciales de identificación para tu integración.
sugerencia super opcional: no repetiría integración dos veces

2021-12-28 17:16 UTC, romisoto commented on guides/in-person-payments/integration-api/notifications.es.md
> +Una vez que hayas implementado las notificaciones y realizado los ajustes necesarios, estas tendrá el siguiente formato:
```suggestion
Una vez que hayas implementado las notificaciones y realizado los ajustes necesarios, estas tendrán el siguiente formato:
```

2021-12-28 17:22 UTC, romisoto commented on guides/in-person-payments/integration-api/point-simulator.es.md
> +Si realizaste los pasos de configuración de las [notificaciones Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/in-person-payments/integration-api/integration#bookmark_3._P
```suggestion
Si realizaste los pasos de configuración de las [notificaciones Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/in-person-payments/integration-api/integration#bookmark_3._Prepara_y_configura_tus_notificaciones_de_Webhook), es momento de que revises tus registros. Allí verás que fue enviada la notificación del estado de la transacción.
```

2021-12-28 17:22 UTC, romisoto requested changes
apenas muy poquitas sugerencias! hermosa documentación!

2021-12-28 22:24 UTC, rwaetemann commented on guides/in-person-payments/integration-api/integration.es.md
> +![Qr Point Scan](/images/mobile/point-qr-scan.png)
@abderossi - Gosti, não entendi o porquê dessa imagem aqui. Alguém pediu que tivesse por algum motivo?

2021-12-29 13:29 UTC, abderossi commented on guides/in-person-payments/integration-api/integration.es.md
> +![Qr Point Scan](/images/mobile/point-qr-scan.png)
```suggestion
```

2021-12-29 13:30 UTC, abderossi commented on guides/in-person-payments/integration-api/integration.es.md
> +![Qr Point Scan](/images/mobile/point-qr-scan.png)
La enviaron ellos pero coincido con vos Rods que no tiene sentido incluirla. La voy a excluir!

2021-12-29 13:30 UTC, abderossi commented on guides/in-person-payments/integration-api/introduction.es.md
> +> Si quieres conocer más detalles acerca de la API de Integraciones y los pedidos de información que puedes hacer, ingresa a [Referencia de API](https://www.mercadopago.com.ar/developers/es/reference
```suggestion
```

2021-12-29 13:31 UTC, abderossi commented on guides/in-person-payments/integration-api/introduction.es.md
> +> Para realizar la integración, primero debes obtener las credenciales de identificación para tu integración.
```suggestion
> Para realizar la integración, primero debes obtener las credenciales de identificación.
```

2021-12-29 14:36 UTC, romisoto approved these changes
aprobado!

2021-12-29 15:06 UTC, rwaetemann commented on guides/in-person-payments/integration-api/introduction.es.md
> +# Conoce la API de Integraciones
```suggestion
# API de Integraciones
```

2021-12-29 15:09 UTC, rwaetemann commented on guides/in-person-payments/integration-api/introduction.es.md
> +La API de Integraciones te permite conectar tus puntos de venta (PDV) al ecosistema Point para recibir pagos en las terminales que tengas configuradas y garantizar una experiencia de cobro unificada.
@abderossi - aqui, logo abaixo temos um diagrama, certo? Vale colocar nesse trecho inicial algo do tipo: No diagrama abaixo mostramos o detalhe do funcionamento da API. 

Ou algo do tipo, sabe?

2021-12-29 15:12 UTC, rwaetemann commented on guides/in-person-payments/integration-api/introduction.es.md
> +> Esta integración soporta los siguientes dispositivos:
```suggestion
> Esta integración soporta el dispositivo **Point Plus (POS)**. Para adquirirlo desde nuestra tienda oficial, . [haga clic aquí](https://www.mercadopago.com.ar/point).

```

2021-12-29 15:12 UTC, rwaetemann commented on guides/in-person-payments/integration-api/introduction.es.md
> +> - Point Plus (POS)
```suggestion

```

2021-12-29 15:12 UTC, rwaetemann commented on guides/in-person-payments/integration-api/introduction.es.md
> +> Puedes adquirir tu dispositivo Point desde nuestra [tienda oficial](https://www.mercadopago.com.ar/point)
```suggestion

```

2021-12-29 15:13 UTC, rwaetemann commented on guides/in-person-payments/integration-api/introduction.es.md
> +> Esta integración soporta los siguientes dispositivos:
@abderossi - acho que aqui podemos fazer igual a nota anterior, o que acha, Gosti?

2021-12-29 15:15 UTC, rwaetemann commented on guides/in-person-payments/integration-api/introduction.es.md
> +### Conoce sus ventajas
@abderossi - esse conteúdo é muito mais voltado para a parte comercial do que técnica, Gosti. A gente deixa essa parte mais "vendável" da solução para o marketing, hehe.

Eu acredito que as vantagens da API podem sair dessa doc. O que acha?

2021-12-29 19:39 UTC, merged