feature/new shopify hpsdk documentation
mercadopago/devsite-docs pull request #1439
Opened 2021-12-02 18:09 UTC by rwaetemann

## Description

A documentação de Shopify precisou ser reescrita/reestruturada pois o checkout foi reformulado. Agora, a integração passará a ser chamada de Shopify HPSDK, com novas features, UI e modos de instalação e configuração.

🔔🔔 Essa documentação será liberada somente no próximo Q, uma vez que o HPSDK ainda está em fase de desenvolvimento 🔔🔔

2021-12-02 18:15 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +1. [Click here](xhttps://apps.shopify.com/checkout-transparente) to access the Mercado Pago Checkout Api app installation page.
```suggestion
1. [Click here](https://apps.shopify.com/checkout-transparente) to access the Mercado Pago Checkout Api app installation page.
```

2021-12-02 18:18 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.en.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:18 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase.en.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase]
```

2021-12-02 18:19 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.en.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:20 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.en.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:20 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase.en.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase]
```

2021-12-02 18:21 UTC, rwaetemann commented on guides/plugins/official/shopify.en.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase.en.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase]
```

2021-12-02 18:22 UTC, rwaetemann commented on guides/plugins/official/shopify.es.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.es.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:22 UTC, rwaetemann commented on guides/plugins/official/shopify.es.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.es.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:23 UTC, rwaetemann commented on guides/plugins/official/shopify.es.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase.es.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase]
```

2021-12-02 18:24 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.pt.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:24 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase.pt.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase]
```

2021-12-02 18:24 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.pt.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:30 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config.pt.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-cpf-config]
```

2021-12-02 18:30 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase.pt.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase]
```

2021-12-02 18:30 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase.pt.md]
```suggestion
[TXTSNIPPET][/guides/snippets/test-integration/shopify-test-purchase]
```

2021-12-02 18:55 UTC, rwaetemann commented on guides/snippets/test-integration/shopify-test-purchase.pt.md
> +Insira um CEP para simular o frete e clique em **Continuar**.
```suggestion
3. Insira um CEP para simular o frete e clique em **Continuar**.
```

2021-12-02 18:55 UTC, rwaetemann commented on guides/snippets/test-integration/shopify-test-purchase.pt.md
> +3. Preencha os campos solicitados e selecione o Mercado Pago como meio de pagamento.
```suggestion
4. Preencha os campos solicitados e selecione o Mercado Pago como meio de pagamento.
```

2021-12-02 18:56 UTC, rwaetemann commented on guides/snippets/test-integration/shopify-test-purchase.pt.md
> +4. Clique em **Finalizar compra**.
```suggestion
5. Clique em **Finalizar compra**.
```

2021-12-06 17:51 UTC, omegafl approved these changes

2021-12-20 19:18 UTC, hgaldino requested changes

2021-12-20 19:18 UTC, hgaldino commented on guides/plugins/official/shopify.pt.md
> +2. Em **Provedore de pagamento** clique em **Escolher provedor**.
```suggestion
2. Em **Provedor de pagamento** clique em **Escolher provedor**.
```

2021-12-20 19:18 UTC, hgaldino commented on guides/plugins/official/shopify.pt.md
> +2. Em **Provedore de pagamento** clique em **Escolher provedor**.
```suggestion
2. Em **Provedor de pagamento** clique em **Escolher provedor**.
```

2021-12-22 12:30 UTC, rwaetemann commented on guides/plugins/official/shopify.pt.md
> +## Teste de compras
```suggestion
### Teste de compras
```

2022-02-24 21:09 UTC, hgaldino approved these changes

2022-03-02 13:38 UTC, merged