fix/Refunds and Cancellations doc update
mercadopago/devsite-docs pull request #1457
Opened 2021-12-10 17:35 UTC by rwaetemann

## Description

A documentação de Devoluções e Cancelamentos precisou ser reescrita e reestruturada devido ao novo atributo (X-Idempotency-Key) que foi inserido no Curl das APIs de devolução integral/parcial.

Além das alterações nos conteúdos e estruturas da documentação, todas as APIs que antes estavam na doc do DevSite estão em processo de documentação na referência. Por este motivo, os links ainda não constam nesse PR, mas assim que tivermos essas docs finalizadas, faremos as devidas inclusões neste PR antes de fazermos o merge e lançarmos para produção.

2021-12-10 18:36 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +To make full or partial refunds of a payment and check the refunds made in your store, visit our Api Reference and access the full and partial refunds Apis by clicking on the links below.
```suggestion
To make full or partial refunds of a payment and check the refunds made in your store, visit our API Reference and access the full and partial refunds Apis by clicking on the links below.
```

2021-12-10 18:37 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Para realizar devoluciones totales o parciales de un pago y verificar las devoluciones realizadas en su tienda, visite nuestra Referencia Api y acceda a las Apis de devolución total y parcial haciend
```suggestion
Para realizar devoluciones totales o parciales de un pago y verificar las devoluciones realizadas en su tienda, visite nuestra Referencia API y acceda a las APIs de devolución total y parcial haciendo clic en los links a continuación.
```

2021-12-10 18:38 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Para realizar devoluções integrais ou parciais de um pagamento e consultar as devoluções feitas em sua loja, visite nossa Referência Api e acesse as Apis de Devolução integral e parcial clicando nos
```suggestion
Para realizar devoluções integrais ou parciais de um pagamento e consultar as devoluções feitas em sua loja, visite nossa Referência API e acesse as APIs de Devolução integral e parcial clicando nos links abaixo.
```

2021-12-10 21:06 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +En esta documentación encontrarás la información necesaria para realizar una devolución total, parcial y cancelar una compra en tu tienda.
```suggestion
En esta documentación, encontrará las instrucciones y los links de las APIs necesarias para realizar una devolución total, parcial y cancelar una compra en tu tienda.
```

2021-12-13 12:47 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +**Refunds** are transactions made when a certain charge is reversed and the amounts paid are returned to the buyer. This means that the customer will receive back on their account or credit card stat
```suggestion
**Refunds** are transactions made when a certain charge is reversed and the amounts paid are returned to the buyer. This means that the customer will receive back the amount paid for the purchase of a certain product or service. on their account or credit card statement
```

2021-12-13 12:55 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +- **Boleto bancário**: If the expiry date of a boleto bancário expires, the user can generate it again by entering the transaction ID of his Mercado Pago account. However, if you want to avoid stock
```suggestion
- **Boleto bancário**: If the expiry date of a boleto bancário expires, the user can generate it again by entering the transaction ID of their Mercado Pago account. However, if you want to avoid stock retention problems, for example, you can choose not to make a new issue of this slip available. To do this, simply cancel it.
```

2021-12-13 12:58 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +To make full or partial refunds of a payment and check the refunds made in your store, visit our API Reference and access the full and partial refunds Apis by clicking on the links below.
```suggestion
To make full or partial refunds of a payment and check the refunds made in your store, visit our API Reference and access the full and partial refunds APIs by clicking on the links below.
```

2021-12-13 12:59 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +En esta documentación, encontrará las instrucciones y los links de las APIs necesarias para realizar una devolución total, parcial y cancelar una compra en tu tienda.
```suggestion
En esta documentación, encontrarás las instrucciones y los links de las APIs necesarias para realizar una devolución total, parcial y cancelar una compra en tu tienda.
```

2021-12-13 12:59 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +> Al ejecutar las API a las que se hace referencia en esta documentación, es posible que encuentre el atributo **X-Idempotency-Key**. Su finalización es importante para asegurar la ejecución y re-eje
```suggestion
> Al ejecutar las API a las que se hace referencia en esta documentación, es posible que encuentres el atributo **X-Idempotency-Key**. Su finalización es importante para asegurar la ejecución y re-ejecución de solicitudes sin efectos secundarios como pagos duplicados en casos de reversión.
```

2021-12-13 13:01 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +- **Status de pago**: Cancelaciones solo se pueden realizar si el estado de pago es Pending o In process. Estos status se muestran en la respuesta a la llamada de la API de cancelación en los campos
```suggestion
- **Status de pago**: Cancelaciones solo se pueden realizar si el estado de pago es Pending o In process. Estos estados se muestran en la respuesta a la llamada de la API de cancelación en los campos de, *Status* y *Status detail* respectivamente.
```

2021-12-13 13:08 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Para realizar devoluciones totales o parciales de un pago y verificar las devoluciones realizadas en su tienda, visite nuestra Referencia API y acceda a las APIs de devolución total y parcial haciend
```suggestion
Para realizar devoluciones totales o parciales de un pago y verificar las devoluciones realizadas en tu tienda, visita nuestra Referencia API y accede a las APIs de devolución total y parcial haciendo clic en los links a continuación.
```

2021-12-13 13:14 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +- **Boleto bancário**: Si expira el período de vigencia de un boleto bancário, el usuario puede volver a generarlo ingresando el ID de transacción de su cuenta de Mercado Pago. Sin embargo, si desea
"Boleto bancario" deberia estas visible para otros paises que no sean Brasil??

2021-12-13 13:15 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Para realizar devoluciones totales o parciales de un pago y verificar las devoluciones realizadas en su tienda, visite nuestra Referencia API y acceda a las APIs de devolución total y parcial haciend
sugiero agregar aquí un link a API ref

2021-12-13 19:45 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Para realizar devoluciones totales o parciales de un pago y verificar las devoluciones realizadas en su tienda, visite nuestra Referencia API y acceda a las APIs de devolución total y parcial haciend
Romi, assim que publicarmos as APIs na referência, vamos inserir os links :)

2021-12-15 12:46 UTC, hgaldino requested changes

2021-12-15 12:46 UTC, hgaldino commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Considerando as informações acima, visite nossa Referência API para ter acesso à API de cancelamento.
Amiga, aqui não seria legal linkar a páginas das referências?

2021-12-15 12:46 UTC, hgaldino commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Apesar de serem transações similares, é importante ter em mente que o cancelamento é feito no mesmo dia da captura do pagamento, devolvendo o limite ao cartão do comprador dentro do período definido
```suggestion
Apesar de serem transações similares, é importante ter em mente que o cancelamento é feito no mesmo dia da captura do pagamento, devolvendo o limite ao cartão do comprador dentro do período definido pelo banco emissor. Já a devolução é feita diretamente na fatura do cartão de crédito ou na conta corrente em casos de pagamento via Pix, boleto ou débito.
```

2021-12-15 12:46 UTC, hgaldino commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Nesta documentação, você encontra as instruções e os links das APIs necessárias para realizar uma devolução integral, parcial, e cancelar uma compra em sua loja.
Amiga, fiquei em dúvida sobre essa última vírgula depois de "parcial"...o que vc acha? Realmente fiquei pensativo se existe ou não.

2021-12-15 20:50 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
>  # Devoluções e cancelamentos
```suggestion
# Reembolsos e cancelamentos
```

2021-12-15 20:50 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +**Devoluções** são transações realizadas quando determinada cobrança é revertida e os valores pagos retornam para o comprador. Isso significa que o cliente receberá de volta em sua conta ou na fatura
```suggestion
**Reembolsos** são transações realizadas quando determinada cobrança é revertida e os valores pagos retornam para o comprador. Isso significa que o cliente receberá de volta em sua conta ou na fatura do cartão de crédito, o valor pago na aquisição de determinado produto ou serviço.
```

2021-12-15 20:51 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Apesar de serem transações similares, é importante ter em mente que o cancelamento é feito no mesmo dia da captura do pagamento, devolvendo o limite ao cartão do comprador dentro do período definido
```suggestion
Apesar de serem transações similares, é importante ter em mente que o cancelamento é feito no mesmo dia da captura do pagamento, devolvendo o limite ao cartão do comprador dentro do período definido pelo banco emissor. Já o reembolso é feito diretamente na fatura do cartão de crédito, ou na conta corrente em casos de pagamento via Pix, boleto ou débito.
```

2021-12-15 20:51 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
>  ## Devoluções
```suggestion
## Reembolsos
```

2021-12-15 20:52 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Devoluções podem ser feitas de duas maneiras: **integral**, quando o valor total da venda é devolvido ao comprador ou **parcial**, quando apenas parte do valor pago é retornado ao comprador.
```suggestion
Reembolsos podem ser feitos de duas maneiras: **integral**, quando o valor total da venda é devolvido ao comprador ou **parcial**, quando apenas parte do valor pago é retornado ao comprador.
```

2021-12-15 20:52 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Antes de realizar uma devolução, é importante considerar os fatores abaixo.
```suggestion
Antes de realizar um reembolso, é importante considerar os fatores abaixo.
```

2021-12-15 20:52 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +* **Prazo de devolução:** é possível devolver um pagamento dentro de 180 dias a partir da sua data de aprovação.
```suggestion
* **Prazo de reembolso:** é possível reembolsar um pagamento dentro de 180 dias a partir da sua data de aprovação.
```

2021-12-15 20:53 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Para realizar devoluções integrais ou parciais de um pagamento e consultar as devoluções feitas em sua loja, visite nossa Referência API e acesse as APIs de Devolução integral e parcial clicando nos
```suggestion
Para realizar reembolsos integrais ou parciais de um pagamento e consultar os reembolsos feitos em sua loja, visite nossa Referência API e acesse as APIs de Reembolso integral e parcial clicando nos links abaixo.
```

2021-12-15 20:53 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +- Devolução integral e parcial
```suggestion
- Reembolsos integrais e parciais
```

2021-12-15 20:53 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +- Consultar Devoluções
```suggestion
- Consultar reembolsos
```

2021-12-15 20:57 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Apesar de serem transações similares, é importante ter em mente que o cancelamento é feito no mesmo dia da captura do pagamento, devolvendo o limite ao cartão do comprador dentro do período definido
```suggestion
Apesar de serem transações similares, é importante ter em mente que o cancelamento é feito no mesmo dia da captura do pagamento, devolvendo o limite ao cartão do comprador dentro do período definido pelo banco emissor. Já o reembolso é feito diretamente na fatura do cartão de crédito ou na conta corrente em casos de pagamento via Pix, boleto ou débito.
```

2021-12-15 20:57 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Nesta documentação, você encontra as instruções e os links das APIs necessárias para realizar uma devolução integral, parcial, e cancelar uma compra em sua loja.
```suggestion
Nesta documentação, você encontra as instruções e os links das APIs necessárias para realizar uma reembolso integral, parcial, e cancelar uma compra em sua loja.
```

2021-12-15 20:59 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +> Ao executar as APIs citadas nesta documentação, você poderá encontrar o atributo **X-Idempotency-Key**. Seu preenchimento é importante para garantir a execução e re-execução de requisições sem que
```suggestion
> Ao executar as APIs citadas nesta documentação, você poderá encontrar o atributo **X-Idempotency-Key**. Seu preenchimento é importante para garantir a execução e re-execução de requisições sem que haja efeitos colaterais como por exemplo, pagamentos em duplicidade em casos de reembolso.
```

2021-12-16 16:20 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
>  # Devoluciones y cancelaciones
```suggestion
# Reembolsos y cancelaciones
```

2021-12-16 16:20 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +**Devoluciones** son transacciones que se realizan cuando un determinado cargo se revierte y las cantidades pagadas se devuelven al comprador. Esto significa que el cliente recibirá en su cuenta o en
```suggestion
**Reembolsos** son transacciones que se realizan cuando un determinado cargo se revierte y las cantidades pagadas se devuelven al comprador. Esto significa que el cliente recibirá en su cuenta o en el extracto de su tarjeta de crédito el monto pagado por la compra de un determinado producto o servicio.
```

2021-12-16 16:21 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Si bien son transacciones similares, es importante tener en cuenta que la cancelación se realiza el mismo día en que se captura el pago, devolviendo el límite a la tarjeta del comprador dentro del pl
```suggestion
Si bien son transacciones similares, es importante tener en cuenta que la cancelación se realiza el mismo día en que se captura el pago, devolviendo el límite a la tarjeta del comprador dentro del plazo definido por el banco emisor. El reembolso referente a la reversión se realiza directamente en la factura de la tarjeta de crédito, o en la cuenta corriente en los casos de pago vía Pix, boleto bancário o débito.
```

2021-12-16 16:21 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +En esta documentación, encontrarás las instrucciones y los links de las APIs necesarias para realizar una devolución total, parcial y cancelar una compra en tu tienda.
```suggestion
En esta documentación, encontrarás las instrucciones y los links de las APIs necesarias para realizar un reembolso total, parcial y cancelar una compra en tu tienda.
```

2021-12-16 16:22 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +> Al ejecutar las API a las que se hace referencia en esta documentación, es posible que encuentres el atributo **X-Idempotency-Key**. Completarlo es importante para asegurar la ejecución y re-ejecuc
```suggestion
> Al ejecutar las API a las que se hace referencia en esta documentación, es posible que encuentres el atributo **X-Idempotency-Key**. Completarlo es importante para asegurar la ejecución y re-ejecución de solicitudes sin efectos secundarios como pagos duplicados en casos de reembolso.
```

2021-12-16 16:23 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Teniendo en cuenta la información anterior, haz clic aquí y visita nuestra Referencia de API para acceder a la API de cancelación.
falta agregar el link, no?

2021-12-16 16:24 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Las devoluciones se pueden realizar de dos formas: **total**, cuando el monto total de la venta se devuelve al comprador, o **parcial**, cuando solo se devuelve al comprador una parte del monto pagad
```suggestion
Los reembolsos se pueden realizar de dos formas: **total**, cuando el monto total de la venta se devuelve al comprador, o **parcial**, cuando solo se devuelve al comprador una parte del monto pagado.
```

2021-12-16 16:24 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Antes de realizar una devolución, es importante considerar los siguientes factores.
```suggestion
Antes de realizar un reembolso, es importante considerar los siguientes factores.
```

2021-12-16 16:24 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +- **Fecha límite de devolución:** es posible devolver un pago dentro de los 180 días posteriores a la fecha de aprobación.
```suggestion
- **Fecha límite de reembolso:** es posible devolver un pago dentro de los 180 días posteriores a la fecha de aprobación.
```

2021-12-16 16:25 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Para realizar devoluciones totales o parciales de un pago y verificar las devoluciones realizadas en tu tienda, visita nuestra Referencia API y accede a las APIs de devolución total y parcial haciend
```suggestion
Para realizar reembolsos totales o parciales de un pago y verificar los reembolsos realizados en tu tienda, visita nuestra Referencia API y accede a las APIs de devolución total y parcial haciendo clic en los links a continuación.
```

2021-12-16 16:25 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +- Ver devoluciones
```suggestion
- Ver reembolsos
```

2021-12-16 16:25 UTC, romisoto commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +- Devolución total y parcial
```suggestion
- Reembolso total y parcial
```

2021-12-16 17:07 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +Teniendo en cuenta la información anterior, haz clic aquí y visita nuestra Referencia de API para acceder a la API de cancelación.
Siii, Romi! Aún no tenemos porque no publicamos las apis, pero pronto estará listo e agregaremos el link.

2021-12-16 17:09 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +Considerando as informações acima, visite nossa Referência API para ter acesso à API de cancelamento.
Sim sim, amiga! Assim que tivermos as APIs publicadas, vamos colocar os links aqui :)

2021-12-16 17:53 UTC, romisoto approved these changes

2021-12-16 18:13 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.en.md
> +- **Boleto bancário**: If the expiry date of a boleto bancário expires, the user can generate it again by entering the transaction ID of their Mercado Pago account. However, if you want to avoid stoc
```suggestion
----[mlb]----
- **Boleto bancário**: If the expiry date of a boleto bancário expires, the user can generate it again by entering the transaction ID of their Mercado Pago account. However, if you want to avoid stock retention problems, for example, you can choose not to make a new issue of this slip available. To do this, simply cancel it.

------------
```

2021-12-16 18:14 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.es.md
> +- **Boleto bancário**: Si expira el período de vigencia de un boleto bancário, el usuario puede volver a generarlo ingresando el ID de transacción de su cuenta de Mercado Pago. Sin embargo, si deseas
```suggestion
----[mlb]----
- **Boleto bancário**: Si expira el período de vigencia de un boleto bancário, el usuario puede volver a generarlo ingresando el ID de transacción de su cuenta de Mercado Pago. Sin embargo, si deseas evitar problemas de retención de inventario, por ejemplo, puedes optar por no hacer disponible una nueva emisión de este boleto. Para hacer esto, simplemente cancélalo.

------------
```

2021-12-16 18:15 UTC, rwaetemann commented on guides/manage-account/account/cancellations-and-refunds.pt.md
> +- **Boleto bancário**: Se o prazo de validade de um boleto expirar, o usuário poderá gerá-lo novamente inserindo o ID da transação da sua conta no Mercado Pago. Contudo, caso queira evitar problemas
```suggestion

----[mlb]----
- **Boleto bancário**: Se o prazo de validade de um boleto expirar, o usuário poderá gerá-lo novamente inserindo o ID da transação da sua conta no Mercado Pago. Contudo, caso queira evitar problemas de retenção de estoque, por exemplo, é possível optar por não disponibilizar uma nova emissão deste boleto. Para isso, basta realizar seu cancelamento.

------------
```

2021-12-17 16:26 UTC, hgaldino approved these changes

2021-12-17 16:26 UTC, merged