Nueva documentación oculta de Fields/Secure inputs
mercadopago/devsite-docs pull request #1458
Opened 2021-12-10 19:27 UTC by romisoto

## Description
Se actualiza la documentación de Checkout API: pago con tarjeta & core methods, y la documentación de PCI. En ambos casos es para incluir los cambios introducidos por Fields/Secure Inputs.
La documentación estará oculta hasta que fields salga de beta.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [√ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [√ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2021-12-21 15:15 UTC, rwaetemann commented on guides/snippets/test-integration/api-response-handling.en.md
> +This will prevent rejections and chargebacks in the case of already approved transactions.  For example, this allows you to correct data upload mistakes or change payment methods.
```suggestion
This will prevent rejections and chargebacks in case of already approved transactions.  For example, this allows you to correct data upload mistakes or change payment methods.
```

2021-12-21 15:21 UTC, rwaetemann commented on guides/security/pci-v2.en.md
> +As a Service Provider, we must meet regulatory and security responsibilities vis-à-vis card brands and acquirers, but even so, security throughout the payment process is the obligation of both partie
@romisoto - Romi, apesar de eu ter AMAAAAADO o "vis-à-vis", não entendi como se aplica aqui kkkk.

2021-12-21 17:19 UTC, rwaetemann approved these changes

2021-12-21 17:30 UTC, romisoto commented on guides/security/pci-v2.en.md
> +As a Service Provider, we must meet regulatory and security responsibilities vis-à-vis card brands and acquirers, but even so, security throughout the payment process is the obligation of both partie
la verdad yo tampoco, pero fue un término usado por los stakeholders,  lo cambio por face to face?

2021-12-21 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Tanto para el frontend como para el backend, recomendamos utilizar [nuestras librerías](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/previous-requirem
```suggestion
Tanto para el frontend como para el backend, te recomendamos utilizar [nuestras librerías](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/previous-requirements#bookmark_utiliza_nuestras_librerías_siempre) para poder recolectar los datos sensibles de tus usuarios de manera segura.
```

2021-12-21 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Tanto para el frontend como para el backend, recomendamos utilizar [nuestras librerías](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/previous-requirem
Sugerencia opcional!

2021-12-21 19:22 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Para crear un pago es necesario hacer la captura de los datos de la tarjeta a través del navegador del comprador. Por cuestiones de seguridad, **es muy importante que los datos sensibles de la tarjet
```suggestion
Para crear un pago es necesario hacer la captura de los datos de la tarjeta a través del navegador del comprador. Por cuestiones de seguridad, **es muy importante que los datos sensibles de la tarjeta nunca lleguen a tus servidores**.
```

2021-12-21 19:24 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +> Los campos seguros son `divs` porque los verdaderos inputs estarán dentro del iframe de manera segura.
No entendí esta oración porque es muy técnica, pero quizás está ok que sea así y cualquier dev lo entiende 🤔. Acerco mi observación por las dudas de que no sea el caso.

2021-12-21 19:53 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Encontre o estado do pagamento no campo _status_.
Esto está ok en portugués?

2021-12-21 19:53 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Encontre o estado do pagamento no campo _status_.
Misma duda que arriba!

2021-12-21 19:54 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Encontre o estado do pagamento no campo _status_.
Repito duda

2021-12-21 19:54 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Encontre o estado do pagamento no campo _status_.
Ya no se como decir "repito duda" sin decir "repito duda"

2021-12-21 19:54 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Encontre o estado do pagamento no campo _status_.
:)

2021-12-21 20:08 UTC, abderossi commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.es.md
> +Al realizar el submit del formulario, generamos un token como una representación segura de los datos de la tarjeta. Podrás a acceder a este token utilizando la función `getCardFormData`, como mostram
Decimos "submit del formulario" en lugar de envío/registro por algo en particular?

2021-12-21 20:09 UTC, romisoto commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +> Los campos seguros son `divs` porque los verdaderos inputs estarán dentro del iframe de manera segura.
explica el tipo de campos (se cambio de otro tipo a divs porque fields permite mayor seguridad)

2021-12-21 20:10 UTC, abderossi commented on guides/security/pci-v2.en.md
> +As a Service Provider, we must meet regulatory and security responsibilities vis-à-vis card brands and acquirers, but even so, security throughout the payment process is the obligation of both partie
No sería más un "regarding to"?

2021-12-21 20:11 UTC, romisoto commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
> +Encontre o estado do pagamento no campo _status_.
Encuentra el estado del pago en el campo _status_.
```

2021-12-21 20:13 UTC, abderossi commented on guides/security/pci-v2.es.md
> +Para poder ser PCI DSS compliance, demostrar tu cumplimiento y a su vez, asegurar los datos de tarjeta de tus clientes, es importante que utilices este tipo de integraciones para asegurar que los dat
Uno es PCI DSS compliance o **compliant**?

2021-12-21 20:13 UTC, abderossi commented on guides/snippets/test-integration/api-payment-notifications.es.md
> +[Configura notificaciones webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/notifications/webhooks) o [notificaciones IPN](https://www.mercadopago[FAKER][URL][DOMAIN]/develop
```suggestion
[Configura las notificaciones webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/notifications/webhooks) o [notificaciones IPN](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/notifications/ipn).
```

2021-12-21 20:15 UTC, abderossi reviewed
Dejé sugerencias y un ajuste de un typo

2021-12-21 20:19 UTC, romisoto commented on guides/security/pci-v2.es.md
> +Para poder ser PCI DSS compliance, demostrar tu cumplimiento y a su vez, asegurar los datos de tarjeta de tus clientes, es importante que utilices este tipo de integraciones para asegurar que los dat
le pregunto a los stakeholders

2021-12-22 01:50 UTC, hgaldino requested changes

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Para capturar os dados do cartão, primeiro deve oferecer um formulário para carregar toda a informação.
```suggestion
Para capturar os dados do cartão, primeiro você deve oferecer um formulário para carregar toda a informação.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Com a **funcionalidade CardForm da biblioteca MercadoPago.js V2**, pode obter e validar todos os dados necessários, como identificar o tipo e nome do meio de pagamento, o banco emissor, o número de p
```suggestion
Com a **funcionalidade CardForm da biblioteca MercadoPago.js V2**, você pode obter e validar todos os dados necessários, como identificar o tipo e o nome do meio de pagamento, o banco emissor, o número de prestações e mais.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +CardForm permite você ter uma implementação segura e uma correta tokenização da informação do cartão.
```suggestion
CardForm permite que você tenha uma implementação segura e uma correta tokenização da informação do cartão.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Referencia técnica
```suggestion
> Referência técnica
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Procure informações acerca dos distintos atributos nas [referências técnicas](https://github.com/mercadopago/sdk-js).
```suggestion
> Procure mais informações sobre os diferentes atributos nas [referências técnicas](https://github.com/mercadopago/sdk-js).
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +
```suggestion
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Para que o IFrame seja renderizado, é necessário passar a opção `iframe` com valor `true` no objeto de parâmetro recebido pelo cardForm. Também é possível passar o `style` para os elementos.
```suggestion
Para que o IFrame seja renderizado, é necessário passar a opção `iframe` com valor `true` no objeto de parâmetro recebido pelo cardForm. Além disso, também é possível passar o `style` para os elementos.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Agora, para inicializar o CardForm, deve relacionar a ID de cada campo do formulário com os atributos correspondentes. A biblioteca será responsável pelo preenchimento, obtenção e validação de todos
```suggestion
Para inicializar o CardForm, deve-se relacionar o ID de cada campo do formulário com os atributos correspondentes. A biblioteca será responsável pelo preenchimento, obtenção e validação de todos os dados necessários na hora de confirmar o pagamento.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +       if (error) return console.log('Callback para tratar o erro: montando o cardForm ', error)
Romi o texto entre parênteses é em PT mesmo? Pergunto isso porque em algumas vezes traduzi coisas de Notifications no google e ele também traduziu o que não precisava KKKKKKKKK

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Obtenha mais informações acerca dos callbacks nas [referências técnicas](https://github.com/mercadopago/sdk-js).
```suggestion
> Obtenha mais informações sobre os callbacks nas [referências técnicas](https://github.com/mercadopago/sdk-js).
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Referencia técnica
```suggestion
> Referência técnica
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Ao enviar o formulário, geramos um token como uma representação segura dos dados do cartão. Você pode acessar este token usando a função `getCardFormData`, como mostramos no exemplo anterior no callb
```suggestion
Ao enviar o formulário, geramos um token como uma representação segura dos dados do cartão. Você pode acessar este token usando a função `getCardFormData`, como mostramos anteriormente no callback `onSubmit`. Também armazenaremos o token em um `input` oculto dentro do seu formulário e o chamaremos de `MPHiddenInputToken`.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Tenha em conta que o token tem uma validade de 7 dias e só pode ser usado uma única vez.
```suggestion
> Tenha em conta que o token tem validade de 7 dias e só pode ser utilizado uma única vez.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Segundo o exemplo, seu backend deveria disponibilizar um endpoint `/process_payment`, para receber ali todos os dados depois de realizar a ação submit.
```suggestion
Segundo o exemplo, seu backend deveria disponibilizar um endpoint `/process_payment` para receber todos os dados depois de realizar a ação submit.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Já estando no seu backend com toda a informação coletada, é o momento de enviar a solicitação ao Mercado Pago através das nossas APIs. Os campos mínimos requeridos para enviar são: `token`, `transact
```suggestion
Estando no seu backend com toda a informação coletada, é o momento de enviar a solicitação ao Mercado Pago através das nossas APIs. Os campos mínimos requeridos para enviar são: `token`, `transaction_amount`, `installments`, `payment_method_id` e o `payer.email`.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +Tenha em conta que para que esse passo funcione é necessário que configure sua [chave privada]([FAKER][CREDENTIALS][URL]) e que para interagir com nossas APIs recomendamos utilizar o [SDK oficial do
```suggestion
Tenha em conta que para que esse passo funcione é necessário que configure sua [chave privada]([FAKER][CREDENTIALS][URL]) e que, para interagir com nossas APIs, recomendamos utilizar o [SDK oficial do Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/previous-requirements#bookmark__instale_o_sdk_do_mercado_pago).
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Se você deseja implementar seu servidor com alguma outra tecnologia, te deixamos um [exemplo completo do formulário de pagamento](https://github.com/mercadopago/card-payment-sample) no GitHub para
```suggestion
> Se você deseja implementar seu servidor com alguma outra tecnologia, te deixamos um [exemplo completo do formulário de pagamento](https://github.com/mercadopago/card-payment-sample) no GitHub para que possa fazer o download.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Disponibilizamos [exemplos completos de integração](https://drive.google.com/file/d/12gSCPLfZCE36iKFbM4BTUwf6lnM7lVEL/view?usp=sharing) para que você possa fazer o download imediatamente.
```suggestion
> Disponibilizamos [exemplos completos de integração](https://drive.google.com/file/d/12gSCPLfZCE36iKFbM4BTUwf6lnM7lVEL/view?usp=sharing) para que você possa fazer o download.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Disponibilizamos [exemplos completos de integração](https://drive.google.com/file/d/12gSCPLfZCE36iKFbM4BTUwf6lnM7lVEL/view?usp=sharing) para que você possa fazer o download imediatamente.
```suggestion
> Disponibilizamos [exemplos completos de integração](https://drive.google.com/file/d/12gSCPLfZCE36iKFbM4BTUwf6lnM7lVEL/view?usp=sharing) para que você possa fazer o download.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Encontre toda informação necessária para interagir com nossas APIs.
```suggestion
> Encontre toda a informação necessária para interagir com nossas APIs.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Conheça todas as opções de pagamentos disponíveis e como oferecê-las.
```suggestion
> Conheça todas as opções de pagamentos disponíveis e veja como oferecê-las.
```

2021-12-22 01:50 UTC, hgaldino commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +> Revise que esteja tudo bem com sua integração com os usuários de teste.
```suggestion
> Confirme que está tudo bem com a sua integração e com os usuários de teste.
```

2021-12-22 12:11 UTC, romisoto commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.pt.md
> +## Como funciona?
gracias! lo mudo

2021-12-22 12:12 UTC, romisoto commented on guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.pt.md
> +> Obtenha mais informações nas [Referências de API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference).
lo paso a formato nota!

2021-12-22 12:15 UTC, romisoto commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +## Como funciona?
lo cambio!

2021-12-22 12:17 UTC, romisoto commented on guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
> +       if (error) return console.log('Callback para tratar o erro: montando o cardForm ', error)
son comments en el código, el equipo es de BR y lo escribió asi, no están traducidos los snippets hahaha

2021-12-22 13:15 UTC, abderossi approved these changes

2021-12-22 14:31 UTC, hgaldino approved these changes

2021-12-22 14:40 UTC, merged