[ADD] Include content related to interop impl to add new columns in settlement-report.
mercadopago/devsite-docs pull request #1481
Opened 2022-01-04 17:39 UTC by ccamargov-meli

## Description
Includes description related to the implementation of **Interop** columns for **balance reports** (Settlement Report). Sections affected (For `guides/manage-account/account-money`):

- Glossary: Include description of new columns.
- Generation: Include alert message to notify new features.
- Changelog: Changelog record.

> The columns `POI_WALLET_NAME` y `POI_BANK_NAME` allow businesses that charge with a Mercado Pago QR code to identify from which digital wallets or banks their payments came from.
> 
> Both of them are the last columns of the report, which is why no conflict is generated by reference position (Column Number) or column mapping by keys (Header).
> 
> By default, these columns are disabled. To display them in the **"All Transactions"** report it is necessary to update the settings preferences from the dashboard or via API.
> 
> Go to settings [from the panel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) o [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/account-money/api).

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [X] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [X] Contribution includes new features. 
- [X] New features were communicated in changelog.
- [X] Requires translations.

2022-01-04 19:35 UTC, romisoto commented on guides/manage-account/reports/account-money/generate.en.md
> +> CWe have created new columns that allow you to identify which digital wallets or banks your clients use when they pay with a Mercado Pago QR Code. Update your settings preferences [from the panel](
```suggestion
> We have created new columns that allow you to identify which digital wallets or banks your clients use when they pay with a Mercado Pago QR Code. Update your settings preferences [from the panel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) o [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/account-money/api) so that you can include these columns in your reports. 
```

2022-01-04 19:37 UTC, romisoto commented on guides/manage-account/reports/account-money/generate.es.md
> +> Creamos nuevas columnas que te permiten identificar las billeteras virtuales o los bancos que tus clientes usan para pagar cuando les ----[mla]----cobrás------------ ----[mlu, mpe, mlm, mco, mlc, m
veo que hicieron localización MLA para el texto de la guía, pero en ninguna parte de la documentación hacemos eso, solo texto en español neutro para hispanos y PT para Brasil. Localizamos en español argentino para emails etc, pero no recuerdo haberlo visto en las guias, que piensas @hgaldino ?

2022-01-04 19:38 UTC, romisoto commented on guides/manage-account/reports/account-money/glossary.en.md
> +| POI_WALLET_NAME | Name of the digital wallet from which a virtual payment comes from. Allows you to identify the origin of a transaction when you charge with a Mercado Pago QR Code.|
```suggestion
| POI_WALLET_NAME | Name of the digital wallet that a virtual payment comes from. Allows you to identify the origin of a transaction when you charge with a Mercado Pago QR Code.|
```

2022-01-04 19:38 UTC, romisoto commented on guides/manage-account/reports/account-money/glossary.en.md
> +| POI_BANK_NAME | Name of the bank from which a virtual payment comes from. Allows you to identify the origin of a transaction when you charge with a Mercado Pago QR Code.|
```suggestion
| POI_BANK_NAME | Name of the bank that a virtual payment comes from. Allows you to identify the origin of a transaction when you charge with a Mercado Pago QR Code.|
```

2022-01-04 19:39 UTC, romisoto commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_WALLET_NAME | Nombre de la billetera virtual desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](
@hgaldino la misma pregunta que en mi comentario anterior sobre localizar texto en español rioplatense dentro de las guias

2022-01-04 19:39 UTC, romisoto commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_BANK_NAME | Nombre de la entidad bancaria desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](htt
@hgaldino la misma pregunta que en mi comentario anterior sobre localizar texto en español rioplatense dentro de las guias

2022-01-04 19:40 UTC, romisoto commented on guides/resources/changelog/current-year.en.md
> +The columns `POI_WALLET_NAME` y `POI_BANK_NAME` allow businesses that charge with a Mercado Pago QR code to identify from which digital wallets or banks their payments came from.
```suggestion
The columns `POI_WALLET_NAME` y `POI_BANK_NAME` allow businesses that charge with a Mercado Pago QR code to identify which digital wallets or banks their payments came from.
```

2022-01-04 19:41 UTC, romisoto commented on guides/resources/changelog/current-year.es.md
> +> Nuevas columnas en reporte de Todas las transacciones
```suggestion
> Nuevas columnas en reporte de "Todas las transacciones"
```

2022-01-04 19:41 UTC, romisoto commented on guides/resources/changelog/current-year.es.md
> +Las columnas `POI_WALLET_NAME` y `POI_BANK_NAME` permiten que los negocios que cobran con un código QR de Mercado Pago, identifiquen desde qué otras billeteras virtuales o bancos recibieron sus pagos
```suggestion
Las columnas `POI_WALLET_NAME` y `POI_BANK_NAME` permiten que los negocios que cobren con un código QR de Mercado Pago, identifiquen desde qué otras billeteras virtuales o bancos recibieron sus pagos.
```

2022-01-04 19:43 UTC, romisoto requested changes
Arreglé algunos typos y gramática en inglés. Dejo una pregunta/sugerencia respecto del uso de español rioplatense dentro de las guian (no recuerdo haberlo visto). Solemos usarlo para MLA y MLU (los dos paises que lo utilizan) para comunicaciones específicas, como emails.

2022-01-05 15:52 UTC, ccamargov-meli commented on guides/manage-account/reports/account-money/generate.es.md
> +> Creamos nuevas columnas que te permiten identificar las billeteras virtuales o los bancos que tus clientes usan para pagar cuando les ----[mla]----cobrás------------ ----[mlu, mpe, mlm, mco, mlc, m
Buen punto. Quedaría atento para aplica el cambio correspondiente. Fue el wording que nos brindó directamente UX.

2022-01-05 15:52 UTC, ccamargov-meli commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_WALLET_NAME | Nombre de la billetera virtual desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](
En este caso se vió necesario aplicarlo para no mostrar la URL para todos los sites, ven algún lío?

2022-01-05 15:52 UTC, ccamargov-meli commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_BANK_NAME | Nombre de la entidad bancaria desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](htt
En este caso se vió necesario aplicarlo para no mostrar la URL para todos los sites, ven algún lío?

2022-01-05 15:53 UTC, ccamargov-meli commented
@hgaldino @romisoto muchas gracias por la revisión! Veo que solo queda el tema de ES Neutro para poder desplegar en beta y programar deploy a prod. Quedo muy pendiente a sus instrucciones o comentarios! 💪

2022-01-05 16:18 UTC, romisoto commented on guides/manage-account/reports/account-money/generate.es.md
> +> Creamos nuevas columnas que te permiten identificar las billeteras virtuales o los bancos que tus clientes usan para pagar cuando les ----[mla]----cobrás------------ ----[mlu, mpe, mlm, mco, mlc, m
En este caso aconsejo utilizar español neutro para todo hispanos, con el fin de no generar discrepancias con el resto de las guías

2022-01-05 16:19 UTC, romisoto commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_WALLET_NAME | Nombre de la billetera virtual desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](
Aconsejo cambiar el wording a español neutro en MLA para no generar discrepancias con el resto de las guías

2022-01-05 16:20 UTC, romisoto commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_BANK_NAME | Nombre de la entidad bancaria desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](htt
Idem que en los casos anteriores, puede quedar separado para no tener el link, pero el wording no recomendamos que sea en español rioplatense, sino neutro

2022-01-05 17:53 UTC, ccamargov-meli commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_BANK_NAME | Nombre de la entidad bancaria desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](htt
Cambio aplicado!

2022-01-05 17:53 UTC, ccamargov-meli commented on guides/manage-account/reports/account-money/glossary.es.md
> +| POI_WALLET_NAME | Nombre de la billetera virtual desde la que se origina un pago digital. Permite identificar el origen de una operación cuando ----[mla]----cobrás con un [código QR interoperable](
Cambio aplicado!

2022-01-05 17:54 UTC, ccamargov-meli commented
@romisoto He aplicado los últimos cambios solicitados. Quedo atento! Gracias.

2022-01-05 18:33 UTC, romisoto approved these changes

2022-01-05 21:45 UTC, hgaldino approved these changes

2022-01-05 21:45 UTC, hgaldino commented on guides/resources/changelog/current-year.pt.md
> +Ir para a configuração pelo [panel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) o [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manag
```suggestion
Acesse a configuração pelo [painel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) ou [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/manage-account/reports/account-money/api).
```

2022-01-05 21:45 UTC, hgaldino commented on guides/resources/changelog/current-year.en.md
> +Go to settings [from the panel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) o [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-ac
```suggestion
Go to settings [from the panel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) or [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/account-money/api).
```

2022-01-05 21:45 UTC, hgaldino commented on guides/manage-account/reports/account-money/generate.en.md
> +> CWe have created new columns that allow you to identify which digital wallets or banks your clients use when they pay with a Mercado Pago QR Code. Update your settings preferences [from the panel](
```suggestion
> We have created new columns that allow you to identify which digital wallets or banks your clients use when they pay with a Mercado Pago QR Code. Update your settings preferences [from the panel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) or [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/account-money/api) so that you can include these columns in your reports. 
```

2022-01-05 21:47 UTC, hgaldino approved these changes

2022-01-05 21:47 UTC, hgaldino commented on guides/manage-account/reports/account-money/generate.en.md
> +> We have created new columns that allow you to identify which digital wallets or banks your clients use when they pay with a Mercado Pago QR Code. Update your settings preferences [from the panel](h
```suggestion
> We have created new columns that allow you to identify which digital wallets or banks your clients use when they pay with a Mercado Pago QR Code. Update your settings preferences [from the panel](https://www.mercadopago[FAKER][URL][DOMAIN]/balance/reports/settlement/settings) or [via API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/account-money/api) so that you can include these columns in your reports. 
```

2022-01-06 19:34 UTC, merged