Update customizations.en.md
mercadopago/devsite-docs pull request #1486
Opened 2022-01-05 21:45 UTC by nicmalegre

## Description
I'm not sure if this is the best place to make this proposal but I think the repo is private. It'll be great if you could change the document number input to 'type=number' in your Checkout Pro form. Right now it have 'type=text' and when you open it from a Webview (app mobile - react native) is not the best experience.
https://user-images.githubusercontent.com/40902023/148293616-4ee3d73f-2daf-4190-9ad7-8f67dc8a413c.png

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2022-01-05 22:01 UTC, hgaldino requested changes
Olá, Nicolás! Não entendi muito bem a descrição do PR, poderia me esclarecer qual foi a sua necessidade?

2022-01-05 22:01 UTC, hgaldino commented on guides/online-payments/checkout-pro/customizations.en.md
> +- Data fields;;
```suggestion
- Data fields;
```

2022-01-06 01:00 UTC, nicmalegre commented on guides/online-payments/checkout-pro/customizations.en.md
> +- Data fields;;
Olá, Heitor! My PR is not related with this file. I just added this minimal change in line 237 to be able to make the PR. I want to propose a change in the Checkout Pro - Form when you are completing card and user information (card number, name, expired date, cvv, document number, email) but I didn't find the repository to make the PR there. 

My proposal is to change the document number input to 'type=number' because right now you could add some letters and it's not right because you only need to add numbers. This change is useful when you open the form in a cellphone so only numeric keyboard appears.
Here is a picture: 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/40902023/148311233-2e6d0635-6fb8-4601-b615-e95a9a755979.png">

2022-01-06 13:38 UTC, hgaldino approved these changes

2022-01-06 19:33 UTC, hgaldino commented on guides/online-payments/checkout-pro/customizations.en.md
> +- Data fields;;
Hi  @nicmalegre! 

Thanks for the explanation! So, "docs" is the repository of documentation from Mercado Pago's Devsite. I recommend that you look for someone from the Cho Pro team on the slack because they might be able to help you better with this request.

2022-01-06 19:34 UTC, merged