[DEVCOMMS-469] API de integraciones Point
mercadopago/devsite-docs pull request #1506
Opened 2022-01-10 15:26 UTC by romisoto

## Description
Se generan traducciones para API de integraciones Point en Guias y API Reference con el fin de disponibilizar la documentación en los 3 idiomas.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2022-01-17 19:16 UTC, abderossi commented on guides/in-person-payments/integration-api/create-payment-intent.en.md
> +Before creating a payment intent, you must obtain the Point devices associated with your account. You can do it in the following way:
```suggestion
Before creating a payment intent, you must obtain the list of Point devices associated with your account. You can do it in the following way:
```

2022-01-17 19:29 UTC, abderossi commented on guides/in-person-payments/integration-api/create-payment-intent.en.md
> +> We’ll explain how to start receiving notifications from Webhooks.
```suggestion
> We'll explain how to start receiving notifications from Webhooks.
```

2022-01-17 19:31 UTC, abderossi commented on guides/in-person-payments/integration-api/glossary.en.md
> +Some terms are new and you may not be familiar with them. Use this glossary so you don't get lost!
```suggestion
Some terms are new and you may not be familiar with them. Use this glossary so you don't get lost:
```

2022-01-17 19:31 UTC, abderossi commented on guides/in-person-payments/integration-api/glossary.en.md
> +Some terms are new and you may not be familiar with them. Use this glossary so you don't get lost!
Super opcional, pero quizás sería bueno sacarle los ! en los tres idiomas. Se me hace un poco más serio... Qué opinas?

2022-01-17 19:46 UTC, abderossi commented on guides/in-person-payments/integration-api/introduction.en.md
> +# Lean about the Point Integrations API
```suggestion
# Learn about the Point Integrations API
```

2022-01-17 19:54 UTC, abderossi commented on guides/in-person-payments/integration-api/integration.en.md
> +-d '{"site_id":----[mla]----"MLA"------------ ----[mlb]----"MLB""------------ ----[mlm]----"MLM"------------}'
```suggestion
-d '{"site_id":----[mla]----"MLA"------------ ----[mlb]----"MLB"------------ ----[mlm]----"MLM"------------}'
```

2022-01-17 19:56 UTC, abderossi commented on guides/in-person-payments/integration-api/integration.en.md
> +-d '{"site_id":----[mla]----"MLA"------------ ----[mlb]----"MLB""------------ ----[mlm]----"MLM"------------}'
@romisoto , en MLA queda con espacios de más entre MLA y el corchete. Quizás habría que sacarle los espacios entre las localizaciones? Si rompe, habría que hacer un curl por país.

2022-01-17 19:57 UTC, abderossi commented on guides/in-person-payments/integration-api/notifications.en.md
> +If you wish, you can receive notifications from Webhooks. These are sent from our Integrations API to your receiving system through an 'HTTP POST' call in relation to the status changes presented by
```suggestion
If you wish, you can receive notifications from Webhooks. These are sent from our Integrations API to your receiving system through an `HTTP POST` call in relation to the status changes presented by a payment intent.
```

2022-01-17 19:58 UTC, abderossi commented on guides/in-person-payments/integration-api/notifications.en.md
> +If you wish, you can receive notifications from Webhooks. These are sent from our Integrations API to your receiving system through an 'HTTP POST' call in relation to the status changes presented by
Creo que esto quedó sin formato en los otros dos idiomas también!

2022-01-17 19:59 UTC, abderossi commented on guides/in-person-payments/integration-api/point-simulator.en.md
> +* **Device Mode**: simulates a virtual Point device so that you can test your integration from HTTP requests. Access the [Device Mode Simulator](https://api.mercadopago.com/point/integrator-simulator
```suggestion
* **Device Mode**: simulates a virtual Point device so that you can test your integration from HTTP requests. Access the [Device Mode Simulator](https://api.mercadopago.com/point/integrator-simulator/sandbox/device?ignoreapidoc=true)
```

2022-01-17 19:59 UTC, abderossi commented on guides/in-person-payments/integration-api/point-simulator.en.md
> +* **Device Mode**: simulates a virtual Point device so that you can test your integration from HTTP requests. Access the [Device Mode Simulator](https://api.mercadopago.com/point/integrator-simulator
En los tres idiomas uno tiene punto y el otro no (mala mía), habría que unificar. Unifiqué sin punto pero si preferís con punto, adelante!

2022-01-17 19:59 UTC, abderossi commented on guides/in-person-payments/integration-api/point-simulator.en.md
> +When using **Device Mode**, you must enter your Access Token and your Device Id obtained when [listing your devices](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/in-person-payment
```suggestion
When using **Device Mode**, you must enter your Access Token and your Device Id obtained when [listing your devices](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/in-person-payments/integration-api/create-payment-intent#bookmark_create_the_payment_intent).
```

2022-01-18 18:07 UTC, hgaldino requested changes
Romiii, fiz algumas sugestões no texto e encontrei duas questões nas imagens:

- images/point-api/2-flow-diagram-pt.png: nessa encontrei alguns pontos com "pago" ao invés de pagamento e "para webhook" quando deveria ser só webhook.
- images/point-api/1-diagram-pt.png: nessa encontrei alguns pontos com "pago".

2022-01-18 18:07 UTC, hgaldino commented on guides/in-person-payments/integration-api/notifications.pt.md
> +Se desejar, você pode receber notificações de Webhooks. Estas são enviadas de nossa API de Integrações para o seu sistema de recebimento por meio de uma chamada 'HTTP POST' em relação às mudanças de
```suggestion
Se desejar, você pode receber notificações Webhooks. Estas são enviadas de nossa API de Integrações para o seu sistema de recebimento por meio de uma chamada 'HTTP POST' em relação às mudanças de status apresentadas por uma intenção de pagamento.
```

2022-01-18 18:07 UTC, hgaldino commented on guides/in-person-payments/integration-api/notifications.pt.md
> +Para integrar notificações de Webhook, siga as instruções [nesta documentação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/introduction).
```suggestion
Para integrar notificações Webhook, siga as instruções [nesta documentação](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/webhooks).
```

2022-01-18 18:07 UTC, hgaldino commented on guides/in-person-payments/integration-api/notifications.pt.md
> +> [Simulador Point](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/PT/guides/in-person-payments/integration-api/point-simulator)
```suggestion
> [Simulador Point](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-person-payments/integration-api/point-simulator)
```

2022-01-19 12:52 UTC, abderossi commented on guides/in-person-payments/integration-api/glossary.es.md
> +Algunos términos son nuevos y quizás no estés familiarizado con ellos. ¡Usa este glosario para no perderte:
```suggestion
Algunos términos son nuevos y quizás no estés familiarizado con ellos. Usa este glosario para no perderte:
```

2022-01-19 13:02 UTC, abderossi approved these changes

2022-01-19 13:10 UTC, hgaldino approved these changes

2022-01-19 14:12 UTC, merged