[DEVCOMMS-470] Feature/Emails API update
mercadopago/devsite-docs pull request #1512
Opened 2022-01-13 16:23 UTC by hgaldino

## Description
Foram inseridas informações nos plugins (PrestaShop, Magento 2 e WooComerce) sobre o não envio de e-mails para usuários não cadastrados no Mercado Pago. Além disso, uma nota também foi criada no CHO Transparente.

Ps. Aproveitei também para atualizar os next steps cards das documentações da Presta e do Woo.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2022-01-14 12:20 UTC, romisoto commented on guides/online-payments/checkout-api/handling-responses.en.md
> +> You can configure or send e-mails to clients with status messages for two orders, such as approved payment. Therefore, the configuration of this shipment must be made in their respective platforms.
```suggestion
> You can configure or send e-mails to clients with status messages for two orders, such as approved payment. Therefore, the configuration of this shipment must be made in their respective platforms. See [WooComerce](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/woocommerce/integration), [PrestaShop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/woocommerce/integration) and [Magento 2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/plugins/magento-two/notifications-configuration) documentation for more details.
```

2022-01-14 12:21 UTC, romisoto commented on guides/online-payments/checkout-api/handling-responses.es.md
> +> Puede configurar e-mails para enviar a los clientes con mensajes de estado del pedido, como pago aprobado. No obstante, la configuración de este envío deberá realizarse en sus respectivas plataform
```suggestion
> Puedes configurar e-mails para enviar a los clientes con mensajes de estado del pedido, como pago aprobado. No obstante, la configuración de este envío deberá realizarse en sus respectivas plataformas. Consulta la documentación de [WooComerce](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/woocommerce/integration), [PrestaShop](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/woocommerce/integration) y [Magento 2](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/plugins/magento-two/notifications-configuration) para obtener más detalles.
```

2022-01-14 12:22 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.en.md
> +Having selected the **Checkout Transparente** to receive payments from your store, it is important to configure the sending of emails that will notify the user of their transactions. See below how to
```suggestion
Having selected the **Checkout API** to receive payments from your store, it is important to configure the sending of emails that will notify the user of their transactions. See below how to customize sending **transactional email** in Magento 2 management panel.
```

2022-01-14 12:24 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.es.md
> +Habiendo seleccionado **Checkout API** para recibir pagos de tu tienda, es importante configurar el envío de correos electrónicos que notificarán al usuario de sus transacciones. Vea a continuación c
```suggestion
Habiendo seleccionado **Checkout API** para recibir pagos de tu tienda, es importante configurar el envío de correos electrónicos que notificarán al usuario de sus transacciones. Ve a continuación cómo personalizar el envío de **e-mail transaccional** en el panel de administración de Magento 2.
```

2022-01-14 12:24 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.es.md
> +1. Ve al menú **Marketing > Communications > Email Templates > Add New Template** y cree la nueva plantilla de e-mail.
```suggestion
1. Ve al menú **Marketing > Communications > Email Templates > Add New Template** y crea la nueva plantilla de e-mail.
```

2022-01-14 12:24 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.es.md
> +2. En **Stores > Settings > Configuration > Sales > Sales Emails**, agregue la plantilla creada en los ajustes de eventos en la plataforma (ejemplo: "pago aprobado").
```suggestion
2. En **Stores > Settings > Configuration > Sales > Sales Emails**, agrega la plantilla creada en los ajustes de eventos en la plataforma (ejemplo: "pago aprobado").
```

2022-01-14 12:24 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.es.md
> +3. Una vez realizadas las configuraciones necesarias, instale y configure un **servidor SMTP** de su elección para habilitar el envío de correos electrónicos.
```suggestion
3. Una vez realizadas las configuraciones necesarias, instala y configura un **servidor SMTP** de tu elección para habilitar el envío de correos electrónicos.
```

2022-01-14 12:24 UTC, rwaetemann approved these changes

2022-01-14 12:25 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.es.md
> +4. Envíe un **e-mail de prueba** para asegurarse de que la plataforma está enviando correos electrónicos correctamente.
```suggestion
4. Envía un **e-mail de prueba** para asegurarte de que la plataforma está enviando correos electrónicos correctamente.
```

2022-01-14 12:29 UTC, romisoto commented on guides/plugins/prestashop/faq.es.md
>  El plugin PrestaShop solo recibe notificaciones del tipo IPN. Para obtener más información,[haz clic aquí](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/Notifications/ipn).
```suggestion
El plugin PrestaShop solo recibe notificaciones del tipo IPN. Para obtener más información, [haz clic aquí](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/notifications/ipn).
```

2022-01-14 12:29 UTC, romisoto commented on guides/plugins/prestashop/faq.es.md
>  Para instalar el plugin manualmente, siga los pasos:
```suggestion
Para instalar el plugin manualmente, sigue los pasos:
```

2022-01-14 12:32 UTC, romisoto commented on guides/plugins/prestashop/integration.en.md
> +7. Having selected the **Checkout Transparente** to receive payments from your store, it is important to configure the sending of emails that will notify the user of their transactions. See below how
```suggestion
7. Having selected **Checkout API** to receive payments from your store, it is important to configure the email notifications that will notify the user of their transactions. See below how to customize the  **transactional email** notifications in the PrestaShop management panel.
```

2022-01-14 12:33 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.en.md
> +3. Once the necessary settings have been made, install and configure a **SMTP server** of your choice to enable the sending of e-mails.
```suggestion
3. Once the necessary settings have been made, install and configure a **SMTP server** of your choice to enable the e-mail notifications.
```

2022-01-14 12:34 UTC, romisoto commented on guides/plugins/magento-two/notifications-configuration.en.md
> +Ready! Sending emails has been successfully configured.
```suggestion
Ready! email notifications have been successfully configured.
```

2022-01-14 12:35 UTC, romisoto commented on guides/plugins/prestashop/integration.en.md
> +* To configure the **SMTP server** and enable the sending of e-mails, access **Advanced Parameters > E-mails** and select the option "Set my own SMTP parameters (for advanced users ONLY)". Fill in th
```suggestion
* To configure the **SMTP server** and enable e-mail notifications, access **Advanced Parameters > E-mails** and select the option "Set my own SMTP parameters (for advanced users ONLY)". Fill in the information of the server responsible for sending.
```

2022-01-14 12:36 UTC, romisoto commented on guides/plugins/prestashop/integration.es.md
> +* En el **Panel Administrativo** de su tienda PrestaShop, haz clic en **International > Translation** y seleccione la plantilla que desea cambiar.
```suggestion
* En el **Panel Administrativo** de tu tienda PrestaShop, haz clic en **International > Translation** y selecciona la plantilla que deseas cambiar.
```

2022-01-14 12:36 UTC, romisoto commented on guides/plugins/prestashop/integration.es.md
> +* Una vez realizados los cambios necesarios, en ***Shop Parameters > Order Settings > Statuses** puede definir una plantilla de correo electrónico para cada estado del pedido.
```suggestion
* Una vez realizados los cambios necesarios, en ***Shop Parameters > Order Settings > Statuses** puedes definir una plantilla de correo electrónico para cada estado del pedido.
```

2022-01-14 12:37 UTC, romisoto commented on guides/plugins/prestashop/integration.es.md
> +* Para configurar el **servidor SMTP** y habilitar el envío de e-mails, acceda a **Advanced Parameters > E-mails** y seleccione la opción "Establecer mis propios parámetros SMTP (SÓLO para usuarios a
```suggestion
* Para configurar el **servidor SMTP** y habilitar el envío de e-mails, accede a **Advanced Parameters > E-mails** y seleccione la opción "Establecer mis propios parámetros SMTP (SÓLO para usuarios avanzados)". Rellena los datos del servidor responsable del envío.
```

2022-01-14 12:37 UTC, romisoto commented on guides/plugins/prestashop/integration.es.md
> +* Envíe un e-mail de prueba para asegurarse de que la plataforma está enviando correos electrónicos correctamente.
```suggestion
* Envía un e-mail de prueba para asegurarte de que la plataforma está enviando correos electrónicos correctamente.
```

2022-01-14 12:41 UTC, romisoto commented on guides/plugins/woocommerce/integration.en.md
> +Having selected the **Checkout Transparente** to receive payments from your store, it is important to configure the sending of emails that will notify the user of their transactions. See below how to
```suggestion
Having selected **Checkout API** to receive payments from your store, it is important to configure the email notifications that will notify the user of their transactions. See below how to customize  **transactional email** notifications in the WooCommerce management panel.
```

2022-01-14 12:41 UTC, romisoto commented on guides/plugins/woocommerce/integration.en.md
> +3. In **E-mails**, enable the sending to be configured by selecting the option ˜activate this notification e-mail".
```suggestion
3. In **E-mails**, enable the notifications to be configured by selecting the option ˜activate this notification e-mail".
```

2022-01-14 12:42 UTC, romisoto commented on guides/plugins/woocommerce/integration.en.md
> +7. Once the necessary settings have been made, install and configure a **SMTP server** of your choice to enable the sending of e-mails.
```suggestion
7. Once the necessary settings have been made, install and configure a **SMTP server** of your choice to enable e-mail notifications.
```

2022-01-14 12:42 UTC, romisoto commented on guides/plugins/woocommerce/integration.es.md
> +Habiendo seleccionado el **Checkout API** para recibir pagos de tu tienda, es importante configurar el envío de los e-mails que notificarán al usuario de sus transacciones. Vea a continuación cómo pe
```suggestion
Habiendo seleccionado el **Checkout API** para recibir pagos de tu tienda, es importante configurar el envío de los e-mails que notificarán al usuario de sus transacciones. Ve a continuación cómo personalizar el envío del **e-mail transaccional** en el panel de administración de WooCommerce.
```

2022-01-14 12:42 UTC, romisoto commented on guides/plugins/woocommerce/integration.es.md
> +3. En **E-mails**, habilitar la configuración del envío seleccionando la opción ˜activar este e-mail de notificación".
```suggestion
3. En **E-mails**, habilita la configuración del envío seleccionando la opción ˜activar este e-mail de notificación".
```

2022-01-14 12:43 UTC, romisoto commented on guides/plugins/woocommerce/integration.es.md
> +4. Personalice la plantilla de correo electrónico con: destinatarios, asunto del correo electrónico y encabezado.
```suggestion
4. Personaliza la plantilla de correo electrónico con: destinatarios, asunto del correo electrónico y encabezado.
```

2022-01-14 12:43 UTC, romisoto commented on guides/plugins/woocommerce/integration.es.md
> +5. Ingrese el **contenido** a enviar y seleccione el tipo de correo electrónico.
```suggestion
5. Ingresa el **contenido** a enviar y selecciona el tipo de correo electrónico.
```

2022-01-14 12:43 UTC, romisoto commented on guides/plugins/woocommerce/integration.es.md
> +6. Indique también el nombre y la dirección de correo electrónico del remitente, así como el logotipo y los colores de su tienda.
```suggestion
6. Indica también el nombre y la dirección de correo electrónico del remitente, así como el logotipo y los colores de tu tienda.
```

2022-01-14 12:43 UTC, romisoto commented on guides/plugins/woocommerce/integration.es.md
> +7. Una vez realizadas las configuraciones necesarias, instale y configure un **servidor SMTP** de su elección para habilitar el envío de correos electrónicos.
```suggestion
7. Una vez realizadas las configuraciones necesarias, instala y configura un **servidor SMTP** de tu elección para habilitar el envío de correos electrónicos.
```

2022-01-14 12:44 UTC, romisoto commented on guides/plugins/woocommerce/integration.es.md
> +8. Envíe un **correo electrónico de prueba** para asegurarse de que la plataforma envíe los correos electrónicos correctamente.
```suggestion
8. Envía un **correo electrónico de prueba** para asegurarte de que la plataforma envíe los correos electrónicos correctamente.
```

2022-01-14 12:44 UTC, romisoto requested changes
Heitor! hice unas pequeñas sugerencias!

2022-01-17 20:19 UTC, romisoto approved these changes

2022-01-19 14:13 UTC, merged