feature/guia nuevas practicas
mercadopago/devsite-docs pull request #1525
Opened 2022-01-19 21:16 UTC by abderossi

## Description
Agregamos la Guía de Buenas prácticas para checkout creada por el equipo de UX.
Se crearon cuatro items de menú nuevos y se adicionaron imágenes para cada idioma.

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [x] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [x] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2022-02-01 17:09 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.en.md
> +To know how your checkout is performing after implementing these best practices, we recommend you integrate a tracking tool (e.g: Google Analytics) and make optimizations based on results to improve
```suggestion
To know how your checkout is performing after implementing these best practices, we recommend you integrate a tracking tool (e.g: Google Analytics) and make optimizations based on results to improve your user's experience and have more conversions.
```

2022-02-01 17:12 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.es.md
> +Ya tienes todo lo que necesitas para crear la mejor experiencia de pago para tus clientes. Integra nuestros productos [Checkout API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/o
en inglés dice "your user experience", no me termina de quedar claro si aca debería ser un "tu" (de quien lee) o un "su" (del usuario), y piesno que poner UX en vez de experiencia de usuario aca queda extraño

2022-02-01 17:12 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.es.md
> +> Sigue los pasos para crear un checkout fácil de recorrer y entender.
```suggestion
> Sigue los pasos para crear un checkout fácil de navegar y entender.
```

2022-02-01 17:17 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +* **Subheadings**: they give context or explain which action is expected.
aca usaría el mismo formato que en los otros dos items de la lista para darle homogeneidad "use them to give context..."

2022-02-01 17:20 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +**Highlights** are underlined or highlighted text. Use highlights to highlight important keywords or sentences that add value and make the screen easier to scan.
"use highlights to highlight" suena un poco circular para explicar, pondría algún sinónimo como: spotlight, call attention to, point up.

2022-02-01 17:21 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +**Forms** are sets of related inputs that have a common purpose, for example, such as those in which personal data is requested.
```suggestion
**Forms** are sets of related inputs that have a common purpose, such as those in which personal data is requested. 
```

2022-02-01 17:22 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +In order to make filling out the form easier and do not tire the user:
```suggestion
In order to make filling out the form easier and not tire the user: 
```

2022-02-01 17:23 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +It is important to know that the placeholder disappears when the cursor is placed on the input or the data is completed. Take this feature into account and avoid using them as the only reference for
```suggestion
It is important to know that the placeholder disappears when the cursor is placed on the input or the data is completed. Take this feature into account and avoid using them as the only reference for your inputs so that the user does not have to make an effort to remember what data goes in each field, or has to delete what was entered if they want to confirm it. 
```

2022-02-01 17:24 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +![en helpers y tooltips dos&don't](/images/best-practices-guide/EngAspectosGeneralesHelpersTooltipv2png)
esta imagen no se ve en el scope, aparece rota

2022-02-01 17:25 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +Use success messages only if the confirmation is necessary or if the entered detail adds value to the user (e.g: free shipping or discount). In case of an **error**, it is important to make it clear
```suggestion
Use success messages only if the confirmation is necessary or if the entered detail adds value to the user (e.g: free shipping or discount). In case of an **error**, it is important to clarify what the problem was and provide a solution so that the user does not make the mistake again and gets frustrated. If the input has a helper, it should be replaced by the error message. 
```

2022-02-01 17:28 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +Therefore, **offer options** that include different possible variables and order them in descending order, taking into account the most used or beneficial for your customers. However, we recommend **
```suggestion
Therefore, **offer options** that include different possible variables and write them in descending order, taking into account the most used or beneficial for your customers. However, we recommend **offering only the most common ones** because otherwise you can confuse and hinder the selection process.
```

2022-02-01 17:29 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +* Use **cards** when it comes to options visual options, among others.
```suggestion
* Use **cards** when it comes to visual options, among others. 
```

2022-02-01 17:35 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +Para facilitar el llenado de datos y no cansar al usuario, te recomendamos:
en esta sección pondría "te recomendamos que:" o bien lo dejaría así pero pondría los verbos de la lista a continuación en infinitivo

2022-02-01 17:35 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +Las **labels** son los nombres de cada input e indican qué dato se debe ingresar allí. Deben permanecer siempre visibles para que el usuario pueda escanear y completar más rápido el formulario, ya qu
```suggestion
Las **labels** son los nombres de cada input e indican qué dato se debe ingresar allí. Deben permanecer siempre visibles para que el usuario pueda escanear y completar más rápido el formulario, ya que sirven como guía y evitan el esfuerzo de recordar. 
```

2022-02-01 17:52 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +* Utiliza **radio buttons** cuando sean pocas opciones y solo se pueda elegir una de ellas
```suggestion
* Utiliza **radio buttons** cuando sean pocas opciones y solo se pueda elegir una de ellas.
```

2022-02-01 17:52 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +* Ofrece **dropdowns** cuando sean varias opciones y no quieras ocupar tanto espacio de pantalla
```suggestion
* Ofrece **dropdowns** cuando sean varias opciones y no quieras ocupar tanto espacio de pantalla.
```

2022-02-01 17:53 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +* Usa **cards** cuando se traten de opciones opciones visuales, entre otras.
```suggestion
* Usa **cards** cuando se traten de opciones visuales, entre otras. 
```

2022-02-01 17:54 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +También puedes utilizar **checkboxes** que infieran información de pasos previos o desplieguen un formulario en caso de que el usuario quiera cargar información diferente.
creo que el témino en inglés aca puede llegar a entorpecer, tal vez pondría "casillas de verificación". Solo una sugerencia!

2022-02-01 17:55 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +Además, antes de finalizar la compra, permite que tus usuarios puedan **revisar** todo el proceso y el precio final. Para esto, agrega una página de confirmación o revisión, previo a realizar el pago
```suggestion
Además, antes de finalizar la compra, permite que tus usuarios puedan **revisar** todo el proceso y el precio final. Para esto, agrega una página de confirmación o revisión, previo a realizar el pago, que incluya un resumen de todas las decisiones tomadas, toda la información cargada y el detalle del total a pagar. Es importante dar la posibilidad de editar cualquiera de los datos desde allí, sin la necesidad de volver a los pasos previos.
```

2022-02-01 17:56 UTC, romisoto requested changes
Te envío algunas sugerencias! el archivo measure-and-optimize no se ve en el scope ni está en el menu, es docu oculta?

2022-02-02 12:41 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/ease-of-conversion.pt.md
> +Para que o processo de pagamento seja prático e rápido para seus usuários e, assim, obter mais conversões, seu checkout deve ser fácil de navegar e consistente. Siga estas dicas para alcançá-lo.
```suggestion
Para que o processo de pagamento seja prático e rápido para seus usuários e assim obter mais conversões, seu checkout deve ser fácil de navegar e consistente. Siga estas dicas para alcançá-lo.
```

2022-02-02 12:48 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/ease-of-conversion.pt.md
> +Para **dispositivos móveis**, opte por etapas curtas, que chamem a atenção e sejam fáceis de navegar. No caso do **desktop**, por outro lado, você pode usar experiências "one step", já que o usuário
```suggestion
Para **dispositivos móveis**, opte por etapas curtas, que chamem a atenção do usuário e permitam uma navegação mais amigável. No caso do **desktop**, você pode usar experiências "one step", já que o usuário consegue controlar melhor suas ações, ficando mais fácil encontrar o que busca.
```

2022-02-02 12:50 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/ease-of-conversion.pt.md
> +A **consistência** é um fator essencial para gerar coerência e congruência. Nos ajuda a estabelecer padrões que os usuários entendam e lembrem. Tente manter a consistência visual e textual.
```suggestion
A **consistência** é um fator essencial para gerar coerência e congruência e ajuda a estabelecer padrões que os usuários entendam e lembrem. Tente manter a consistência visual e textual.
```

2022-02-02 12:50 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/ease-of-conversion.pt.md
> +Agora, você conta com todas as informações de que precisa para criar a melhor experiência de pagamento para seus clientes. Integre nossos produtos e otimize a experiência do usuário com essas boas pr
```suggestion
Agora, você conta com todas as informações necessárias para criar a melhor experiência de pagamento para seus clientes. Integre nossos produtos e otimize a experiência do usuário com essas boas práticas.
```

2022-02-02 12:53 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/ease-of-conversion.pt.md
> +> Confira os componentes principais de um checkout e saiba como otimizá-los para que seus usuários tenham uma experiência ainda melhor, gerando mais conversão.
```suggestion
> Conheça os componentes principais de um checkout e saiba como oferecer a melhor experiência de compra aos usuários.
```

2022-02-02 12:54 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/introduction.pt.md
> +Para impulsionar seus negócios, criamos uma guía de boas práticas de UX para checkouts que vão te ajudar a melhorar a experiência de pagamento dos seus clientes, ter mais conversão e oferecer um serv
```suggestion
Para impulsionar seus negócios, criamos um guia de boas práticas de UX para checkouts que vai te ajudar a melhorar a experiência de pagamento dos seus clientes e aumentar as conversões de vendas.
```

2022-02-02 12:55 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/introduction.pt.md
> +> Para saber cómo performa tu checkout una vez implementadas estas buenas prácticas, te recomendamos integrar alguna herramienta de trackeo y realizar optimizaciones en base a los resultados para mej
@abderossi - Gosti, aqui está em ES.

2022-02-02 12:56 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/introduction.pt.md
> +> Otimize sua experiência de checkout
```suggestion
> Otimize a experiência de checkout
```

2022-02-02 13:32 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.pt.md
> +Para saber sobre o desempenho do seu checkout depois de implementar essas boas práticas, recomendamos que você integre alguma ferramenta de acompanhamento (por exemplo, o Google Analytics) e faça oti
```suggestion
Para avaliar o desempenho do seu checkout após implementar essas boas práticas, recomendamos a integração de alguma ferramenta de acompanhamento (por exemplo, o Google Analytics). Essa ferramenta trará dados importantes que servirão como base para realizar otimizações, melhorar a experiência dos seus usuários e ter mais conversão.
```

2022-02-02 13:33 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.pt.md
> +Agora, você conta com todas as informações de que precisa para criar a melhor experiência de pagamento para seus clientes. Integre nossos produtos [Checkout API](https://www.mercadopago[FAKER][URL][D
```suggestion
Agora, você conta com todas as informações necessárias para criar a melhor experiência de pagamento para seus clientes. Integre nossos produtos [Checkout API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/introduction) ou as soluções de [Plugins e plataformas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/plugins) e otimize a experiência do usuário com essas boas práticas.
```

2022-02-02 13:34 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.pt.md
> +> Siga estas etapas para criar um checkout fácil de navegar e entender.
```suggestion
> Saiba como criar um checkout com navegação simples e de fácil compreensão.
```

2022-02-02 13:37 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Mostraremos como você pode otimizar sua experiência de checkout usando seus componentes principais e da melhor maneira para obter o objetivo específico, o que resultará em mais conversões de vendas.
```suggestion
Nesta seção você encontra todas as informações necessárias para otimizar a experiência de compra no checkout utilizando seus componentes. Isso permitirá uma navegação simples, fluida e objetiva, contribuindo ainda mais para a conversão de vendas.
```

2022-02-02 13:37 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +## Melhora a escaneabilidade
```suggestion
## Melhore a escaneabilidade
```

2022-02-02 13:38 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Mantenha os dados agrupados tematicamente e forneça contexto ao usuário sobre as etapas a serem seguidas para concluir sua transação. Isso ajudará a escaneabilidade e fará com que o usuário se sinta
```suggestion
Mantenha os dados agrupados por tema e forneça contexto ao usuário sobre as etapas a serem seguidas para concluir sua transação. Isso ajudará na escaneabilidade e fará com que o usuário se sinta mais seguro ao compartilhar suas informações. Para isso, recomendamos que você use:
```

2022-02-02 13:39 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +### Progress indicator
@abderossi - Gosti, esse título será em EN mesmo? Penso se não seria melhor colocarmos "Indicador de progresso" ou "Barra de progresso" mesmo.

2022-02-02 13:40 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Trata-se de uma **barra de progresso** que indica ao usuário em qual etapa ele está. É possível segmentá-la em partes iguais, indicando cada passo do checkout. Dessa maneira, seu usuário poderá acomp
```suggestion
Trata-se de uma **barra de progresso** que indica ao usuário em qual etapa ele está. É possível segmentá-la em partes iguais, indicando cada etapa do checkout. Dessa maneira, seu usuário poderá acompanhar em qual passo está e quanto falta para concluir o processo de pagamento.
```

2022-02-02 13:40 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +### Bullets y highlights
```suggestion
### Bullets e highlights
```

2022-02-02 13:42 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Recomendamos o uso de **formulários** para coletar os dados que você precisa do usuário. Os formulários são **conjuntos de inputs**, relacionados entre si e com um objetivo comum, como aqueles em que
```suggestion
Recomendamos o uso de **formulários** para coletar os dados de usuário. Os formulários são **conjuntos de inputs**, relacionados entre si e com um objetivo comum, como aqueles em que são solicitados dados pessoais.
```

2022-02-02 13:50 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Para facilitar o preenchimento dos dados e não cansar o usuário:
```suggestion
Para facilitar o preenchimento dos dados e evitar que o usuário não conclua a ação:
```

2022-02-02 13:51 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +* Solicite cada dado apenas uma vez para evitar ser redundante.
```suggestion
* Evite redundância e solicite cada dado apenas uma vez.
```

2022-02-02 13:55 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Os **placeholders** são os textos que aparecem dentro de cada um input, que exemplificam o dado que o usuário deve inserir. Aproveite esse espaço para incluir exemplos de formato ou de acionáveis.
```suggestion
Os **placeholders** são os textos que aparecem dentro de cada input que exemplificam o dado que o usuário deve inserir. Aproveite esse espaço para incluir exemplos de formato ou de acionáveis. 
```

2022-02-02 13:55 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +É importante saber que o placeholder desaparece quando o usuário coloca o cursor do mouse no input ou preenche o dado exigido. Leve esse recurso em consideração e evite usá-los como única referência
```suggestion
É importante saber que o placeholder desaparece quando o usuário coloca o cursor do mouse no input ou preenche o dado exigido. Leve esse recurso em consideração e evite usá-lo como única referência para sua entrada, assim, o usuário não precisa se esforçar para lembrar qual dado deve preencher em cada input ou apagar o dado inserido caso queira confirmá-lo.
```

2022-02-02 13:56 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Tanto as labels quanto os placeholders devem ser curtos, diretos e claros, para evitar que o usuário cometa erros.
```suggestion
Tanto as labels quanto os placeholders devem ser curtos, diretos e claros para evitar que o usuário cometa erros.
```

2022-02-02 13:59 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Os **helpers** são textos que vão embaixo dos inputs e fornecem mais informações sobre o dado e porque ele está sendo pedido. Use-os para justificar a solicitação de dados sensíveis ou dar informaçõe
```suggestion
Os **helpers** são textos que vão embaixo dos inputs e fornecem mais informações sobre o dado e por que ele está sendo pedido. Use-os para justificar a solicitação de dados sensíveis ou dar informações relevantes sobre o campo em questão. 
```

2022-02-02 14:02 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Os **Call to action** (CTAs) são chamadas para o usuário realizar uma determinada ação. Eles permitem que as ações principais e secundárias de uma tela sejam realizadas e podem ser aplicadas com dife
```suggestion
Os **Call to action** (CTAs) são chamadas para o usuário realizar uma determinada ação. Eles permitem que as ações principais e secundárias de uma tela sejam realizadas e podem ser aplicadas com diferentes estilos, como botões, ícones ou links, com diferentes hierarquias e em diferentes locais, como cartões e dicas, entre outros.
```

2022-02-02 14:05 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +* Inclua links para ações secundárias que agreguem contexto e procure usar textos autoexplicativos, que façam referência para onde o usuário será redirecionado ao clicar ali.
```suggestion
* Inclua links para ações secundárias que agreguem contexto e procure usar textos auto-explicativos, que façam referência para onde o usuário será redirecionado ao clicar ali. 
```

2022-02-02 14:06 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Num checkout, o usuário deve escolher entre diferentes opções ao longo do processo de pagamento, como tipo de entrega, formas de pagamento, número de parcelas, entre outras. Nesse processo, a convers
```suggestion
Em um checkout, o usuário deve escolher entre diferentes opções ao longo do processo de pagamento, como tipo de entrega, formas de pagamento, número de parcelas, entre outras. Nesse processo, a conversão pode variar de acordo com diferentes fatores e o contexto de cada um.
```

2022-02-02 14:06 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Por isso, **ofereça opções** que incluam as diferentes variáveis possíveis e ordena-las de forma decrescente, levando em consideração aquelas que são mais usadas ou vantajosas para seus clientes. No
```suggestion
Por isso, **ofereça opções** que incluam as diferentes variáveis possíveis e organize-as de forma decrescente, levando em consideração aquelas que são mais usadas ou vantajosas para seus clientes. No entanto, recomendamos **oferecer apenas os mais comuns**, caso contrário, isso pode tornar o processo de escolha confuso e poluído. 
```

2022-02-02 14:15 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +* Use **radio buttons** quando houver poucas opções e você só puder escolher uma delas.
@abderossi o que são radio buttons, dropdowns e cards? (eu particularmente sei o que são, mas acho que talvez valeria colocar alguma descrição sobre o que seriam esses modelos).

2022-02-02 14:23 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Evite pedir dados repetidos ou que não sejam necessários para concluir a compra. Para isso, aproveite as etapas em que os dados obrigatórios são exigidos para conseguir mais informações que serão nec
```suggestion
Evite pedir dados repetidos ou que não sejam necessários para concluir a compra. Para isso, aproveite as etapas em que os dados obrigatórios são exigidos para conseguir mais informações que serão necessárias posteriormente. Por exemplo, use as informações pessoais e de envio para pegar os dados de faturamento. Assim, você evita incluir um formulário extra, o que atrasaria o processo de pagamento. 
```

2022-02-02 14:29 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Além disso, antes da conclusão da compra, permite que os usuários possam **revisar** todo o processo e o preço final. Para isso, inclua uma página de confirmação ou revisão, antes de a pessoa efetiva
```suggestion
Além disso, antes da conclusão da compra, permita que os usuários possam **revisar** todo o processo e o preço final. Para isso, inclua uma página de confirmação ou revisão, antes de o usuário concluir o pagamento. É importante dar a possibilidade de o usuário editar qualquer dado ali mesmo, sem precisar voltar às etapas anteriores.
```

2022-02-02 18:55 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/introduction.pt.md
> +> Para saber cómo performa tu checkout una vez implementadas estas buenas prácticas, te recomendamos integrar alguna herramienta de trackeo y realizar optimizaciones en base a los resultados para mej
```suggestion
> Para saber o desempenho do seu checkout após a implementação dessas boas práticas, recomendamos que você integre uma ferramenta de rastreamento e realize otimizações com base nos resultados para melhorar a experiência de seus usuários e ter mais conversões.
```

2022-02-02 18:55 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/introduction.pt.md
> +> Para saber cómo performa tu checkout una vez implementadas estas buenas prácticas, te recomendamos integrar alguna herramienta de trackeo y realizar optimizaciones en base a los resultados para mej
@rwaetemann Listo! Cómo lo ves ahora?

2022-02-02 18:56 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.es.md
> +Ya tienes todo lo que necesitas para crear la mejor experiencia de pago para tus clientes. Integra nuestros productos [Checkout API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/o
```suggestion
Ya tienes todo lo que necesitas para crear la mejor experiencia de pago para tus clientes. Integra nuestros productos y optimiza la experiencia de usuario con estas buenas prácticas.
```

2022-02-02 18:57 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +**Highlights** are underlined or highlighted text. Use highlights to highlight important keywords or sentences that add value and make the screen easier to scan.
```suggestion
**Highlights** are underlined or highlighted text. Use highlights to call attention to important keywords or sentences that add value and make the screen easier to scan.
```

2022-02-02 18:57 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +![en helpers y tooltips dos&don't](/images/best-practices-guide/EngAspectosGeneralesHelpersTooltipv2png)
```suggestion
![en helpers y tooltips dos&don't](/images/best-practices-guide/EngAspectosGeneralesHelpersTooltipv2.png)
```

2022-02-02 18:58 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +Para facilitar el llenado de datos y no cansar al usuario, te recomendamos:
```suggestion
Para facilitar el llenado de datos y no cansar al usuario, te damos algunas recomendaciones:
```

2022-02-02 18:59 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +### Progress indicator
Sería en inglés Rods! Incluso en ES y PT

2022-02-02 19:01 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.en.md
> +* **Subheadings**: they give context or explain which action is expected.
```suggestion
* **Subheadings**: use them to give context or explain which action is expected.
```

2022-02-02 19:02 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +También puedes utilizar **checkboxes** que infieran información de pasos previos o desplieguen un formulario en caso de que el usuario quiera cargar información diferente.
Por elección de UX, los términos quedaron en inglés. Lo que podemos hacer es sumar una aclaración!

2022-02-02 19:02 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +También puedes utilizar **checkboxes** que infieran información de pasos previos o desplieguen un formulario en caso de que el usuario quiera cargar información diferente.
```suggestion
También puedes utilizar **checkboxes**, también llamadas casillas de verificación, que infieran información de pasos previos o desplieguen un formulario en caso de que el usuario quiera cargar información diferente.
```

2022-02-02 19:03 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +También puedes utilizar **checkboxes** que infieran información de pasos previos o desplieguen un formulario en caso de que el usuario quiera cargar información diferente.
Cómo lo ves ahí @romisoto ?

2022-02-02 19:03 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +* Use **radio buttons** quando houver poucas opções e você só puder escolher uma delas.
Coincido Rods! Voy a sumar una descripción en los tres idiomas ;)

2022-02-02 19:05 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +* Utiliza **radio buttons** cuando sean pocas opciones y solo se pueda elegir una de ellas.
```suggestion
* Utiliza **radio buttons** o botones de opción cuando sean pocas opciones y solo se pueda elegir una de ellas.
```

2022-02-02 19:08 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/optimized-experience.pt.md
> +Você também pode usar **checkboxes** que deduzem informações de etapas anteriores ou exibem um formulário caso o usuário queira carregar informações diferentes.
```suggestion
Você também pode usar **checkboxes** o caixas de seleção que deduzem informações de etapas anteriores ou exibem um formulário caso o usuário queira carregar informações diferentes.
```

2022-02-02 19:09 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.pt.md
> +Agora, você conta com todas as informações necessárias para criar a melhor experiência de pagamento para seus clientes. Integre nossos produtos [Checkout API](https://www.mercadopago[FAKER][URL][DOMA
```suggestion
Agora, você conta com todas as informações necessárias para criar a melhor experiência de pagamento para seus clientes. Integre nossos produtos e otimize a experiência do usuário com essas boas práticas.
```

2022-02-02 19:10 UTC, abderossi commented on guides/best-practices/ux-for-checkouts/measure-and-optimize.en.md
> +Now you have all the information you need to create the best payment experience for your clients. Integrate our [Checkout API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-
```suggestion
Now you have all the information you need to create the best payment experience for your clients. Integrate our solutions and optimize your user experience with these best practices.
```

2022-02-02 19:44 UTC, romisoto commented on guides/best-practices/ux-for-checkouts/optimized-experience.es.md
> +También puedes utilizar **checkboxes** que infieran información de pasos previos o desplieguen un formulario en caso de que el usuario quiera cargar información diferente.
@abderossi perfecto!!

2022-02-03 19:50 UTC, romisoto approved these changes

2022-02-03 19:55 UTC, rwaetemann commented on guides/best-practices/ux-for-checkouts/introduction.pt.md
> +> Para saber cómo performa tu checkout una vez implementadas estas buenas prácticas, te recomendamos integrar alguna herramienta de trackeo y realizar optimizaciones en base a los resultados para mej
Perfectooooo!

2022-02-03 19:55 UTC, rwaetemann approved these changes

2022-02-04 13:21 UTC, merged