[DEVCOMMS-487] Atualização da documentação do Dashboard
mercadopago/devsite-docs pull request #1555
Opened 2022-02-04 00:42 UTC by hgaldino

## Description
Atualização da documentação do Dashboard, separando em alguns menus e ajustando partes do texto. Além disso, aproveitamos para incluir também a nova versão da documentação do OAuth.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2022-02-07 14:35 UTC, romisoto commented on guides/resources/dashboard/aplications.en.md
> +To every application created, a new card containing the application's name, description and ID is automatically created on the [Dashboard](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/dashb
```suggestion
For every application created, a new card containing the application's name, description and ID is automatically created on the [Dashboard](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/dashboard/introduction) homepage.
```

2022-02-07 14:37 UTC, romisoto commented on guides/resources/dashboard/aplications.en.md
> + - *Application blocking*. If there is, it will indicate the reason for the application being blocked for use. Click on **Block Details** to check the solution for the reported block.
```suggestion
 - *Application blocking*. If blocked, it will indicate the reason for the application being blocked for use. Click on **Block Details** to check the solution for the reported block.
```

2022-02-07 15:07 UTC, romisoto commented on guides/resources/dashboard/aplications.en.md
> +> Check informations about regarding third-party accounts that you have been given permission to use.
```suggestion
> Check information regarding third-party accounts that you have been given permission to use.
```

2022-02-07 15:10 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> + - *Permisos de la aplicación*. Este campo muestra las opciones de acceso para tu aplicación, siendo: lectura (read), acceso sin conexión (offline access) y escritura (write). De forma predeterminada
```suggestion
 - *Permisos de la aplicación*. Este campo muestra las opciones de acceso para tu aplicación, las cuales son: lectura (read), acceso sin conexión (offline access) y escritura (write). De forma predeterminada, tu aplicación se crea con todos los permisos habilitados. Pero puedes deshabilitar un permiso haciendo clic en la casilla de verificación del que deseas cambiar.
```

2022-02-07 15:11 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> + - *Redirigir URL*. Este campo define la URL en la que deseas recibir el código de autorización cuando tu integración se configura como Marketplace o se realiza a través de OAuth. Vea [OAuth](https:/
```suggestion
 - *Redirigir URL*. Este campo define la URL en la que deseas recibir el código de autorización cuando tu integración se configura como Marketplace o se realiza a través de OAuth. Lee [OAuth](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/security/oauth/introduction) para más detalles.
```

2022-02-07 15:11 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> + - *Bloqueo de aplicaciones*. Si lo hay, indicará el motivo por el cual la aplicación está bloqueada para su uso. Haz clic en **Detalles del bloque** para verificar [la solución](https://www.mercadop
```suggestion
 - *Bloqueo de aplicaciones*. Si lo hay, indicará el motivo por el cual la aplicación está bloqueada para su uso. Haz clic en **Detalles del bloqueo** para verificar [la solución](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/support/23066) para el bloqueo informado.
```

2022-02-07 15:13 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> +> Tenga en cuenta que cuando eliminas una aplicación, tu tienda ya no recibirá pagos a través de la integración asociada con la aplicación y se perderán todas las configuraciones, incluidas las crede
```suggestion
> Ten en cuenta que cuando eliminas una aplicación, tu tienda ya no recibirá pagos a través de la integración asociada con la aplicación y se perderán todas las configuraciones, incluidas las credenciales asociadas. Una vez que se elimina una aplicación, no se puede recuperar.
```

2022-02-07 15:14 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> +* **Nombre e ID de la aplicación**. En esta área puede seleccionar la aplicación que desee en función de su ID. Simplemente haga clic en el número que se muestra y seleccione la identificación desead
```suggestion
* **Nombre e ID de la aplicación**. En esta área puede seleccionar la aplicación que desees en función de su ID. Simplemente haz clic en el número que se muestra y selecciona la identificación deseada.
```

2022-02-07 15:15 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> +Se presentan las credenciales de producción y prueba necesarias para acceder a su aplicación. Las **credenciales de prueba** deben usarse para probar sus integraciones y se pueden usar junto con tarj
```suggestion
Se presentan las credenciales de producción y prueba necesarias para acceder a tu aplicación. Las **credenciales de prueba** deben usarse para probar tus integraciones y se pueden usar junto con tarjetas de crédito de prueba para simular recibos de tarjetas, mientras que las **credenciales de producción** se usan para recibir pagos.
```

2022-02-07 15:16 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> +> Si no eres desarrollador, te recomendamos integrar Mercado Pago con tu tienda a través de [plugins y plataformas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/gguides/plugins) y obtén
```suggestion
> Si no eres desarrollador, te recomendamos integrar Mercado Pago con tu tienda a través de [plugins y plataformas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/gguides/plugins). Obtén tus credenciales a través de tu cuenta de Mercado Pago en **Tu negocio > Configuración > Gestión y Administración > Credenciales**.  Lee [Credenciales](https://www.mercadopago[FAKER][URL][DOMINIO]/developers/en/guides/resources/credentials) para más información.
```

2022-02-07 15:17 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> +Configure las URL de producción y prueba desde las que se recibirán las notificaciones de webhook y seleccione los eventos que serán responsables de generar estas notificaciones. Lee [Webhooks](https
```suggestion
Configura las URL de producción y prueba desde las que se recibirán las notificaciones de webhook y selecciona los eventos que serán responsables de generar estas notificaciones. Lee [Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/notifications/webhooks) para más información.
```

2022-02-07 15:18 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> +> Vea informaciónes a cerca de cuentas de terceros que se le ha dado permiso para usar.
```suggestion
> Accede a información acerca de cuentas de terceros que se te ha dado permiso para usar.
```

2022-02-07 15:20 UTC, romisoto commented on guides/resources/dashboard/certification.en.md
> +The **certificates** can be downloaded from your computer's local files, in addition to having different colors for each certification and an authentication QR Code. The file can also be shared on so
aca seria FROM o TO your computer´s local files?

2022-02-07 15:24 UTC, romisoto commented on guides/resources/dashboard/certification.en.md
> +> Check informations about regarding third-party accounts that you have been given permission to use.
```suggestion
> Check information regarding third-party accounts that you have been given permission to use.
```

2022-02-07 15:26 UTC, romisoto commented on guides/resources/dashboard/certification.es.md
> +Las **insignias** actúan como una insignia para identificar a los desarrolladores que ya completaron nuestro proceso de certificación oficial y, al igual que los certificados, tienen diferentes color
lo mismo que en la versión en inglés, suena extraño, tal vez podrias poner algo como "Las insignias actúan como una forma de identificar..."

2022-02-07 15:27 UTC, romisoto commented on guides/resources/dashboard/certification.es.md
> +Consulte la página [&lt;dev&gt;program](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/developer-program) para obtener más información.
```suggestion
Consulta la página [&lt;dev&gt;program](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/developer-program) para obtener más información.
```

2022-02-07 15:29 UTC, romisoto commented on guides/resources/dashboard/header.en.md
> +The header contains your identification as an integrating user of Mercado Pago. Your ID is made up of two IDs.
"integrating user of" = "a member of" ??

2022-02-07 15:33 UTC, romisoto commented on guides/resources/dashboard/header.es.md
> +El encabezado contiene su identificación como usuario integrante de Mercado Pago. Su DNI se compone de dos DNI.
```suggestion
El encabezado contiene tu identificación como usuario integrante de Mercado Pago. Tu ID se compone de dos ID.
```

2022-02-07 15:33 UTC, romisoto commented on guides/resources/dashboard/header.es.md
> +Número único que lo identifica como miembro del **&lt;dev&gt;program** generado automáticamente después de su primera certificación exitosa. Se encuentra junto a tu ID de Mercado Pago (ID de usuario)
```suggestion
Número único que te identifica como miembro del **&lt;dev&gt;program** generado automáticamente después de tu primera certificación exitosa. Se encuentra junto a tu ID de Mercado Pago (ID de usuario) y solo aparece después de que se haya generado.
```

2022-02-07 15:34 UTC, romisoto commented on guides/resources/dashboard/header.es.md
> +Consulta la página del [&lt;dev&gt;program](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/developer-program) y realiza la certificación del producto deseado, recibe tu ID de integrador e
```suggestion
Consulta la página del [&lt;dev&gt;program](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/developer-program) y realiza la certificación del producto deseado, recibe tu ID de integrador e introdúcelo en tus integraciones para recibir beneficios adicionales.
```

2022-02-07 15:35 UTC, romisoto commented on guides/resources/dashboard/header.es.md
> +> Vea informaciónes acerca de sus aplicaciones creadas.
```suggestion
> Accede a información acerca de tus aplicaciones creadas.
```

2022-02-07 15:39 UTC, romisoto commented on guides/resources/dashboard/integration.en.md
> +> Check informations about your certifications in our certified developer program (**&lt;dev&gt;program**).
```suggestion
> Check information about your certifications in our certified developer program (**&lt;dev&gt;program**).
```

2022-02-07 15:41 UTC, romisoto commented on guides/resources/dashboard/integration.es.md
> +2. Complete el correo electrónico de la cuenta para la cual se solicitarán las credenciales.
```suggestion
2. Completa el correo electrónico de la cuenta para la cual se solicitarán las credenciales.
```

2022-02-07 15:41 UTC, romisoto commented on guides/resources/dashboard/integration.es.md
> +> Vea informaciónes a cerca de sus certificaciones en nuestro programa de desarrolladores certificados (**&lt;dev&gt;program**).
```suggestion
> Accede a información a cerca de tus certificaciones en nuestro programa de desarrolladores certificados (**&lt;dev&gt;program**).
```

2022-02-07 15:42 UTC, romisoto commented on guides/resources/dashboard/introduction.en.md
> +The [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) is your integration management environment automatically created with an user ID for you when you open a Mercado Pago account
```suggestion
The [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) is your integration management environment automatically created with a user ID for you when you open a Mercado Pago account. In it you can create, edit and delete applications.
```

2022-02-07 15:43 UTC, romisoto commented on guides/resources/dashboard/introduction.es.md
> +El [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) es tu entorno de gestión de integración. Es creado automáticamente con una identificación de usuario para tí con solo abrir un
```suggestion
El [Dashboard](https://mercadopago[FAKER][URL][DOMAIN]/developers/panel) es tu entorno de gestión de integración. Es creado automáticamente con un ID de usuario para tí con solo abrir una cuenta de Mercado Pago. En él puedes crear, editar y eliminar aplicaciones.
```

2022-02-07 15:44 UTC, romisoto commented on guides/resources/dashboard/introduction.es.md
> +* **Tus aplicaciones**: muestra sus aplicaciones creadas y le permite crear otras nuevas.
```suggestion
* **Tus aplicaciones**: muestra tus aplicaciones creadas y te permite crear otras nuevas.
```

2022-02-07 15:44 UTC, romisoto commented on guides/resources/dashboard/introduction.es.md
> +* **Tus certificaciones**: información a cerca de sus certificaciones en nuestro programa de desarrolladores certificados (**&lt;dev&gt;program**).
```suggestion
* **Tus certificaciones**: información acerca de tus certificaciones en nuestro programa de desarrolladores certificados (**&lt;dev&gt;program**).
```

2022-02-07 15:45 UTC, romisoto commented on guides/resources/dashboard/introduction.es.md
> +> Vea el resumen de sus datos.
```suggestion
> Accede al resumen de tus datos.
```

2022-02-07 15:45 UTC, romisoto commented on guides/security/oauth/apis-map.en.md
> +The following actions are available for OAuth.
```suggestion
The following actions are available for **OAuth**.
```

2022-02-07 15:46 UTC, romisoto commented on guides/security/oauth/apis-map.es.md
> +Las siguientes acciones están disponibles para OAuth.
```suggestion
Las siguientes acciones están disponibles para **OAuth**.
```

2022-02-07 15:53 UTC, romisoto commented on guides/security/oauth/creation.en.md
> +The authorization_code flow is characterized by the intervention of the seller to explicitly authorize the application's access to their data and by the use of a code granted by the authentication se
```suggestion
The `authorization_code` flow is characterized by the intervention of the seller to explicitly authorize the application's access to their data and by the use of a code granted by the authentication server so that the application can obtain an access token and an associated refresh token.
```

2022-02-07 15:54 UTC, romisoto commented on guides/security/oauth/creation.en.md
> +| Seller Mercado Pago Accounts | Mercado Pago seller accounts will be required. One for you and one for the seller. | Seller account in Mercado Pago. If you don't have one, [clik here](https://www.me
```suggestion
| Mercado Pago Seller Accounts | Mercado Pago seller accounts will be required. One for you and one for the seller. | Seller account in Mercado Pago. If you don't have one, [click here](https://www.mercadopago[FAKER][URL[DOMAIN]/hub/registration/landing) to create it. |
```

2022-02-07 15:55 UTC, romisoto commented on guides/security/oauth/creation.en.md
> +| Credentials | The [credenciales](https://www.mercadopago[FAKER][URL[DOMAIN]/developers/en/guides/resources/credentials) are unique passwords with which we identify an integration in your account, a
```suggestion
| Credentials | The [credentials](https://www.mercadopago[FAKER][URL[DOMAIN]/developers/en/guides/resources/credentials) are unique passwords with which we identify an integration in your account, and are used to securely capture payments in virtual stores and other applications. | To test and ensure the integration works, test credentials will be required. After this step, you will need production credentials to receive actual payments. |
```

2022-02-07 15:58 UTC, romisoto commented on guides/security/oauth/creation.en.md
> +1. Edit your application so that it contains your Redirect URL. See [Edit Application]().
aca falta el link

2022-02-07 15:58 UTC, romisoto commented on guides/security/oauth/creation.en.md
> +  - **client_id**: replace the "APP_ID" value with your app ID. Check [Application ID]().
falta el link

2022-02-07 16:06 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +> Recuerda que utilizarás información sensible de tus vendedores. Asegúrate de guardarlos de forma segura. No los utilices en la URL de autenticación y gestiona todo el proceso únicamente desde tu se
```suggestion
> Recuerda que utilizarás información sensible de tus vendedores. Asegúrate de guardarla de forma segura. No la utilices en la URL de autenticación y gestiona todo el proceso únicamente desde tu servidor.
```

2022-02-07 16:06 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +1. Edita tu aplicación para que contenga tu Redirect URL. Consulta [Editar aplicación]().
falta el link

2022-02-07 16:07 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +2. Envie a URL de autenticación para o vendedor cuja conta você deseja vincular à sua com os seguintes campos:
```suggestion
2. Envía la URL de autenticación al vendedor cuya cuenta quieres vincular a la tuya con los siguientes campos:
```

2022-02-07 16:07 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +  - **client_id**: edita tu aplicación para que contenga tu Redirect URL. Consulta [Editar aplicación]().
falta el link

2022-02-07 16:08 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +> Se recomienda realizar este procedimiento de una única vez junto con el usuario, ya que el código recibido por la Redirect URL después de la autorización tiene una validez de 10 minutos y el access
aqui seria usuario o vendedor?

2022-02-07 16:08 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +> Vea el flujo de renovación de un access token caducado.
```suggestion
> Lee sobre el flujo de renovación de un access token caducado.
```

2022-02-07 17:41 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +1. Selecione “Nova aplicação” ou “Criar sua primeira aplicação”.
@hgaldino - migo, as aplicações são criadas diretamente no Dashboard, certo? Pelo sim pelo não, eu colocaria como primeiro etapa:

1. Acesse o seu Dashboard com login e senha.
2. Em Suas Aplicações, selecione "Nova aplicação” ou “Criar sua primeira aplicação”.
3. Defina um nome para a aplicação.
4. e assim por diante.

O que acha?

2022-02-07 17:43 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +## Gerenciar aplicação
@hgaldino - não devemos colocar título 2 e logo em seguida um título 3... Aqui acho que vale ou colocar uma intro logo abaixo de título 2 ou logo abaixo de "Gerenciar aplicação" começar falando sobre a edição, saca? Talvez isso mude com os guias independentes BUT, por ora acho que seria o correto :)

2022-02-07 17:44 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> + - *Nome da aplicação (limite de 50 caracteres)*.
@hgaldino - migo, não entendi os nomes estarem todos em itálico. O que estão em EN até que tudo bem...Mas todos os outros o correto é deixarmos normal, tá? Vale aqui fazer a alteração.

2022-02-07 17:46 UTC, romisoto commented on guides/security/oauth/introduction.en.md
> +OAuth is an authorization protocol that allows applications to have limited access to the private information of Mercado Pago accounts, through the HTTP protocol that introduces an authentication and
```suggestion
OAuth is an authorization protocol that allows applications to have limited access to the private information of Mercado Pago accounts, through the HTTP protocol that introduces an authentication and authorization layer in which you request access to the protected resources of sellers, through an access token limited to a particular application, without the need for the credentials of the sellers through the access flows.
```

2022-02-07 17:47 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> + - *Nome da aplicação (limite de 50 caracteres)*.
Uma outra observação: Na frente de cada bullet deveríamos ter uma breve explicação do que se trata? Por exemplo.

- Nome da aplicação: Nome definido para identificação da aplicação criada (não deve ultrapassar o limite de 50 caracteres).
- Permissões da aplicação: campo onde estão disponíveis as opções de acesso da sua aplicação...

E assim por diante, saca?

2022-02-07 17:47 UTC, romisoto commented on guides/security/oauth/introduction.en.md
> +The flujos, also called grant types, refer to the way in which an application obtains an access token that allows accessing the data displayed through an API. In the case of Mercado Pago, there are t
```suggestion
The flows, also called grant types, refer to the way in which an application obtains an access token that allows accessing the data displayed through an API. In the case of Mercado Pago, there are two available access flows: `authorization_code` and `refresh_token`. In both flows, the main entities involved in the processes are:
```

2022-02-07 17:47 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +* **Produto a ser integrado**. Esta seção define o produto a ser integrado na sua aplicação. O campo "Produtos disponíveis" apresenta a lista de produtos disponíveis a serem integrados. Por padrão, o
@hgaldino falta o bullet nessa aqui também?

2022-02-07 17:48 UTC, romisoto commented on guides/security/oauth/introduction.en.md
> +* **Access token**: code used in different requests of public origin to access a protected resource that represents an authorization granted by a vendor to a client application that contains scopes a
```suggestion
* **Access token**: code used in different requests of public origin to access a protected resource that represents an authorization granted by a seller to a client application that contains scopes and a limited period of time for such access.
```

2022-02-07 17:50 UTC, romisoto commented on guides/security/oauth/introduction.es.md
> +> Important
```suggestion
> Importante
```

2022-02-07 17:51 UTC, romisoto commented on guides/security/oauth/introduction.es.md
> +> Conozca el flujo de autorización de acceso a datos.
```suggestion
> Conoce el flujo de autorización de acceso a datos.
```

2022-02-07 17:51 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +Caso você precise por algum motivo, excluir uma aplicação, basta clicar em "Excluir" e confirmar a ação na caixa de diálogo.
@hgaldino sei que parece meio óbvio, mas vale colocar o passo a passo. Por exemplo.

Caso seja necessário excluir uma aplicação em seu Dashboard, clique nos 3 pontos verticais na card da aplicação e selecione a opção **Excluir**

(aí acho que vale colocar um gif ilustrando).

2022-02-07 17:52 UTC, romisoto commented on guides/security/oauth/management.en.md
> +* **Laundering of credentials for raud**: it is possible that the Information Security and Fraud Prevention department performs a complete update of a user's credentials. This triggers the deletion o
```suggestion
* **Laundering of credentials for fraud**: it is possible that the Information Security and Fraud Prevention department performs a complete update of a user's credentials. This triggers the deletion of all tokens and temporal grants associated with the seller in question.
```

2022-02-07 17:52 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +> Atenção
```suggestion
> Importante
```

2022-02-07 17:53 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +* **Notificações webhook**. Eventos que você pode receber através chamadas POST HTTP toda vez que houver um evento relacionado a transações na sua aplicação. Leia [Webhooks](https://www.mercadopago[F
```suggestion
* **Notificações webhook:** Eventos que você pode receber através chamadas POST HTTP toda vez que houver um evento relacionado a transações na sua aplicação. Leia [Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/webhooks) para mais informações para mais informações.
```

2022-02-07 17:53 UTC, romisoto commented on guides/security/oauth/management.en.md
> +Management
```suggestion
# Management
```

2022-02-07 17:54 UTC, romisoto commented on guides/security/oauth/management.es.md
> +Actualmente existen diferentes formas en las que los **access token** y las **temporal grant** creadas se pueden deshabilitar e invalidar para autorizar solicitudes de recursos protegidos o para camb
```suggestion
Actualmente existen diferentes formas en las que los **access tokens** y las **temporal grants** creadas se pueden deshabilitar e invalidar para autorizar solicitudes de recursos protegidos o para cambiarlos por nuevos tokens.
```

2022-02-07 17:55 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +Os IDs servem para que você possa identificar as suas aplicações e são criados automaticamente sempre que uma nova aplicação for criada.
```suggestion
Os IDs da aplicação são números de identificação criados automaticamente que permitem localizar as aplicações sempre que uma nova aplicação for criada.
```

2022-02-07 17:55 UTC, romisoto commented on guides/security/oauth/management.es.md
> +> Vea videos tutoriales y acceda a las API.
```suggestion
> Accede a videos tutoriales y a las API.
```

2022-02-07 17:56 UTC, romisoto commented on guides/security/oauth/renewal.en.md
> +The flow allows you to continue using a valid access token with the same characteristics as the original token without the need for a new interaction with the user. By performing this flow, the origi
al final de la 1ra oracion es "user" o "seller"?

2022-02-07 17:57 UTC, romisoto commented on guides/security/oauth/renewal.en.md
> +The flow allows you to continue using a valid access token with the same characteristics as the original token without the need for a new interaction with the user. By performing this flow, the origi
```suggestion
The flow allows you to continue using a valid access token with the same characteristics as the original token without the need for a new interaction with the user. By performing this flow, the original token is exchanged for a new one which also offers the ability to limit scopes by returning a new refresh token for future exchange.
```

2022-02-07 17:59 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +Configure as URLs de produção e teste da qual serão recebidas as notificações webhook e selecione os eventos que serão responsáveis por gerar essas notificações. Leia [Webhooks](https://www.mercadopa
```suggestion
Configure as URLs de produção e teste da qual serão recebidas as notificações webhook e selecione os eventos que serão responsáveis por gerar essas notificações. Leia [Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/webhooks) para mais informações.
```

2022-02-07 18:00 UTC, romisoto commented on guides/security/oauth/renewal.es.md
> +> Solo es posible utilizar este flujo si la aplicación contiene el alcance `offline_access` y el vendedor ha autorizado previamente esta acción.
```suggestion
> Solo es posible utilizar este flujo si la aplicación contiene el scope `offline_access` y el vendedor ha autorizado previamente esta acción.
```

2022-02-07 18:01 UTC, rwaetemann commented on guides/resources/dashboard/aplications.pt.md
> +São apresentadas as credenciais de produção e de teste necessárias para acessar a sua aplicação. As **credenciais de teste** devem ser usadas para testar suas integrações e podem ser utilizadas em co
```suggestion
As credenciais são senhas únicas com as quais identificamos uma integração na sua conta. Servem para capturar pagamentos em lojas virtuais e outras aplicações de forma segura.

As **credenciais de teste** devem ser usadas para testar suas integrações e podem ser utilizadas em conjunto com os [cartões de crédito de teste](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/localization/local-cards para simular todo o fluxo de pagamento, enquanto as **credenciais de produção** são usadas para receber pagamentos reais.
```

2022-02-07 18:02 UTC, romisoto commented on guides/security/oauth/renewal.es.md
> +> Administración del OAuth.
```suggestion
> Administración de OAuth.
```

2022-02-07 18:02 UTC, rwaetemann commented on guides/resources/dashboard/header.pt.md
> +No cabeçalho consta sua identificação enquanto usuário integrador do Mercado Pago. Sua identificação é composta por dois IDs.
```suggestion
No cabeçalho consta sua identificação enquanto usuário integrador do Mercado Pago. Esta identificação é composta por dois IDs.
```

2022-02-07 18:03 UTC, rwaetemann commented on guides/resources/dashboard/header.pt.md
> +Número de identificação (Mercado Pago ID) gerado automaticamente na criação da conta no Mercado Pago. É um número único o ID que identifica o usuário Mercado Pago.
```suggestion
Número de identificação (Mercado Pago ID) gerado automaticamente na criação da conta no Mercado Pago. É um número único  que identifica o usuário Mercado Pago.
```

2022-02-07 18:03 UTC, rwaetemann commented on guides/resources/dashboard/header.pt.md
> +Número único que o identifica como membro do **&lt;dev&gt;program** gerado automaticamente após sua primeira certificação bem sucedida. Ele e está localizado ao lado de seu Mercado Pago ID (user ID)
```suggestion
Número único que o identifica como membro do **&lt;dev&gt;program** gerado automaticamente após sua primeira certificação bem sucedida. Ele está localizado ao lado de seu Mercado Pago ID (user ID) e é exibido somente após ser gerado.

2022-02-07 18:07 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> + - *Bloqueo de aplicaciones*. Si lo hay, indicará el motivo por el cual la aplicación está bloqueada para su uso. Haz clic en **Detalles del bloque** para verificar [la solución](https://www.mercadop
el link me dice que no encuentra la página

2022-02-07 18:08 UTC, romisoto commented on guides/resources/dashboard/aplications.es.md
> +* **Notificaciones de webhook**. Notificaciones que puedes recibir a través de llamadas HTTP POST siempre que haya un evento relacionado con una transacción en tu aplicación. Lee [Webhooks](https://w
al abrir el link me dice que la pagina no existe

2022-02-07 18:10 UTC, rwaetemann commented on guides/resources/dashboard/integration.pt.md
> +Você pode integrar soluções para outras contas além da sua própria. Quando estiver integrando soluções para outras contas, você pode solicitar acesso às credenciais desta conta de forma a manter a se
```suggestion
É possível integrar soluções para outras contas além da sua própria. Para isso, no momento de realizar a integração será necessário solicitar o acesso às credenciais da conta que irá integrar.

Siga os passos abaixo para saber como solicitar o acesso a essas credenciais.
```

2022-02-07 18:11 UTC, rwaetemann commented on guides/resources/dashboard/integration.pt.md
> +1. Clicar no botão "Solicitar credenciais".
@hgaldino - migo, onde que pede isso? Dentro do Dashboard? Se for, lembre-se sempre de colocar o local onde o usuário terá que estar para concluir as etapas.

1. Acesse o Dashboard.
2. Clique no botão xxx
3. Preencha o e-mail xxxxx
4. Confirme a solicitação....

2022-02-07 18:12 UTC, romisoto commented on guides/resources/dashboard/aplications.en.md
> +* **Webhook notifications**. Notifications received via HTTP POST calls whenever there is a transaction-related event in your application. Check [Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]
al abrir el link me dice que la pagina no existe

2022-02-07 18:12 UTC, rwaetemann commented on guides/resources/dashboard/introduction.pt.md
> +* **Contas que você integra**: informações a respeito de contas de terceiro das quais você recebeu permissão para utilizar.
```suggestion
* **Contas que você integra**: informações sobre contas de terceiro das quais você recebeu permissão para utilizar.
```

2022-02-07 18:12 UTC, rwaetemann commented on guides/resources/dashboard/introduction.pt.md
> +* **Suas certificações**: informações a respeito das suas certificações no nosso programa de desenvolvedores certificados (**&lt;dev&gt;program**).
```suggestion
* **Suas certificações**: informações sobre suas certificações no nosso programa de desenvolvedores certificados (**&lt;dev&gt;program**).
```

2022-02-07 18:14 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +| Cuentas de vendedor de Mercado Pago | Se requerirán cuentas de vendedor de Mercado Pago. Uno para ti y otro para el vendedor. | Cuenta de vendedor en Mercado Pago. Si no la tienes, haz [clic aquí](
el link me dice bloqueado, no se por que no me abre

2022-02-07 18:15 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +| Aplicación | Las aplicaciones son las distintas integraciones contenidas en una o varias tiendas. Puedes crear una aplicación para cada solución que implementes, con el fin de tener todo organizado
al abrir el link me dice bloqueado y queda la pagina en blanco

2022-02-07 18:17 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +| Credenciales | Las [credenciales](https://www.mercadopago[FAKER][URL[DOMAIN]/developers/es/guides/resources/credentials) son contraseñas únicas con las que identificamos una integración en tu cuent
al abrir el link me dice bloqueado y queda la pagina en blanco

2022-02-07 18:19 UTC, romisoto commented on guides/security/oauth/creation.es.md
> +| URL de autenticación | https://auth.mercadopago.com.br/authorization?client_id=APP_ID&response_type=code&platform_id=mp&state=RANDOM_ID&redirect_uri=https://www.redirect-url.com |
tal vez aqui seria mejor en los 3 idiomas cambiar la URL por un texto cliqueable como "clic aqui para acceder" que lleve a la url

2022-02-07 18:20 UTC, romisoto commented on guides/security/oauth/renewal.es.md
> +1. Envía el código del `refresh_token`, tus credenciales y el `authorization_code` (consulta [Creacióm](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/dashboard/creation))
la URL no me funciona en el scope local

2022-02-07 18:21 UTC, romisoto commented on guides/security/oauth/management.es.md
> +Puedes recibir notificaciones de webhook cada vez que un vendedor autorice o desautorice tu aplicación. Para configurarlos, lee [Creacióm](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/gu
```suggestion
Puedes recibir notificaciones de webhook cada vez que un vendedor autorice o desautorice tu aplicación. Para configurarlos, lee [Creación](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/dashboard/creation) a través del Dashboard.
```

2022-02-07 18:22 UTC, romisoto commented on guides/security/oauth/creation.en.md
> +| Seller Mercado Pago Accounts | Mercado Pago seller accounts will be required. One for you and one for the seller. | Seller account in Mercado Pago. If you don't have one, [clik here](https://www.me
al intentar abrir la url me dice "blocked"

2022-02-07 18:22 UTC, romisoto commented on guides/security/oauth/creation.en.md
> +| Application | Applications are the different integrations contained in one or more stores. You can create an application for each solution you implement, in order to have everything organized and m
al intentar abrir la url me dice "blocked"

2022-02-07 18:23 UTC, romisoto commented on guides/security/oauth/renewal.en.md
> +1. Send the `refresh_token` code, your **credentials**, and the `authorization_code` (see [Creation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/dashboard/creation)) to
el link de creation: al intentar abrir la url me dice "blocked"

2022-02-07 18:24 UTC, romisoto commented on guides/security/oauth/management.en.md
> +You can receive webhook notifications every time a seller authorizes or deauthorizes your application. To configure them, read [Creation](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/gui
el link de creation: al intentar abrir la url me dice "blocked"

2022-02-07 18:25 UTC, romisoto requested changes
Solo unas sugerencias!
encontre algunos links que no funcionan, en algunos no se por qué y en otros creo que falta parte de la URL (como el de webhooks que termina en webhooks/webhooks, creo!)

2022-02-08 04:04 UTC, hgaldino commented on guides/resources/dashboard/aplications.en.md
> +* **Webhook notifications**. Notifications received via HTTP POST calls whenever there is a transaction-related event in your application. Check [Webhooks](https://www.mercadopago[FAKER][URL][DOMAIN]
Ajustado!

2022-02-08 04:10 UTC, hgaldino commented on guides/security/oauth/creation.es.md
> +| URL de autenticación | https://auth.mercadopago.com.br/authorization?client_id=APP_ID&response_type=code&platform_id=mp&state=RANDOM_ID&redirect_uri=https://www.redirect-url.com |
é que nesse caso, Romi...o usuário precisa ver a URL mesmo porque ele precisa identificar o código que retorna em tal parâmetro.

2022-02-08 04:12 UTC, hgaldino commented on guides/security/oauth/renewal.es.md
> +1. Envía el código del `refresh_token`, tus credenciales y el `authorization_code` (consulta [Creacióm](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/dashboard/creation))
Ajustado!

2022-02-08 04:27 UTC, hgaldino commented on guides/resources/dashboard/certification.en.md
> +The **certificates** can be downloaded from your computer's local files, in addition to having different colors for each certification and an authentication QR Code. The file can also be shared on so
to! <3

2022-02-08 04:29 UTC, hgaldino commented on guides/resources/dashboard/certification.en.md
> +The **badges** act as a badge to identify developers who have already completed our official certification process and, like the certificates, have different colors for each type of certification. Th
<3

2022-02-08 04:31 UTC, hgaldino commented on guides/resources/dashboard/certification.es.md
> +Las **insignias** actúan como una insignia para identificar a los desarrolladores que ya completaron nuestro proceso de certificación oficial y, al igual que los certificados, tienen diferentes color
<3

2022-02-08 05:36 UTC, hgaldino commented on guides/resources/dashboard/aplications.pt.md
> +## Gerenciar aplicação
@rwaetemann miga, foi uma definição da Pri já pensando nos guias independentes do futuro...seriam menus separados, mas optamos por colocar tudo que fosse de aplicação em um mesmo local e separar por guias depois. =S

2022-02-08 05:39 UTC, hgaldino commented on guides/resources/dashboard/aplications.pt.md
> + - *Nome da aplicação (limite de 50 caracteres)*.
@rwaetemann miga vou tirar os itálicos super porque ficou feio também kkkkk e foi incluir as descrições nos dois primeiros campos. <3 

Sobre a questão dos bullets, eu tinha deixado desse jeito que você comentou (com dois pontos e a definição), mas Pri ajustou para o formato que está hoje e acabei deixando assim.

2022-02-09 17:49 UTC, merged