feature/new marketplace documentation
mercadopago/devsite-docs pull request #1570
Opened 2022-02-10 20:00 UTC by rwaetemann

## Description

A documentação de Marketplace foi reescrita usando como base a estrutura de How-to.

2022-02-10 20:10 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +> La comisión de Mercado Pago se descuenta de los fondos recibidos por el vendedor. Es decir, primero se descuenta la comisión de Mercado Pago y del resto se descuenta la comisión del marketplace.
```suggestion
> La comisión de Mercado Pago se descuenta de los fondos recibidos por el vendedor. Es decir, primero se descuenta la comisión de Mercado Pago y la comisión del marketplace se descuenta del saldo restante.
```

2022-02-10 20:10 UTC, hgaldino approved these changes

2022-02-10 20:10 UTC, hgaldino commented on guides/online-payments/marketplace/integrate-marketplace.pt.md
> +
```suggestion
```

2022-02-10 20:10 UTC, hgaldino commented on guides/online-payments/marketplace/integrate-marketplace.pt.md
> +
```suggestion
```

2022-02-10 20:10 UTC, hgaldino commented on guides/online-payments/marketplace/integrate-marketplace.pt.md
> +
```suggestion
```

2022-02-10 20:10 UTC, hgaldino commented on guides/online-payments/marketplace/integrate-marketplace.pt.md
> +
```suggestion
```

2022-02-10 20:11 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +Para realizar la integración deberá seguir el flujo de integración habitual del _checkout_ elegido utilizando necesariamente un token de acceso para cada vendedor, obtenido a través de OAuth. A conti
```suggestion
Para realizar la integración deberás seguir el flujo de integración habitual del _checkout_ elegido, utilizando necesariamente un token de acceso para cada vendedor, obtenido a través de OAuth. A continuación, enumeramos los pasos necesarios para integrar una caja con el _mercado_.
```

2022-02-10 20:11 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +1. Siga los pasos descritos en la OAuth para obtener cada `access_token`. Esta información será necesaria durante el proceso de integración de pago en el _marketplace_.
```suggestion
1. Sigue los pasos descritos en la  documentación de OAuth para obtener cada `access_token`. Esta información será necesaria durante el proceso de integración de pago en el _marketplace_.
```

2022-02-10 20:12 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +1. Siga los pasos descritos en la OAuth para obtener cada `access_token`. Esta información será necesaria durante el proceso de integración de pago en el _marketplace_.
aqui agregaria un link a la documentación de OAuth, que piensas?

2022-02-10 20:12 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +2. Elija el tipo de pago que desea ([Checkout Pro](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-pro/introduction) o [Checkout API](https://www.mercadopago
```suggestion
2. Elige el tipo de pago que desea ([Checkout Pro](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-pro/introduction) o [Checkout API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/introduction)) y sigue todo el flujo de integración.
```

2022-02-10 20:12 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +3. En la integración del _checkout_, use la `public_key` de su cuenta de integrador en el frontend e inserte el `access_token` del vendedor obtenido en el paso 1, en el backend o en el _header_ de la
```suggestion
3. En la integración del _checkout_, usa la `public_key` de tu cuenta de integrador en el frontend e inserta el `access_token` del vendedor obtenido en el paso 1, en el backend o en el _header_ de la solicitud.
```

2022-02-10 20:12 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +    - Si el checkout es Pro, complete el parámetro `marketplace_fee` con el porcentaje que se cobrará por cada preferencia de pago creada en la API **/checkout/preferences**.
```suggestion
    - Si el checkout es Pro, completa el parámetro `marketplace_fee` con el porcentaje que se cobrará por cada preferencia de pago creada en la API **/checkout/preferences**.
```

2022-02-10 20:13 UTC, romisoto commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +    - Si el checkout es transparente, complete el parámetro `application_fee` con el porcentaje que se cobrará por cada pago creado en la API **/payments**.
```suggestion
    - Si el checkout es transparente, completa el parámetro `application_fee` con el porcentaje que se cobrará por cada pago creado en la API **/payments**.
```

2022-02-10 20:13 UTC, romisoto requested changes
solo algunos cambios sugeridos!

2022-02-10 21:25 UTC, hgaldino approved these changes

2022-02-10 21:25 UTC, hgaldino commented on guides/online-payments/marketplace/integrate-marketplace.en.md
> +1. Follow the steps described in the OAuth documentation to get each `access_token`. This information will be needed during the checkout integration process into the marketplace.
```suggestion
1. Follow the steps described in the [OAuth documentation](https://www.mercadopago/[FAKER][URL][DOMAIN]/developers/en/guides/security/oauth/introduction) to get each `access_token`. This information will be needed during the checkout integration process into the marketplace.
```

2022-02-10 21:25 UTC, hgaldino commented on guides/online-payments/marketplace/integrate-marketplace.pt.md
> +1. Siga as etapas descritas na documentação OAuth para obter cada `access_token`. Esta informação será necessária durante o processo de integração do checkout ao _marketplace_.
```suggestion
1. Siga as etapas descritas na [documentação OAuth](https://www.mercadopago/[FAKER][URL][DOMAIN]/developers/pt/guides/security/oauth/introduction) para obter cada `access_token`. Esta informação será necessária durante o processo de integração do checkout ao _marketplace_.
```

2022-02-10 21:25 UTC, hgaldino commented on guides/online-payments/marketplace/integrate-marketplace.es.md
> +1. Sigue los pasos descritos en la  documentación de OAuth para obtener cada `access_token`. Esta información será necesaria durante el proceso de integración de pago en el _marketplace_.
```suggestion
1. Sigue los pasos descritos en la  [documentación de OAuth](https://www.mercadopago/[FAKER][URL][DOMAIN]/developers/en/guides/security/oauth/introduction) para obtener cada `access_token`. Esta información será necesaria durante el proceso de integración de pago en el _marketplace_.
```

2022-02-11 13:22 UTC, romisoto approved these changes

2022-02-11 13:23 UTC, merged