[DEVCOMMS-644] Doc Proximity
mercadopago/devsite-docs pull request #1574
Opened 2022-02-11 20:49 UTC by hgaldino

## Description
Documentação funcional de Proximity para Mercado Pago Delivery.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2022-03-09 12:52 UTC, romisoto commented on guides/mp-delivery/accept-order.en.md
> +> [Print order receipt](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/mp-delivery/print-order)
```suggestion
> [Print order receipt](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/mp-delivery/print-order-receipt)
```

2022-03-09 12:52 UTC, romisoto commented on guides/mp-delivery/accept-order.es.md
> +> [Imprimir recibo de pedido](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/print-order)
```suggestion
> [Imprimir recibo de pedido](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/print-order-receipt)
```

2022-03-09 14:01 UTC, romisoto requested changes
Te deje algunos comentarios! el documento que tiene la imagen no se visualiza en el scope, pero no ser por que

2022-03-09 14:01 UTC, romisoto commented on guides/mp-delivery/print-order-receipt.es.md
> +![recibo](/images/mp-delivery/recibo.png)
esto solo esta en ES, las versiones en EN & PT no lo tienen. Ademas dice "recibo.png" pero la imagen que tenemos abajo se llama "comprovante.png"

2022-03-11 14:33 UTC, hgaldino commented on guides/mp-delivery/api-map.en.md
> +# API map
Daleee!

2022-03-23 14:38 UTC, romisoto commented on guides/mp-delivery/accept-order.en.md
> +> It is important to know that only in the states **ready_to_ship** and **ready_to_print** it is possible to accept an order. After accepting the order, the substatus will be “printed”. If the order
```suggestion
> It is important to know that only in the statuses **ready_to_ship** and **ready_to_print** it is possible to accept an order. After accepting the order, the substatus will be “printed”. If the order is not accepted 5 minutes after its creation, it will be automatically cancelled.
```

2022-03-23 14:40 UTC, romisoto commented on guides/mp-delivery/accept-order.es.md
> +Cuando el estado de entrega sea **Ready_to_ship**, puedes aceptar el pedido.
```suggestion
Cuando el estado de entrega sea **Ready_to_ship**, puedes aceptar la orden.
```

2022-03-23 14:40 UTC, romisoto commented on guides/mp-delivery/accept-order.es.md
> +Para aceptar el pedido que fue confirmado en el PDV/POS, realiza un PUT enviando el `shipment_id` y el `access-token` (generado por el proceso de autenticación OAuth) al endpoint [/proximity-integrat
```suggestion
Para aceptar  la orden que fue confirmada en el PDV/POS, realiza un PUT enviando el `shipment_id` y el `access-token` (generado por el proceso de autenticación OAuth) al endpoint [/proximity-integration/shipments/{shipment_id}/accept](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/mp_delivery/_proximity-integration_shipments_shipment_id_accept/put). Consulta [Seguridad](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/security/oauth/introduction) para obtener más información sobre OAuth.
```

2022-03-23 14:41 UTC, romisoto commented on guides/mp-delivery/accept-order.es.md
> +Al aceptar el pedido, se cambiará el estado y en la respuesta se indicará el estado del nuevo pedido.
```suggestion
Al aceptar la orden, se cambiará el estado y en la respuesta se indicará el estado de la nueva orden.
```

2022-03-23 14:43 UTC, romisoto commented on guides/mp-delivery/accept-order.es.md
> +> Es importante saber que solo en los estados **ready_to_ship** y **ready_to_print** es posible aceptar un pedido. Después de aceptar el pedido, el subestado será "impreso". Si el pedido no es acepta
```suggestion
> Es importante saber que solo es posible aceptar una orden en los estados **ready_to_ship** y **ready_to_print**. Después de aceptar la orden, el subestado será **printed**. Si la orden no es aceptada 5 minutos después de su creación, se cancelará automáticamente.
```

2022-03-23 14:43 UTC, romisoto commented on guides/mp-delivery/accept-order.es.md
> +> Imprimir recibo de pedido
```suggestion
> Imprimir recibo de orden
```

2022-03-23 14:45 UTC, romisoto commented on guides/mp-delivery/accept-order.es.md
> +> [Imprimir recibo de pedido](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/print-order-receipt)
```suggestion
> [Imprimir recibo de orden](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/print-order-receipt)
```

2022-03-23 14:46 UTC, romisoto commented on guides/mp-delivery/cancel-order.en.md
> +To cancel a request that was accepted in the POS, perform a put sending the `shipment_id` and the` access-token` (generated by the OAuth authentication process) to the endpoint [/proximity-integratio
```suggestion
To cancel an order that was accepted in the POS, perform a PUT sending the `shipment_id` and the` access-token` (generated by the OAuth authentication process) to the endpoint [/proximity-integration/shipment/{shipment_id}/cancel](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/mp_delivery/_proximity-integration_shipments_shipment_id_cancel/put). 
```

2022-03-23 14:47 UTC, romisoto commented on guides/mp-delivery/cancel-order.en.md
> +> Learn how to consult and manage informations of stores.
```suggestion
> Learn how to consult and manage store information.
```

2022-03-23 14:48 UTC, romisoto commented on guides/mp-delivery/cancel-order.es.md
> +> Aprende a consultar y gestionar informaciónes de sus tiendas.
```suggestion
> Aprende a consultar y gestionar la información de tu tienda.
```

2022-03-23 14:51 UTC, romisoto commented on guides/mp-delivery/change-store-external-id.es.md
> +# Cambiar ID externo de la tienda
en Galileo el nombre de este menu es distinto, podríamos ponerlo en Galileo igual que aca

2022-03-23 14:53 UTC, romisoto commented on guides/mp-delivery/change-store-external-id.es.md
> +# Cambiar ID externo de la tienda
```suggestion
# Cambiar ID externo de la sucursal
```

2022-03-23 14:54 UTC, romisoto commented on guides/mp-delivery/cancel-order.es.md
> +> [Administración de tiendas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/store-management)
```suggestion
> [Administración de sucursales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/store-management)
```

2022-03-23 14:55 UTC, romisoto commented on guides/mp-delivery/change-store-external-id.es.md
> +Para ingresar el valor de una ID externa en una tienda, realice un PUT enviando el `store_id` y el `access-token` (generados por el proceso de autenticación OAuth) al punto final [/proximity-integrat
```suggestion
Para ingresar el valor de una ID externa en una sucursal, realiza un PUT enviando el `store_id` y el `access-token` (generados por el proceso de autenticación OAuth) al punto final [/proximity-integration/stores/{StoreID}/external_id](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/mp_delivery/_proximity-integration_store_id_external_id/put). Consulta [Seguridad](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/security/oauth/introduction) para obtener más información sobre OAuth.
```

2022-03-23 14:56 UTC, romisoto commented on guides/mp-delivery/change-store-external-id.es.md
> +> También podrás consultar la información de una tienda a través de su ID externo. Para eso, envíe como parámetros de solicitud el `user_id` relacionado con la tienda, el `external_id` y el `access_t
```suggestion
> También podrás consultar la información de una sucursal a través de su ID externo. Para eso, envía como parámetros de solicitud el `user_id` relacionado con la sucursal, el `external_id` y el `access_token`. Accede a más información en la API [Obtener sucursal por ID externo](https://www.mercadopago[FAKER][URL][DOMINIO]/developers/pt/reference/mp_delivery/_proximity-integration_users_SellerID_stores_external_id_ExternalID/get).
```

2022-03-23 14:56 UTC, romisoto commented on guides/mp-delivery/change-store-external-id.es.md
> +> Aprenda a cambiar el estado de funcionamiento de la tienda de la tienda.
```suggestion
> Aprende a cambiar el estado de funcionamiento de la sucursal
```

2022-03-23 14:57 UTC, romisoto commented on guides/mp-delivery/change-store-external-id.es.md
> +> [Cambiar estado de tienda](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guias/mp-delivery/change-store-status)
```suggestion
> [Cambiar estado de una sucursal](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guias/mp-delivery/change-store-status)
```

2022-03-23 14:59 UTC, romisoto commented on guides/mp-delivery/change-store-status.en.md
> +The health statuses are defined as follows:
```suggestion
The peformance statuses are defined as follows:
```

2022-03-23 15:00 UTC, romisoto commented on guides/mp-delivery/change-store-status.es.md
> +Los estados de salud se definen de la siguiente manera:
```suggestion
Los estados de funcionamiento se definen de la siguiente manera:
```

2022-03-23 15:02 UTC, romisoto commented on guides/mp-delivery/change-store-status.es.md
> +Para cambiarlos, debe realizar un PUT enviando el `store_id` y el `access-token` (generados por el proceso de autenticación OAuth) al endpoint [/proximity-integration/stores/{store_id}/status](https:
```suggestion
Para cambiarlos, debes realizar un PUT enviando el `store_id` y el `access-token` (generados por el proceso de autenticación OAuth) al endpoint [/proximity-integration/stores/{store_id}/status](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/mp_delivery/_proximity-integration_users_seller_id_stores/get). Consulta [Seguridad](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/security/oauth/introduction) para obtener más información sobre OAuth.
```

2022-03-23 15:02 UTC, romisoto commented on guides/mp-delivery/change-store-status.es.md
> +> Cambiar ID externo de la tienda
```suggestion
> Cambiar ID externo de la sucursal
```

2022-03-23 15:02 UTC, romisoto commented on guides/mp-delivery/change-store-status.es.md
> +> Aprende a cambiar el ID externo de su tienda.
```suggestion
> Aprende a cambiar el ID externo de tu sucursal.
```

2022-03-23 15:03 UTC, romisoto commented on guides/mp-delivery/change-store-status.es.md
> +> [Cambiar ID externo de tienda](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/change-store-external-id)
```suggestion
> [Cambiar ID externo de sucursal](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/change-store-external-id)
```

2022-03-23 15:08 UTC, romisoto commented on guides/mp-delivery/get-order-data.en.md
> +  * **Ready_to_ship**: this state has two substates that denote that an order is deliverable (because it has been received and can be accepted or because it has been accepted and can be printed).
aca seria state/substate o status/substatus?

2022-03-23 15:09 UTC, romisoto commented on guides/mp-delivery/get-order-data.en.md
> +* **Extension.substatus**: substate in which the order is. The substate relates directly to the state.
state/substate o status/substatus

2022-03-23 15:10 UTC, romisoto commented on guides/mp-delivery/get-order-data.es.md
> +Para consultar los datos de un pedido, realice un GET enviando `shipment_id` y `access-token` (generados por el proceso de autenticación OAuth) al endpoint[/proximity-integration/v1/orders/{shipmentI
```suggestion
Para consultar los datos de una orden, realiza un GET enviando `shipment_id` y `access-token` (generados por el proceso de autenticación OAuth) al endpoint[/proximity-integration/v1/orders/{shipmentId}](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/mp_delivery/_proximity-integrationorders_shipment_id/get). Consulta [Seguridad](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/security/oauth/introduction) para obtener más información sobre OAuth.
```

2022-03-23 15:10 UTC, romisoto commented on guides/mp-delivery/get-order-data.es.md
> +* **Merchant**: información sobre el restaurante que recibió el pedido.
```suggestion
* **Merchant**: información sobre el restaurante que recibió la orden.
```

2022-03-23 15:10 UTC, romisoto commented on guides/mp-delivery/get-order-data.es.md
> +* **Discounts**: descuentos aplicados al pedido.
```suggestion
* **Discounts**: descuentos aplicados a la orden.
```

2022-03-23 15:10 UTC, romisoto commented on guides/mp-delivery/get-order-data.es.md
> +* **Total**: importe total pagado en un pedido.
```suggestion
* **Total**: importe total pagado en una orden.
```

2022-03-23 15:11 UTC, romisoto commented on guides/mp-delivery/get-order-data.es.md
> +* **Payments**: información sobre el método de pago de un pedido.
```suggestion
* **Payments**: información sobre el método de pago de una orden.
```

2022-03-23 15:14 UTC, romisoto commented on guides/mp-delivery/integration.en.md
> +4. Use available APIs to manage orders. Check [Order management](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/mp-delivery/order-management).
```suggestion
4. Use available APIs to manage orders. Check [Order management](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/mp-delivery/order-management).
```

2022-03-23 15:17 UTC, romisoto commented on guides/mp-delivery/integration.es.md
> +3. Utiliza las API disponibles para consultar y gestionar informaciónes de sus tiendas. Ver [Administración de tiendas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/proximity-mp-d
```suggestion
3. Utiliza las API disponibles para consultar y gestionar información de tus sucursales. Ver [Administración de tiendas](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/store-management).
```

2022-03-23 15:17 UTC, romisoto commented on guides/mp-delivery/integration.es.md
> +4. Utiliza las API disponibles para gestionar las órdenes. Ver [Administración de órdenes](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/proximity-mp-delivery/order-management).
```suggestion
4. Utiliza las API disponibles para gestionar las órdenes. Ver [Administración de órdenes](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/order-management).
```

2022-03-23 15:19 UTC, romisoto commented on guides/mp-delivery/introduction.en.md
> +* Close the cashier efficiently using the already integrated reconciliation solution, displaying in detail all the financial transactions carried out.
```suggestion
* Close the cash register efficiently using the already integrated reconciliation solution, displaying in detail all the financial transactions carried out.
```

2022-03-23 15:20 UTC, romisoto commented on guides/mp-delivery/introduction.es.md
> +Puedes integrar el TPV/POS de tu restaurante con Mercado Pago Delivery para:
```suggestion
Puedes integrar el PDV/POS de tu restaurante con Mercado Pago Delivery para:
```

2022-03-23 15:21 UTC, romisoto commented on guides/mp-delivery/introduction.es.md
> +El **Gestor de Pedidos** es una herramienta encargada de controlar todo el flujo de un pedido. Para acceder a él, en el [panel de usuario de Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/
```suggestion
El **Gestor de Pedidos** es una herramienta encargada de controlar todo el flujo de una orden. Para acceder a él, en el [panel de usuario de Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/home) haz clic en **Delivery > Order Manager**. Es solo para restaurantes que no cuentan con un software de gestión integrado con Mercado Pago, ya que no es posible integrar el Gestor con otro software de gestión de órdenes.
```

2022-03-23 15:22 UTC, romisoto commented on guides/mp-delivery/introduction.es.md
> +El software de gestión de pedidos, luego de realizar la integración, recibirá notificaciones de nuevos pedidos a través de un webhook registrado durante el proceso de creación de una aplicación dentr
```suggestion
El software de gestión de pedidos, luego de realizar la integración, recibirá notificaciones de nuevas órdenes a través de un webhook registrado durante el proceso de creación de una aplicación dentro de Mercado Pago.
```

2022-03-23 15:24 UTC, romisoto commented on guides/mp-delivery/previous-requirements.en.md
> +|Mercado Pago Account| It is necessary for the integrator to have an account on Mercado Pago in order to be able to generate their credentials. If you don't have it, [check here](https://www.mercadop
```suggestion
|Mercado Pago Account| It is necessary for the integrator to have an Mercado Pago account in order to be able to generate their credentials. If you don't have one, [check here](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) to create it.|
```

2022-03-23 15:25 UTC, romisoto commented on guides/mp-delivery/previous-requirements.en.md
> +|Credentials| The [credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) are unique passwords with which we identify an integration in your account and
```suggestion
|Credentials| The [credentials](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/resources/credentials) are unique passwords with which we identify an integration in your account , and which are used to capture payments in virtual stores and other applications securely.|
```

2022-03-23 15:27 UTC, romisoto commented on guides/mp-delivery/previous-requirements.es.md
> +|Credenciales| Las [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) son contraseñas únicas con las que identificamos una integración en tu cuenta
```suggestion
|Credenciales| Las [credenciales](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/credentials) son contraseñas únicas con las que identificamos una integración en tu cuenta, y que sirven para capturar pagos en tiendas virtuales y otras aplicaciones de forma segura.|
```

2022-03-23 15:29 UTC, romisoto commented on guides/mp-delivery/print-order-receipt.es.md
> +> Conoce cómo cancelar pedidos en Mercado Pago Delivery.
```suggestion
> Conoce cómo cancelar órdenes en Mercado Pago Delivery.
```

2022-03-23 15:29 UTC, romisoto commented on guides/mp-delivery/print-order-receipt.es.md
> +> [Cancelar pedido](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/cancel-order)
```suggestion
> [Cancelar orden](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/cancel-order)
```

2022-03-23 16:45 UTC, romisoto commented on guides/mp-delivery/store-data.es.md
> +Para obtener información sobre todas las tiendas que están vinculadas a **un usuario específico**, realice un GET enviando el `user_id` y el `access-token` (generados por el proceso de autenticación
```suggestion
Para obtener información sobre todas las sucursales que están vinculadas a **un usuario específico**, realice un GET enviando el `user_id` y el `access-token` (generados por el proceso de autenticación de OAuth) al punto final [[/proximity-integration/users/{seller_id}/stores](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/mp_delivery/_proximity-integration_users_seller_id_stores/get). Consulte [Seguridad](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/security/oauth/introduction) para obtener más información sobre OAuth.
```

2022-03-23 16:46 UTC, romisoto commented on guides/mp-delivery/store-data.es.md
> +También es posible consultar información de una **tienda específica** usando su **ID**. Para ello, realiza un GET enviando el `store_id` y el `access-token` al endpoint [/proximity-integration/stores
```suggestion
También es posible consultar información de una **sucursal específica** usando su **ID**. Para ello, realiza un GET enviando el `store_id` y el `access-token` al endpoint [/proximity-integration/stores/{StoreID}](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/mp_delivery/_proximity-integration_stores_store_id/get).
```

2022-03-23 16:48 UTC, romisoto commented on guides/mp-delivery/store-data.es.md
> +> También podrás consultar la información de una tienda a través de su ID externo, si lo tiene. Para eso, envíe como parámetros de solicitud el `user_id` relacionado con la tienda, el `external_id` y
```suggestion
> También podrás consultar la información de una sucursal a través de su ID externo, si lo tiene. Para eso, envía como parámetros de solicitud el `user_id` relacionado con la sucursal, el `external_id` y el `access_token`. Accee a más información en la API [Obtener sucursal por ID externo](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/mp_delivery/_proximity-integration_users_SellerID_stores_external_id_ExternalID/get).
```

2022-03-23 16:48 UTC, romisoto commented on guides/mp-delivery/store-data.es.md
> +> Para saber cómo crear un ID externo para tu tienda y utilizarlo como identificador para el sistema de software de gestión de pedidos, accede a [Cambiar ID externo de la tienda](https://www.mercadop
```suggestion
> Para saber cómo crear un ID externo para tu sucursal y utilizarlo como identificador para el sistema de software de gestión de pedidos, accede a [Cambiar ID externo de la sucursal](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/mp_delivery/change-store-external-id)
```

2022-03-23 16:48 UTC, romisoto commented on guides/mp-delivery/store-data.es.md
> +> Cambiar el estado de la tienda
```suggestion
> Cambiar el estado de la sucursal
```

2022-03-23 16:51 UTC, romisoto commented on guides/mp-delivery/store-management.es.md
> +# Administración de la tienda
```suggestion
# Administración de la sucursal
```

2022-03-23 16:53 UTC, romisoto commented on guides/mp-delivery/store-management.es.md
> +> Más información sobre cómo obtener datos de la tienda.
```suggestion
> Más información sobre cómo obtener datos de la sucursal.
```

2022-03-23 16:53 UTC, romisoto commented on guides/mp-delivery/store-management.es.md
> +> [Obtener datos de la tienda](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/store-data)
```suggestion
> [Obtener datos de la sucursal](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/mp-delivery/store-data)
```

2022-03-23 16:53 UTC, romisoto requested changes
solo unas sugerencias!

2022-03-23 18:34 UTC, hgaldino commented on guides/mp-delivery/get-order-data.en.md
> +  * **Ready_to_ship**: this state has two substates that denote that an order is deliverable (because it has been received and can be accepted or because it has been accepted and can be printed).
status! <3

2022-03-23 19:03 UTC, romisoto approved these changes

2022-04-25 16:30 UTC, closed without merging