[DEVCOMMS-675] Reescritura de la documentación de IPN
mercadopago/devsite-docs pull request #1577
Opened 2022-02-14 21:00 UTC by romisoto

## Description

Se reescribe la documentación de IPN para agregar y actualizar información. Se agregan también los mapas de APIs.

2022-02-21 15:51 UTC, abderossi commented on guides/notifications/ipn/apis-map.es.md
> +> Recuerda que también puedes hacer consultas a la API  sumando query params para:
```suggestion
> Recuerda que también puedes hacer consultas a la API sumando query params para:
```

2022-02-21 15:51 UTC, abderossi commented on guides/notifications/ipn/apis-map.en.md
> +> Remember that you can also make API calls suing query params for the following:
```suggestion
> Remember that you can also make API calls using query params for the following:
```

2022-02-21 15:53 UTC, abderossi commented on guides/notifications/ipn/inperson-configuration.es.md
> +Para cada escaneo QR, se genera un `merchant_order` diferente. Recuerda que si el cliente hace más de un escaneo, un pedido estará **opened** indefinidamente y, para cerrar la transacción, el `mercha
```suggestion
Para cada escaneo de QR, se genera un `merchant_order` diferente. Recuerda que si el cliente hace más de un escaneo, un pedido estará **opened** indefinidamente y, para cerrar la transacción, el `merchant_order` debe tener `status` = **closed**.
```

2022-02-21 15:53 UTC, abderossi commented on guides/notifications/ipn/inperson-configuration.es.md
> +Para cada escaneo QR, se genera un `merchant_order` diferente. Recuerda que si el cliente hace más de un escaneo, un pedido estará **opened** indefinidamente y, para cerrar la transacción, el `mercha
Sugerencia!

2022-02-21 15:54 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.en.md
> +We notify events related to your orders (`merchant_order`) or payments received (` payment`).
```suggestion
We notify events related to your orders (`merchant_order`) or payments received (`payment`).
```

2022-02-21 15:54 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.en.md
> +Whenever an event occurs related to any of the mentioned resources, we will send you a notification using `HTTP POST` to the` notification_url` you specified.
```suggestion
Whenever an event occurs related to any of the mentioned resources, we will send you a notification using `HTTP POST` to the `notification_url` you specified.
```

2022-02-21 15:55 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.en.md
> +|`topic`|Identifies what it is about. It can be `payment` or` merchant_order`.|
```suggestion
|`topic`|Identifies what it is about. It can be `payment` or `merchant_order`.|
```

2022-02-21 15:55 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.en.md
> +> **Example:** If you set the `notification_url`: `https: // www.yoursite.com / notifications`, you will receive payment notifications like this: `https://www.yoursite.com/notifications?topic=merchan
La primera URL tiene espacios. Es buscado?

2022-02-21 15:56 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.en.md
> +> Configue in person payment notifications
```suggestion
> Configure in person payment notifications
```

2022-02-21 15:56 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.en.md
> +> [Configue in person payment notifications](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/notifications/ipn/inperson-configuration)
```suggestion
> [Configure in person payment notifications](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/notifications/ipn/inperson-configuration)
```

2022-02-21 15:57 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.es.md
> +1. **Registrar la Merchant Order (MO).** Al escanear un QR que contenga un monto, este creará una merchant order automáticamente, enviando una notificación. Resulta preciso tener en cuenta el siguien
```suggestion
1. **Registrar la Merchant Order (MO).** Al escanear un QR que contenga un monto, este creará una merchant order automáticamente, enviando una notificación. Resulta preciso tener en cuenta el siguiente escenario: si se escanea varias veces el mismo QR, cada uno creará una merchant order distinta y, por lo tanto, una nueva notificación.
```

2022-02-21 15:58 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +|`topic`|Identificação do que se trata. Podendo ser `payment` ou` merchant_order`.|
```suggestion
|`topic`|Identificação do que se trata. Podendo ser `payment` ou `merchant_order`.|
```

2022-02-21 15:58 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +1. O campo `status` do` merchant_order` permanecerá **aberto** quando ainda não tiver pagamentos associados, ou se tiverem rejeitados ou aprovados por um valor inferior ao total do pedido.
```suggestion
1. O campo `status` do `merchant_order` permanecerá **aberto** quando ainda não tiver pagamentos associados, ou se tiverem rejeitados ou aprovados por um valor inferior ao total do pedido.
```

2022-02-21 15:59 UTC, abderossi commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +2. O campo `status` do` merchant_order` será **fechado** quando a soma dos pagamentos aprovados for igual que o total do pedido.
```suggestion
2. O campo `status` do `merchant_order` será **fechado** quando a soma dos pagamentos aprovados for igual que o total do pedido.
```

2022-02-21 15:59 UTC, abderossi commented on guides/notifications/ipn/inperson-order-query.en.md
> +> Nota
```suggestion
> Note
```

2022-02-21 16:03 UTC, abderossi approved these changes

2022-02-21 21:30 UTC, hgaldino requested changes

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +Notificamos eventos referente a suas ordem (`merchant_order`) o pagamento recebido (`payment`)
```suggestion
Notificamos eventos referente a suas ordem (`merchant_order`) o pagamento recebido (`payment`). 
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +1. **Registrar o Merchant Order (MO)**  Ao digitalizar um QR que contém um valor, ele criará automaticamente um pedido do lojista, enviando uma notificação (Se o mesmo QR for escaneado várias vezes,
```suggestion
1. **Registrar o Merchant Order (MO).**  Ao digitalizar um QR que contém um valor, ele criará automaticamente um pedido do lojista, enviando uma notificação (se o mesmo QR for escaneado várias vezes, cada um criará um pedido comercial diferente e, portanto, uma nova notificação, a integração deve levar este cenário em consideração).
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +2. **Atualização de pagamentos.** Cada tentativa de pagamento por parte do cliente atualizará as informações do pedido do lojista e enviará uma notificação
```suggestion
2. **Atualização de pagamentos.** Cada tentativa de pagamento por parte do cliente atualizará as informações do pedido do lojista e enviará uma notificação.
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +3. **Fechamento do MO.** Assim que um pagamento aprovado for feito, o status do MO aparecerá fechado e uma notificação será enviada
```suggestion
3. **Fechamento do MO.** Assim que um pagamento aprovado for realizado, o status do MO aparecerá fechado e uma notificação será enviada.
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +
```suggestion
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +Mercado Pago informará a esta `notification_url` tanto en la creación como actualización de los estados de pagos u órdenes con dos parámetros:
Está em ES. 

(Romi, uma coisa...tem um snipet de notifications que fala sobre essa questão da ação após receber a notificação)

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +Se você estiver integrando pagamentos presencial, recomendamos o uso de notificações IPN do tipo `merchant_order`. Para fazer isso, mantenha as seguintes regras em mente:
```suggestion
Se você estiver integrando pagamentos presenciais, recomendamos o uso de notificações IPN do tipo `merchant_order`. Para fazer isso, mantenha as seguintes regras em mente:
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +> Configurar notificações de pagamento cara a cara
```suggestion
> Configurar notificações de pagamentos presenciais
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +> Configurar notificações de pagamento com código QR.
```suggestion
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +> [Configurar notificações de pagamento cara a cara](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn/inperson-configuration)
```suggestion
> [Configurar notificações de pagamentos presenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn/inperson-configuration)
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +> Consulta da ordem
```suggestion
> Consultar pedidos

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +> Verifique o status das ordens.
```suggestion
> Verifique o status dos pedidos.
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-notification-events.pt.md
> +> [Consulta da ordem](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn/inperson-order-query)
```suggestion
> [Consultar pedidos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn/inperson-order-query)
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-introduction.pt.md
> +Se você estiver integrando pagamentos presenciais com QR code, abaixo apresentaremos informações sobre as notificações por IPN nesse tipo de pagamento. Além disso, indicaremos como consultar a ordem
```suggestion
Se você estiver integrando pagamentos presenciais com QR code, abaixo apresentaremos informações sobre as notificações por IPN nesse tipo de pagamento. Além disso, indicaremos como consultar pedidos com o external reference e o que será necessário realizar caso o cliente escaneie o QR code duas vezes (deixando um pedido sempre em aberto).
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-introduction.pt.md
> +> Configurar notificações de pagamento cara a cara
```suggestion
> Configurar notificações de pagamentos presenciais.
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-introduction.pt.md
> +> Configurar notificações de pagamento com código QR.
```suggestion
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-introduction.pt.md
> +> [Configurar notificações de pagamento cara a cara](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn/inperson-configuration)
```suggestion
> [Configurar notificações  de pagamentos presenciais](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/notifications/ipn/inperson-configuration)
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/inperson-order-query.pt.md
> +Para poder consultar o status do pedido por meio do `merchant_order`, você precisará fazer um get usando o id que você recebeu no servidor de notificações.
```suggestion
Para poder consultar o status do pedido por meio do `merchant_order`, você precisará fazer um GET usando o ID que você recebeu no servidor de notificações.
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/online-url-configuration.pt.md
> +> Leia nossa introdução ao IPN..
```suggestion
> Leia nossa introdução ao IPN.
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/troubleshooting.pt.md
> +**Se nenhuma notificação for recebida**, será necessário aplicar a busca de pedidos como um método de contingência usando sua `external_reference`  como critério de busca. A busca pode ser feita de d
```suggestion
**Se nenhuma notificação for recebida**, será necessário aplicar a busca de pedidos como um método de contingência usando sua `external_reference` como critério de busca. A busca pode ser feita de duas maneiras:
```

2022-02-21 21:30 UTC, hgaldino commented on guides/notifications/ipn/troubleshooting.pt.md
> +A resposta será a mesma que usar o id de pagamento e devem usar os mesmos critérios mencionados acima para confirmar o pedido.
```suggestion
A resposta será a mesma que quando utilizar o ID de pagamento e eles devem usar os mesmos critérios mencionados acima para confirmar o pedido.
```

2022-02-23 12:26 UTC, romisoto commented on guides/notifications/ipn/inperson-introduction.pt.md
> +> Configurar notificações de pagamento com código QR.
los pagos presenciales son con código QR! :D por eso tenemos en el card como titulo una cosa y como explicación debajo que son con QR

2022-02-23 21:10 UTC, merged