feature/new-subscriptions-documentation
mercadopago/devsite-docs pull request #1614
Opened 2022-03-11 19:05 UTC by rwaetemann

## Description

A documentação de assinaturas foi totalmente reescrita e reestruturada com base nos guias independentes. A única dependência para este PR é a finalização do desenvolvimento do DevSite para suportar a estrutura criada.

2022-03-14 16:27 UTC, abderossi commented on guides/snippets/test-integration/cancellations-and-refunds.en.md
> +- **Expiry date**: A payment expires after 30 days without confirmation and the cancellation is automatic. The final status of this transaction will appear as *Canceled* or *Expired*. This informatio
Expiration?

2022-03-14 16:28 UTC, abderossi commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +**Reembolsos** son transacciones que se realizan cuando un determinado cargo se revierte y las cantidades pagadas se devuelven al comprador. Esto significa que el cliente recibirá en su cuenta o en e
```suggestion
Los **Reembolsos** son transacciones que se realizan cuando un determinado cargo se revierte y las cantidades pagadas se devuelven al comprador. Esto significa que el cliente recibirá en su cuenta o en el extracto de su tarjeta de crédito el monto pagado por la compra de un determinado producto o servicio.
```

2022-03-14 16:29 UTC, abderossi commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +**Reembolsos** son transacciones que se realizan cuando un determinado cargo se revierte y las cantidades pagadas se devuelven al comprador. Esto significa que el cliente recibirá en su cuenta o en e
Si quisieras que quede **Reembolsos** como primera palabra, sugiero cambiarlo por "**Reembolsos**: son transacciones..."

2022-03-14 16:38 UTC, abderossi commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +**Cancelaciones** ocurren cuando se realiza una compra pero el pago aún no ha sido aprobado por algún motivo. En este caso, considerando que la transacción no fue procesada y el establecimiento no re
Mismo caso acá!

2022-03-14 17:36 UTC, romisoto commented on guides/snippets/test-integration/chargebacks.en.md
> +If the buyer doesn't recognize a charge in their credit card statement, a chargeback can be made.  To avoid these cases, fill out [your business data](https://www.mercadopago.com.uy/settings/account)
la url es .com.uy, es correcto?

2022-03-14 17:38 UTC, romisoto commented on guides/snippets/test-integration/chargebacks.en.md
> +For an enhanced validation of payment security, send us as much information as possible when creating the payment.  For example, if you send us information about the buyer, we can detect if that buye
```suggestion
For an enhanced validation of payment security, send us as much information as possible when creating the payment.  For example, if you send us information about the buyer, we can detect if that buyer has made any suspicious payments before and prevent it.
```

2022-03-14 17:38 UTC, romisoto commented on guides/snippets/test-integration/chargebacks.en.md
> +When we detect an irregular behavior or are notified that a stolen credit card was used, we will contact via e-mail to let you know what happened. We recommend you to [cancel the purchase](https://ww
```suggestion
When we detect an irregular behavior or are notified that a stolen credit card was used, we will contact you via e-mail to let you know what happened. We recommend you to [cancel the purchase](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/account/cancellations-and-refunds) and refund the money to the buyer so that you can avoid a chargeback.
```

2022-03-14 17:42 UTC, romisoto commented on guides/snippets/test-integration/chargebacks.en.md
> +For more information, you can see the [Seller Protection Program](https://www.mercadopago.com.ar/ayuda/requisitos-programa-proteccion-vendedor_294).
la url dice .com.ar, es correcto?

2022-03-14 17:49 UTC, romisoto commented on guides/snippets/test-integration/owasp.en.md
> +It is critical to ensure that any input validation performed on the client-side also should be performed on the server-side since they could be bypassed on the client-side by an attacker.
```suggestion
It is critical to ensure that any input validation performed on the client-side should also be performed on the server-side since they could be bypassed on the client-side by an attacker. 
```

2022-03-14 17:54 UTC, romisoto commented on guides/snippets/test-integration/payment-approval.en.md
> +In order to avoid any revenue loss with your business and to enhance your customers experience, we work with agents from each payment method and operate with the latest tools for fraud prevention and
```suggestion
In order to avoid any revenue loss with your business and to enhance your customers' experience, we work with agents from each payment method and operate with the latest tools for fraud prevention and payment growth.
```

2022-03-14 17:57 UTC, romisoto commented on guides/snippets/test-integration/payment-approval.en.md
> +#### VIEW Values
esta VIEW todo en mayúsculas por alguna razon?

2022-03-14 17:58 UTC, romisoto commented on guides/snippets/test-integration/payment-approval.en.md
> +- A global javascript variable is automatically created `MP_DEVICE_SESSION_ID` with the value ` device_id`. If you prefer that we assign it to another variable, indicate the name by adding the attrib
```suggestion
- A global javascript variable is automatically created `MP_DEVICE_SESSION_ID` with the value `device_id`. If you prefer that we assign it to another variable, indicate the name by adding the attribute `output`.
```

2022-03-14 18:07 UTC, romisoto commented on guides/snippets/test-integration/pci.en.md
> +As a Service Provider, we must meet regulatory and security responsibilities vis-à-vis card brands and acquirers, but even so, security throughout the payment process is the obligation of both partie
```suggestion
As a Service Provider, we must meet regulatory and security responsibilities vis-à-vis card brands and acquirers, but even so, security throughout the payment process is the obligation of both parties. Merchants and/or e-commerce platforms that are integrated with payment processors such as Mercado Pago must meet minimum security requirements to mitigate risks of fraud and information leakage, securing user data.
```

2022-03-14 18:07 UTC, romisoto commented on guides/snippets/test-integration/pci.en.md
> +PCI regulations establish a basic level of protection for cardholders (cardholders) and help reduce fraud and data breaches within the entire payments ecosystem.
```suggestion
PCI regulations establish a basic level of protection for cardholders and help reduce fraud and data breaches within the entire payments ecosystem. 
```

2022-03-14 18:10 UTC, romisoto commented on guides/snippets/test-integration/pci.en.md
> +For each of the twelve PCI requirements, there are basically four different levels of compliance, typically based on the volume of card transactions your processes organization annually, and each lev
aca no sería "your organization processes"?

2022-03-14 18:15 UTC, romisoto commented on guides/snippets/test-integration/pci.en.md
> +To comply with PCI DSS, demonstrate your compliance, and in turn protect your customers' card details, it is important to use secure payment integrations like Checkou Pro to ensure that cardholder da
```suggestion
To comply with PCI DSS, demonstrate your compliance, and in turn protect your customers' card details, it is important to use secure payment integrations like Checkout Pro to ensure that cardholder data does not reach your servers.
```

2022-03-14 18:21 UTC, romisoto commented on guides/snippets/test-integration/webhooks.en.md
> +Webhook (also known as web callback) is a simple method that makes it easy for an app or system to provide real-time information whenever an event happens, that is, it is a way to passively receive d
```suggestion
Webhook (also known as web callback) is a simple method that makes it easy for an app or system to provide real-time information whenever an event happens, that is, it is a way to passively receive data between two systems through an `HTTP POST`.
```

2022-03-14 18:32 UTC, romisoto commented on guides/snippets/test-integration/webhooks.en.md
> +| **date_created** | Resorce (payments, mp-connect, subscription etc) creation date |
```suggestion
| **date_created** | Resource (payments, mp-connect, subscription etc) creation date |
```

2022-03-14 19:01 UTC, romisoto commented on guides/subscriptions/payment-methods.en.md
> +To offer subscriptions with payments via boleto bancário, send a POST with the `payment_methods_allowed" parameter informing the payment method to be displayed on the checkout, such as `bolbradesco`,
```suggestion
To offer subscriptions with payments via boleto bancário, send a POST with the `payment_methods_allowed` parameter informing the payment method to be displayed on the checkout, such as `bolbradesco`, to the[/preapproval_plan](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/subscriptions/_preapproval_plan/post) endpoint, and execute the request.
```

2022-03-14 19:04 UTC, romisoto commented on guides/subscriptions/previous-requirements.en.md
> +To perform signature integration, you must meet the requirements listed below.
```suggestion
To perform a signature integration, you must meet the requirements listed below.
```

2022-03-14 19:04 UTC, romisoto commented on guides/subscriptions/previous-requirements.en.md
> +| Mercado Pago or Mercado Livre seller account | To integrate subscriptions on your website, you need a seller account on Mercado Pago or Mercado Livre. If not, [click here](https://www.mercadopago[F
```suggestion
| Mercado Pago or Mercado Libre seller account | To integrate subscriptions on your website, you need a seller account on Mercado Pago or Mercado Libre. If not, [click here](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) to create. | 
```

2022-03-14 19:12 UTC, romisoto commented on guides/subscriptions/subscriptions-associated-plan.en.md
> +The integration of **subscriptions with an associated plan** happens in two steps: In the first, it is necessary to **create a plan** to be associated with the subscription, and in the second step, t
```suggestion
The integration of **subscriptions with an associated plan** happens in two steps: In the first one, it is necessary to **create a plan** to be associated with the subscription, and in the second step, to **create a subscription**.
```

2022-03-14 19:13 UTC, romisoto commented on guides/subscriptions/subscriptions-associated-plan.en.md
> +Once you create a plan, you can create a subscription. Subscription is a payer authorization for recurring charges with a defined payment method (credit card, for example). When subscribing to a prod
```suggestion
Once you create a plan, you can create a subscription. A subscription is a payer authorization for recurring charges with a defined payment method (credit card, for example). When subscribing to a product/service, the customer agrees to be periodically charged a certain amount for the defined period.
```

2022-03-14 19:14 UTC, romisoto requested changes
solo unas pequeñas sugerencias!

2022-03-14 19:19 UTC, abderossi commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +- **Status de pago**: Cancelaciones solo se pueden realizar si el estado de pago es Pending o In process. Estos estados se muestran en la respuesta a la llamada de la API de cancelación en los campos
```suggestion
- **Status de pago**: las cancelaciones solo se pueden realizar si el estado de pago es Pending o In process. Estos estados se muestran en la respuesta a la llamada de la API de cancelación en los campos de, *Status* y *Status detail* respectivamente.
```

2022-03-14 19:19 UTC, abderossi commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +- **Boleto bancário**: Si expira el período de vigencia de un boleto bancário, el usuario puede volver a generarlo ingresando el ID de transacción de su cuenta de Mercado Pago. Sin embargo, si deseas
```suggestion
- **Boleto bancário**: si expira el período de vigencia de un boleto bancário, el usuario puede volver a generarlo ingresando el ID de transacción de su cuenta de Mercado Pago. Sin embargo, si deseas evitar problemas de retención de inventario, por ejemplo, puedes optar por no hacer disponible una nueva emisión de este boleto. Para hacer esto, simplemente cancélalo.
```

2022-03-14 19:21 UTC, abderossi commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +) y visita nuestra Referencia de API para acceder a la API de cancelación.
Creo que acá quedó en una linea aparte el link!

2022-03-14 19:33 UTC, abderossi commented on guides/snippets/test-integration/chargebacks.es.md
> +Se crea un contracargo cuando **el cliente disputa un cobro de su tarjeta de crédito o débito ante el banco emisor de su tarjeta y pide un reembolso del dinero.**
```suggestion
Se crea un contracargo cuando **el cliente disputa un cobro de su tarjeta de crédito o débito ante el banco emisor de su tarjeta y pide un reembolso del dinero**.
```

2022-03-14 19:34 UTC, abderossi commented on guides/snippets/test-integration/chargebacks.es.md
> +> Si recibiste un contracargo y no sabes qué hacer, consulta nuestras [preguntas frecuentes](https://www.mercadopago.com.ar/ayuda/recib%C3%AD-un-contracargo_4249).
Este link no está localizado para otros países. Solo está disponible en Argentina=

2022-03-14 19:58 UTC, abderossi commented on guides/snippets/test-integration/chargebacks.es.md
> +#### Posibles valores para `view`
Es duda: se puede poner una palabra en formato `code` en un título?

2022-03-14 19:58 UTC, abderossi commented on guides/snippets/test-integration/chargebacks.es.md
> +Si el comprador no reconoce el cargo en el resumen de su tarjeta puede realizar un contracargo. Para evitar estos casos, completa la [información de tu negocio](https://www.mercadopago.com.uy/setting
Misma duda acá con este link que es de .uy

2022-03-14 20:50 UTC, abderossi commented on guides/subscriptions/payment-methods.es.md
> +Al integrar las suscripciones, es posible personalizar y definir un valor proporcional para el pago de la suscripción. Para realizar esta integración, siga los pasos que se describen a continuación.
```suggestion
Al integrar las suscripciones, es posible personalizar y definir un valor proporcional para el pago de la suscripción. Para realizar esta integración, sigue los pasos que se describen a continuación.
```

2022-03-14 20:57 UTC, abderossi commented on guides/subscriptions/subscription-no-associated-plan.en.md
> +To offer **subscriptions without an associated plan and with authorized payment**, send a POST with the necessary attributes to the [/preapproval](https://www.mercadopago[FAKER][URL][DOMAIN]/develope
```suggestion
To offer **subscriptions without an associated plan and with authorized payment**, send a POST with the necessary attributes to the [/preapproval](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/subscriptions/_preapproval/post) endpoint and pay attention to the `status` parameter, which must be filled in with the value `authorized`.
```

2022-03-14 20:58 UTC, abderossi commented on guides/subscriptions/subscription-no-associated-plan.en.md
> +To offer **subscriptions without an associated plan and with authorized payment**, send a POST with the necessary attributes to the [/preapproval](https://www.mercadopago[FAKER][URL][DOMAIN]/develope
No cambié nada acá @rwaetemann. Solo que no se por qué, no muestra el formato en negritas. Si en local se ve bien, ignorá este mensaje.

2022-03-14 20:59 UTC, abderossi requested changes
Dejo algunos fixes y sugerencias

2022-03-15 04:28 UTC, hgaldino requested changes

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/subscriptions-associated-plan.pt.md
> +
```suggestion
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/subscriptions-associated-plan.pt.md
> +Ao executar a API, o plano estará criado e você terá acesso ao `preapproval_plan_id`, **que na resposta à API, será exibido apenas como ìd`.** Este **atributo é mandatório** para a criação da assinat
```suggestion
Ao executar a API, o plano estará criado e você terá acesso ao `preapproval_plan_id`, **que na resposta à API, será exibido apenas como `id`.** Este **atributo é mandatório** para a criação da assinatura. 
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/subscription-no-associated-plan.pt.md
> +
```suggestion
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/subscription-no-associated-plan.pt.md
> +Finalizando o preenchimento dos campos,  execute a requisição.
```suggestion
Finalizando o preenchimento dos campos, execute a requisição.
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/subscription-no-associated-plan.pt.md
> +
```suggestion
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/subscription-no-associated-plan.pt.md
> +Finalizando o preenchimento dos campos,  execute a requisição.
```suggestion
Finalizando o preenchimento dos campos, execute a requisição.
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/proportional-amount.pt.md
> +
```suggestion
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/subscription-management.pt.md
> +| Cancelar ou passar assinatura | Possibilita cancelar ou pausar uma assinatura existente. Para isso, envie um PUT com o atributo `status` e o valor `cancelled` ao endpoint [/preapproval/{id}](https:
```suggestion
| Cancelar ou pausar assinatura | Possibilita cancelar ou pausar uma assinatura existente. Para isso, envie um PUT com o atributo `status` e o valor `cancelled` ao endpoint [/preapproval/{id}](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_id/put) e execute a requisição. E para pausar uma assinatura envie um PUT com o atributo `status` e o valor `paused` ao mesmo endpoint e execute a requisição. |
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/previous-requirements.pt.md
> +| Credenciais | Senhas únicas com as quais identificamos uma integração na sua conta. Para realizar as integrações, serão necessárias a _Public key_ e o _Access Token_. [clique aqui](https://www.merc
```suggestion
| Credenciais | Senhas únicas com as quais identificamos uma integração na sua conta. Para realizar as integrações, serão necessárias a _Public key_ e o _Access Token_. [Clique aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/credentials) para mais informações. |
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/glossary.pt.md
> +Tem características semelhantes ao template, já que é possível criar uma assinatura a partir de um plano. |
Amiga, aqui nessa tabela eu não sei se foi só impressão pelo layout do git ou se em alguns casos rolou essa pulada de linha.

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/introduction.pt.md
> +* **Assinatura com plano associado:**utilizada caso seja necessário usar a mesma assinatura em diferentes ocasiões e organizá-las em grupos identificáveis. Por exemplo: uma assinatura mensal e anual
```suggestion
* **Assinatura com plano associado:** utilizada caso seja necessário usar a mesma assinatura em diferentes ocasiões e organizá-las em grupos identificáveis. Por exemplo: uma assinatura mensal e anual de uma academia.
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/create-test-user.pt.md
> +* **Vendedor:** É a conta que você usa para configurar a aplicação e as credenciais para a cobrança.
```suggestion
* **Vendedor:** é a conta que você usa para configurar a aplicação e as credenciais para a cobrança.
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/create-test-user.pt.md
> +* **Comprador:** É a conta que você usa para testar o processo de compra.
```suggestion
* **Comprador:** é a conta que você usa para testar o processo de compra.
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +Ao integrar assinaturas, é possível customizar e oferecer diferentes meios de pagamento além das opções de cartão de crédito disponíveis, como boleto bancário ou definir um valor proporcional (Pro ra
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +Para oferecer pagamento de assinaturas via boleto bancário, envie um POST com o parâmetro `payment_methods_allowed" informando o meio de pagamento que deverá aparecerá no checkout, por exemplo, `bolb
```suggestion
Para oferecer pagamento de assinaturas via boleto bancário, envie um POST com o parâmetro `payment_methods_allowed` informando o meio de pagamento que deverá aparecerá no checkout, por exemplo, `bolbradesco` ao endpoint [/preapproval_plan](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_plan/post) e execute a requisição. 
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +
```suggestion
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +>NOTE
```suggestion
> NOTE
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +> O pagamento de assinaturas por boleto bancário está disponível somente para assinaturas criadas pelo Checkout Pro, onde o vendedor deverá redirecionar o comprador para a URL  gerada no parâmetro `i
```suggestion
> O pagamento de assinaturas por boleto bancário está disponível somente para assinaturas criadas pelo Checkout Pro, onde o vendedor deverá redirecionar o comprador para a URL gerada no parâmetro `init_point`. 
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +### Valor proporcional (Pro rata)
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +Pro rata é o valor cobrado do assinante caso a assinatura comece em um dia diferente da data de cobrança definida pelo vendedor. Ao criar uma assinatura o vendedor pode decidir se deseja ou não ofere
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +
```suggestion
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +
```suggestion
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +Para definir uma pro-rata no pagamento de assinaturas, envie um POST com os parâmetros `billing_day`, com o dia do mês em que a cobrança deverá ser realizada (este campo aceita valores de 1 a 28) e o
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][U
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/payment-methods.pt.md
> +> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][U
```suggestion
> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_plan_id/put), altere o valor de `false` para `true` e execute a requisição.
```

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/proportional-amount.pt.md
> +### Valor proporcional (Pro rata)
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/proportional-amount.pt.md
> +Pro rata é o valor cobrado do assinante caso a assinatura comece em um dia diferente da data de cobrança definida pelo vendedor. Ao criar uma assinatura o vendedor pode decidir se deseja ou não ofere
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/proportional-amount.pt.md
> +> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][U
pró-rata, pro rata ou pro rata?

2022-03-15 04:28 UTC, hgaldino commented on guides/subscriptions/proportional-amount.pt.md
> +> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][U
```suggestion
> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_plan_id/put), altere o valor de `false` para `true` e execute a requisição.
```

2022-03-15 11:52 UTC, rwaetemann commented on guides/snippets/test-integration/cancellations-and-refunds.en.md
> +- **Expiry date**: A payment expires after 30 days without confirmation and the cancellation is automatic. The final status of this transaction will appear as *Canceled* or *Expired*. This informatio
```suggestion
- **Expiration date**: A payment expires after 30 days without confirmation and the cancellation is automatic. The final status of this transaction will appear as *Canceled* or *Expired*. This information will be displayed in the response of the Cancellation API call, in the fields *Status* and *Status detail* respectively.
```

2022-03-15 11:52 UTC, rwaetemann commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +**Reembolsos** son transacciones que se realizan cuando un determinado cargo se revierte y las cantidades pagadas se devuelven al comprador. Esto significa que el cliente recibirá en su cuenta o en e
```suggestion
**Reembolsos:** son transacciones que se realizan cuando un determinado cargo se revierte y las cantidades pagadas se devuelven al comprador. Esto significa que el cliente recibirá en su cuenta o en el extracto de su tarjeta de crédito el monto pagado por la compra de un determinado producto o servicio.
```

2022-03-15 11:53 UTC, rwaetemann commented on guides/snippets/test-integration/cancellations-and-refunds.es.md
> +**Cancelaciones** ocurren cuando se realiza una compra pero el pago aún no ha sido aprobado por algún motivo. En este caso, considerando que la transacción no fue procesada y el establecimiento no re
```suggestion
**Cancelaciones:** ocurren cuando se realiza una compra pero el pago aún no ha sido aprobado por algún motivo. En este caso, considerando que la transacción no fue procesada y el establecimiento no recibió ningún monto, la compra se cancela y no hay cargo.
```

2022-03-15 11:56 UTC, rwaetemann commented on guides/snippets/test-integration/chargebacks.es.md
> +#### Posibles valores para `view`
```suggestion
#### Posibles valores para view
```

2022-03-15 11:58 UTC, rwaetemann commented on guides/snippets/test-integration/pci.en.md
> +For each of the twelve PCI requirements, there are basically four different levels of compliance, typically based on the volume of card transactions your processes organization annually, and each lev
```suggestion
For each of the twelve PCI requirements, there are basically four different levels of compliance, typically based on the volume of card transactions your organization processes annually, and each level has a set of obligations.
```

2022-03-15 12:13 UTC, rwaetemann commented on guides/subscriptions/payment-methods.pt.md
> +Ao integrar assinaturas, é possível customizar e oferecer diferentes meios de pagamento além das opções de cartão de crédito disponíveis, como boleto bancário ou definir um valor proporcional (Pro ra
@hgaldino amiga, na internet diz Pro rata. haha.

2022-03-15 14:58 UTC, rwaetemann commented on guides/subscriptions/payment-methods.pt.md
> +Para definir uma pro-rata no pagamento de assinaturas, envie um POST com os parâmetros `billing_day`, com o dia do mês em que a cobrança deverá ser realizada (este campo aceita valores de 1 a 28) e o
```suggestion
Para definir uma pro rata no pagamento de assinaturas, envie um POST com os parâmetros `billing_day`, com o dia do mês em que a cobrança deverá ser realizada (este campo aceita valores de 1 a 28) e o `billing_day_proportional` com o valor true ao endpoint [/preapproval_plan](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_plan/post) e execute a requisição.
```

2022-03-15 14:59 UTC, rwaetemann commented on guides/subscriptions/payment-methods.pt.md
> +Para definir uma pro-rata no pagamento de assinaturas, envie um POST com os parâmetros `billing_day`, com o dia do mês em que a cobrança deverá ser realizada (este campo aceita valores de 1 a 28) e o
```suggestion
Para definir uma pro rata no pagamento de assinaturas, envie um POST com os parâmetros `billing_day`, com o dia do mês em que a cobrança deverá ser realizada (este campo aceita valores de 1 a 28) e o `billing_day_proportional` com o valor true ao endpoint [/preapproval_plan](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_plan/post) e execute a requisição.
```

2022-03-15 15:00 UTC, rwaetemann commented on guides/subscriptions/payment-methods.pt.md
> +> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][U
```suggestion
> Caso queira modificar uma assinatura específica e definir uma pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_plan_id/put),  altere o valor de `false` para `true` e execute a requisição.
```

2022-03-15 15:03 UTC, rwaetemann commented on guides/subscriptions/proportional-amount.pt.md
> +> Caso queira modificar uma assinatura específica e definir uma Pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][U
```suggestion
> Caso queira modificar uma assinatura específica e definir uma pro rata, envie um PUT com o parâmetro `billing_day_proportional` ao endpoint [/preapproval_plan/{id}](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/subscriptions/_preapproval_plan_id/put),  altere o valor de `false` para `true` e execute a requisição.
```

2022-03-15 16:13 UTC, romisoto approved these changes

2022-03-16 17:53 UTC, abderossi approved these changes

2022-03-18 20:32 UTC, rwaetemann commented on guides/testing/test-purchase.pt.md
> +Pronto! Com o teste concluído corretamente, seu produto/serviço já poderão ser disponibilizadas para os seus clientes.
```suggestion
Pronto! Com o teste concluído corretamente, seu produto/serviço já poderão ser disponibilizados para os seus clientes.
```

2022-04-25 16:33 UTC, merged