SDK-797: update simulator's docs to support test AT
mercadopago/devsite-docs pull request #1618
Opened 2022-03-14 17:41 UTC by jeff-mendoza

## Description

In our [simulator](https://api.mercadopago.com/point/integrator-simulator/sandbox/?ignoreapidoc=true) we have added a new functionality to integrate it with the Payments API.

This new functionality requires the use of the test access token and this PR documents its use, how to obtain it and where to consult the test payments.

2022-03-14 17:53 UTC, maryvelandia approved these changes

2022-03-15 19:11 UTC, hgaldino requested changes

2022-03-15 19:11 UTC, hgaldino commented on guides/in-person-payments/integration-api/point-simulator.pt.md
> +* **Device Mode**: Simula um dispositivo de ponto virtual para que você possa testar sua integração a partir de HTTP requests. Acesse o [Simulador Device Mode](https://api.mercadopago.com/point/integ
```suggestion
* **Device mode**: simula um dispositivo de ponto virtual para que você possa testar sua integração a partir de HTTP requests. Acesse o [Simulador device mode](https://api.mercadopago.com/point/integrator-simulator/sandbox/device?ignoreapidoc=true).
```

2022-03-15 19:11 UTC, hgaldino commented on guides/in-person-payments/integration-api/point-simulator.pt.md
> +* **PDV Mode:** Você deve inserir seu Token de Acesso de teste e o simulador atribuirá a você um dispositivo virtual.
```suggestion
* **PDV mode:** você deve inserir seu `access-token` de teste e o simulador atribuirá a você um dispositivo virtual.
```

2022-03-15 19:11 UTC, hgaldino commented on guides/in-person-payments/integration-api/point-simulator.pt.md
> +> Lembre-se que para usar o simulador você deve configurar um Token de Acesso de teste(`TEST-XXXXX-XXXXX-XXXXXXX`) e você pode obtê-lo em suas [integrações](https://www.mercadopago[FAKER][URL][DOMAIN
```suggestion
> Lembre-se que para usar o simulador você deve configurar um `access-token` de teste (`TEST-XXXXX-XXXXX-XXXXXXX`) e você pode obtê-lo em suas [integrações](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/panel/applications), opção **Minhas credenciais > Credenciais de teste**.
```

2022-03-15 19:11 UTC, hgaldino commented on guides/in-person-payments/integration-api/point-simulator.pt.md
> +* **Device Mode:** Você deve inserir seu token de acesso de teste e seu ID de dispositivo obtido em [lista seus dispositivos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-perso
```suggestion
* **Device mode:** você deve inserir seu `access-token` de teste e seu ID de dispositivo obtido em [lista seus dispositivos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-person-payments/integration-api/create-payment-intent#https://www.mercadopago.com.br/developers/pt/guides/in-person-payments/integration-api/create-payment-intent#bookmark_obtenha_a_lista_de_seus_dispositivos_dispon%C3%ADveis).
```

2022-03-16 16:05 UTC, merged