CORECH-2033 - Ajustas snippets de armazenamento de dados do cliente e…
mercadopago/devsite-docs pull request #1693
Opened 2022-05-19 12:38 UTC by meliguilhermefernandes

… cartao

## Description

Describe what your Pull Request is about, including important information about what was done.

### Issue involved

Fixes #<issue>

2022-05-19 13:38 UTC, eltinMeli commented
Guilherme no site ainda existem links que levam para a versão 1 da documentação que também contém os CRULs errados.
https://www.mercadopago.com.br/developers/pt/docs/checkout-api-v1/advanced-integration

https://github.com/mercadopago/devsite-docs/blob/development/guides/X-LEGACY/online-payments/checkout-api/v1/advanced-integration.en.md

2022-05-19 13:40 UTC, eltinMeli requested changes
Verificar que para a página advanced_integration existe a versão v1

2022-05-19 14:07 UTC, eltinMeli approved these changes

2022-05-20 05:26 UTC, hgaldino approved these changes

2022-05-20 19:39 UTC, merged