Feature/Yampi-newdoc
mercadopago/devsite-docs pull request #1767
Opened 2022-07-14 16:47 UTC by hgaldino

## Description

Documentação da integração com a plataforma Yampi.

### Issue involved

Fixes #<issue>

2022-08-25 19:11 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.en copy.md
> +>WARNING
```suggestion
> WARNING
```

2022-08-25 19:12 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es copy.md
> +>WARNING
```suggestion
> WARNING
```

2022-08-25 19:12 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es copy.md
> +>Importante
```suggestion
> Importante
```

2022-08-25 19:15 UTC, abderossi commented on guides/yampi/integration.en.md
> +1. On your Yampi store's Dashboard, access the **Checkout** menu and click on **Pagamento**.
@hgaldino las opciones que figuran acá en portugués es porque no están traducidad en la plataforma?

2022-08-25 19:16 UTC, abderossi commented on guides/yampi/integration.en.md
> +> PREV_STEP_CARD_EN
@hgaldino aquí podés quitar los next steps ;)

2022-08-25 19:17 UTC, abderossi commented on guides/yampi/integration.es.md
> +> PREV_STEP_CARD_ES
Extra next steps

2022-08-25 19:17 UTC, abderossi commented on guides/yampi/integration.es.md
> +2. En la pantalla de **administración de pasarela de pago**, haz clic en el botón **+ Nova afiliação** y selecciona la pasarela de Mercado Pago.
```suggestion
2. En la pantalla de **administración de gateway de pago**, haz clic en el botón **+ Nova afiliação** y selecciona la pasarela de Mercado Pago.
```

2022-08-25 19:18 UTC, abderossi commented on guides/yampi/integration.es.md
> +3. Luego, indica el **nombre del método de pago** que le aparecerá al comprador, por ejemplo, "Mercado Pago - Pix".
Pix está solo disponible para MLB. Esta documentación está limitada solo para MLB?

2022-08-25 19:44 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.en.md
> +With the [Checkout Transparente](/developers/pt/guides/checkout-api/landing), the entire checkout process will take place within the online store environment, without the need to redirect to an exter
```suggestion
With the [Checkout Transparente](/developers/en/guides/checkout-api/landing), the entire checkout process will take place within the online store environment, without the need to redirect to an external page. In addition to allowing greater control in the customization and integration process, the checkout offers a complete structure for processing payments with the main means available on the market.
```

2022-08-25 19:45 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.en.md
> +> The Pix payment option can only be used if there is a [Pix key registered](/developers/em/docs/checkout-api/integration-configuration/integrate-with-pix) in Mercado Pago. In addition, there is a li
```suggestion
> The Pix payment option can only be used if there is a [Pix key registered](/developers/en/docs/checkout-api/integration-configuration/integrate-with-pix) in Mercado Pago. In addition, there is a limit to the value of Pix, established by the Central Bank of Brazil, which can be moved during the night period (between 8:00 pm and 6:00 am) of R$1,000. For the daytime period (between 6 am and 8 pm), however, there is no movement limit.
```

2022-08-25 19:47 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.en.md
> +> PREV_STEP_CARD_EN
Extra next steps

2022-08-25 19:49 UTC, abderossi commented on guides/yampi/integration.es.md
> +7. Haz clic en **Salvar** para confirmar la información de integración. Para cambiar la información ingresada, en la pantalla de **administración de pasarela de pago**, haz clic en **editar** junto a
```suggestion
7. Haz clic en **Salvar** para confirmar la información de integración. Para cambiar la información ingresada, en la pantalla de **administración de gateway de pago**, haz clic en **editar** junto a el gateway de Mercado Pago.
```

2022-08-25 19:50 UTC, abderossi commented on guides/yampi/integration.pt.md
> +> PREV_STEP_CARD_PT
Extra next steps

2022-08-25 19:52 UTC, abderossi commented on guides/yampi/integration.pt.md
> +> NEXT_STEP_CARD_PT
Extra next steps

2022-08-25 19:57 UTC, abderossi requested changes

2022-08-25 19:57 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.es.md
> +> PREV_STEP_CARD_ES
extra next steps

2022-08-25 19:57 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.pt.md
> +> PREV_STEP_CARD_PT
extra next steps

2022-08-25 19:57 UTC, abderossi commented on guides/yampi/prerequisites.es.md
> +Para integrar el Mercado Pago con Yampi, debes cumplir con los requisitos a continuación.
```suggestion
Para integrar Mercado Pago con Yampi, debes cumplir con los requisitos a continuación.
```

2022-08-25 19:57 UTC, abderossi commented on guides/yampi/prerequisites.es.md
> +> PREV_STEP_CARD_ES
extra next steps

2022-08-26 13:40 UTC, hgaldino commented on guides/yampi/integration.en.md
> +1. On your Yampi store's Dashboard, access the **Checkout** menu and click on **Pagamento**.
Isso, @abderossi!!!! Não tem versão em ES da plataforma KKKKK daí fiquei nessa dúvida, mas achei que não fazia sentido traduzir nesse caso.

2022-09-07 16:22 UTC, abderossi commented on guides/yampi/landing.es.md
> + - benefit_message: Reciba pagos con los principales métodos de pago aceptados en el país (boleto bancário, tarjeta de crédito y Pix).
```suggestion
 - benefit_message: Recibe pagos con los principales métodos de pago aceptados en el país (boleto bancário, tarjeta de crédito y Pix).
```

2022-09-07 16:23 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.es.md
> +1. En la pantalla de **administración de los gateways de pago**, localice el método de pago que desea usar o edite y haz clic en **Visualizar**.
```suggestion
1. En la pantalla de **administración de los gateways de pago**, localiza el método de pago que deseas usar o editar y haz clic en **Visualizar**.
```

2022-09-07 16:23 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.es.md
> +2. En la pantalla de **administración del medio de pago seleccionado**, si aún no está indicado, seleccione la **afiliação** registrada para Mercado Pago.
```suggestion
2. En la pantalla de **administración del medio de pago seleccionado**, si aún no está indicado, selecciona la **afiliação** registrada para Mercado Pago.
```

2022-09-07 16:23 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.es.md
> +3. Para algunos de los métodos de pago disponibles, también puede configurar algunos datos, como:
```suggestion
3. Para algunos de los métodos de pago disponibles, también puedes configurar algunos datos, como:
```

2022-09-07 16:24 UTC, abderossi commented on guides/yampi/payment-configuration-cho-api.es.md
> +> Para pagos con tarjetas de crédito, la configuración de cuotas e intereses debe verificarse directamente en su [panel de usuario de Mercado Pago](https://www.mercadopago.com.br/costs-section#from-s
```suggestion
> Para pagos con tarjetas de crédito, la configuración de cuotas e intereses debe verificarse directamente en tu [panel de usuario de Mercado Pago](https://www.mercadopago.com.br/costs-section#from-section=menu). </br> <br/>
```

2022-09-07 16:25 UTC, abderossi requested changes
@hgaldino dejé unos ajustes pequeños de idioma español. Apenas estén, avisame y apruebo directamente!

2022-09-08 14:12 UTC, abderossi approved these changes

2022-09-08 14:27 UTC, merged