Feature/Test user admin - new doc
mercadopago/devsite-docs pull request #1768
Opened 2022-07-14 18:17 UTC by hgaldino

## Description

Documentação da nova plataforma no Devsite de criação de usuários de teste.

### Issue involved

Fixes #<issue>

2022-08-12 19:14 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +Para realizar la prueba, debe tener al menos dos cuentas:
```suggestion
Para realizar la prueba, debes tener al menos dos cuentas:
```

2022-08-12 19:18 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +* **Usuario/Vendedor**: cuenta requerida para **configurar la aplicación y las credenciales de facturación**. Esta es su cuenta de usuario.
```suggestion
* **Usuario/Vendedor**: cuenta requerida para **configurar la aplicación y las credenciales de facturación**. Esta es tu cuenta de usuario.
```

2022-08-12 19:21 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +Además de estas cuentas, también es importante utilizar las [tarjetas de prueba](/developers/es/guides/additional-content/testing/test-cards) para probar la integración de pago y simular el proceso d
```suggestion
Además de estas cuentas, también es importante utilizar las [tarjetas de prueba](/developers/es/guides/additional-content/testing/test-cards) para probar la integración de pago y simular el proceso de compra, así como el **saldo en la cuenta de Mercado Pago del usuario de prueba**. Te mostramos más detalles a continuación.
```

2022-08-12 19:21 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +Para crear cuentas y probar cómo funcionan las integraciones, siga los pasos a continuación.
```suggestion
Para crear cuentas y probar cómo funcionan las integraciones, sigue los pasos a continuación.
```

2022-08-12 19:21 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +1. En [Devsite](/developers/es/docs), acceda al menú **Tus integraciones > Cuentas de prueba** y haz clic en el botón **Crear cuenta de prueba**.
```suggestion
1. En el [Devsite](/developers/es/docs), accede al menú **Tus integraciones > Cuentas de prueba** y haz clic en el botón **Crear cuenta de prueba**.
```

2022-08-12 19:22 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +2. En la pantalla "Crear nueva cuenta", ingrese una descripción para la identificación de la cuenta. Ejemplo: "Vendedor - Tienda 1".
```suggestion
2. En la pantalla "Crear nueva cuenta", ingresa una descripción para la identificación de la cuenta. Ejemplo: "Vendedor - Tienda 1".
```

2022-08-12 19:26 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +3. Luego, seleccione el **país de operación** para la cuenta. Esta información no se puede editar posteriormente y, además, los usuarios Comprador y Vendedor deben ser del mismo país.
```suggestion
3. Luego, selecciona el **país de operación** para la cuenta. Esta información no se puede editar posteriormente y, además, los usuarios Comprador y Vendedor deben ser del mismo país.
```

2022-08-12 19:29 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +3. Luego, seleccione el **país de operación** para la cuenta. Esta información no se puede editar posteriormente y, además, los usuarios Comprador y Vendedor deben ser del mismo país.
@hgaldino , si la información **no** se puede editar posteriormente, no sería bueno resaltarlo?

2022-08-12 19:29 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +4. Rellena una **cantidad de dinero ficticia** que te servirá de referencia para probar tus aplicaciones. Este monto aparecerá como saldo en la cuenta de Mercado Pago del usuario de prueba y podrá se
```suggestion
4. Rellena una **cantidad de dinero ficticio** que te servirá de referencia para probar tus aplicaciones. Este monto aparecerá como saldo en la cuenta de Mercado Pago del usuario de prueba y podrá ser utilizado para simular pagos, así como con tarjeta de crédito.
```

2022-08-12 19:30 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +* **País** lugar de origen de la cuenta seleccionada en tu registro.
```suggestion
* **País**: lugar de origen de la cuenta seleccionada en tu registro.
```

2022-08-12 19:31 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +* **Idemntificación de cuenta**: descripción para la identificación de la cuenta de prueba.
```suggestion
* **Identificación de cuenta**: descripción para la identificación de la cuenta de prueba.  
```

2022-08-12 19:31 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +* **Usuario**: username de la cuenta de prueba generado automáticamente. Este username se utiliza para iniciar sesión con el usuario de prueba.
```suggestion
* **Usuario**: nombre de usuario de la cuenta de prueba generado automáticamente. Este nombre de usuario se utiliza para iniciar sesión con el usuario de prueba.
```

2022-08-12 19:33 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +* **Contraseña**: contraseña de acceso a la cuenta de usuario de prueba generada automáticamente. Para generar una nueva contraseña, haz clic en los 3 puntos verticales al final de la fila de la tabl
```suggestion
* **Contraseña**: contraseña de acceso a la cuenta de usuario de prueba generada automáticamente. Para generar una nueva contraseña, haz clic en los 3 puntos verticales al final de la fila de la tabla y selecciona la opción **Generar nueva contraseña**.
```

2022-08-12 19:33 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.es.md
> +> Para editar la **Idemntificación de cuenta** o **agregar más dinero ficticio** para probar sus aplicaciones, haz clic en los **3 puntos verticales** al final de la fila de la tabla y seleccione la
```suggestion
> Para editar la **Identificación de cuenta** o **agregar más dinero ficticio** para probar sus aplicaciones, haz clic en los **3 puntos verticales** al final de la fila de la tabla y seleccione la opción **Editar datos**.
```

2022-08-12 19:34 UTC, abderossi requested changes
Dejo ajustes gramaticales para los textos en español.

2022-08-12 19:35 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.en.md
> +In addition to these accounts, it is also important to use [test cards](/developers/en/guides/additional-content/testing/test-cards) to test payment integration and simulate the purchase process, as
```suggestion
In addition to these accounts, it is also important to use [test cards](/developers/en/guides/additional-content/testing/test-cards) to test payment integration and simulate the purchase process, as well as **balance in the test user's Mercado Pago account**. See more details below.
```

2022-08-12 19:36 UTC, abderossi requested changes
Agrego un ajuste de formato en inglés

2022-08-15 19:47 UTC, hgaldino commented on guides/snippets/test-integration/create-test-users.es.md
> +3. Luego, seleccione el **país de operación** para la cuenta. Esta información no se puede editar posteriormente y, además, los usuarios Comprador y Vendedor deben ser del mismo país.
Boa, Goixtii!

2022-08-16 22:01 UTC, abderossi commented on guides/snippets/test-integration/create-test-users.en.md
> +In addition to these accounts, it is also important to use [test cards](/developers/en/guides/additional-content/testing/test-cards) to test payment integration and simulate the purchase process, as
```suggestion
In addition to these accounts, it is also important to use [test cards](/developers/en/guides/additional-content/testing/test-cards) to test payment integration and simulate the purchase process, as well as **balance in the test user's Mercado Pago account**. See more details below.
```

2022-08-16 22:03 UTC, abderossi approved these changes
Dejo un ajuste de formato pequeño

2022-08-24 14:40 UTC, merged