feature/tokenizer-migration-to-bricks
mercadopago/devsite-docs pull request #1796
Opened 2022-08-04 23:23 UTC by abderossi

## Description

Describe what your Pull Request is about, including important information about what was done.

### Issue involved

Fixes #<issue>

2022-08-24 13:49 UTC, hgaldino requested changes

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/cardform-clientside.es.md
> +> h3
```suggestion
> h2
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/cardform-clientside.pt.md
> +> h3
```suggestion
> h2
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/cardform-clientside.pt.md
> +> PREV_STEP_CARD_PT
Goixti, já podemos tirar os next steps e incluir lá no menu

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/howto-migrate.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/howto-migrate.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/howto-migrate.en.md
> +/how-tos/how-to-migrate/web-tokenize-checkout-v1/clientside# How to migrate your integration to Checkout Bricks
```suggestion
# How to migrate your integration to Checkout Bricks
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v1-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v1-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v1-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v1-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v1-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v1-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v1-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/checkout-bricks/web-tokenize-checkout-v2-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-serverside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.en.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.es.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.pt.md
> +
```suggestion
```

2022-08-24 13:49 UTC, hgaldino commented on guides/web-tokenize-checkout/web-tokenize-checkout-v2-serverside.en.md
> +
```suggestion
```

2022-08-25 18:33 UTC, abderossi commented on guides/checkout-bricks/cardform-clientside.pt.md
> +> PREV_STEP_CARD_PT
```suggestion
```

2022-08-25 18:33 UTC, abderossi commented on guides/checkout-bricks/cardform-clientside.pt.md
> +>
```suggestion
```

2022-08-25 18:33 UTC, abderossi commented on guides/checkout-bricks/cardform-clientside.pt.md
> +> Como migrar para o Checkout Bricks
```suggestion
```

2022-08-25 18:33 UTC, abderossi commented on guides/checkout-bricks/cardform-clientside.pt.md
> +>
```suggestion
```

2022-08-25 18:33 UTC, abderossi commented on guides/checkout-bricks/cardform-clientside.pt.md
> +> Conheça como migrar sua integração de outro produto para o Checkout Bricks.
```suggestion
```

2022-08-25 18:33 UTC, abderossi commented on guides/checkout-bricks/cardform-clientside.pt.md
> +>
```suggestion
```

2022-08-25 18:34 UTC, abderossi commented on guides/checkout-bricks/cardform-clientside.pt.md
> +> [Como migrar para o Checkout Bricks](/developers/pt/docs/checkout-bricks/how-tos/how-to-migrate)
```suggestion
```

2022-08-25 22:05 UTC, hgaldino approved these changes

2022-08-25 22:05 UTC, merged