new files and archiving old files on legacy
mercadopago/devsite-docs pull request #1805
Opened 2022-08-11 14:19 UTC by abderossi

## Description

Nueva guia independiente de WooCommerce.
Se actualizaron las instrucciones de integración del plugin de Mercado Pago para WooCommerce. Creamos una nueva sección de pagos, detallada según el medio de pago disponible para cada país. Además, se agregó una sección más detallada de pruebas de la tienda.

2022-09-06 16:16 UTC, hgaldino requested changes
Goixtiii

Deixei alguns comentários pontuais só e inclui uma info dos meios de pagamento que vamos começar a incluir em todas as landings daqui pra frente. Como você já está fazendo Woo, aproveitei pra já incluir hehe <3

2022-09-06 16:16 UTC, hgaldino commented on guides/woocommerce/integration-test.pt.md
> +1. Na tela de pagamento, escolha pagar com um novo cartão de crédito e use os [cartões de teste](https://mercadopago[FAKER][URL][DOMAIN]/developers/es/docs/woocommerce/additional-content/cartõesdetes
```suggestion
1. Na tela de pagamento, escolha pagar com um novo cartão de crédito e use os [cartões de teste](/developers/pt/docs/woocommerce/additional-content/test-cards) para efetuar o pagamento. É importante não fazer login na conta do Mercado Pago ou tentar pagar com cartões para uso pessoal.
```

2022-09-06 16:16 UTC, hgaldino commented on guides/woocommerce/integration-test.es.md
> +1. En la pantalla de pago, elija pagar con una nueva tarjeta de crédito y use las [tarjetas de prueba](https://mercadopago[FAKER][URL][DOMAIN]/developers/es/docs/woocommerce/additional-content/test-c
```suggestion
1. En la pantalla de pago, elija pagar con una nueva tarjeta de crédito y use las [tarjetas de prueba](/developers/es/docs/woocommerce/additional-content/test-cards) para realizar el pago. Es importante no iniciar sesión en la cuenta de Mercado Pago ni intentar pagar con tarjetas para uso personal.
```

2022-09-06 16:16 UTC, hgaldino commented on guides/woocommerce/integration-test.en.md
> +1. Choose to pay with a new credit card and use the [test cards](https://mercadopago[FAKER][URL][DOMAIN]/developers/es/docs/woocommerce/additional-content/test-cards) to make the payment. It is impor
```suggestion
1. Choose to pay with a new credit card and use the [test cards](/developers/es/docs/woocommerce/additional-content/test-cards) to make the payment. It is important not to pay with cards for personal use.
```

2022-09-06 16:16 UTC, hgaldino commented on guides/woocommerce/integration-test.en.md
> +1. On the payment screen, choose to pay with a new credit card and use the [test cards](https://mercadopago[FAKER][URL][DOMAIN]/developers/es/docs/woocommerce/additional- content/test-cards) to make
```suggestion
1. On the payment screen, choose to pay with a new credit card and use the [test cards](/developers/es/docs/woocommerce/additional-content/test-cards) to make the payment. It is important not to log in to the Mercado Pago account or try to pay with cards for personal use.
```

2022-09-06 16:16 UTC, hgaldino commented on guides/woocommerce/integration-test.es.md
> +1. Elija pagar con una nueva tarjeta de crédito y utilice las [tarjetas de prueba](https://mercadopago[FAKER][URL][DOMAIN]/developers/es/docs/woocommerce/additional-content/test-cards) para realizar
```suggestion
1. Elija pagar con una nueva tarjeta de crédito y utilice las [tarjetas de prueba](/developers/es/docs/woocommerce/additional-content/test-cards) para realizar el pago. Es importante no pagar con tarjetas para uso personal.
```

2022-09-07 16:34 UTC, abderossi commented on guides/woocommerce/goto-production.pt.md
> +Para obter mais informações, visite nossa documentação [Requisitos para ir para a produção](/developers/en/docs/woocommerce/additional-content/goto-production).
```suggestion
Para obter mais informações, visite nossa documentação [Requisitos para entrar em produção](/developers/en/docs/woocommerce/additional-content/goto-production).
```

2022-09-07 16:35 UTC, abderossi commented on guides/woocommerce/integration-test.es.md
> +1. Seleccione la opción **Quiero pagar con tarjeta de crédito**.
```suggestion
1. Selecciona la opción **Quiero pagar con tarjeta de crédito**.
```

2022-09-07 16:35 UTC, abderossi commented on guides/woocommerce/integration-test.es.md
> +1. Agregue la información de la tarjeta de prueba indicada (número de tarjeta, CVV y fecha de vencimiento).
```suggestion
1. Agrega la información de la tarjeta de prueba indicada (número de tarjeta, CVV y fecha de vencimiento).
```

2022-09-07 16:40 UTC, abderossi commented
@hgaldino aplicados los ajustes!

2022-09-08 13:52 UTC, hgaldino approved these changes

2022-09-08 13:52 UTC, merged