Changes for mexico and argentina added
mercadopago/devsite-docs pull request #1834
Opened 2022-09-12 17:19 UTC by danielrodriguezMELI

## Description

Cambios para Mexico y Argentina para las campañas de apagado del bank y NLedger

### Issue involved
[MPRC-11856](https://mercadolibre.atlassian.net/browse/MPRC-11856)

2022-09-15 20:52 UTC, abderossi commented on guides/additional-content/reports/available-money/generate.en.md
> +> As of December 12th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use
```suggestion
> As of December 12th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use the "Releases" report](https://bit.ly/3zCb1ye).
```

2022-09-15 20:53 UTC, abderossi commented on guides/additional-content/reports/available-money/generate.es.md
> +> A partir del 1 de agosto no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones.](h
```suggestion
> A partir del 1 de agosto no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible, [usa el reporte Liberaciones](https://vendedores.mercadolibre[FAKER][URL][DOMAIN]/lleva-el-control-de-tu-dinero-con-el-reporte-de-liberaciones).
```

2022-09-15 20:54 UTC, abderossi commented on guides/additional-content/reports/available-money/generate.pt.md
> +> A partir de 5 de dezembro, não será mais possível criar novos relatórios de "Dinheiro retirado". Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por fa
```suggestion
> A partir de 5 de dezembro, não será mais possível criar novos relatórios de Dinheiro retirado. Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por favor, [use o relatório Liberações](https://bit.ly/3B7Q5Qy).
```

2022-09-15 20:54 UTC, abderossi commented on guides/additional-content/reports/available-money/generate.pt.md
> +> A partir de 12 de dezembro, não será mais possível criar novos relatórios de "Dinheiro retirado". Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por f
```suggestion
> A partir de 12 de dezembro, não será mais possível criar novos relatórios de Dinheiro retirado. Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por favor, [use o relatório Liberações](https://bit.ly/3RH0KJ4).
```

2022-09-15 20:57 UTC, abderossi commented on guides/additional-content/reports/available-money/glossary.en.md
> +> As of December 12th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use
```suggestion
> As of December 12th, you will no longer be able to create new Money withdrawn reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use the Releases report](https://bit.ly/3zCb1ye).
```

2022-09-15 21:00 UTC, abderossi commented on guides/additional-content/reports/available-money/glossary.en.md
> +> As of December 5th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use t
```suggestion
> As of December 5th, you will no longer be able to create new Money withdrawn reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use the Releases report](https://bit.ly/3zCb1ye).
```

2022-09-15 21:01 UTC, abderossi commented on guides/additional-content/reports/available-money/glossary.es.md
> +> A partir del 5 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usá el reporte Liberaciones]
```suggestion
> A partir del 5 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones](https://bit.ly/3JzFPEG).
```

2022-09-15 21:02 UTC, abderossi commented on guides/additional-content/reports/available-money/glossary.es.md
> +> A partir del 12 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones
```suggestion
> A partir del 12 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones](https://bit.ly/3QiCD2f).
```

2022-09-15 21:02 UTC, abderossi commented on guides/additional-content/reports/available-money/glossary.pt.md
> +> A partir de 5 de dezembro, não será mais possível criar novos relatórios de "Dinheiro retirado". Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por fa
```suggestion
> A partir de 5 de dezembro, não será mais possível criar novos relatórios de Dinheiro retirado. Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por favor,[use o relatório Liberações](https://bit.ly/3B7Q5Qy).
```

2022-09-15 21:02 UTC, abderossi commented on guides/additional-content/reports/available-money/glossary.pt.md
> +> A partir de 12 de dezembro, não será mais possível criar novos relatórios de "Dinheiro retirado". Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por f
```suggestion
> A partir de 12 de dezembro, não será mais possível criar novos relatórios de Dinheiro retirado. Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por favor,[use o relatório Liberações](https://bit.ly/3RH0KJ4).
```

2022-09-15 21:02 UTC, abderossi commented on guides/additional-content/reports/available-money/how-to-use.en.md
> +> As of December 12th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use
```suggestion
> As of December 12th, you will no longer be able to create new Money withdrawn reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use the Releases report](https://bit.ly/3zCb1ye).
```

2022-09-15 21:03 UTC, abderossi commented on guides/additional-content/reports/available-money/how-to-use.en.md
> +> As of December 5th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use t
```suggestion
> As of December 5th, you will no longer be able to create new Money withdrawn reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use the Releases report](https://bit.ly/3zCb1ye).
```

2022-09-15 21:03 UTC, abderossi commented on guides/additional-content/reports/available-money/how-to-use.es.md
> +> A partir del 12 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones
```suggestion
> A partir del 12 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones](https://bit.ly/3QiCD2f).
```

2022-09-15 21:04 UTC, abderossi commented on guides/additional-content/reports/available-money/how-to-use.pt.md
> +> A partir de 5 de dezembro, não será mais possível criar novos relatórios de "Dinheiro retirado". Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por fa
```suggestion
> A partir de 5 de dezembro, não será mais possível criar novos relatórios de Dinheiro retirado. Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por favor, [use o relatório Liberações](https://bit.ly/3B7Q5Qy)
```

2022-09-15 21:04 UTC, abderossi commented on guides/additional-content/reports/available-money/introduction.en.md
> +> As of December 12th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use
```suggestion
> As of December 12th, you will no longer be able to create new Money withdrawn reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use the Releases report.](https://bit.ly/3zCb1ye).
```

2022-09-15 21:04 UTC, abderossi commented on guides/additional-content/reports/available-money/introduction.en.md
> +> As of December 5th, you will no longer be able to create new "Money withdrawn" reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use t
```suggestion
> As of December 5th, you will no longer be able to create new Money withdrawn reports. In order to keep tracking all the transfers, withdrawals and movements of your available money, [please use the Releases report](https://bit.ly/3zCb1ye).
```

2022-09-15 21:04 UTC, abderossi commented on guides/additional-content/reports/available-money/introduction.es.md
> +> A partir del 12 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones
```suggestion
> A partir del 12 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones](https://bit.ly/3QiCD2f).
```

2022-09-15 21:05 UTC, abderossi commented on guides/additional-content/reports/available-money/introduction.es.md
> +> A partir del 5 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usá el reporte Liberaciones.
```suggestion
> A partir del 5 de diciembre no podrás crear nuevos reportes Dinero retirado. Para seguir llevando el control de todos los retiros y movimientos de tu dinero disponible [usa el reporte Liberaciones](https://bit.ly/3JzFPEG).
```

2022-09-15 21:05 UTC, abderossi commented on guides/additional-content/reports/available-money/introduction.pt.md
> +> A partir de 5 de dezembro, não será mais possível criar novos relatórios de "Dinheiro retirado". Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por fa
```suggestion
> A partir de 5 de dezembro, não será mais possível criar novos relatórios de Dinheiro retirado. Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por favor,[use o relatório Liberações](https://bit.ly/3B7Q5Qy).
```

2022-09-15 21:05 UTC, abderossi commented on guides/additional-content/reports/available-money/introduction.pt.md
> +> A partir de 12 de dezembro, não será mais possível criar novos relatórios de "Dinheiro retirado". Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por f
```suggestion
> A partir de 12 de dezembro, não será mais possível criar novos relatórios de Dinheiro retirado. Para continuar controlando as transferências, saques e movimentações do seu saldo disponível, por favor,[use o relatório Liberações](https://bit.ly/3RH0KJ4).
```

2022-09-15 21:06 UTC, abderossi commented on guides/additional-content/reports/released-money/introduction.en.md
> +> The reports you generate from October 5th onwards will show your money movements in chronological order, so you will be able to identify them more easily and better control your business finances.
```suggestion
> The reports you generate from October 5th onwards will show your money movements in chronological order, so you will be able to identify them more easily and better control your business finances. [Learn how to use it](https://bit.ly/3zCb1ye).
```

2022-09-15 21:06 UTC, abderossi commented on guides/additional-content/reports/released-money/introduction.es.md
> +> Los reportes que generes a partir del 12 de octubre presentarán tus movimientos en orden cronológico para que puedas identificarlos más facilmente y controlar mejor las finanzas de tu negocio. [Con
```suggestion
> Los reportes que generes a partir del 12 de octubre presentarán tus movimientos en orden cronológico para que puedas identificarlos con más facilidad y controlar mejor las finanzas de tu negocio. [Conoce la nueva anatomía del reporte](https://bit.ly/3QiCD2f).
```

2022-09-15 21:07 UTC, abderossi commented on guides/additional-content/reports/released-money/introduction.es.md
> +> Los reportes que generes a partir del 5 de octubre presentarán tus movimientos en orden cronológico para que puedas identificarlos más fácil y controlar mejor las finanzas de tu negocio. [Conoce la
```suggestion
> Los reportes que generes a partir del 5 de octubre presentarán tus movimientos en orden cronológico para que puedas identificarlos más fácil y controlar mejor las finanzas de tu negocio. [Conoce la nueva estructura del reporte](https://bit.ly/3JzFPEG).
```

2022-09-15 21:07 UTC, abderossi requested changes
Cambios de puntuación y estilo en relación con el devsite.

2022-09-15 21:49 UTC, danielrodriguezMELI commented
@abderossi Ya aprove los cambios que me sugeriste. Muchas gracias

2022-09-15 22:01 UTC, rwaetemann approved these changes

2022-09-16 14:43 UTC, abderossi approved these changes

2022-09-16 14:59 UTC, merged