Feature/salesforce doc
mercadopago/devsite-docs pull request #1836
Opened 2022-09-13 15:11 UTC by abderossi

## Description

Nueva documentación sobre el plugin de Mercado Pago en Salesforce.

2022-09-27 18:46 UTC, BrunoCamarda requested changes
@abderossi, fiz algumas alterações. Alguns links estavam indicando as documentações em espanhol e em alguns casos, fiz alguns ajustes simples para facilitar o entendimento.

2022-09-27 18:46 UTC, BrunoCamarda commented on guides/salesforce/requirements.pt.md
> +| Conta de vendedor do Mercado Pago ou Mercado Livre | Para integrar o cartucho do Mercado Pago em sua loja Salesforce, você precisa de uma conta de vendedor no Mercado Pago ou Mercado Livre. Se você
```suggestion
| Conta de vendedor do Mercado Pago ou Mercado Livre | Para integrar o cartucho do Mercado Pago em sua loja Salesforce, você precisa de uma conta de vendedor no Mercado Pago ou Mercado Livre. Se você ainda não tem, [clique aqui](https://www.mercadopago[FAKER][URL][DOMAIN]/hub/registration/landing) para criá-la. |
```

2022-09-27 18:46 UTC, BrunoCamarda commented on guides/salesforce/requirements.pt.md
> +| Salesforce Commerce Cloud | Você deve ter uma loja criada no Salesforce Commerce Cloud. Este cartucho está disponível a partir da versão 22.8 do Commerce Cloud. Para obter mais informações sobre o
```suggestion
| Salesforce Commerce Cloud | Você deve ter uma loja criada no Salesforce Commerce Cloud. Este cartucho está disponível a partir da versão 22.8 do Commerce Cloud. Para obter mais informações sobre o Salesforce Commerce Cloud, acesse o [site oficial](https://www.salesforce.com/products/commerce-cloud/overview/) |
```

2022-09-27 18:46 UTC, BrunoCamarda commented on guides/salesforce/installation.pt.md
> +1. [Integrar cartucho](/developers/en/docs/salesforce-commerce-cloud/installation/cartridge-integration)
```suggestion
1. [Integrar cartucho](/developers/pt/docs/salesforce-commerce-cloud/installation/cartridge-integration)
```

2022-09-27 18:46 UTC, BrunoCamarda commented on guides/salesforce/installation.pt.md
> +2. [Construir loja](/developers/en/docs/salesforce-commerce-cloud/installation/store-build)
```suggestion
2. [Construir loja](/developers/pt/docs/salesforce-commerce-cloud/installation/store-build)
```

2022-09-27 18:46 UTC, BrunoCamarda commented on guides/salesforce/installation.pt.md
> +3. [Carregar loja](/developers/en/docs/salesforce-commerce-cloud/installation/store-deploy)
```suggestion
3. [Carregar loja](/developers/pt/docs/salesforce-commerce-cloud/installation/store-deploy)
```

2022-09-27 18:46 UTC, BrunoCamarda commented on guides/salesforce/credentials.pt.md
> +Para receber pagamentos com o Mercado Pago, primeiro você deve ter as credenciais. Você pode verificar suas credenciais no [Dashboard](/developers/panel). Se você quiser saber mais sobre as credencia
```suggestion
Para receber pagamentos com o Mercado Pago, primeiro você deve ter as credenciais. Você pode verificar suas credenciais no [Dashboard](/developers/panel). Se você quiser saber mais sobre as credenciais do Mercado Pago, acesse [esta documentação](/developers/pt/docs/salesforce-commerce-cloud/additional-content/credentials).
```

2022-09-27 18:46 UTC, BrunoCamarda commented on guides/salesforce/payments-configuration.pt.md
> +2. Na caixa, procure a coluna **Ordem de classificação**. Nesta coluna, atribua um pedido numérico aos métodos de pagamento de sua loja para definir o pedido em que deseja exibi-los.
```suggestion
2. Na caixa, procure a coluna **Ordem de classificação**. Nesta coluna, atribua uma ordem numérica aos métodos de pagamento de sua loja para definir a ordem em que deseja exibi-los.
```

2022-09-27 18:59 UTC, pcanosa commented on guides/salesforce/plugin-integration.es.md
> +Primero, deberás hacer una descarga del estado actual del sitio de tu tienda. Para eso, ve a **Administración > Desarrollo del sitio > Implementación de código**. introduce la versión activa y descár
```suggestion
Primero, deberás hacer una descarga del estado actual del sitio de tu tienda. Para eso, ve a **Administración > Desarrollo del sitio > Implementación de código**. Introduce la versión activa y descárgala. Luego, descomprime el archivo .zip que descargaste.
```

2022-09-27 19:08 UTC, pcanosa commented on guides/salesforce/store-deploy.es.md
> +Para usar Mercado Pago con Salesforce Commerce Cloud, debes tener una cuenta de Mercado Pago. Sigue [esta documentación](/developers/es/docs/salesforce-commerce-cloud/aditional-content/credentials) p
```suggestion
Para usar Mercado Pago con Salesforce Commerce Cloud, debes tener una cuenta de Mercado Pago. Sigue [esta documentación](/developers/es/docs/salesforce-commerce-cloud/additional-content/credentials) para generar tus credenciales. Después de eso, ve a **Herramientas comerciales > Preferencias personalizadas > MercadopagoCredentials** y completa los campos **Public Key** y **Access Token**.
```

2022-09-27 19:10 UTC, pcanosa commented on guides/salesforce/configuration.es.md
> +* [Verificar la instalación de Mercado Pago](/developers/es/docs/salesforce-commerce-cloud/integration-configuration/instalation-verification)
```suggestion
* [Verificar la instalación de Mercado Pago](/developers/es/docs/salesforce-commerce-cloud/integration-configuration/installation-verification)
```

2022-09-27 19:19 UTC, pcanosa commented on guides/salesforce/payments-configuration.es.md
> +2. Dentro del cuadro, busca la columna **Sort Order**. En esta columna, asígnale un orden numérico a los medios de pago de tu tienda para definir el orden en el que quieras mostrarlos.
```suggestion
2. Dentro del cuadro, busca la columna **Sort Order**. En esta columna, asígnale un orden numérico a los medios de pago de tu tienda para definir la posición en la que quieras mostrarlos. 
```

2022-09-27 19:22 UTC, pcanosa commented on guides/salesforce/integration-test.es.md
> +1. Elige pagar con una nueva tarjeta de crédito y utiliza las [tarjetas de prueba](/developers/es/docs/salesforce-commerce-cloud/aditional-content/test-cards) para realizar el pago. **Es importante n
```suggestion
1. Elige pagar con una nueva tarjeta de crédito y utiliza las [tarjetas de prueba](/developers/es/docs/salesforce-commerce-cloud/additional-content/test-cards) para realizar el pago. **Es importante no pagar con tarjetas para uso personal**.
```

2022-09-27 19:22 UTC, pcanosa commented on guides/salesforce/integration-test.es.md
> +Para corroborar que la tienda esté configurada correctamente, te recomendamos realizar compras de prueba utilizando las [tarjetas de prueba](/developers/es/docs/salesforce-commerce-cloud/aditional-co
```suggestion
Para corroborar que la tienda esté configurada correctamente, te recomendamos realizar compras de prueba utilizando las [tarjetas de prueba](/developers/es/docs/salesforce-commerce-cloud/additional-content/test-cards) de Mercado Pago. 
```

2022-09-27 19:23 UTC, pcanosa commented on guides/salesforce/integration-test.es.md
> +1. Elige pagar con una nueva tarjeta de crédito y utiliza las [tarjetas de prueba](/developers/es/docs/salesforce-commerce-cloud/aditional-content/test-cards) para realizar el pago. **Es importante n
```suggestion
1. Elige pagar con una nueva tarjeta de crédito y utiliza las [tarjetas de prueba](/developers/es/docs/salesforce-commerce-cloud/aditional-content/test-cards) para realizar el pago. **Es importante no pagar con tarjetas de uso personal**.
```

2022-09-27 19:27 UTC, pcanosa reviewed
Ahí fue la revisión con algunos arreglos en enlaces y cosas breves en redacción.

2022-09-28 12:52 UTC, abderossi commented on guides/salesforce/integration-test.pt.md
> +1. Opte por pagar com um novo cartão de crédito e use os [cartões de teste](/developers/pt/docs/salesforce-commerce-cloud/additional-content/test-cards) para efetuar o pagamento. **É importante não p
```suggestion
1. Opte por pagar com um novo cartão de crédito e use os [cartões de teste](/developers/pt/docs/salesforce-commerce-cloud/additional-content/test-cards) para efetuar o pagamento. **É importante não pagar com cartões de uso pessoal**.
```

2022-09-28 14:39 UTC, abderossi commented
@BrunoCamarda @pcanosa apliqué los ajustes que dejaron. Si ven ok el pull request, aguardo sus aprobaciones.

2022-10-03 21:23 UTC, hgaldino approved these changes

2022-10-03 21:23 UTC, merged