[DEVCOMMS-1214] Feature/openFinance-choAPI
mercadopago/devsite-docs pull request #1899
Opened 2022-11-16 20:46 UTC by BrunoCamarda

Adição da documentação de Open Finance para Checkout API.

2022-11-30 15:49 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Open Finance es un nuevo sistema financiero que le permite tener un dominio total de sus datos y mayor libertad con sus finanzas. Con él, es posible compartir historias financieras con otras instituc
```suggestion
Open Finance es un nuevo sistema financiero que te permite tener un dominio total de sus datos y mayor libertad con sus finanzas. Con él, es posible compartir historias financieras con otras instituciones para acceder a productos y servicios más ventajosos.
```

2022-11-30 15:51 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Con Open Finance, se pueden hacer pagos Pix con saldos de otras cuentas bancarias, **en el Checkout API**.
```suggestion
Con Open Finance, se pueden hacer pagos Pix con saldos de otras cuentas bancarias **en Checkout API**.
```

2022-11-30 15:53 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Para usar esta función, debe registrar una clave Pix en su cuenta de Mercado Pago. Si aún no lo ha hecho, [haga clic aquí](https://www.youtube.com/watch?v=60tApKYVnkA) para obtener más información
```suggestion
> Para usar esta función, debes registrar una clave Pix en su cuenta de Mercado Pago. Si aún no lo has hecho, [haz clic aquí](https://www.youtube.com/watch?v=60tApKYVnkA) para obtener más información sobre cómo registrarte.
```

2022-11-30 15:54 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Use nuestras API o SDK para crear su propio sistema de pago Open Finance en su sitio web o aplicación móvil. Desde la configuración básica hasta la avanzada, controlando todo el flujo de acuerdo con
```suggestion
Usa nuestras API o SDK para crear tu propio sistema de pago Open Finance en tu sitio web o aplicación móvil. Desde la configuración básica hasta la avanzada, controlando todo el flujo de acuerdo con tu experiencia de pago.
```

2022-11-30 15:55 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +* Cree su propia plataforma de Iniciación de Pagos dentro de su sitio web.
```suggestion
* Crea tu propia plataforma de Iniciación de Pagos dentro de tu sitio web.
```

2022-11-30 15:55 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +* Permita que sus clientes paguen con saldos de otras cuentas.
```suggestion
* Permite que tus clientes paguen con saldos de otras cuentas. 
```

2022-11-30 15:56 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +### Cómo integrar Open Finance en su Checkout
```suggestion
### Cómo integrar Open Finance en tu Checkout
```

2022-11-30 15:57 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Para iniciar un pago utilizando Open Finance, debe tener configurado previamente el método de pago Pix. Para obtener instrucciones de configuración e integración, [consulte la documentación](/develop
```suggestion
Para iniciar un pago utilizando Open Finance, debes tener configurado previamente el método de pago Pix. Para obtener instrucciones de configuración e integración, [consulta la documentación](/developers/es/docs/checkout-api/prerequisites).
```

2022-11-30 15:59 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Una vez que haya configurado correctamente el método de pago, deberá agregar nueva información a la solicitud para [crear el pago](/developers/es/reference/payments/_payments/post), a través del pará
```suggestion
Una vez que hayas configurado correctamente el método de pago, deberás agregar nueva información a la solicitud para [crear el pago](/developers/es/reference/payments/_payments/post), a través del parámetro `point_of_interaction`, que indica el modo de financiación abierta. Esto es válido tanto a través de la API como a través de nuestros SDK, como se muestra en los siguientes ejemplos:
```

2022-11-30 16:01 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Para asegurar que el usuario pagador comprenda el uso de la opción de Inicio de Transacción de Pago de Open Finance, es necesario asegurarse de que en el Checkout quede claro que el pago **se realiza
```suggestion
Para asegurar que el usuario pagador comprenda el uso de la opción de Inicio de Transacción de Pago de Open Finance, es necesario asegurarse de que en el Checkout quede claro que el pago **se realiza a través de Open Finance dentro del ecosistema de pagos de Mercado Pago**.
```

2022-11-30 16:02 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Para permitir que el cliente inicie una transacción de pago a través del iniciador de transacciones de pago de Open Finance, debe hacer lo siguiente:
```suggestion
Para permitir que el cliente inicie una transacción de pago a través del iniciador de transacciones de pago de Open Finance, debes hacer lo siguiente:
```

2022-11-30 16:02 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Para hacer esto, solo haga la siguiente solicitud:
```suggestion
Para hacer esto, solo haz la siguiente solicitud:
```

2022-11-30 16:04 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Con el ID de banco elegido por el usuario, cree un pago y pase esta información al campo `transaction_data.bank_info.origin_bank_id` de la solicitud de creación de pago.
```suggestion
Con el ID de banco elegido por el usuario, crea un pago y pasa esta información al campo `transaction_data.bank_info.origin_bank_id` de la solicitud de creación de pago.
```

2022-11-30 16:04 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Para más información, vea la sección de creación de pagos en [esta documentación](#bookmark_creación_de_pago)
```suggestion
Para más información, ve la sección de creación de pagos en [esta documentación](#bookmark_creación_de_pago)
```

2022-11-30 16:07 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Recuerde que el Banco Central de Brasil requiere que el cliente conozca el Iniciador de la Transacción de Pago que está orquestando la transacción, por lo que es necesario informar que la transacci
```suggestion
> Recuerda que el Banco Central de Brasil requiere que el cliente conozca el Iniciador de la Transacción de Pago que está orquestando la transacción, por lo que es necesario informar que la transacción se "realiza a través de Mercado Pago".
```

2022-11-30 16:08 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Si necesita abrir una aplicación móvil, le recomendamos que cree un [Android App Link](https://developer.android.com/training/app-links) o un [Universal Link](https://developer.android.com/training/a
```suggestion
Si necesitas abrir una aplicación móvil, te recomendamos que crees un [Android App Link](https://developer.android.com/training/app-links) o un [Universal Link](https://developer.android.com/training/app-links). Vale recordar que en Androids con versiones anteriores a la 12, el usuario tiene la posibilidad de elegir dónde abrir el App Link como se muestra en la siguiente imagen:
```

2022-11-30 16:08 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Por lo tanto, incluso si el flujo va a terminar en una aplicación móvil, **le recomendamos que también cree una pantalla web de handover** para usarla cuando el usuario quiera abrir el link en su nav
```suggestion
Por lo tanto, incluso si el flujo va a terminar en una aplicación móvil, **te recomendamos que también crees una pantalla web de handover** para usarla cuando el usuario quiera abrir el link en su navegador.
```

2022-11-30 16:08 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Ofrezca a sus clientes información clara y precisa sobre posibles errores en la Iniciación de Operaciones de Pago o el estado de los pagos realizados. Esto le permite notificarles qué acción pueden t
```suggestion
Ofrece a tus clientes información clara y precisa sobre posibles errores en la Iniciación de Operaciones de Pago o el estado de los pagos realizados. Esto te permite notificarles qué acción pueden tomar para resolver o comunicar si hay pasos adicionales que tomar.
```

2022-11-30 16:09 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Recuerde que el Banco Central de Brasil requiere que cada transacción comenzada a través del Iniciador de transacciones de pago venza después de 60 minutos.
```suggestion
> Recuerda que el Banco Central de Brasil requiere que cada transacción comenzada a través del Iniciador de transacciones de pago venza después de 60 minutos.
```

2022-11-30 16:11 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +| INSUFFICIENT_AMOUNT        | El usuario que paga no tiene                                           | Saldo insuficiente en la cuenta que has elegido. Elija otra cuenta y vuelva a intentarlo.
Bru, aquí está incompleta la segunda columna, sería "El usuario que paga no tiene saldo disponible", o algo así?

2022-11-30 16:11 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +| REJECTED_CAP_EXCEEDED      | El limite del valor Pix se supera                                      | Esta cantidad excede su límite diario de Pix. Vuelve a la {{institución retenedora}} y elige un
```suggestion
| REJECTED_CAP_EXCEEDED      | El límite del valor Pix se supera                                      | Esta cantidad excede su límite diario de Pix. Vuelve a la {{institución retenedora}} y elige una cantidad más baja, o vuelve a intentarlo mañana. |
```

2022-11-30 16:12 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +* Informe la URL de redireccionamiento en `callback_url`.
```suggestion
* Informar la URL de redireccionamiento en `callback_url`.
```

2022-11-30 16:13 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +En el entorno de Sandbox, se mostrará una pantalla que simula la institución propietaria de la cuenta, con tres botones que le permitirán elegir cuál será el estado final de este pago de prueba:
```suggestion
En el entorno de Sandbox, se mostrará una pantalla que simula la institución propietaria de la cuenta, con tres botones que te permitirán elegir cuál será el estado final de este pago de prueba:
```

2022-11-30 16:13 UTC, pcanosa commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Finalmente, después de elegir el estado de pago final, será redirigido a la pantalla de feedbacks.
```suggestion
Finalmente, después de elegir el estado de pago final, serás redirigido a la pantalla de feedbacks.
```

2022-11-30 16:20 UTC, pcanosa commented on guides/checkout-api-v2/integrate-openfinance.es.md
> +> Para usar esta función, debe registrar una clave Pix en su cuenta de Mercado Pago. Si aún no lo ha hecho, [haga clic aquí](https://www.youtube.com/watch?v=60tApKYVnkA) para obtener más información
```suggestion
> Para usar esta función, debes registrar una clave Pix en tu cuenta de Mercado Pago. Si aún no lo has hecho, [haz clic aquí](https://www.youtube.com/watch?v=60tApKYVnkA) para obtener más información sobre cómo registrarse.
```

2022-11-30 16:21 UTC, pcanosa commented on guides/checkout-api-v2/integrate-openfinance.es.md
> +Una vez que haya configurado correctamente el método de pago, deberá agregar nueva información a la solicitud para [crear el pago](/developers/es/reference/payments/_payments/post), a través del pará
```suggestion
Una vez que hayas configurado correctamente el método de pago, deberás agregar nueva información a la solicitud para [crear el pago](/developers/es/reference/payments/_payments/post) a través del parámetro `point_of_interaction`, que indica el modo de financiación abierta. Esto es válido tanto a través de la API como a través de nuestros SDK, como se muestra en los siguientes ejemplos:
```

2022-11-30 16:22 UTC, pcanosa commented on guides/checkout-api-v2/integrate-openfinance.es.md
> +Para esto, puede redirigir al usuario a la URL directamente o presentar un botón que redirija cuando se haga clic.
```suggestion
Para esto, puedes redirigir al usuario a la URL directamente o presentar un botón que redirija cuando se haga clic.
```

2022-11-30 16:23 UTC, pcanosa commented on guides/checkout-api-v2/integrate-openfinance.es.md
> +Para probar la integración, debe usar una credencial de prueba al crear un pago y tener un usuario de prueba con una clave Pix registrada. [Haga clic aquí](/developers/es/docs/checkout-api/integratio
```suggestion
Para probar la integración, debes usar una credencial de prueba al crear un pago y tener un usuario de prueba con una clave Pix registrada. [Haz clic aquí](/developers/es/docs/checkout-api/integration-test/make-test-purchase) para acceder a la documentación y encontrar más detalles sobre cómo hacerlo.
```

2022-11-30 16:23 UTC, pcanosa commented on guides/checkout-api-v2/integrate-openfinance.es.md
> +Cree un pago de Pix Open Finance y utilice la URL disponible en el atributo `point_of_interaction.transaction_data.ticket_url` para acceder a la página de redirección.
```suggestion
Crea un pago de Pix Open Finance y utiliza la URL disponible en el atributo `point_of_interaction.transaction_data.ticket_url` para acceder a la página de redirección.
```

2022-11-30 18:54 UTC, BrunoCamarda commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +| INSUFFICIENT_AMOUNT        | El usuario que paga no tiene                                           | Saldo insuficiente en la cuenta que has elegido. Elija otra cuenta y vuelva a intentarlo.
si si exactamente 😅

2022-12-02 16:04 UTC, hgaldino approved these changes

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +Redirection must occur to the secure digital channel of the Financial Institution holding the account, which may be:
```suggestion

Redirection must occur to the secure digital channel of the Financial Institution holding the account, which may be:
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +> Important
```suggestion
> Attention
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +After the payment has been authorized at the other institution, the user will be redirected to a Mercado Pago web page, which regulates this payment flow. The user will then be directed to the URL in
```suggestion

After the payment has been authorized at the other institution, the user will be redirected to a Mercado Pago web page, which regulates this payment flow. The user will then be directed to the URL inserted in the 'callback_url' attribute when creating the payment.
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +
```suggestion
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +>
```suggestion
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +> Note
```suggestion
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +>
```suggestion
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +**Reasons of rejection**
```suggestion
**Reasons of rejection**:
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +To test your integration, simply create a PIX Open Finance payment and follow the steps below:
```suggestion

To test your integration, simply create a PIX Open Finance payment and follow the steps below:
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +
```suggestion
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +> Important
```suggestion
> Attention
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +Open Finance is a new financial system that gives you more freedom with your finances and control over your data. Financial histories can be shared with other institutions to gain access to more bene
```suggestion

Open Finance is a new financial system that gives you more freedom with your finances and control over your data. Financial histories can be shared with other institutions to gain access to more beneficial products and services.
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +
```suggestion
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +
```suggestion
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +> Important information
```suggestion
> Attention
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +> - For this type of payment method, the **CPF number is mandatory**.
```suggestion
> For this type of payment method, the **CPF number is mandatory**.
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +> - The `callback_url` parameter must contain the URL value that shows the feedback page.
```suggestion
> The `callback_url` parameter must contain the URL value that shows the feedback page.
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +Response
```suggestion
Response:
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +With the payment creation response, just use the URL available in the `point_of_interaction.transaction_data.ticket_url` object. This allows the buyer to finalize the payment through Open Finance.
```suggestion

With the payment creation response, just use the URL available in the `point_of_interaction.transaction_data.ticket_url` object. This allows the buyer to finalize the payment through Open Finance.
```

2022-12-02 16:04 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.en.md
> +If you want to test the integration, you must have a test user with a registered Pix key and a test credential. You can find more details on how to do this by [clicking here](/developers/en/docs/chec
```suggestion

If you want to test the integration, you must have a test user with a registered Pix key and a test credential. You can find more details on how to do this by [clicking here](/developers/en/docs/checkout-api/integration-test/make-test-purchase).
```

2022-12-02 16:10 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.es.md
> +Open Finance es un nuevo sistema financiero que te permite tener un dominio total de tus datos y mayor libertad con tus finanzas. Con él, es posible compartir historias financieras con otras instituc
```suggestion

Open Finance es un nuevo sistema financiero que te permite tener un dominio total de tus datos y mayor libertad con tus finanzas. Con él, es posible compartir historias financieras con otras instituciones para acceder a productos y servicios más ventajosos.
```

2022-12-02 16:11 UTC, hgaldino commented on guides/checkout-api-v2/integrate-openfinance.es.md
> +Respuesta
```suggestion
Respuesta:
```

2022-12-02 16:33 UTC, hgaldino approved these changes

2022-12-02 16:33 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +**Erros possíveis**:
```suggestion
**Possible errors**:
```

2022-12-02 16:33 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +
```suggestion
```

2022-12-02 16:33 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +**Payment Status**:
```suggestion
**Payment status**:
```

2022-12-02 16:33 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.en.md
> +> Important information
```suggestion
> Attention
```

2022-12-02 16:35 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +### Características
```suggestion
## Características
```

2022-12-02 16:35 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +* Crea tu propia plataforma de Iniciación de Pagos dentro de tu sitio web.
```suggestion

* Crea tu propia plataforma de Iniciación de Pagos dentro de tu sitio web.
```

2022-12-02 16:35 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +### Cómo integrar Open Finance en tu Checkout
```suggestion
## Cómo integrar Open Finance en tu Checkout
```

2022-12-02 16:35 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Para iniciar un pago utilizando Open Finance, debes tener configurado previamente el método de pago Pix. Para obtener instrucciones de configuración e integración, [consulta la documentación](/develo
```suggestion

Para iniciar un pago utilizando Open Finance, debes tener configurado previamente el método de pago Pix. Para obtener instrucciones de configuración e integración, [consulta la documentación](/developers/es/docs/checkout-api/prerequisites).
```

2022-12-02 16:35 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +
```suggestion
```

2022-12-02 16:35 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> - Para este tipo de método de pago, **el número de CPF es obligatorio**.
```suggestion
> Para este tipo de método de pago, **el número de CPF es obligatorio**.
```

2022-12-02 16:36 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> - El parámetro `callback_url` tiene que ser la URL de la pantalla de feedback.
```suggestion
> El parámetro `callback_url` tiene que ser la URL de la pantalla de feedback.
```

2022-12-02 16:36 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Informaciones importantes
```suggestion
> Atención
```

2022-12-02 16:36 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Respuesta
```suggestion
Respuesta:
```

2022-12-02 16:36 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Para asegurar que el usuario pagador comprenda el uso de la opción de Inicio de Transacción de Pago de Open Finance, es necesario asegurarse de que en el Checkout quede claro que el pago **se realiza
```suggestion

Para asegurar que el usuario pagador comprenda el uso de la opción de Inicio de Transacción de Pago de Open Finance, es necesario asegurarse de que en el Checkout quede claro que el pago **se realiza a través de Open Finance dentro del ecosistema de pagos de Mercado Pago**.
```

2022-12-02 16:36 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +Presentar una lista de posibles entidades financieras para que el usuario seleccione la que le gustaría para proceder al pago.
```suggestion

Presentar una lista de posibles entidades financieras para que el usuario seleccione la que le gustaría para proceder al pago.
```

2022-12-02 16:36 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +**Parámetros de filtro**
```suggestion
**Parámetros de filtro**:
```

2022-12-02 16:37 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +>
```suggestion
```

2022-12-02 16:37 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Nota
```suggestion
```

2022-12-02 16:37 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +>
```suggestion
```

2022-12-02 16:37 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> NOTE
```suggestion
```

2022-12-02 16:37 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +**Respuesta**
```suggestion
**Respuesta**:
```

2022-12-02 16:37 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +**Errores posibles**
```suggestion
**Errores posibles**:
```

2022-12-02 16:37 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Importante
```suggestion
> Atención
```

2022-12-02 16:38 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Importante
```suggestion
> Atención
```

2022-12-02 16:39 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +> Importante
```suggestion
> Atención
```

2022-12-02 16:41 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +#### Prácticas recomendadas
Aqui e nivel 4 mesmo?

2022-12-02 16:43 UTC, hgaldino requested changes

2022-12-02 16:43 UTC, hgaldino commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +#### Prácticas recomendadas
Aqui e nivel 4 mesmo?

2022-12-05 11:49 UTC, BrunoCamarda commented on guides/checkout-api-v2/advanced-openFinance.es.md
> +#### Prácticas recomendadas
Sim. Conferi aqui e é isso mesmo

2022-12-07 16:30 UTC, merged