feature/salesforce-checkoutpro
mercadopago/devsite-docs pull request #1904
Opened 2022-11-22 22:44 UTC by abderossi

## Description

Se actualiza la documentación de Salesforce para incluir la siguiente información:
- Integración del Checkout Pro como medio de pago
- Nuevas intrucciones de testeo de los medios de pago

2022-12-22 14:52 UTC, pcanosa commented on guides/salesforce/integration-test.en.md
> +Next, find out how to test the different types of payment.
```suggestion
Find out how to test the different types of payment below.
```

2022-12-22 14:54 UTC, pcanosa commented on guides/salesforce/integration-test.en.md
> +1. Complete the transaction on the Mecado Pago page using one of the available payment methods. If you choose to pay by credit card, remember to use [test cards](/developers/en/docs/salesforce-commer
```suggestion
1. Complete the transaction on the Mecado Pago page using one of the available payment methods. If you choose to pay by credit card, remember to use [test cards](/developers/en/docs/salesforce-commerce-cloud/additional-content/test-cards) to make the payment. **Never use your personal cards**.
```

2022-12-22 14:54 UTC, pcanosa commented on guides/salesforce/integration-test.en.md
> +1. Click the buy button.
```suggestion
1. Click the "buy" button.
```

2022-12-22 14:55 UTC, pcanosa commented on guides/salesforce/integration-test.en.md
> +1. Click the buy button.
```suggestion
1. Click the "buy" button.
```

2022-12-22 14:57 UTC, pcanosa commented on guides/salesforce/integration-test.es.md
> +1. Haz clic en el botón de comprar.
```suggestion
1. Haz clic en el botón "comprar".
```

2022-12-22 14:58 UTC, pcanosa commented on guides/salesforce/integration-test.es.md
> +1. Haz clic en el botón de comprar.
```suggestion
1. Haz clic en el botón "comprar".
```

2022-12-22 15:14 UTC, pcanosa commented on guides/salesforce/pix.es.md
> +> Para ofrecer pagos con Pix es necesario asegurarse de que las claves Pix han sido creadas. Si aún no las creaste, [haz clic aquí](https://www.youtube.com/watch?v=60tApKYVnkA) y consulta el paso a p
```suggestion
> Para ofrecer pagos con Pix es necesario asegurarse de que las claves Pix hayan sido creadas. Si aún no las creaste, [haz clic aquí](https://www.youtube.com/watch?v=60tApKYVnkA) y consulta el paso a paso.
```

2022-12-26 18:12 UTC, hgaldino requested changes

2022-12-26 18:12 UTC, hgaldino commented on guides/salesforce/credit-debit-card.pt.md
> +2. Para ativar a forma de pagamento com cartões de crédito ou débito, posicione-se na opção **CREDIT_CARD**. Em seguida, na coluna "Ativado" e selecione a opção **Sim** para habilitá-lo.
```suggestion
2. Para ativar a forma de pagamento com cartões de crédito ou débito, posicione o cursos na opção **CREDIT_CARD** e, em seguida, na coluna "Ativado" e selecione a opção **Sim** para habilitá-lo.
```

2022-12-26 18:12 UTC, hgaldino commented on guides/salesforce/cho-pro.pt.md
> +2. Para ativar a forma de pagamento, posicione-se na opção **Mercado Pago**. Em seguida, na coluna "Ativado" e selecione a opção **Sim** para habilitá-lo.
```suggestion
2. Para ativar a forma de pagamento, posicione o cursor na opção **Mercado Pago** e, em seguida, na coluna "Ativado" e selecione a opção **Sim** para habilitá-lo.
```

2022-12-26 18:12 UTC, hgaldino commented on guides/salesforce/payment-configuration.en.md
> +By default, the Mercado Pago cartridge will first show the Pix payment method and then the credit card.
Goixti, aqui deveria localizar só para MLB por questão do Pix, né?

2022-12-26 18:12 UTC, hgaldino commented on guides/salesforce/payment-configuration.pt.md
> +
```suggestion
------------

```

2022-12-26 18:12 UTC, hgaldino commented on guides/salesforce/payment-configuration.pt.md
> +Por padrão, o cartucho do Mercado Pago mostrará primeiro a forma de pagamento Pix e depois o cartão de crédito.
Goixti, aqui deveria localizar só para MLB por questão do Pix, né?

2022-12-26 19:17 UTC, hgaldino approved these changes

2022-12-27 13:16 UTC, merged