Feature/BoletoMultaeJuros-Choapi
mercadopago/devsite-docs pull request #1919
Opened 2022-12-14 15:25 UTC by pcanosa

## Description
Agregado de multa e juros para boleto

2022-12-14 17:02 UTC, BrunoCamarda reviewed
Review `boleto-bancario.pt.md`

2022-12-26 14:11 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.en.md
> +To offer **Pagamento via boleto bancário**, follow the steps below.
```suggestion
To offer **payments via boleto bancário**, follow the steps below.
```

2022-12-26 15:07 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.en.md
> +To configure **pagamento via boleto bancárioa**, send a **POST** with the following parameters to the endpoint [/v1/payments](/developers/en/reference/payments/_payments/post) and run the request or,
```suggestion
To configure **payments via boleto bancárioa**, send a **POST** with the following parameters to the endpoint [/v1/payments](/developers/en/reference/payments/_payments/post) and run the request or, if you prefer, use one of our SDKs below.
```

2022-12-26 15:08 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.en.md
> +The default expiration date for **pagamento com boleto bancário** is 3 days. Optionally, it is possible to change this date by sending the date_of_expiration field in the payment creation request, de
```suggestion
The default expiration date for **payments with boleto bancário** is 3 days. Optionally, it is possible to change this date by sending the date_of_expiration field in the payment creation request, defining a period between 1 and 30 days from the boleto issuance date.
```

2022-12-26 15:11 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.es.md
> +Para configurar **pagos con boleto bancario**, envía un POST con los siguientes parámetros al endpoint [/v1/payments](/developers/es/reference/payments/_payments/post) y ejecuta la solicitud o, si lo
```suggestion
Para configurar **pagos vía boleto bancario**, envía un POST con los siguientes parámetros al endpoint [/v1/payments](/developers/es/reference/payments/_payments/post) y ejecuta la solicitud o, si lo prefieres, utiliza uno de nuestros SDKs indicados a continuación.
```

2022-12-26 15:11 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.es.md
> +Con el Checkout API de Mercado Pago, es posible ofrecer, además de tarjeta y Pix, **pagos vía boleto bancario**. También puedes crear **boletos bancarios con descuentos, multas e intereses** para los
```suggestion
Con el Checkout Transparente de Mercado Pago, es posible ofrecer, además de tarjeta y Pix, **pagos vía boleto bancario**. También puedes crear **boletos bancarios con descuentos, multas e intereses** para los pagos que se realicen o bien por adelantado, o bien por fuera del plazo estipulado en la fecha de vencimiento.
```

2022-12-26 15:20 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.es.md
> +Para realizar la integración de Checkout API, es necesario capturar los datos necesarios para procesar el pago.
```suggestion
Para realizar la integración de Checkout Transparente, es necesario capturar los datos necesarios para procesar el pago.
```

2022-12-26 15:23 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.es.md
> +Si quieres ofrecer **boletos bancarios con descuentos, multas e intereses**, ya sea para los pagos que se realicen por adelantado, como para los pagos que se realicen por fuera de la fecha de vencimi
"Mercado Pago API" sería la API de Mercado Pago?  Si es así, normalmente la mencionamos de esa manera :)

2022-12-26 15:24 UTC, abderossi commented on guides/checkout-api-v2/boleto-bancario.pt.md
> +Para configurar **pagamentos com boleto bancário**, envie um POST com os seguintes parâmetros ao endpoint [/v1/payments](/developers/pt/reference/payments/_payments/post) e execute a requisição ou, s
```suggestion
Para configurar **pagamentos com boleto bancário**, envie um **POST** com os seguintes parâmetros ao endpoint [/v1/payments](/developers/pt/reference/payments/_payments/post) e execute a requisição ou, se preferir, utilize um de nossos SDKs abaixo.
```

2022-12-26 15:25 UTC, abderossi commented on guides/checkout-api-v2/other-payment-methods.en.md
> +With Mercado Pago's Checkout API, it is possible to offer, in addition to card, Pix and payments via boleto bancário, **pagamentos em lotérica**.
```suggestion
With Mercado Pago's Transparent Checkout, it is possible to offer, in addition to card, Pix and payments via boleto bancário, **pagamentos em lotérica**.
```

2022-12-26 15:26 UTC, abderossi commented on guides/checkout-api-v2/other-payment-methods.es.md
> +Con el Checkout API de Mercado Pago, es posible ofrecer, además de tarjeta, Pix y Boleto, **pagos en agencias de lotería**.
```suggestion
Con el Checkout Transparente de Mercado Pago, es posible ofrecer, además de tarjeta, Pix y Boleto, **pagos en agencias de lotería**.
```

2022-12-26 15:27 UTC, abderossi requested changes
Dejo ajustes!

2022-12-26 15:38 UTC, pcanosa commented on guides/checkout-api-v2/boleto-bancario.es.md
> +Si quieres ofrecer **boletos bancarios con descuentos, multas e intereses**, ya sea para los pagos que se realicen por adelantado, como para los pagos que se realicen por fuera de la fecha de vencimi
```suggestion
Si quieres ofrecer **boletos bancarios con descuentos, multas e intereses**, ya sea para los pagos que se realicen por adelantado, como para los pagos que se realicen por fuera de la fecha de vencimiento, puedes crearlos directamente vía la API de Mercado Pago, o bien utilizando los siguientes SDKs:
```

2022-12-26 15:48 UTC, abderossi approved these changes

2024-08-14 13:25 UTC, closed without merging