Feature/pse-choapi
mercadopago/devsite-docs pull request #1973
Opened 2023-03-06 20:00 UTC by pcanosa

Agregado de PSE como medio de pago para Cho API Colombia.

Fixes #<issue>

2023-03-08 20:15 UTC, abderossi commented on guides/checkout-api-v2/integrate-pse.es.md
> +Con el Checkout API de Mercado Pago se puede ofrecer pagos con **PSE -Pagos Seguros en Línea-**, el servicio que permite realizar compras y pagos a través de internet debitando los recursos en línea
```suggestion
Con el Checkout API de Mercado Pago puedes ofrecer pagos con **PSE -Pagos Seguros en Línea-**, el servicio que permite realizar compras y pagos a través de internet debitando los recursos en línea directamente de cuentas de ahorros, corriente o depósito electrónico.
```

2023-03-08 20:53 UTC, hgaldino requested changes

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/other-payment-methods.pt.md
> +> Para esta etapa, ao realizar a requisição via API ou SDKs, é necessário enviar sua Chave Privada - Access token.
```suggestion
> Para esta etapa, ao realizar a requisição via API ou SDKs, é necessário enviar a sua Chave Privada (`access_token`). 
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +
```suggestion
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +
```suggestion
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +
```suggestion
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +> WARNING
```suggestion
> NOTE
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +Incluindo o elemento do tipo `select` com o id: `id = docType` que está no formulário, será possível preencher automaticamente as opções disponíveis quando chamar a função a seguir:
```suggestion
Incluindo o elemento do tipo `select` com o ID `id = docType` que está no formulário, será possível preencher automaticamente as opções disponíveis quando chamar a função a seguir:
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +Com a biblioteca MercadoPago.js incluída, adicione o formulário de pagamento abaixo ao seu projeto para garantir a captura segura dos dados dos compradores. Nesta etapa é importante utilizar a lista
```suggestion
Com a biblioteca `MercadoPago.js` incluída, adicione o formulário de pagamento abaixo ao seu projeto para garantir a captura segura dos dados dos compradores. Nesta etapa, é importante utilizar a lista que você consultou para obter os meios de pagamento disponíveis para criar as opções de pagamento que deseja oferecer.
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +
```suggestion
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +As credenciais são senhas únicas com as quais identificamos uma integração na sua conta. Servem para capturar pagamentos em lojas virtuais e outras aplicações de forma segura.
```suggestion
As [credenciais](/developers/pt/guides/additional-content/credentials/credentials) são senhas únicas com as quais identificamos uma integração na sua conta, servindo para capturar pagamentos em lojas virtuais e outras aplicações de forma segura.
```

2023-03-08 20:53 UTC, hgaldino commented on guides/checkout-api-v2/integrate-pse.pt.md
> +Esta é a primeira etapa de uma estrutura completa de código que deverá ser seguida para a correta integração dos pagamentos. Atente-se aos blocos abaixo para adicionar aos códigos conforme indicado.
```suggestion
Essa é a primeira etapa de uma estrutura completa de código que deverá ser seguida para a correta integração dos pagamentos. Atente-se aos blocos abaixo para adicionar aos códigos conforme indicado.
```

2023-03-09 14:53 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.en.md
> +This capture is made by including the MercadoPago.js library in your project, followed by the payment form. Use the code below to import the library before adding the payment form.
```suggestion
This capture is made by including the `MercadoPago.js` library in your project, followed by the payment form. Use the code below to import the library before adding the payment form.
```

2023-03-09 14:53 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.en.md
> +With the MercadoPago.js library included, add the payment form below to your project to ensure the secure capture of buyer data. In this step, it is important to use the list you consulted to obtain
```suggestion
With the `MercadoPago.js` library included, add the payment form below to your project to ensure the secure capture of buyer data. In this step, it is important to use the list you consulted to obtain the available payment methods to create the payment options you want to offer.
```

2023-03-09 14:55 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.en.md
> +> For this step, when making the request via API or SDKs, it is necessary to send your Private Key - Access token.
```suggestion
> For this step, when making the request via API or SDKs, it is necessary to send your Private Key (`access_token`).
```

2023-03-09 14:55 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.en.md
> +> WARNING
```suggestion
> NOTE
```

2023-03-09 14:56 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.es.md
> +Esta captura se realiza incluyendo la biblioteca MercadoPago.js en tu proyecto, seguida del formulario de pago. Utiliza el siguiente código para importar la biblioteca MercadoPago.js antes de añadir
```suggestion
Esta captura se realiza incluyendo la biblioteca `MercadoPago.js` en tu proyecto, seguida del formulario de pago. Utiliza el siguiente código para importar la biblioteca MercadoPago.js antes de añadir el formulario de pago.
```

2023-03-09 14:57 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.es.md
> +Esta captura se realiza incluyendo la biblioteca MercadoPago.js en tu proyecto, seguida del formulario de pago. Utiliza el siguiente código para importar la biblioteca MercadoPago.js antes de añadir
```suggestion
Esta captura se realiza incluyendo la biblioteca `MercadoPago.js` en tu proyecto, seguida del formulario de pago. Utiliza el siguiente código para importar la biblioteca MercadoPago.js antes de añadir el formulario de pago.
```

2023-03-09 14:57 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.es.md
> +Con la biblioteca MercadoPago.js incluida, añade el siguiente formulario de pago a tu proyecto para garantizar la captura segura de los datos de los compradores. En esta etapa es importante utilizar
```suggestion
Con la biblioteca `MercadoPago.js` incluida, añade el siguiente formulario de pago a tu proyecto para garantizar la captura segura de los datos de los compradores. En esta etapa es importante utilizar la lista que consultaste para obtener los medios de pago disponibles para crear las opciones de pago que deseas ofrecer.
```

2023-03-09 14:59 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.es.md
> +> WARNING
```suggestion
> NOTE
```

2023-03-09 14:59 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.pt.md
> +Esta captura é feita a partir da inclusão da biblioteca MercadoPago.js em seu projeto, seguida do formulário de pagamento. Utilize o código abaixo para importar a biblioteca MercadoPago.js antes de a
```suggestion
Esta captura é feita a partir da inclusão da biblioteca `MercadoPago.js` em seu projeto, seguida do formulário de pagamento. Utilize o código abaixo para importar a biblioteca MercadoPago.js antes de adicionar o formulário de pagamento.
```

2023-03-09 15:34 UTC, abderossi commented on guides/checkout-api-v2/integrate-pse.es.md
> +| transaction_details.financial_institution | Banco informado en el POST para hacer la transferencia electrónica. Se debe mostrar al usuario el listado de bancos y permitirle seleccionar. El listado
"Consumir la información" qué vendría a ser? utilizar? descargar?

2023-03-09 15:39 UTC, abderossi commented on guides/checkout-api-v2/integrate-pse.es.md
> +El pago creado con **PSE** expira automáticamente dentro de los 15 minutos de generado y su status pasa a ser rechazado. Si el usuario no accede a la web y realiza el pago dentro de ese tiempo, se de
Duda: es necesario poner que "si el comprador no accede a la web"? Es necesario ese detalle o podríamos simplemente dejarlo en "si el comprador no realiza el pago"?

2023-03-09 15:52 UTC, abderossi commented on guides/checkout-api-v2/integrate-pse.es.md
> +Para obtener una lista detallada de todos los medios de pago disponibles para integración, envía un **GET** con tu _Access token_ al endpoint [/v1/payment_methods](/developers/es/reference/payment_me
```suggestion
Para obtener una lista detallada de todos los medios de pago disponibles para integración, envía un **GET** con tu `access_token` al endpoint [/v1/payment_methods](/developers/es/reference/payment_methods/_payment_methods/get) y ejecuta la solicitud o, si lo prefieres, haz la solicitud utilizando uno de nuestros SDKs.
```

2023-03-09 15:53 UTC, abderossi commented on guides/checkout-api-v2/integrate-pse.es.md
> +> Para esta etapa, al realizar la solicitud vía API o SDKs, es necesario que envíes tu clave privada - Access Token.
```suggestion
> Para esta etapa, al realizar la solicitud vía API o SDKs, es necesario que envíes tu clave privada (`access_token`).
```

2023-03-09 15:55 UTC, abderossi commented on guides/checkout-api-v2/integrate-pse.pt.md
> +A resposta mostrará o **status pendente** até que o comprador realize o pagamento. Além disso, na resposta à requisição, o parâmetro `external_resource_url` retornará uma URL que contém as instruções
```suggestion
A resposta mostrará o status `pendente` até que o comprador realize o pagamento. Além disso, na resposta à requisição, o parâmetro `external_resource_url` retornará uma URL que contém as instruções para que o comprador realize o pagamento. Você pode redirecioná-lo para este mesmo link para conclusão do fluxo de pagamento.
```

2023-03-09 15:56 UTC, abderossi commented on guides/checkout-api-v2/integrate-pse.es.md
> +La respuesta mostrará el **status pendiente** hasta que el comprador realice el pago. Además, en la respuesta a la solicitud, el parámetro `external_resource_url` devolverá una URL que contiene las i
```suggestion
La respuesta mostrará el status `pendiente` hasta que el comprador realice el pago. Además, en la respuesta a la solicitud, el parámetro `external_resource_url` devolverá una URL que contiene las instrucciones para que el comprador efectúe el pago. Puedes redirigirlo a este mismo link para finalizar el flujo de pago.
```

2023-03-09 15:58 UTC, abderossi commented on guides/checkout-api-v2/other-payment-methods.es.md
> +> Para esta etapa, al realizar la solicitud vía API o SDKs, es necesario que envíes tu clave privada - Access Token.
```suggestion
> Para esta etapa, al realizar la solicitud vía API o SDKs, es necesario que envíes tu clave privada (`access_token`).
```

2023-03-09 15:58 UTC, abderossi commented on guides/checkout-api-v2/other-payment-methods.es.md
> +Para obtener una lista detallada de todos los medios de pago disponibles para integración, envía un **GET** con tu _Access token_ al endpoint [/v1/payment_methods](/developers/es/reference/payment_me
```suggestion
Para obtener una lista detallada de todos los medios de pago disponibles para integración, envía un **GET** con tu `access_token` al endpoint [/v1/payment_methods](/developers/es/reference/payment_methods/_payment_methods/get) y ejecuta la solicitud o, si lo prefieres, haz la solicitud utilizando uno de nuestros SDKs.
```

2023-03-09 17:35 UTC, pcanosa commented on guides/checkout-api-v2/integrate-pse.es.md
> +Los siguientes campos para enviar un pago son **obligatorios** y deberás completarlos siguiendo las especificaciones de la siguiente tabla:
```suggestion
Los siguientes campos para enviar un pago son **obligatorios** y deberás completarlos siguiendo las especificaciones de la de la tabla a continuación:
```

2023-03-09 22:45 UTC, hgaldino approved these changes

2023-03-10 14:58 UTC, merged