feature/self-homologation
mercadopago/devsite-docs pull request #2026
Opened 2023-05-05 22:25 UTC by pcanosa

## Description

Mejoras en la documentación de Calidad de integración.
Incluye modificaciones en las documentaciones de Improve payments approval, Create payment intent (integration API) y Requisitos para salir a producción.

2023-05-08 13:14 UTC, abderossi commented on guides/additional-content/homologator/homologator.en.md
> +2. In the [Your applications](/developers/en/guides/additional-content/dashboard/applications) area of ​​the Dashboard, **click on the desired application**. It must be an application in which there
Esta oración es un poco rebuscada y confusa. Pero la fui a buscar en español y me pasó lo mismo. Quizás tenemos una manera más directa de contar este paso?

2023-05-08 13:19 UTC, abderossi commented on guides/additional-content/homologator/homologator.es.md
> +| Experiencia de Usuario  | Para crecer y mantener la tasa de usuarios en tu integración, debes poder ofrecer una buena experiencia de pago. Las sugerencias brindadas por Mercado Pago en  la homologa
```suggestion
| Experiencia de Usuario  | Para crecer y mantener la tasa de usuarios en tu integración, debes poder ofrecer una buena experiencia de pago. Las sugerencias brindadas por Mercado Pago en la homologación te guiarán para obtener los mejores resultados.                                                                                                                                                  |
```

2023-05-08 13:21 UTC, abderossi commented on guides/additional-content/homologator/homologator.es.md
> +4. En la pantalla **"Calidad de integración"**, haz clic en **Evaluar calidad** e ingresa el `payment ID` de un pago realizado con [credenciales](/developers/es/guides/additional-content/credentials/
Para **"Calidad de integración"** dejaría las comillas o las negritas. Usualmente no los usamos juntos.

2023-05-08 13:25 UTC, abderossi commented on guides/additional-content/how-tos/improve-approval.es.md
> +> Recomendamos  evaluar la [calidad de tu integración](/developers/es/docs/checkout-api/additional-content/integration-quality) antes de salir a producción para que puedas validar si estás cumpliendo
A veces hablar de "garantizar una buena taza de aprobación" es un poco delicado, porque estamos prometiendo algo que no siempre depende solo de MP. Quizás sería bueno cambiarlo por algo un poco más tibio? Nos pasó cuando hicimos la guía de buenas prácticas para checkout, que no pudimos afirmar que iban a mejorar sus ventas porque no correspondía.

2023-05-08 13:27 UTC, abderossi requested changes
Dejo algunas dudas/sugerencias y solo un cambio por un espacio extra.

2023-05-08 13:34 UTC, pcanosa commented on guides/additional-content/homologator/homologator.es.md
> +4. En la pantalla **"Calidad de integración"**, haz clic en **Evaluar calidad** e ingresa el `payment ID` de un pago realizado con [credenciales](/developers/es/guides/additional-content/credentials/
```suggestion
4. En la pantalla **Calidad de integración**, haz clic en **Evaluar calidad** e ingresa el `payment ID` de un pago realizado con [credenciales](/developers/es/guides/additional-content/credentials/credentials) de producción de la aplicación que estás queriendo homologar. Siempre que sea posible, mostraremos en el campo el último `payment ID` productivo que identificamos en esa aplicación.
```

2023-05-08 13:35 UTC, pcanosa commented on guides/additional-content/homologator/homologator.en.md
> +4. On the **"Integration Quality"** screen, click **Evaluate quality** and enter the `payment ID` of a payment made with production [credentials](/developers/en/guides/additional-content/credentials/
```suggestion
4. On the **Integration Quality** screen, click **Evaluate quality** and enter the `payment ID` of a payment made with production [credentials](/developers/en/guides/additional-content/credentials/credentials) of the application you wish to homologate. Whenever possible, we will show in the field the last productive `payment ID` that we identified in the application in question.
```

2023-05-08 13:37 UTC, pcanosa commented on guides/additional-content/how-tos/improve-approval.es.md
> +> Recomendamos  evaluar la [calidad de tu integración](/developers/es/docs/checkout-api/additional-content/integration-quality) antes de salir a producción para que puedas validar si estás cumpliendo
```suggestion
> Recomendamos  evaluar la [calidad de tu integración](/developers/es/docs/checkout-api/additional-content/integration-quality) antes de salir a producción para que puedas validar si estás cumpliendo con los estándares de calidad y seguridad de Mercado Pago  que pueden mejorar tu tasa de aprobación de pagos.
```

2023-05-08 13:44 UTC, pcanosa commented on guides/additional-content/how-tos/improve-approval.en.md
> +> We recommend to assess your [integration’s quality](/developers/en/docs/checkout-api/additional-content/integration-quality) before going to production to check if you are meeting the Mercado Pago
```suggestion
> We recommend assessing your [integration’s quality](/developers/en/docs/checkout-api/additional-content/integration-quality) before going to production to check if you are meeting the Mercado Pago quality and security standards that would help you obtain a good payment approval rate.
```

2023-05-08 13:45 UTC, pcanosa commented on guides/integration-api/create-payment-intent.en.md
> +> We recommend to assess your [integration’s quality](/developers/en/docs/checkout-api/additional-content/integration-quality) to check if you are meeting the Mercado Pago quality and security standa
```suggestion
> We recommend assessing your [integration’s quality](/developers/en/docs/checkout-api/additional-content/integration-quality) to check if you are meeting the Mercado Pago quality and security standards that would help you obtain a good payment approval rate.
```

2023-05-08 13:46 UTC, pcanosa commented on guides/integration-api/create-payment-intent.es.md
> +> Recomendamos  evaluar la [calidad de tu integración](/developers/es/docs/checkout-api/additional-content/integration-quality) para validar si estás cumpliendo con los estándares de calidad y seguri
```suggestion
> Recomendamos  evaluar la [calidad de tu integración](/developers/es/docs/checkout-api/additional-content/integration-quality) para validar si estás cumpliendo con los estándares de calidad y seguridad de Mercado Pago que pueden mejorar tu tasa de aprobación de pagos. 
```

2023-05-08 19:06 UTC, hgaldino requested changes

2023-05-08 19:06 UTC, hgaldino commented on guides/additional-content/homologator/homologator.pt.md
> +> Por enquanto, a ferramenta para medir a qualidade da integração só está disponível para integrações com o [Checkout Pro,](/developers/pt/docs/checkout-pro/landing) [Checkout API](/developers/pt/doc
Pili, coloquei o "." dentro dos [] porque o Devsite deixa eles separados da palavras quando colocamos em Prod KKKRYING

2023-05-08 19:06 UTC, hgaldino commented on guides/additional-content/homologator/homologator.pt.md
> +> Por enquanto, a ferramenta para medir a qualidade da integração só está disponível para integrações com o [Checkout Pro,](/developers/pt/docs/checkout-pro/landing) [Checkout Transparente](/develope
```suggestion
> Por enquanto, a ferramenta para medir a qualidade da integração só está disponível para integrações com o [Checkout Pro,](/developers/pt/docs/checkout-pro/landing) [Checkout Transparente,](/developers/pt/docs/checkout-api/landing) [Checkout Bricks](/developers/pt/docs/checkout-bricks/landing) e [Mercado Pago Point.](/developers/pt/docs/mp-point/landing)
```

2023-05-08 20:01 UTC, pcanosa commented on guides/additional-content/homologator/homologator.en.md
> +2. In the [Your applications](/developers/en/guides/additional-content/dashboard/applications) area of ​​the Dashboard, **click on the desired application**. It must be an application in which there
```suggestion
2. In the [Your applications](/developers/en/guides/additional-content/dashboard/applications) area of ​​the Dashboard, **click on the desired application**. It must be an application in which you have integrated a product admitted by the homologation tool (Checkout Pro, Checkout Bricks, Checkout API, or Mercado Pago Point).
```

2023-05-08 20:03 UTC, pcanosa commented on guides/additional-content/homologator/homologator.es.md
> +2. En el área [Tus aplicaciones](/developers/es/guides/additional-content/dashboard/applications) del Dashboard, **haz clic en la aplicación deseada**. Debe ser una aplicación en la que haya un produ
```suggestion
2. En el área [Tus aplicaciones](/developers/es/guides/additional-content/dashboard/applications) del Dashboard, **haz clic en la aplicación deseada**. Debe ser una aplicación en la que hayas integrado uno de los productos disponibles en la herramienta de medición (Checkout Pro, Checkout Bricks, ----[mla, mlm, mlu, mco, mlc, mpe]---- Checkout API ------------ ----[mlb]---- Checkout Transparente ------------, o Mercado Pago Point).
```

2023-05-10 13:52 UTC, pcanosa commented on guides/additional-content/homologator/homologator.en.md
> +4. On the **Integration Quality** screen, click **Evaluate quality** and enter the `payment ID` of a payment made with production [credentials](/developers/en/guides/additional-content/credentials/cr
```suggestion
4. On the **Integration Quality** screen, click **Evaluate quality** and enter the `payment ID` of a recent payment made with production [credentials](/developers/en/guides/additional-content/credentials/credentials) of the application you wish to homologate. Whenever possible, use the last productive `payment ID` identified in the application in question.
```

2023-05-10 13:53 UTC, pcanosa commented on guides/additional-content/homologator/homologator.es.md
> +4. En la pantalla **Calidad de integración**, haz clic en **Evaluar calidad** e ingresa el `payment ID` de un pago realizado con [credenciales](/developers/es/guides/additional-content/credentials/cr
```suggestion
4. En la pantalla **Calidad de integración**, haz clic en **Evaluar calidad** e ingresa el `payment ID` de un pago reciente realizado con [credenciales](/developers/es/guides/additional-content/credentials/credentials) de producción de la aplicación que estás queriendo homologar. Siempre que sea posible, ingresa en el campo el último `payment ID` productivo que identificas en esa aplicación.
```

2023-05-10 13:55 UTC, pcanosa commented on guides/additional-content/homologator/homologator.pt.md
> +4. Na tela **"Qualidade da integração"**, clique em **Avaliar qualidade** e insira o `payment ID` de um pagamento feito com [credenciais](/developers/pt/guides/additional-content/credentials/credenti
```suggestion
4. Na tela **"Qualidade da integração"**, clique em **Avaliar qualidade** e insira o `payment ID` de um pagamento recente feito com [credenciais](/developers/pt/guides/additional-content/credentials/credentials) de produção da aplicação você está certificando. Sempre que possível, insira no campo de preenchimento o último `payment ID` produtivo que você identifica na aplicação em questão.
```

2023-05-10 13:57 UTC, pcanosa commented on guides/additional-content/how-tos/improve-approval.pt.md
> +> Recomendamos avaliar a [qualidade de sua integração](/developers/pt/docs/checkout-api/additional-content/integration-quality) antes de entrar em produção para verificar se você está cumprindo os pa
```suggestion
> Recomendamos avaliar a [qualidade de sua integração](/developers/pt/docs/checkout-api/additional-content/integration-quality) antes de entrar em produção para verificar se você está cumprindo os padrões de qualidade e segurança do Mercado Pago que podem melhorar sua taxa de aprovação de pagamentos.
```

2023-05-10 13:57 UTC, pcanosa commented on guides/integration-api/create-payment-intent.pt.md
> +> Recomendamos avaliar a [qualidade de sua integração](/developers/pt/docs/checkout-api/additional-content/integration-quality) para verificar se você está cumprindo os padrões de qualidade e seguran
```suggestion
> Recomendamos avaliar a [qualidade de sua integração](/developers/pt/docs/checkout-api/additional-content/integration-quality) para verificar se você está cumprindo os padrões de qualidade e segurança do Mercado Pago que podem melhorar sua taxa de aprovação de pagamentos.
```

2023-05-10 14:50 UTC, hgaldino approved these changes

2023-05-10 19:54 UTC, abderossi commented on guides/additional-content/homologator/homologator.en.md
> +> For now, the integration quality measuring tool is only available for integrations with [Checkout Pro,](/developers/en/docs/checkout-pro/landing) [Checkout API](/developers/en/docs/checkout-api/lan
```suggestion
> For now, the integration quality measuring tool is only available for integrations with [Checkout Pro,](/developers/en/docs/checkout-pro/landing) [Checkout API](/developers/en/docs/checkout-api/landing), [Checkout Bricks](/developers/en/docs/checkout-bricks/landing) and [Mercado Pago Point](/developers/en/docs/mp-point/landing).
```

2023-05-10 19:55 UTC, abderossi commented on guides/additional-content/homologator/homologator.en.md
> +2. In the [Your applications](/developers/en/guides/additional-content/dashboard/applications) area of ​​the Dashboard, **click on the desired application**. It must be an application in which you ha
Acá faltaría localizar CHO Transparente para Brasil

2023-05-10 19:56 UTC, abderossi commented on guides/additional-content/homologator/homologator.en.md
> +2. In the [Your applications](/developers/en/guides/additional-content/dashboard/applications) area of ​​the Dashboard, **click on the desired application**. It must be an application in which you ha
```suggestion
2. In the [Your applications](/developers/en/guides/additional-content/dashboard/applications) area of ​​the Dashboard, **click on the desired application**. It must be an application in which you have integrated a product admitted by the homologation tool (Checkout Pro, Checkout Bricks, ----[mla, mlm, mlu, mco, mlc, mpe]---- Checkout API ------------ ----[mlb]---- Checkout Transparente ------------, or Mercado Pago Point).
```

2023-05-10 19:58 UTC, abderossi commented on guides/additional-content/homologator/homologator.pt.md
> +> Por enquanto, a ferramenta para medir a qualidade da integração só está disponível para integrações com o [Checkout Pro,](/developers/pt/docs/checkout-pro/landing) [Checkout API,](/developers/pt/do
```suggestion
> Por enquanto, a ferramenta para medir a qualidade da integração só está disponível para integrações com o [Checkout Pro](/developers/pt/docs/checkout-pro/landing) [Checkout API,](/developers/pt/docs/checkout-api/landing), [Checkout Bricks](/developers/pt/docs/checkout-bricks/landing) e [Mercado Pago Point.](/developers/pt/docs/mp-point/landing)
```

2023-05-10 19:58 UTC, abderossi commented on guides/additional-content/homologator/homologator.pt.md
> +> Por enquanto, a ferramenta para medir a qualidade da integração só está disponível para integrações com o [Checkout Pro,](/developers/pt/docs/checkout-pro/landing) [Checkout Transparente,](/develop
```suggestion
> Por enquanto, a ferramenta para medir a qualidade da integração só está disponível para integrações com o [Checkout Pro,](/developers/pt/docs/checkout-pro/landing) [Checkout Transparente](/developers/pt/docs/checkout-api/landing), [Checkout Bricks](/developers/pt/docs/checkout-bricks/landing) e [Mercado Pago Point.](/developers/pt/docs/mp-point/landing)
```

2023-05-10 19:59 UTC, abderossi commented on guides/integration-api/create-payment-intent.es.md
> +> Recomendamos  evaluar la [calidad de tu integración](/developers/es/docs/checkout-api/additional-content/integration-quality) para validar si estás cumpliendo con los estándares de calidad y seguri
```suggestion
> Recomendamos evaluar la [calidad de tu integración](/developers/es/docs/checkout-api/additional-content/integration-quality) para validar si estás cumpliendo con los estándares de calidad y seguridad de Mercado Pago que pueden mejorar tu tasa de aprobación de pagos. 
```

2023-05-10 19:59 UTC, abderossi commented on guides/snippets/test-integration/go-live-requirements.en.md
> +You must also test your [integration’s quality](/developers/es/docs/checkout-api/additional-content/integration-quality) to verify if you are meeting the Mercado Pago quality and security standards.
```suggestion
You must also test your [integration’s quality](/developers/en/docs/checkout-api/additional-content/integration-quality) to verify if you are meeting the Mercado Pago quality and security standards.
```

2023-05-10 19:59 UTC, abderossi commented on guides/snippets/test-integration/go-live-requirements.en.md
> +You must also test your [integration’s quality](/developers/es/docs/checkout-api/additional-content/integration-quality) to verify if you are meeting the Mercado Pago quality and security standards.
```suggestion
You must also test your [integration’s quality](/developers/en/docs/checkout-api/additional-content/integration-quality) to verify if you are meeting the Mercado Pago quality and security standards.
```

2023-05-10 20:00 UTC, abderossi approved these changes

2023-05-10 20:59 UTC, merged