Feature/mpdelivery catalogapi
mercadopago/devsite-docs pull request #2049
Opened 2023-05-29 14:08 UTC by abderossi

## Description

Se agregan endpoints para gestionar el catálogo en Mercado Pago Delivery.

### Issue involved

Fixes #<issue>

2023-06-01 15:58 UTC, hgaldino requested changes

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +                      por: Atual status do processo de publicação do catálogo.
```suggestion
                      por: Status atual do processo de publicação do catálogo.
```

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +        por: Endpoint para verificar o status atual de uma publicação de catálogo, usando o id gerado retornado na resposta da publicação.
```suggestion
        por: Endpoint para verificar o status atual de uma publicação de catálogo, utilizando o id gerado retornado na resposta da publicação.
```

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +                                            por: Atual estado do item de comeplemento, pode estar ativo ("actived") ou pausado ("paused").
```suggestion
                                            por: Estado atual do item de complemento, podendo estar ativo ("actived") ou pausado ("paused").
```

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +                                            por: O preço do item complementar, que pode ser zero se for gratuito ou incluído no preço do item principal.
```suggestion
                                            por: O preço do item complementar, que pode ser zero, se for gratuito, ou incluído no preço do item principal.
```

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +                                            por: String obrigatória. O identificador público do item complementar (SKU) deve ser único para cada loja. Usado para futuras atualizações de itens.
```suggestion
                                            por: String obrigatória. O identificador público do item complementar (SKU) deve ser único para cada loja. Utilizado para futuras atualizações de itens.
```

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +                                por: Atual estado do item, pode estar ativo ("active") ou pausado ("paused").
```suggestion
                                por: Estado atual do item, podendo estar ativo ("active") ou pausado ("paused").
```

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +                                por: O identificador público do item (SKU), deve ser único para cada loja. Usado para futuras atualizações de itens.
```suggestion
                                por: O identificador público do item (SKU) deve ser único para cada loja. Utilizado para futuras atualizações de itens.
```

2023-06-01 15:58 UTC, hgaldino commented on reference/api/mp_delivery.yaml
> +                          por: Array de ids de pagamento. Cada item do pedido possui seu próprio payment_id por esse motivo poderão aparecer vários payments. Além disso, o custo de envio também tem s
```suggestion
                          por: Array de ids de pagamento. Cada item do pedido possui seu próprio payment_id e, por esse motivo, poderão aparecer vários payments. Além disso, o custo de envio também tem seu próprio payment_id.
```

2023-06-01 17:16 UTC, rwaetemann commented on reference/api/mp_delivery.yaml
> +        por: Esse endpoint importa um catálogo de forma assíncrona para uma ou mais lojas. Cada loja gera um identificador de importação que pode ser usado para verificar o status do processo posteri
```suggestion
        por: Esse endpoint importa um catálogo de forma assíncrona para uma ou mais lojas. Cada loja gera um identificador de importação que pode ser usado para verificar o status do processo posteriormente. Retornará uma resposta '202 - Success' quando todas as requisições forem enviadas corretamente ou '206 - Partial error' caso alguma requisição falhe.
```

2023-06-01 17:17 UTC, rwaetemann commented on reference/api/mp_delivery.yaml
> +                    por: Array de objetos que contem informações das seções que deverão ser importados para o catálogo.
```suggestion
                    por: Array de objetos que contém informações das seções que deverão ser importados para o catálogo.
```

2023-06-01 17:18 UTC, rwaetemann commented on reference/api/mp_delivery.yaml
> +                          por: String opcional, que descreve a seção do catálogo.
```suggestion
                          por: String opcional que descreve a seção do catálogo.
```

2023-06-01 17:52 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                          eng: Array with payment ids. Each order item has its own payment_id for this reason, multiple payments may appear. In addition, the shipping cost also has its own payment_id
```suggestion
                          eng: Array with payment ids. Each order item has its own payment_id and, for this reason, multiple payments may appear. In addition, the shipping cost also has its own payment_id.
```

2023-06-01 17:52 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                          spa: Array de ids de pagos. Cada item del pedido tiene su propio payment_id, por lo que pueden aparecer varios pagos. Además, el costo de envío también tiene su propio payme
```suggestion
                          spa: Array de ids de pagos. Cada ítem del pedido tiene su propio payment_id, por lo que pueden aparecer varios pagos. Además, el costo de envío también tiene su propio payment_id.
```

2023-06-01 17:53 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +      description: This endpoint sends a catalog to be imported asynchronously to one or more stores. Each store generates an import identifier that can be used to check the process status afterwards
```suggestion
      description: This endpoint sends a catalog to be imported asynchronously to one or more stores. Each store generates an import identifier that can be used to check the process status afterwards. It will return a '202 - Success' response when all requests were sent successfully, or '206 - Partial Error' if any post fails
```

2023-06-01 17:58 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                              description: The item public identifier (SKU), must be unique for each store. Used for future item updates.
```suggestion
                              description: The item public identifier (SKU) must be unique for each store. It is used for future item updates.
```

2023-06-01 17:58 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                                eng: The item public identifier (SKU), must be unique for each store. Used for future item updates.
```suggestion
                                eng: The item public identifier (SKU) must be unique for each store. It is used for future item updates.
```

2023-06-01 18:02 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                                            eng: Required string.The complement item public identifier (SKU), must be unique for each store. Used for future item updates.
```suggestion
                                            eng: Required string.The complement item public identifier (SKU) must be unique for each store. It is used for future item updates.
```

2023-06-01 18:03 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                                            spa: Nombre del item de complemento.
```suggestion
                                            spa: Nombre del ítem de complemento.
```

2023-06-01 18:04 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                      eng: Array of publication results per store.List of publications that were sent to the processing queue.
```suggestion
                      eng: Array of publication results per store. List of publications that were sent to the processing queue.
```

2023-06-01 18:05 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +                      eng: Array of publication results per store.List of publications that were sent to the processing queue.
```suggestion
                      eng: Array of publication results per store. List of publications that were sent to the processing queue.
```

2023-06-01 18:07 UTC, pcanosa commented on reference/api/mp_delivery.yaml
> +        spa: Endpoint para verificar el estado actual de una publicación de catálogo, utilizando la ID generada devuelta en la respuesta de publicación.
```suggestion
        spa: Endpoint para verificar el estado actual de una publicación de catálogo, utilizando la ID devuelta en la respuesta de publicación.
```

2023-06-01 18:12 UTC, abderossi commented on reference/api/mp_delivery.yaml
> +        eng: This endpoint sends a catalog to be imported asynchronously to one or more stores. Each store generates an import identifier that can be used to check the process status afterwards. Will
```suggestion
        eng: This endpoint sends a catalog to be imported asynchronously to one or more stores. Each store generates an import identifier that can be used to check the process status afterwards. It will return a '202 - Success' response when all requests were sent successfully, or '206 - Partial Error' if any post fails
```

2023-06-01 18:18 UTC, abderossi commented on reference/api/mp_delivery.yaml
> +                              description: Optional field. Array containing group of complements present in the main item.
```suggestion
                              description: Optional field. Array containing a group of complements present in the main item.
```

2023-06-01 18:19 UTC, abderossi commented on reference/api/mp_delivery.yaml
> +                                          description: Required string. The complement item public identifier (SKU), must be unique for each store. Used for future item updates.
```suggestion
                                          description: Required string. The complement item public identifier (SKU), must be unique for each store. It is used for future item updates.
```

2023-06-01 18:31 UTC, rwaetemann approved these changes

2023-06-01 19:40 UTC, hgaldino approved these changes

2023-06-02 16:12 UTC, hgaldino approved these changes

2023-06-02 16:14 UTC, merged