feature/cho-pro-mobile-integration
mercadopago/devsite-docs pull request #2140
Opened 2023-08-28 23:43 UTC by abderossi

## Description

Se dividen los pasos de integración de Checkout Pro, diferenciándolos como Web o Mobile.
Para eso, se agregan los siguientes archivos:

- Configurar las preferencias (información ya existente actualmente en producción)
- Cómo integrar para web (información ya existente actualmente en producción)
- Cómo integrar para mobile
   - Android
      - React Native CLI
      - React Native Expo Go
      - Java/Kotlin
   - iOS
      - React Native CLI
      - React Native Expo Go
      - Swift

2023-08-29 12:35 UTC, pcanosa commented on guides/checkout-pro/integrate-chopro-web.en.md
> +Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkou
Me genera duda por qué "download" está en itálica. Por lo que vi, en ES no lo pusiste. Sólo llamo la atención ahí por las dudas :)

2023-08-29 12:46 UTC, pcanosa commented on guides/checkout-pro/integrate-chopro-web.es.md
> +Para incluir el SDK de Mercado Pago.js, agrega el siguiente código al HTML del proyecto o instale la biblioteca para ReactJs.
```suggestion
Para incluir el SDK de Mercado Pago.js, agrega el siguiente código al HTML del proyecto o instala la biblioteca para ReactJs.
```

2023-08-29 12:50 UTC, pcanosa commented on guides/checkout-pro/integrate-chopro-web.en.md
> +> It is extremely important to pay attention, when creating the preference, to the configuration of the `back_urls` because they will be responsible for guiding the return flow to your website when t
```suggestion
> It is extremely important to pay attention, when creating the preference, to the configuration of the `back_urls`. They will be responsible for guiding the return flow to your website when the checkout is completed. It is possible to define three different return URLs, for payment pending, success or error scenarios. For more information, see the [Return URLs](/developers/en/docs/checkout-pro/checkout-customization/user-interface/redirection) section.
```

2023-08-29 12:50 UTC, pcanosa commented on guides/checkout-pro/integrate-chopro-web.es.md
> +> Es sumamente importante prestar atención, al crear la preferencia, a la configuración de las `back_urls` ya que estas serán las encargadas de guiar el flujo de regreso a tu sitio web cuando se comp
```suggestion
> Es sumamente importante prestar atención, al crear la preferencia, a la configuración de las `back_urls`. Estas serán las encargadas de guiar el flujo de regreso a tu sitio web cuando se complete el pago. Es posible definir tres URL de retorno diferentes que corresponden a escenarios de pago pendiente, éxito o error. Para obtener más información, consulta la sección [URL de retorno](/developers/es/docs/checkout-pro/checkout-customization/user-interface/redirection).
```

2023-08-29 13:05 UTC, pcanosa commented on guides/checkout-pro/integration-android-java-kotlin.es.md
> +Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación ya sea haciendo click en un link de “Volver” o de forma automática al terminar todo un flujo de pago exitoso, para
```suggestion
Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación, ya sea haciendo click en un link de “Volver”, o de forma automática al terminar todo un flujo de pago exitoso, para luego ser redirigido a tu App.
```

2023-08-29 13:05 UTC, pcanosa commented on guides/checkout-pro/integration-android-java-kotlin.es.md
> +Para esto debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return` según corresponda.
```suggestion
Para esto, debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return`, según corresponda.
```

2023-08-29 14:14 UTC, pcanosa commented on guides/checkout-pro/integration-android-reactnative-cli.en.md
> +* Keeps users within the context of the application increasing retention and consistency of the experience.
```suggestion
* Keeps users within the context of the application, increasing retention and consistency of the experience.
```

2023-08-29 14:23 UTC, pcanosa commented on guides/checkout-pro/integration-android-reactnative-expo-go.en.md
> +> Implementación de Expo-Web-Browser
Estas dos líneas están en ES

2023-08-29 14:26 UTC, pcanosa commented on guides/checkout-pro/integration-android-reactnative-expo-go.es.md
> +Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación ya sea haciendo click en un link de “Volver” o de forma automática al terminar todo un flujo de pago exitoso, para
```suggestion
Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación, ya sea haciendo click en un link de “Volver”, o de forma automática al terminar todo un flujo de pago exitoso, para luego ser redirigido a tu App.
```

2023-08-29 14:26 UTC, pcanosa commented on guides/checkout-pro/integration-android-reactnative-expo-go.es.md
> +Para esto debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return` según corresponda.
```suggestion
Para esto, debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return`, según corresponda.
```

2023-08-29 14:28 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-cli.en.md
> +* Keeps users within the context of the application increasing retention and consistency of the experience.
```suggestion
* Keeps users within the context of the application, increasing retention and consistency of the experience.
```

2023-08-29 14:32 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-cli.es.md
> +Con React Native CLI, te sugerimos usar [React-Native-InAppBrowser](https://www.npmjs.com/package/react-native-inappbrowser-reborn), una dependencia  altamente flexible que brinda una solución integr
```suggestion
Con React Native CLI, te sugerimos usar [React-Native-InAppBrowser](https://www.npmjs.com/package/react-native-inappbrowser-reborn), una dependencia  altamente flexible que brinda una solución completa para integrar un navegador web dentro de tu aplicación de React Native. Al considerar el uso de React-Native-InAppBrowser-Reborn se tuvieron en cuenta los siguientes aspectos:
```

2023-08-29 14:32 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-cli.es.md
> +* Mantiene a los usuarios dentro del contexto de la aplicación aumentando la retención y la coherencia de la experiencia.
```suggestion
* Mantiene a los usuarios dentro del contexto de la aplicación, aumentando la retención y la coherencia de la experiencia.
```

2023-08-29 14:33 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-cli.es.md
> +Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación ya sea haciendo click en un link de “Volver” o de forma automática al terminar todo un flujo de pago exitoso, para
```suggestion
Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación, ya sea haciendo click en un link de “Volver”, o de forma automática al terminar todo un flujo de pago exitoso, para luego ser redirigido a tu App.
```

2023-08-29 14:36 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-expo-go.en.md
> +When you run `npx expo prebuild` your `ios/appname/Info.plist` file should contain something similar to the following code.
```suggestion
When you run `npx expo prebuild`, your `ios/appname/Info.plist` file should contain something similar to the following code.
```

2023-08-29 14:37 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-expo-go.en.md
> +In the case of iOS **it is necessary to close the Safari View Controller manually**. To do this, you'll need to listen for the url change event from the component that opens the window or application
Lo mismo que en los dos archivos previos en EN y ES, el párrafo se repite

2023-08-29 14:38 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-expo-go.es.md
> +Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación ya sea haciendo click en un link de “Volver” o de forma automática al terminar todo un flujo de pago exitoso, para
```suggestion
Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación, ya sea haciendo click en un link de “Volver”, o de forma automática al terminar todo un flujo de pago exitoso, para luego ser redirigido a tu App.
```

2023-08-29 14:38 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-expo-go.es.md
> +Para esto debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return` según corresponda.
```suggestion
Para esto, debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return`, según corresponda.
```

2023-08-29 14:38 UTC, pcanosa commented on guides/checkout-pro/integration-ios-reactnative-expo-go.es.md
> +Para ello, verifica que ru archivo **app.json** contenga el nombre del scheme:
```suggestion
Para ello, verifica que tu archivo **app.json** contenga el nombre del scheme:
```

2023-08-29 14:44 UTC, pcanosa commented on guides/checkout-pro/integration-ios-swift.es.md
> +Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación ya sea haciendo click en un link de “Volver” o de forma automática al terminar todo un flujo de pago exitoso, para
```suggestion
Desde nuestro checkout es posible configurar Deep Links para volver a tu aplicación, ya sea haciendo click en un link de “Volver”, o de forma automática al terminar todo un flujo de pago exitoso, para luego ser redirigido a tu App.
```

2023-08-29 14:44 UTC, pcanosa commented on guides/checkout-pro/integration-ios-swift.es.md
> +Para esto debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return` según corresponda.
```suggestion
Para esto, debemos agregar en la creación de la preferencia de pago las propiedades `back_urls` y `auto_return`, según corresponda.
```

2023-08-29 14:46 UTC, pcanosa requested changes
Dejo algunos cambios

2023-08-29 14:59 UTC, rwaetemann commented on guides/checkout-pro/integrate-chopro-mobile.pt.md
> +Si quieres integrar Checkout Pro a una aplicación mobile, a continuación te brindamos distintas de tecnologías para que elijas la que mejor se ajuste a tu proyecto y sus necesidades.
```suggestion
Para integrar o Checkout Pro em uma aplicação móvel, disponibilizamos várias tecnologias, permitindo que selecione a mais adequada para o seu projeto e suas especificidades.
```

2023-08-29 15:01 UTC, rwaetemann commented on guides/checkout-pro/integrate-chopro-web.pt.md
> +> Adicionar o checkout
```suggestion
> Adicionar checkout
```

2023-08-29 15:05 UTC, rwaetemann commented on guides/checkout-pro/integrate-chopro-web.pt.md
> +Em seguida, você deverá instalar o SDK de frontend do Mercado Pago no seu projeto para adicionar o botão de pagamento.
```suggestion
Em seguida, instale o SDK de frontend do Mercado Pago no seu projeto para adicionar o botão de pagamento.
```

2023-08-29 15:06 UTC, rwaetemann commented on guides/checkout-pro/integrate-chopro-web.pt.md
> +A instalação é feita, essencialmente, em **dois passos**:
```suggestion
A instalação é feita em **duas etapas**:
```

2023-08-30 22:01 UTC, abderossi commented on guides/checkout-pro/integrate-chopro-web.en.md
> +Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkou
```suggestion
Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkout Pro.
```
```suggestion
Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkout Pro.
```
```suggestion
Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkout Pro.
```
```suggestion
Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkout Pro.
```
```suggestion
Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkout Pro.
```
```suggestion
Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkout Pro.
```
```suggestion
Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to download a basic project for quick implementation from Checkout Pro.
```

2023-08-30 22:01 UTC, abderossi commented on guides/checkout-pro/integrate-chopro-web.en.md
> +Check out the [full integration example](http://github.com/mercadopago/checkout-payment-sample) on GitHub for **PHP** or **NodeJS** to _download_ a basic project for quick implementation from Checkou
Es una excelente duda para la cual no tengo respuesta :-P ya lo ajusto!

2023-08-31 13:32 UTC, abderossi commented on guides/checkout-pro/integrate-preferences.en.md
> +The integration with Checkout Pro allows you to charge via our web form from any device in a simple, fast and secure way.
```suggestion
The integration with Checkout Pro allows you to receive payments via our web form from any device in a simple, fast and secure way.
```

2023-08-31 13:36 UTC, abderossi commented on guides/checkout-pro/integration-android-reactnative-expo-go.en.md
> +> Implementación de Expo-Web-Browser
```suggestion
> Implementation of Expo-Web-Browser
```

2023-08-31 13:36 UTC, abderossi commented on guides/checkout-pro/integration-android-reactnative-expo-go.en.md
> +Para implementar la dependencia Expo-Web-Browser, sigue el ejemplo que mostramos a continuación.
```suggestion
To implement the Expo-Web-Browser dependency, follow the example below.
```

2023-08-31 14:01 UTC, abderossi commented on guides/checkout-pro/integration-ios-reactnative-expo-go.es.md
> +Siga o exemplo abaixo para fechar o Safari View Controller manualmente usando **Expo-Web-Browser**.
```suggestion
Sigue el ejemplo a continuación para cerrar manualmente Safari View Controller usando **Expo-Web-Browser**.
```

2023-08-31 15:32 UTC, pcanosa approved these changes

2023-08-31 17:04 UTC, rwaetemann approved these changes

2023-08-31 17:20 UTC, gabri-elly approved these changes

2023-08-31 18:21 UTC, merged