How to "Como ativar os logs de pagamento?" em Adobe Commerce
mercadopago/devsite-docs pull request #2362
Opened 2024-05-21 06:50 UTC by gabri-elly

2024-05-30 13:16 UTC, pcanosa commented on guides/adobe-commerce/activate-payment-logs.en.md
> +2. In the **settings**, click on the **Sales** menu on the side. In the submenu that opens, select **Payment Methods**.
```suggestion
2. In **Settings**, click on the **Sales** menu on the side. In the submenu that opens, select **Payment Methods**.
```

2024-05-30 13:16 UTC, pcanosa commented on guides/adobe-commerce/activate-payment-logs.en.md
> +4. In the plugin configuration screen, select the **Basic Settings** > **Developer Support**.
```suggestion
4. In the plugin configuration screen, select **Basic Settings > Developer Support**.
```

2024-05-30 13:18 UTC, pcanosa commented on guides/adobe-commerce/activate-payment-logs.es.md
> +Siga los pasos a continuación para activar los _logs_ de pago.
```suggestion
Sigue los pasos a continuación para activar los _logs_ de pago.
```

2024-05-30 13:19 UTC, pcanosa commented on guides/adobe-commerce/activate-payment-logs.es.md
> +2. En **configuración**, haz clic en el menú lateral **Sales**. En el submenú que se abrirá, selecciona **Payment Methods**.
Gabai, acá debería ser "Configuration", no?

2024-05-30 13:20 UTC, pcanosa commented on guides/adobe-commerce/activate-payment-logs.es.md
> +3. En **Otros medios de pago**, localiza el plugin de Mercado Pago y haz clic en el botón **Configure** para abrir las configuraciones.
Por lo que veo en las imágenes, acá debería ser "Other payment methods", pero no propongo directamente el cambio para que te fijes vos, que la tenés más clara con el plugin.

2024-05-30 13:22 UTC, pcanosa commented on guides/adobe-commerce/activate-payment-logs.es.md
> +Con esta configuración, el plugin de Mercado Pago registra los _logs_ en el servidor donde la tienda está alojada, permitiendo que un usuario administrador los acceda fácilmente.
```suggestion
Con esta configuración, el plugin de Mercado Pago registra los _logs_ en el servidor donde la tienda está alojada, permitiendo que un usuario administrador tenga acceso a ellos fácilmente.
```

2024-05-30 13:22 UTC, pcanosa approved these changes

2024-05-30 14:15 UTC, abderossi commented on guides/adobe-commerce/activate-payment-logs.en.md
> +![Methods](/images/adobe-commerce/logs-payment-method-es.gif)
Aviso por las dudas que el nombre del gif es "-es"

2024-05-30 14:24 UTC, abderossi commented on guides/adobe-commerce/activate-payment-logs.pt.md
> +1. Para acessar a página de configurações, clique no menu lateral **Lojas** > **Configuração**:
```suggestion
1. Para acessar a página de configurações, clique no menu lateral **Lojas > Configuração**:
```

2024-05-30 14:46 UTC, abderossi commented on guides/adobe-commerce/activate-payment-logs.pt.md
> +4. Na tela de configurações do plugin, selecione a opção **Configurações básicas** > **Suporte para desenvolvedores**.
```suggestion
4. Na tela de configurações do plugin, selecione a opção **Configurações básicas > Suporte para desenvolvedores**. 
```

2024-05-30 14:47 UTC, abderossi requested changes
Dejo ajustes menores

2024-06-03 17:17 UTC, gabri-elly commented on guides/adobe-commerce/activate-payment-logs.es.md
> +2. En **configuración**, haz clic en el menú lateral **Sales**. En el submenú que se abrirá, selecciona **Payment Methods**.
Siiii! Gracias <3

2024-06-03 18:26 UTC, hgaldino approved these changes

2024-06-03 18:29 UTC, gabri-elly commented on guides/adobe-commerce/activate-payment-logs.en.md
> +![Methods](/images/adobe-commerce/logs-payment-method-es.gif)
É o comportamento esperado

2024-06-03 18:37 UTC, abderossi approved these changes

2024-06-03 18:41 UTC, merged