Devsite proposta Q2-Wix
mercadopago/devsite-docs pull request #721
Opened 2020-05-23 23:30 UTC by douglas-cruz

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-05-26 14:14 UTC, adfonseca commented on guides/plugins/unofficial/wix.pt.md
> +> Antes de iniciar sua operação em produção, assegure se de preencher o formulário ‘Ir para produção’. Caso já tenha realizado este passo o link não será apresentado.
Aqui não seria interessante ter o link de "Ir a produção"?

2020-05-26 14:22 UTC, douglas-cruz commented
Bom dia, Adriano.

Muito boa observação, vou atribui este link.

Obrigado.

*Att,*
*Douglas da Cruz*
*Online Payments | Mercado Pago IT  *


Em ter., 26 de mai. de 2020 às 11:14, Adriano Fonseca <
notifications@github.com> escreveu:

> *@adfonseca* commented on this pull request.
> ------------------------------
>
> In guides/plugins/unofficial/wix.pt.md
> <https://github.com/mercadopago/devsite-docs/pull/721#discussion_r430445049>
> :
>
> >
>
> -Com isso o Mercado pago estará instalado e ativado.
>
> +Você conta com um par de chaves para conectar-se com a Wix, estas chaves podem ser encontradas no painel [credenciais da sua conta](https://www.mercadolibre.com/jms/mlb/lgz/login?platform_id=mp&go=https://www.mercadopago.com/mlb/account/credentials) na seção "Checkout de Mercado Pago".
>
> +
>
> +> WARNING
>
> +>
>
> +> Importante
>
> +>
>
> +> Antes de iniciar sua operação em produção, assegure se de preencher o formulário ‘Ir para produção’. Caso já tenha realizado este passo o link não será apresentado.
>
>
> Aqui não seria interessante ter o link de "Ir a produção"?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mercadopago/devsite-docs/pull/721#pullrequestreview-418341148>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM2YBBVGBVCMFULWTDBN65DRTPFEDANCNFSM4NIURPRA>
> .
>

2020-06-08 11:24 UTC, lamaralmp commented on guides/plugins/unofficial/wix.pt.md
> +1. No painel de administração de sua loja, acesse "Pagamentos" do módulo de configurações.
```suggestion
1. No painel de administração de sua loja, acesse "Pagamentos" no módulo de configurações.
```

2020-06-08 11:27 UTC, lamaralmp commented on guides/plugins/unofficial/wix.pt.md
> +3. Complete os campos "Client ID e Client Secret" que corresponde as credenciais de sua conta "Mercado Pago".
```suggestion
3. Complete os campos "Client ID e Client Secret" que corresponde as [credenciais]([FAKER][CREDENTIALS][URL]) de sua conta "Mercado Pago".
```

2020-06-08 11:30 UTC, lamaralmp commented on guides/plugins/unofficial/wix.pt.md
> +E pronto! Você está oferecendo parcelamento sem acréscimo, assumindo as tarifas de parcelamento que você configurou.
```suggestion
E pronto! Você está oferecendo parcelamento sem acréscimo, assumindo as [tarifas de parcelamento](https://www.mercadopago.com.br/ajuda/oferecer-parcelas-sem-juros-para-compradores_454) que você configurou.
```

2020-06-08 17:37 UTC, pamalv7 commented on guides/plugins/unofficial/wix.pt.md
> +Você poderá oferecer aos seus clientes a possibilidade de pagar [diretamente no ambiente do Mercado Pago](#bookmark_configure_a_forma_de_pagamento).
```suggestion
Você poderá oferecer aos seus clientes a possibilidade de pagar [diretamente no site do Mercado Pago](#bookmark_configure_a_forma_de_pagamento).
```

2020-06-08 17:38 UTC, pamalv7 commented on guides/plugins/unofficial/wix.pt.md
> +3. Configure a forma de pagamento Mercado Pago.
```suggestion
3. Configure a forma de pagamento.
```

2020-06-08 17:39 UTC, pamalv7 commented on guides/plugins/unofficial/wix.pt.md
> +1. No painel de administração de sua loja, acesse "Pagamentos" do módulo de configurações.
```suggestion
1. No painel de administração de sua loja, acesse Pagamentos no módulo de configurações.
```

2020-06-08 17:39 UTC, pamalv7 commented on guides/plugins/unofficial/wix.pt.md
> +2. Clique no botão “Adicionar métodos de pagamento".
```suggestion
2. Clique no botão Adicionar métodos de pagamento. 
```

2020-06-08 17:39 UTC, pamalv7 commented on guides/plugins/unofficial/wix.pt.md
> +3. Na lista de métodos de pagamentos, selecione o "Mercado Pago" e clique em "Adicionar".
```suggestion
3. Na lista de métodos de pagamentos, selecione o Mercado Pago e clique em Adicionar.
```

2020-06-08 17:40 UTC, pamalv7 commented on guides/plugins/unofficial/wix.pt.md
> +E pronto! O Mercado Pago já está instalado.
```suggestion
Pronto! O Mercado Pago já está instalado.
```

2020-06-08 17:42 UTC, pamalv7 commented on guides/plugins/unofficial/wix.pt.md
> +## Credenciais de sua conta Mercado Pago
@douglas-cruz Acho redundante adicionar as credenciais novamente. Com o GIF, é super claro. Talvez você possa simplesmente deixar a nota.

2020-06-09 14:06 UTC, lamaralmp commented
Pendente de status com produto. Não adicionado a release 1.11.0.

2020-09-02 21:50 UTC, juones requested changes

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +1. No painel "Métodos de pagamentos", localize o "Mercado Pago" e clique em "Configurar conta para ativar".
````suggestion
1. No painel métodos de pagamentos, busque por Mercado Pago e clique em "Configurar conta para ativar".
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +2. Clique no botão “Conecte uma conta existente".
````suggestion
1. Clique em “Conecte uma conta existente". 
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +3. Complete os campos "Client ID e Client Secret" que corresponde as [credenciais]([FAKER][CREDENTIALS][URL]) de sua conta "Mercado Pago".
````suggestion
1. Complete os campos Client ID e Client Secret com as [credenciais de produção]([FAKER][CREDENTIALS][URL]) de sua conta do Mercado Pago.
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +4. Clique em "Conectar Minha Conta".
````suggestion
1. Por último, clique em "Conectar Minha Conta".
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +E pronto! O Mercado Pago já está ativado para receber pagamentos.
````suggestion
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +1. Acesse sua [conta Mercado Pago](https://www.mercadopago.com.br/business/) e clique em "Seu negócio".
````suggestion
1. Acesse sua [conta do Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/business/) e clique em "Seu negócio".
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +2. Clique na opção Configurações, navegue até o campo "Oferecer parcelas sem acréscimo" e clique em "Ativar".
````suggestion
1. Clique em "Configurações" e na seção oferecer parcelas sem acréscimo, clique em "Ativar".
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +3. Escolha "Quantas parcelas você quer oferecer?" e clique em "Ativar" para confirmar as alterações.
````suggestion
1. Escolha quantas parcelas você quer oferecer e clique em "Ativar".
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +E pronto! Você está oferecendo parcelamento sem acréscimo, assumindo as [tarifas de parcelamento](https://www.mercadopago.com.br/ajuda/oferecer-parcelas-sem-juros-para-compradores_454) que você confi
````suggestion
E pronto! Agora você está oferecendo parcelamento sem acréscimo, assumindo as [tarifas de parcelamento](https://www.mercadopago[FAKER][URL][DOMAIN]/ajuda/oferecer-parcelas-sem-juros-para-compradores_454) que você configurou.
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +## Credenciais de sua conta Mercado Pago
@douglas-cruz pode revisar isso porfa?

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +> Para mais informação, visite o site [oficial da Wix](https://pt.wix.com/ecommerce/loja-virtual).
````suggestion
> Para mais informações, visite o [site oficial da Wix](https://pt.wix.com/ecommerce/loja-virtual).
````

2020-09-02 21:50 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +## Credenciais de sua conta Mercado Pago
Talvez possamos fazer como fizemos com linx.

"> Encontre todas as informações sobre suas credenciais em [perguntas frequentes](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/faqs/credentials/)."

2020-09-08 22:07 UTC, juones requested changes

2020-09-08 22:07 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +Para **adicionar o Mercado Pago a sua loja**, siga os seguintes passos:
````suggestion
Para **adicionar o Mercado Pago em sua loja**, siga os passos abaixo:
````

2020-09-08 22:07 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +## Ative sua conta Mercado Pago
````suggestion
## Ative sua conta do Mercado Pago
````

2020-09-09 12:29 UTC, juones requested changes

2020-09-09 12:29 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +1. No painel administrativo, acesse "Pagamentos" no módulo de configurações.
````suggestion
1. No painel administrativo, acesse "Pagamentos".
````

2020-09-09 12:40 UTC, juones requested changes

2020-09-09 12:40 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +1. No painel administrativo, acesse "Pagamentos" no módulo de configurações.
````suggestion
1. No painel administrativo, acesse "Pagamentos" na seção de configurações.
````

2020-09-18 19:52 UTC, juones commented
Novo PR com nova estrutura https://github.com/mercadopago/devsite-docs/pull/872

2020-09-18 19:54 UTC, closed without merging