Arreglos en API Ref de Cajas
mercadopago/devsite-docs pull request #853
Opened 2020-09-01 03:54 UTC by juanseferrari2

## Description
Se agrego unos espacios en el resource de POS en API Ref porque no estaba levantando bien el markdown en las otras secciones de API Ref

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-09-07 14:02 UTC, pamalv7 requested changes

2020-09-07 14:02 UTC, pamalv7 commented on reference/pos/resource.yaml
> +          en: URL to get the order of the integrator system. It is optional and is used only in the disregarded integration model.
```suggestion
          en: URL to get the order of the integrator system. It is optional and is used only in the unattended integration model.
```

2020-09-07 14:02 UTC, pamalv7 commented on reference/pos/resource.yaml
> +          pt: URL para obter a ordem do sistema integrador. É opcional e é usado apenas no modelo de integração autônoma.
```suggestion
          pt: URL para obter a ordem do sistema integrador. É opcional e é usado apenas no modelo de integração desatendido.
```

2020-09-08 20:04 UTC, bacarvalho approved these changes

2020-09-08 20:06 UTC, pamalv7 approved these changes

2020-09-08 22:37 UTC, merged