feature/arreglosQR
mercadopago/devsite-docs pull request #868
Opened 2020-09-11 18:56 UTC by juanseferrari2

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-09-15 15:11 UTC, pamalv7 requested changes

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/advanced-integration.en.md
> +Obtain more information in our [API Reference](https://www.mercadopago.com.ar/developers/es/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_pos_external_pos_id_orders/get/).
```suggestion
Obtain more information in our [API Reference](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_pos_external_pos_id_orders/get/).
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/advanced-integration.es.md
> +Puedes obtener más información en la [Referencias de API](https://www.mercadopago.com.ar/developers/es/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_pos_external_pos_id_orders/get
```suggestion
Puedes obtener más información en la [Referencias de API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_pos_external_pos_id_orders/get/).
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/advanced-integration.pt.md
> +Pode obter mais informações em [Referências do API](https://www.mercadopago.com.br/developers/pt/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_pos_external_pos_id_orders/get/).
```suggestion
Pode obter mais informações em [Referências do API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_pos_external_pos_id_orders/get/).
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/qr-attended-part-b.en.md
> +Obtain more information in our [API Reference](https://www.mercadopago.com.ar/developers/en/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_stores_external_store_id_pos_external_pos
```suggestion
Obtain more information in our [API Reference](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_stores_external_store_id_pos_external_pos_id_orders/put/).
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/qr-attended-part-b.es.md
> +Puedes obtener más información en la [Referencias de API](https://www.mercadopago.com.ar/developers/es/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_stores_external_store_id_pos_e
```suggestion
Puedes obtener más información en la [Referencias de API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_stores_external_store_id_pos_external_pos_id_orders/put/).
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/qr-attended-part-b.pt.md
> +Pode obter mais informações em [Referências do API](https://www.mercadopago.com.br/developers/pt/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_stores_external_store_id_pos_externa
```suggestion
Pode obter mais informações em [Referências do API](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/instore_orders_v2/_instore_qr_seller_collectors_user_id_stores_external_store_id_pos_external_pos_id_orders/put/).
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.en.md
> +> [Integrate QR attended model](https://www.mercadopago.com.ar/developers/en/guides/in-person-payments/qr-code/qr-attended-part-b/)
```suggestion
> [Integrate QR attended model](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/in-person-payments/qr-code/qr-attended-part-b/)
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.es.md
> +> [Integrar QR modelo atendido](https://www.mercadopago.com.ar/developers/es/guides/in-person-payments/qr-code/qr-attended-part-b/)
```suggestion
> [Integrar QR modelo atendido](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/in-person-payments/qr-code/qr-attended-part-b/)
```

2020-09-15 15:11 UTC, pamalv7 commented on guides/in-person-payments/qr-code/stores-pos.pt.md
> +> [Integrar o modelo QR atendido](https://www.mercadopago.com.br/developers/pt/guides/in-person-payments/qr-code/qr-attended-part-b/)
```suggestion
> [Integrar o modelo QR atendido](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-person-payments/qr-code/qr-attended-part-b/)
```

2020-09-15 15:50 UTC, pamalv7 approved these changes

2020-09-15 18:13 UTC, bacarvalho approved these changes

2020-09-16 12:53 UTC, lamaralmp approved these changes

2020-09-16 18:02 UTC, merged