Feature/at headers
mercadopago/devsite-docs pull request #871
Opened 2020-09-18 14:29 UTC by jcapotondo

## Description
There is the need of moving the access tokens from the query params to the headers

2020-09-18 23:44 UTC, pamalv7 requested changes

2020-09-18 23:44 UTC, pamalv7 commented on reference/merchant_orders/endpoints/_merchant_orders_id/samples/get_curl.sh
> +  'https://api.mercadopago.com/merchant_orders/{id}' \
```suggestion
  'https://api.mercadopago.com/merchant_orders/:id' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/payments/endpoints/_payments_id/samples/get_curl.sh
> +    'https://api.mercadopago.com/v1/payments/{id}' \
```suggestion
    'https://api.mercadopago.com/v1/payments/:id' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/pos/endpoints/_pos_id/samples/delete_curl.sh
> +     'https://api.mercadopago.com/pos/{id}' \
```suggestion
     'https://api.mercadopago.com/pos/ID' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/pos/endpoints/_pos_id/samples/get_curl.sh
> +  'https://api.mercadopago.com/pos/{pos_id}' \
```suggestion
  'https://api.mercadopago.com/pos/POS_ID' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/pos/endpoints/_pos_id/samples/put_curl.sh
> +   'https://api.mercadopago.com/pos/{id}' \
```suggestion
   'https://api.mercadopago.com/pos/ID' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/stores/endpoints/_stores_id/samples/get_curl.sh
> +  'https://api.mercadopago.com/stores/{id}' \
```suggestion
  'https://api.mercadopago.com/stores/ID' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/stores/endpoints/_users_user_id_stores/samples/post_curl.sh
> +  'https://api.mercadopago.com/users/{user_id}/stores' \
```suggestion
  'https://api.mercadopago.com/users/USER_ID/stores' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/stores/endpoints/_users_user_id_stores_id/samples/delete_curl.sh
> +     'https://api.mercadopago.com/users/{user_id}/stores/{id}' \
```suggestion
     'https://api.mercadopago.com/users/USER_ID/stores/{id}' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/stores/endpoints/_users_user_id_stores_id/samples/put_curl.sh
> +   'https://api.mercadopago.com/users/{user_id}/stores/{id}' \
```suggestion
   'https://api.mercadopago.com/users/USER_ID/stores/{id}' \
```

2020-09-18 23:44 UTC, pamalv7 commented on reference/stores/endpoints/_users_user_id_stores_search/samples/get_curl.sh
> +  'https://api.mercadopago.com/users/{user_id}/stores/search' \
```suggestion
  'https://api.mercadopago.com/users/USER_ID/stores/search' \
```

2020-09-20 03:50 UTC, jcapotondo commented on reference/merchant_orders/endpoints/_merchant_orders_id/samples/get_curl.sh
> +  'https://api.mercadopago.com/merchant_orders/{id}' \
done

2020-09-20 03:50 UTC, jcapotondo commented on reference/payments/endpoints/_payments_id/samples/get_curl.sh
> +    'https://api.mercadopago.com/v1/payments/{id}' \
done

2020-09-20 03:51 UTC, jcapotondo commented on reference/pos/endpoints/_pos_id/samples/delete_curl.sh
> +     'https://api.mercadopago.com/pos/{id}' \
done

2020-09-20 03:51 UTC, jcapotondo commented on reference/pos/endpoints/_pos_id/samples/get_curl.sh
> +  'https://api.mercadopago.com/pos/{pos_id}' \
done

2020-09-20 03:52 UTC, jcapotondo commented on reference/pos/endpoints/_pos_id/samples/put_curl.sh
> +   'https://api.mercadopago.com/pos/{id}' \
done

2020-09-20 03:52 UTC, jcapotondo commented on reference/stores/endpoints/_stores_id/samples/get_curl.sh
> +  'https://api.mercadopago.com/stores/{id}' \
done

2020-09-20 03:53 UTC, jcapotondo commented on reference/stores/endpoints/_users_user_id_stores/samples/post_curl.sh
> +  'https://api.mercadopago.com/users/{user_id}/stores' \
done

2020-09-21 14:04 UTC, juanrossi requested changes
Vi que casi todos los curl no tienen \ al final, y muchos en la línea de -d tampoco. Pegale una revisada a eso mientras sigo mirando.

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-gas-station.en.md
> +curl -X POST
Falta \ acá

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-gas-station.es.md
> +curl -X POST
Falta \ acá y en la línea -d

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-gas-station.es.md
> +curl -X POST
Falta \ acá

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-gas-station.es.md
> +curl -X POST
Falta \ acá

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-gas-station.pt.md
> +curl -X POST
Falta \ acá y en la línea -d

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-gas-station.pt.md
> +curl -X POST
Falta \ acá

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-gas-station.pt.md
> +curl -X POST
Falta \ acá

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-pos.en.md
> +curl -X POST
Falta \ acá

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-pos.en.md
> +curl -X POST
Falta \ acá y en la línea -d

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-pos.en.md
> +curl -X DELETE
Falta \ acá

2020-09-21 14:04 UTC, juanrossi commented on guides/in-person-payments/qr-code-legacy/qr-pos.en.md
> +curl -X POST
Falta \ acá

2020-09-21 14:16 UTC, juanrossi commented
Quedaron 9 ocurrencias del AT por qs:
```
Searching 1151 files for "?access_token="

./devsite-docs/guides/manage-account/account/chargebacks.en.md:
  100      {
  101        "type": "image/png",
  102:       "url": "https://api.mercadopago.com/v1/chargebacks/documentation/op/op-4ccf4f39-b6f7-4c7b-a5ce-e8941a2a2b5f?access_token=TEST-7330838325999170-111309-c5e69fb44fb5dc008668f64e27653767-345521533",
  103        "description": "File: img.png, Size: 3324"
  104      }

./devsite-docs/guides/manage-account/account/chargebacks.es.md:
  100      {
  101        "type": "image/png",
  102:       "url": "https://api.mercadopago.com/v1/chargebacks/documentation/op/op-4ccf4f39-b6f7-4c7b-a5ce-e8941a2a2b5f?access_token=TEST-7330838325999170-111309-c5e69fb44fb5dc008668f64e27653767-345521533",
  103        "description": "File: img.png, Size: 3324"
  104      }

./devsite-docs/guides/manage-account/account/chargebacks.pt.md:
  100      {
  101        "type": "image/png",
  102:       "url": "https://api.mercadopago.com/v1/chargebacks/documentation/op/op-4ccf4f39-b6f7-4c7b-a5ce-e8941a2a2b5f?access_token=TEST-7330838325999170-111309-c5e69fb44fb5dc008668f64e27653767-345521533",
  103        "description": "File: img.png, Size: 3324"
  104      }

./devsite-docs/guides/online-payments/checkout-api/other-payment-ways.en.md:
 1439      -H 'accept: application/json' \
 1440      -H 'content-type: application/json' \
 1441:     'https://api.mercadopago.com/v1/payment_methods?access_token=ENV_ACCESS_TOKEN' \
 1442  ```
 1443  ]]]

./devsite-docs/guides/online-payments/checkout-pro/latest/integration.pt.md:
  212  ```curl
  213  curl -X POST \
  214:   'https://api.mercadolibre.com/checkout/preferences?access_token="**PROD_ACCESS_TOKEN**"' \
  215    -H 'Content-Type: application/json' \
  216    -H 'cache-control: no-cache' \

./devsite-docs/guides/online-payments/marketplace/checkout-api/create-marketplace.es.md:
  142          -H 'accept: application/json' \
  143          -H 'content-type: application/json' \
  144:         https://api.mercadopago.com/v1/payments?access_token=USER_AT \
  145          -d '{
  146                  "transaction_amount": 100,

./devsite-docs/guides/online-payments/marketplace/checkout-api/create-marketplace.pt.md:
  143          -H 'accept: application/json' \
  144          -H 'content-type: application/json' \
  145:         https://api.mercadopago.com/v1/payments?access_token=USER_AT \
  146          -d '{
  147                  "transaction_amount": 100,

./devsite-docs/guides/online-payments/marketplace/checkout-pro/create-marketplace.es.md:
  154  -H 'accept: application/json' \
  155  -H 'content-type: application/json' \
  156: 'https://api.mercadolibre.com/checkout/preferences?access_token=SELLER_AT' \
  157  -d '{
  158      "items": [

./devsite-docs/guides/online-payments/marketplace/checkout-pro/create-marketplace.pt.md:
  148  -H 'accept: application/json' \
  149  -H 'content-type: application/json' \
  150: 'https://api.mercadolibre.com/checkout/preferences?access_token=SELLER_AT' \
  151  -d '{
  152      "items": [

9 matches across 9 files
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/manage-account/reports/account-money/api.en.md
> +    -H 'Authorization: Bearer ENV_ACCESS_TOKEN' \
en este aarchivo hay uno curl sin cambio. esta bien?

```
curl -G \
    -H 'accept: application/json' \
    -d 'access_token=ENV_ACCESS_TOKEN' \
    'https://api.mercadopago.com/v1/account/settlement_report/list'
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/manage-account/reports/account-money/api.es.md
> +    -H 'Authorization: Bearer ENV_ACCESS_TOKEN' \
en este aarchivo hay uno curl sin cambio. esta bien?

```
curl -G \
    -H 'accept: application/json' \
    -d 'access_token=ENV_ACCESS_TOKEN' \
    'https://api.mercadopago.com/v1/account/settlement_report/list'
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/manage-account/reports/account-money/api.pt.md
> +    -H 'Authorization: Bearer ENV_ACCESS_TOKEN' \
en este aarchivo hay uno curl sin cambio. esta bien?

```
curl -G \
    -H 'accept: application/json' \
    -d 'access_token=ENV_ACCESS_TOKEN' \
    'https://api.mercadopago.com/v1/account/settlement_report/list'
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/manage-account/reports/available-money/api.en.md
> +    -H 'Authorization: Bearer ENV_ACCESS_TOKEN' \
en este aarchivo hay un curl sin modificar, esta bien?

```
curl -G \
    -H 'accept: application/json' \
    -d 'access_token=ENV_ACCESS_TOKEN' \
    'https://api.mercadopago.com/v1/account/bank_report/list'
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/manage-account/reports/available-money/api.es.md
> +    -H 'Authorization: Bearer ENV_ACCESS_TOKEN' \
en este aarchivo hay un curl sin modificar, esta bien?

```
curl -G \
    -H 'accept: application/json' \
    -d 'access_token=ENV_ACCESS_TOKEN' \
    'https://api.mercadopago.com/v1/account/bank_report/list'
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/manage-account/reports/available-money/api.pt.md
> +    -H 'Authorization: Bearer ENV_ACCESS_TOKEN' \
en este aarchivo hay un curl sin modificar, esta bien?

```
curl -G \
    -H 'accept: application/json' \
    -d 'access_token=ENV_ACCESS_TOKEN' \
    'https://api.mercadopago.com/v1/account/bank_report/list'
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/in-person-payments/qr-code/pre-requisites.en.md
> +"https://api.mercadopago.com/users/test_user
```suggestion
"https://api.mercadopago.com/users/test_user"
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/in-person-payments/qr-code/pre-requisites.es.md
> +"https://api.mercadopago.com/users/test_user
```suggestion
"https://api.mercadopago.com/users/test_user"
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/in-person-payments/qr-code/pre-requisites.pt.md
> +"https://api.mercadopago.com/users/test_user
```suggestion
"https://api.mercadopago.com/users/test_user"
```

2020-09-21 20:52 UTC, Juanii95 commented on guides/online-payments/checkout-api/other-features.en.md
> +    'https://api.mercadopago.com/v1/payments \
```suggestion
    'https://api.mercadopago.com/v1/payments' \
```

2020-09-22 03:21 UTC, pabal1708 reviewed
Review hasta "guides/online-payments/gateway/advanced-payments/cancel-payment.pt.md"

To be continued.

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments \'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments '

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.en.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.es.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-api/other-payment-ways.pt.md
> +  'https://api.mercadopago.com/v1/payments \
sugerencia de cambio 'https://api.mercadopago.com/v1/payments'

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-pro/latest/integration.en.md
> +  -H 'Authorization: Bearer **PROD_ACCESS_TOKEN**' \
Sugerencia de cambio  -H 'Authorization: Bearer PROD_ACCESS_TOKEN' \

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-pro/latest/integration.en.md
> +  -H 'Authorization: Bearer **PROD_ACCESS_TOKEN**' \
Sugerencia de cambio  -H 'Authorization: Bearer PROD_ACCESS_TOKEN' \

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-pro/latest/integration.es.md
> +  -H 'Authorization: Bearer **PROD_ACCESS_TOKEN**' \
Sugerencia de cambio  -H 'Authorization: Bearer PROD_ACCESS_TOKEN' \

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-pro/latest/integration.es.md
> +  -H 'Authorization: Bearer **PROD_ACCESS_TOKEN**' \
Sugerencia de cambio  -H 'Authorization: Bearer PROD_ACCESS_TOKEN' \

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-pro/latest/integration.pt.md
> +  -H 'Authorization: Bearer **PROD_ACCESS_TOKEN**' \
Sugerencia de cambio  -H 'Authorization: Bearer PROD_ACCESS_TOKEN' \

2020-09-22 03:21 UTC, pabal1708 commented on guides/online-payments/checkout-pro/latest/integration.pt.md
> +  -H 'Authorization: Bearer **PROD_ACCESS_TOKEN**' \
Sugerencia de cambio  -H 'Authorization: Bearer PROD_ACCESS_TOKEN' \

2020-09-22 14:32 UTC, pabal1708 commented on guides/resources/localization/identification-types.en.md
> +-H 'Authorization: Bearer ACCESS_TOKEN' \
```suggestion

```

2020-09-22 14:32 UTC, pabal1708 commented on guides/resources/localization/identification-types.es.md
> +-H 'Authorization: Bearer ACCESS_TOKEN' \
```suggestion

```

2020-09-22 14:32 UTC, pabal1708 commented on guides/resources/localization/identification-types.pt.md
> +-H 'Authorization: Bearer ACCESS_TOKEN' \
```suggestion

```

2020-09-22 17:40 UTC, juanrossi approved these changes

2020-09-22 18:04 UTC, Juanii95 approved these changes

2020-09-22 18:13 UTC, pabal1708 approved these changes

2020-09-22 18:43 UTC, pamalv7 requested changes

2020-09-22 18:43 UTC, pamalv7 commented on guides/manage-account/reports/account-money/api.pt.md
>  params = { 'access_token': 'ENV_ACCESS_TOKEN' }
¿No deberíamos eliminar esta linea?

2020-09-22 18:43 UTC, pamalv7 commented on guides/manage-account/reports/account-money/api.pt.md
> +    'https://api.mercadopago.com/v1/account/settlement_report/schedule
```suggestion
    'https://api.mercadopago.com/v1/account/settlement_report/schedule'
```

2020-09-22 19:58 UTC, pamalv7 requested changes

2020-09-22 19:58 UTC, pamalv7 commented on guides/online-payments/checkout-api/money-transfer.es.md
> +$ curl https://api.mercadopago.com/v1/payments\
```suggestion
$ curl https://api.mercadopago.com/v1/payments \
```

2020-09-22 19:58 UTC, pamalv7 commented on guides/resources/localization/migrating-v0-v1.es.md
> +        "https://api.mercadopago.com/v1/payments/:id/refunds?"
```suggestion
        "https://api.mercadopago.com/v1/payments/:id/refunds"
```

2020-09-22 19:58 UTC, pamalv7 commented on guides/manage-account/reports/available-money/api.es.md
> +}
A esto lo sumamos distinto en inglés, ¿es por algo en particular? 

Detalle /en: 

headers = {
    'accept': 'application/json',
    'content-type': 'application/json',
    'Authorization': 'Bearer ENV_ACCESS_TOKEN'
}

2020-09-23 13:22 UTC, pamalv7 approved these changes

2020-09-23 14:00 UTC, nicolassalvanes approved these changes

2020-09-23 17:15 UTC, merged