fix Wix traducao es en
mercadopago/devsite-docs pull request #872
Opened 2020-09-18 18:50 UTC by douglas-cruz

## Description

fix Wix tradução es en em nova estrutura devsite.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-09-18 20:03 UTC, juones requested changes

2020-09-18 20:03 UTC, juones commented on guides/plugins/unofficial/wix.pt.md
> +E pronto! Agora você está oferecendo parcelamento sem acréscimo, assumindo as [tarifas de parcelamento](https://www.mercadopago[FAKER][URL][DOMAIN]/ajuda/oferecer-parcelas-sem-juros-para-compradores_
````suggestion
E pronto! Agora você está oferecendo parcelamento sem acréscimo, assumindo as [tarifas de parcelamento](https://www.mercadopago.com.br/ajuda/_454) que você configurou.
````

2020-09-21 15:36 UTC, juones approved these changes

2020-09-22 17:50 UTC, juones approved these changes

2020-09-23 12:49 UTC, juones requested changes

2020-09-23 12:49 UTC, juones commented on guides/plugins/unofficial/wix.es.md
````suggestion
````

2020-09-23 12:50 UTC, juones commented on guides/plugins/unofficial/wix.en.md
````suggestion
````

2020-09-23 12:55 UTC, juones commented on guides/plugins/unofficial/wix.en.md
````suggestion
````

2020-09-23 12:55 UTC, juones commented on guides/plugins/unofficial/wix.en.md
````suggestion
````

2020-09-23 12:55 UTC, juones commented on guides/plugins/unofficial/wix.es.md
````suggestion
````

2020-09-23 12:55 UTC, juones commented on guides/plugins/unofficial/wix.es.md
````suggestion
````

2020-09-23 14:56 UTC, pabal1708 approved these changes

2020-09-23 19:50 UTC, pabal1708 approved these changes

2020-09-24 00:20 UTC, pamalv7 approved these changes

2020-09-24 00:20 UTC, pamalv7 commented on guides/plugins/unofficial/wix.en.md
> +1. Click on “Connect an existing account”
```suggestion
1. Click on “Connect an existing account”.
```

2020-09-24 00:20 UTC, pamalv7 commented on guides/plugins/unofficial/wix.es.md
> +1. Haz clic en “Agregar medio de pago”
```suggestion
1. Haz clic en “Agregar medio de pago”.
```

2020-09-24 00:20 UTC, pamalv7 commented on guides/plugins/unofficial/wix.es.md
> +Para **configurar la activación de tu cuenta de Mercado Pago**, sigue estos pasos
```suggestion
Para **configurar la activación de tu cuenta de Mercado Pago**, sigue estos pasos:
```

2020-09-24 02:42 UTC, pamalv7 approved these changes

2020-09-24 02:48 UTC, merged