Feature/subscriptions
mercadopago/devsite-docs pull request #875
Opened 2020-09-22 20:17 UTC by claudiobelen

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-09-29 19:58 UTC, bacarvalho requested changes

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/advanced-integration.en.md
> +>To get more information about the available fields, view the<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/" target="_blank">API references.</a>.
```suggestion
>To get more information about the available fields, view the<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/" target="_blank">API references.</a>.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/advanced-integration.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/testing/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/advanced-integration.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/payment-retry/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/payment-retry/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/advanced-integration.pt.md
> +>Para saber mais sobre os campos disponíveis, confira as <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/" target="_blank">Referências de API.</a>.
```suggestion
>Para saber mais sobre os campos disponíveis, confira as <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referências de API.</a>.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/advanced-integration.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/testing/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/advanced-integration.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/payment-retry/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/payment-retry/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.en.md
> +> Do you have questions about what a plan or other concept is? Keep the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/introduction" target="_
```suggestion
> Do you have questions about what a plan or other concept is? Keep the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/introduction" target="_blank">key concepts</a> handy to review them when needed.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.en.md
> +> ¿Do you have questions about how to create the payment token? Find all the information in the section of __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/sdks/official/js
```suggestion
> ¿Do you have questions about how to create the payment token? Find all the information in the section of __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/sdks/official/js/" target="_blank">Capture data from the card.</a>__.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.en.md
> +>You can get more information about the fields in the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/" target="_blank">API Reference</a>.
```suggestion
>You can get more information about the fields in the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/" target="_blank">API Reference</a>.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.en.md
> +> You can get more information about the fields in the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/" target="_blank">API reference</a>.
```suggestion
> You can get more information about the fields in the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/" target="_blank">API reference</a>.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/testing/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advanced-integration/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/advanced-integration/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.pt.md
> +> Dúvidas sobre o que é um plano ou outro conceito? Tenha em mãos os <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/introduction" target="_bla
```suggestion
> Dúvidas sobre o que é um plano ou outro conceito? Tenha em mãos os <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/introduction" target="_blank">conceitos-chave</a> para revisá-los quando necessário.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.pt.md
> +> Dúvidas sobre como criar o token de pagamento? Encontre todas as informações na seção de __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/sdks/official/js/" target="_blan
```suggestion
> Dúvidas sobre como criar o token de pagamento? Encontre todas as informações na seção de __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/sdks" target="_blank">Capturar dados do cartão.</a>__.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.pt.md
> +>Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/" target="_blank">Referência de API.</a>.
```suggestion
>Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referência de API.</a>.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.pt.md
> +> Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/reference/" target="_blank">Referência de API.</a>.
```suggestion
> Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referência de API.</a>.
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/testing/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advanced-integration/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/advanced-integration/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/introduction.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/previous-requirements/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/previous-requirements/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/introduction.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/previous-requirements/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/previous-requirements/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/payment-retry.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advenced-integration/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/advenced-integration/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/payment-retry.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/subscriptions/testing/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advenced-integration/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/advenced-integration/)
```

2020-09-29 19:58 UTC, bacarvalho commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/testing/)
```

2020-09-29 20:16 UTC, claudiobelen commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
Done!

2020-09-29 20:17 UTC, claudiobelen commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advenced-integration/)
Done!

2020-09-29 20:17 UTC, claudiobelen commented on guides/online-payments/subscriptions/payment-retry.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/testing/)
Done!

2020-09-29 20:17 UTC, claudiobelen commented on guides/online-payments/subscriptions/payment-retry.en.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advenced-integration/)
Done!

2020-09-29 20:17 UTC, claudiobelen commented on guides/online-payments/subscriptions/introduction.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/previous-requirements/)
Done!

2020-09-29 20:17 UTC, claudiobelen commented on guides/online-payments/subscriptions/previous-requirements.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/integration/)
Done!

2020-09-30 04:12 UTC, pamalv7 requested changes
Es necesario replicar los cambios para los tres idiomas.

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.es.md
> +> LEFT_BUTTON_RECOMMENDED_ES
```suggestion
> LEFT_BUTTON
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.es.md
> +> RIGHT_BUTTON_RECOMMENDED_ES
```suggestion
> RIGHT_BUTTON
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> LEFT_BUTTON_RECOMMENDED_PT
```suggestion
> LEFT_BUTTON
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> RIGHT_BUTTON_RECOMMENDED_PT
```suggestion
> RIGHT_BUTTON
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> testes
```suggestion
> Testes
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/testing/)
```suggestion
> [Testes](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/testing/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/advenced-integration/)
```suggestion
> [Integração avançada](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/advenced-integration/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/payment-retry.es.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advenced-integration/)
```suggestion
> [Integración avanzada](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advenced-integration/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/advanced-integration.pt.md
> +> RIGHT_BUTTON_RECOMMENDED_PT
```suggestion
> RIGHT_BUTTON
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.pt.md
> +Se você ainda não tem uma, pode <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/" target="_blank">criar uma conta Mercado Pago</a> quando quiser.
```suggestion
Se você ainda não tem uma, pode <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/" target="_blank">criar uma conta</a> quando quiser.
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/integration/)
```suggestion
> [Integre assinaturas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/integration/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.es.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/integration/)
```suggestion
> [Integrar suscripciones](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/integration/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +
```suggestion
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +# Testes
```suggestion
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +## Teste de assinaturas
```suggestion
# Teste de assinaturas
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +### Como testar sua integração
Mismos cambios que en español

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +------------ 	 |	--------
```suggestion
--- | ---
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +Tipos de usuário |   Descrição
```suggestion
Tipos de usuário | Descrição  
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +Use a <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/account/credentials" target="_blank">chave pública de teste</a> do seu usuário vendedor na hora de criar a assinatura que quiser testar
```suggestion
Use a <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/account/credentials" target="_blank">chave pública de teste</a> do seu usuário vendedor na hora de criar a assinatura que quiser testar.
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +> NOTE
```suggestion
> WARNING
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.es.md
> +> NOTE
```suggestion
> WARNING
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.es.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/payment-retry/)
```suggestion
> [Reintentos de cobros](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/payment-retry/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.es.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advanced-integration/)
```suggestion
> [Integración avanzada](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/advanced-integration/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +------------ 	 |	--------    |	--------    |	--------
```suggestion
--- |	--- | --- | --- 
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/advanced-integration/)
```suggestion
> [Integração avançada](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/advanced-integration/)
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +> RIGHT_BUTTON_RECOMMENDED_PT
```suggestion
> RIGHT_BUTTON
```

2020-09-30 04:12 UTC, pamalv7 commented on guides/online-payments/subscriptions/testing.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/subscriptions/payment-retry/)
```suggestion
> [Novas tentativas de cobrança](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/subscriptions/payment-retry/)
```

2020-09-30 14:18 UTC, bacarvalho requested changes

2020-09-30 14:18 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.es.md
> +`card_token_id (requerido)` | La información de la tarjeta será convertida en un token para enviar los datos de modo seguro. |
```suggestion
`card_token_id`(requerido) | La información de la tarjeta será convertida en un token para enviar los datos de modo seguro. |
```

2020-09-30 14:18 UTC, bacarvalho commented on guides/online-payments/subscriptions/integration.es.md
> +`payer_email (requerido)` | E-mail del pagador. |
```suggestion
`payer_email` (requerido) | E-mail del pagador. |
```

2020-09-30 17:51 UTC, bacarvalho approved these changes

2020-09-30 19:54 UTC, pamalv7 requested changes

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.en.md
> +Subscription or pre-approval | Payer authorization for recurring payments with a defined payment method that will be the basis for creating installments according to the recurrence that is defined. I
```suggestion
Subscription or pre-approval | Payer authorization for recurring payments with a defined payment method that will be the basis for creating installments according to the recurrence that is defined. It has similar characteristics to the template, since a subscription can be created from a plan. |  
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.pt.md
> +1. O __vendedor__ ou __cobrador__, proprietário da assinatura e credor dos valores devidos.
```suggestion
1. O __vendedor__ ou __collector__, proprietário da assinatura e credor dos valores devidos.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.pt.md
> +1. O __pagador__, que pagará os valores automaticamente com o meio de pagamento escolhido.
```suggestion
1. O __pagador__ ou __payer__, que pagará os valores automaticamente com o meio de pagamento escolhido.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.en.md
> +>Do you have questions about credentials? You can check our <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/support/" target="_blank">Frequently Asked Questions</a>.
```suggestion
>Do you have questions about credentials? You can check our <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/faqs/credentials/" target="_blank">FAQs</a>.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.pt.md
> +>Dúvidas sobre credenciais? Você pode conferir nossas <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/support/" target="_blank">perguntas frequentes.</a>.
```suggestion
>Dúvidas sobre credenciais? Você pode conferir nossas <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/resources/faqs/credentials/" target="_blank">perguntas frequentes</a>.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/previous-requirements.es.md
> +>¿Tienes dudas sobre credenciales? Puedes consultar nuestras <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/support/" target="_blank">preguntas frecuentes</a>.
```suggestion
>¿Tienes dudas sobre credenciales? Puedes consultar nuestras <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/resources/faqs/credentials/" target="_blank">preguntas frecuentes</a>.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +Along with the frequency, they define the installment cycle that a subscription will have. <br><br>For example, if every fifteen days you need to generate an instalment to be charged it would look li
```suggestion
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +`auto_recurring.frequency_type` (required) | Indicates the type of frequency. It can be by month (months) or day (days).
```suggestion
`auto_recurring.frequency_type` (required) | Indicates the type of frequency. It can be by month (months) or day (days). <br><br> Along with the frequency, they define the installment cycle that a subscription will have. <br><br>For example, if every fifteen days you need to generate an instalment to be charged it would look like this: `auto_recurring.frequency`: 15 y `auto_recurring.frequency_type`: days |
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +Along with the frequency, they define the installment cycle that a subscription will have.<br><br> For example, if every fifteen days you need to generate an instalment to be collected it would look
```suggestion
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +`auto_recurring.frequency_type` | Indicates the type of frequency. It can be by month (months) or day (days).
```suggestion
`auto_recurring.frequency_type` | Indicates the type of frequency. It can be by month (months) or day (days). Along with the frequency, they define the installment cycle that a subscription will have.<br><br> For example, if every fifteen days you need to generate an instalment to be collected it would look as follows: `auto_recurring.frequency`: 15 y  `auto_recurring.frequency_type`: days |
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/advanced-integration.en.md
> +To update, pause, cancel or reactivate a subscription already created, you need to use the preapproval_id that returns after the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscriptions/int
```suggestion
To update, pause, cancel or reactivate a subscription already created, you need to use the `preapproval_id` that returns after the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscriptions/integration/" target="_blank">creation</a>. 
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/advanced-integration.en.md
> +>To get more information about the available fields, view the<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/" target="_blank">API references.</a>.
```suggestion
>To get more information about the available fields, view the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/reference/" target="_blank">API references</a>.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/advanced-integration.pt.md
> +>Para saber mais sobre os campos disponíveis, confira as <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referências de API.</a>.
```suggestion
>Para saber mais sobre os campos disponíveis, confira as <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referências de API</a>.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +> ¿Tienes dudas sobre cómo crear el token de pago? Encuentra toda la información en la sección de __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/sdks/official/js/" target
```suggestion
> ¿Tienes dudas sobre cómo crear el token de pago? Encuentra toda la información en la sección de __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/receiving-payment-by-card#bookmark_captura_los_datos_de_la_tarjeta" target="_blank">Capturar datos de la tarjeta</a>__.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.pt.md
> +> Dúvidas sobre como criar o token de pagamento? Encontre todas as informações na seção de __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/sdks" target="_blank">Capturar d
```suggestion
> Dúvidas sobre como criar o token de pagamento? Encontre todas as informações na seção de __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/receiving-payment-by-card#bookmark_capture_os_dados_de_cart_o" target="_blank">Capturar dados do cartão</a>__.
```

2020-09-30 19:54 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +> ¿Do you have questions about how to create the payment token? Find all the information in the section of __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/sdks/official/js
```suggestion
> ¿Do you have questions about how to create the payment token? Find all the information in the section of __<a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/receiving-payment-by-card#bookmark_card_data_capture" target="_blank">Capture data from the card</a>__.
```

2020-09-30 20:31 UTC, pamalv7 requested changes

2020-09-30 20:31 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.es.md
> +> Ingresa en la sección de <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans" target="_blank">Suscripciones</a> en el panel de tu cuenta de Mercado Pago, configura tus datos ¡y
```suggestion
> Ingresa en la sección de <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans" target="_blank">Suscripciones</a> en el panel de tu cuenta de Mercado Pago, configura tus datos ¡y listo!
```

2020-09-30 20:31 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.pt.md
> +> Entre na seção de <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans" target="_blank">Assinaturas</a> no painel da sua conta Mercado Pago, configure os dados que precisar e pro
```suggestion
> Entre na seção de <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans" target="_blank">Assinaturas</a> no painel da sua conta Mercado Pago, configure os dados que precisar e pronto!
```

2020-09-30 20:31 UTC, pamalv7 commented on guides/online-payments/subscriptions/introduction.en.md
> +> Enter the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans" target="_blank">Subscriptions</a> section on your Mercado Pago account panel, set the data you need and that's it!
```suggestion
> Enter the <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/subscription-plans" target="_blank">Subscriptions</a> section on your Mercado Pago account panel, set the data you need and that's it!
```

2020-09-30 20:31 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.pt.md
> +>Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referência de API.</a>.
```suggestion
>Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referência de API</a>.
```

2020-09-30 20:31 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.pt.md
> +> Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referência de API.</a>.
```suggestion
> Você pode obter mais informações sobre os campos na <a href="https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/reference/" target="_blank">Referência de API</a>.
```

2020-09-30 20:35 UTC, pamalv7 requested changes

2020-09-30 20:35 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.pt.md
> +`auto_recurring.free_trial.frequency_type` | Indica o número de parcelas que não serão cobradas pelo serviço. Deve ser consistente com `auto_recurring.frequency_type` |
```suggestion
`auto_recurring.free_trial.frequency_type` | Indica o número de parcelas que não serão cobradas pelo serviço. Deve ser consistente com `auto_recurring.frequency_type`. |
```

2020-09-30 20:35 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +`auto_recurring.free_trial.frequency_type` | Indica la cantidad de cuotas que no se van a cobrar por el servicio. Tiene que ser consistente con `auto_recurring.frequency_type` |
```suggestion
`auto_recurring.free_trial.frequency_type` | Indica la cantidad de cuotas que no se van a cobrar por el servicio. Tiene que ser consistente con `auto_recurring.frequency_type`. |
```

2020-09-30 20:35 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +`auto_recurring.free_trial.frequency_type` | Indicates the number of installments that will not be charged for the service. It must be consistent with `auto_recurring.frequency_type` |
```suggestion
`auto_recurring.free_trial.frequency_type` | Indicates the number of installments that will not be charged for the service. It must be consistent with `auto_recurring.frequency_type`. |
```

2020-09-30 20:35 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.en.md
> +`auto_recurring.free_trial.frequency_type` | Indicates the amount of installments that will not be charged for the service. It must be consistent with `auto_recurring.frequency_type` |
```suggestion
`auto_recurring.free_trial.frequency_type` | Indicates the amount of installments that will not be charged for the service. It must be consistent with `auto_recurring.frequency_type`. |
```

2020-09-30 20:35 UTC, pamalv7 commented on guides/online-payments/subscriptions/integration.es.md
> +`auto_recurring.free_trial.frequency_type` | Indica la cantidad de cuotas que no se van a cobrar por el servicio. Tiene que ser consistente con `auto_recurring.frequency_type` |
```suggestion
`auto_recurring.free_trial.frequency_type` | Indica la cantidad de cuotas que no se van a cobrar por el servicio. Tiene que ser consistente con `auto_recurring.frequency_type`. |
```

2020-09-30 20:37 UTC, pamalv7 approved these changes

2020-09-30 20:37 UTC, merged