Sample projects in Checkout API and changelog
mercadopago/devsite-docs pull request #877
Opened 2020-09-23 20:25 UTC by pamalv7

## Description

- Sumamos contenidos para projectos descargables.
- Agregamos novedad en changelog. 

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [X] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-09-23 21:57 UTC, juones requested changes

2020-09-23 21:57 UTC, juones commented on guides/online-payments/checkout-api/receiving-payment-by-card.pt.md
> +Use os [exemplos para download](#bookmark_exemplos_para_download) para conhecer a integração completa ou para ataptá-los de acordo com o que precisa.
````suggestion
Use os [exemplos para download](#bookmark_exemplos_para_download) para conhecer a integração completa ou para adaptá-los de acordo com o que precisa.
````

2020-09-24 02:45 UTC, pabal1708 approved these changes

2020-09-24 02:51 UTC, Juanii95 approved these changes

2020-09-24 02:56 UTC, merged