New prestashop v4.2.0 changelog
mercadopago/devsite-docs pull request #882
Opened 2020-09-28 13:44 UTC by GiovanniCavallari

## Description
PR para comunicar o lançamento da nova versão 4.2.0 para o plugin de Prestashop.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [x] New features were communicated in changelog.
- [ ] Requires translations.

2020-09-28 22:30 UTC, juones requested changes

2020-09-28 22:30 UTC, juones commented on guides/plugins/official/shopify.pt.md
> +1. Aprove a conta para [ir a Produção](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/payments/api/goto-production/) e receber o dinheiro das suas vendas no Mercado Pago.
Aqui não seria mais adequado "Ative" ao invés de Aprove?

2020-09-28 22:30 UTC, juones commented on guides/plugins/official/shopify.pt.md
> +> Mercado Pago é um parceiro oficial do Shopify: oferecemos segurança a todos os pagamentos feitos em sua loja.
````suggestion
> Mercado Pago é um parceiro oficial do Shopify: oferecemos segurança à todos os pagamentos feitos em sua loja.
````

2020-09-29 13:25 UTC, GiovanniCavallari commented on guides/plugins/official/shopify.pt.md
> +1. Aprove a conta para [ir a Produção](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/payments/api/goto-production/) e receber o dinheiro das suas vendas no Mercado Pago.
Pode ser, deixar igual a parte de credenciais.

2020-09-29 13:28 UTC, GiovanniCavallari commented on guides/plugins/official/shopify.pt.md
> +> Mercado Pago é um parceiro oficial do Shopify: oferecemos segurança a todos os pagamentos feitos em sua loja.
Alterado

2020-09-29 15:01 UTC, juones approved these changes

2020-09-29 15:52 UTC, pamalv7 requested changes

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.es.md
> +__Checkout redirect Mercado Pago__: configura el Checkout de Mercado Pago para que tus clientes finalicen su pago en nuestro sitio. Ya se encuentra pre-instalada en tu administrador de Shopify.
```suggestion
__Checkout redirect Mercado Pago__: configura Checkout Pro para que tus clientes finalicen su pago en nuestro sitio. Ya se encuentra pre-instalada en tu administrador de Shopify.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.es.md
> +Sigue estos pasos para procesar los pagos con el Checkout de Mercado Pago:
```suggestion
Sigue estos pasos para procesar los pagos con Checkout Pro:
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.es.md
> +> Consulta la documentación del [Checkout de Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/payments/web-payment-checkout/introduction/) para conocer mejor todas sus c
```suggestion
> Consulta la documentación de [Checkout Pro](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/payments/web-payment-checkout/introduction/) para conocer mejor todas sus características y funcionalidades.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.es.md
> +| Estado del pago | Mercado Pago status | Shopify order status |
A "Mercado Pago status" y a "Shopify order status", ¿los dejamos en inglés por algo en particular?

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.es.md
> +1. Busca *“Checkout transparente de Mercado Pago”* entre la oferta de apps.
```suggestion
1. Busca “Checkout transparente de Mercado Pago” entre la oferta de apps.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.es.md
> +1. Haz clic en *Agregar app*.
```suggestion
1. Haz clic en "Agregar app".
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.es.md
> +> Consulta los [requisitos para ir a producción](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/payments/api/goto-production/) si tienes alguna duda con el proceso.
Creo que no es necesario sumar está referencia.

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.en.md
> +__Mercado Pago Redirect Checkout__: configure Mercado Pago Checkout, so that your customers finalize their payment on our website. It is already pre-installed in your Shopify administrator.
```suggestion
__Mercado Pago Redirect Checkout__: configure Checkout Pro, so that your customers finalize their payment on our website. It is already pre-installed in your Shopify administrator.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.en.md
> +1. Search for *“Mercado Pago Transparent Checkout”* in the apps offer.
```suggestion
1. Search for “Mercado Pago Transparent Checkout” in the apps offer.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.en.md
> +1. Click on *Add app*.
```suggestion
1. Click on "Add app".
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.en.md
> +> Check the [requirements to go to production](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/payments/api/goto-production/) if you have any questions about the process.
Creo que no es necesario sumar está referencia.

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.en.md
> +Follow these steps to process payments with Mercado Pago Checkout:
```suggestion
Follow these steps to process payments with Checkout Pro:
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.en.md
> +> Check [Mercado Pago Checkout](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/payments/web-payment-checkout/introduction/) documentation to learn more about all its features and fu
```suggestion
> Check [Checkout Pro](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/payments/web-payment-checkout/introduction/) documentation to learn more about all its features and functionalities.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.pt.md
> +__Checkout redirect Mercado Pago__: configure o Checkout do Mercado Pago para que seus clientes finalizem o pagamento no nosso site. Ele já está pré-instalado no seu administrador do Shopify.
```suggestion
__Checkout redirect Mercado Pago__: configure o Checkout Pro para que seus clientes finalizem o pagamento no nosso site. Ele já está pré-instalado no seu administrador do Shopify.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.pt.md
> +1. Pesquise por *“Checkout transparente do Mercado Pago”* na oferta de apps.
```suggestion
1. Pesquise por “Checkout transparente do Mercado Pago” na oferta de apps.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.pt.md
> +1. Clique em *Adicionar app*.
```suggestion
1. Clique em "Adicionar app".
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.pt.md
> +> Confira os [requisitos para ir a produção](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/payments/api/goto-production/) se você tem alguma dúvida em relação ao processo.
Creo que no es necesario sumar está referencia.

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.pt.md
> +Siga estas etapas para processar pagamentos com o Checkout do Mercado Pago:
```suggestion
Siga estas etapas para processar pagamentos com o Checkout Pro:
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.pt.md
> +> Confira a documentação do [Checkout do Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/payments/web-payment-checkout/introduction/) para conhecer melhor todas as suas
```suggestion
> Confira a documentação do [Checkout Pro](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/payments/web-payment-checkout/introduction/) para conhecer melhor todas as suas características e funcionalidades.
```

2020-09-29 15:52 UTC, pamalv7 commented on guides/plugins/official/shopify.pt.md
> +| Status do pagamento | Mercado Pago status | Shopify order status |
A "Mercado Pago status" y a "Shopify order status", ¿los dejamos en inglés por algo en particular?

2020-09-29 15:52 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +### September 25th
Hay que unificar este changelog con el de abajo ya que tienen la misma fecha.

2020-09-29 15:52 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +### 25 de septiembre
Hay que unificar este changelog con el de abajo ya que tienen la misma fecha.

2020-09-29 15:52 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +### 25 de setembro
Hay que unificar este changelog con el de abajo ya que tienen la misma fecha.

2020-09-29 18:29 UTC, GiovanniCavallari commented on guides/resources/changelog/current-year.pt.md
> +### 25 de setembro
Unificados.

2020-09-29 18:29 UTC, GiovanniCavallari commented on guides/resources/changelog/current-year.es.md
> +### 25 de septiembre
Unificados.

2020-09-29 18:29 UTC, GiovanniCavallari commented on guides/resources/changelog/current-year.en.md
> +### September 25th
Unificados.

2020-09-29 18:52 UTC, GiovanniCavallari commented on guides/plugins/official/shopify.pt.md
> +| Status do pagamento | Mercado Pago status | Shopify order status |
Hicimos un depara en inglés, porque en las docus, tanto de mp cuanto de shopify, la referencia de los estados son en inglés.

2020-09-29 18:52 UTC, GiovanniCavallari commented on guides/plugins/official/shopify.es.md
> +| Estado del pago | Mercado Pago status | Shopify order status |
Hicimos un depara en inglés, porque en las docus, tanto de mp cuanto de shopify, la referencia de los estados son en inglés.

2020-09-30 14:44 UTC, pamalv7 requested changes

2020-09-30 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +
```suggestion

<span></span>
```

2020-09-30 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +
```suggestion

<span></span>
```

2020-09-30 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +
```suggestion

<span></span>
```

2020-09-30 17:53 UTC, pamalv7 requested changes

2020-09-30 17:53 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +
```suggestion

<br>
```

2020-09-30 17:53 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +
```suggestion

<br>
```

2020-09-30 17:53 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +
```suggestion

<br>
```

2020-09-30 18:34 UTC, pamalv7 approved these changes

2020-09-30 18:38 UTC, merged