Feature/expiration date preference
mercadopago/devsite-docs pull request #897
Opened 2020-10-16 14:49 UTC by ramiroarguelles

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-10-20 18:46 UTC, lamaralmp approved these changes

2020-10-27 01:39 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.en.md
> +Check [credit times by payment method](https://www.mercadopago[FAKER][URL][DOMAIN]/ayuda/Medios-de-pago-y-acreditaci-n_221) when configuring.
```suggestion
Check [credit times by payment method](https://www.mercadopago[FAKER][URL][DOMAIN]/ayuda/_221) when configuring.
```

2020-10-27 01:39 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.es.md
> +Ten en cuenta los [tiempos de acreditación por medio de pago](https://www.mercadopago[FAKER][URL][DOMAIN]/ayuda/Medios-de-pago-y-acreditaci-n_221) para realizar la configuración.
```suggestion
Ten en cuenta los [tiempos de acreditación por medio de pago](https://www.mercadopago[FAKER][URL][DOMAIN]/ayuda/_221) para realizar la configuración.
```

2020-10-27 01:39 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.pt.md
> +Revise os [tempos de creditação por meio de pagamento](https://www.mercadopago[FAKER][URL][DOMAIN]/ayuda/Medios-de-pago-y-acreditaci-n_221) para executar a configuração.
```suggestion
Revise os [tempos de creditação por meio de pagamento](https://www.mercadopago[FAKER][URL][DOMAIN]/ajuda/_221) para executar a configuração.
```

2020-10-27 01:39 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.es.md
> +Por defecto, la fecha de vencimiento para los pagos en efectivo es de 30 días. Si quieres, puedes cambiarla enviando el campo `date_of_expiration` en la solicitud de creación de la preferencia. La fe
¿La fecha de vencimiento por defecto sigue siendo 30 o es 7?

2020-10-27 01:39 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.en.md
> +"date_of_expiration": "2020-05-30T23:59:59.000-04:00";
```suggestion
"date_of_expiration": "2020-05-30T23:59:59.000-04:00"
```

2020-10-27 01:39 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.es.md
> +"date_of_expiration": "2020-05-30T23:59:59.000-04:00";
```suggestion
"date_of_expiration": "2020-05-30T23:59:59.000-04:00"
```

2020-10-27 01:39 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.pt.md
> +"date_of_expiration": "2020-05-30T23:59:59.000-04:00";
```suggestion
"date_of_expiration": "2020-05-30T23:59:59.000-04:00"
```

2020-11-16 19:50 UTC, SofiaMoralesGonzalez1992 reviewed
Modifico el texto con la informacion correcta sobre fechas de vencimientos de pagos en efectivo.

2020-11-16 19:50 UTC, SofiaMoralesGonzalez1992 commented on guides/online-payments/checkout-pro/latest/configurations.es.md
> +Por defecto, la fecha de vencimiento para los pagos en efectivo es de 30 días. Si quieres, puedes cambiarla enviando el campo `date_of_expiration` en la solicitud de creación de la preferencia. La fe
```suggestion
Por defecto, la fecha de vencimiento puede variar entre 5 a 30 días según el medio de pago en efectivo que estes utilizando. Si quieres, puedes cambiarla enviando el campo `date_of_expiration` en la solicitud de creación de la preferencia. La fecha configurada debe ser entre 5 y 30 días a partir de la fecha de creación de la preferencia de pago.
```

2020-11-16 19:50 UTC, SofiaMoralesGonzalez1992 commented on guides/online-payments/checkout-pro/latest/configurations.pt.md
> +A data de expiração padrão para pagamentos em dinheiro é de 30 dias. Opcionalmente é possível alterar essa data enviando o campo `date_of_expiration` na requisição de criação da preferência. A data c
```suggestion
A data de validade pode variar entre 5 a 30 dias dependendo do método de pagamento que você está usando opcionalmente é possível alterar essa data enviando o campo `date_of_expiration` na requisição de criação da preferência. A data configurada deve estar entre 5 e 30 dias a partir da data de emissão.
```

2020-11-16 19:50 UTC, SofiaMoralesGonzalez1992 commented on guides/online-payments/checkout-pro/latest/configurations.en.md
> +The default expiration date for cash payments is 30 days. If you want, you can change this date by sending the `date_of_expiration` field in the preference creation request. The configured date must
```suggestion
The default expiration date can vary between 5 to 30 days depending on the means of payment you are using.. If you want, you can change this date by sending the `date_of_expiration` field in the preference creation request. The configured date must be between 5 and 30 days from the preference creation date.
```

2020-11-17 17:47 UTC, pamalv7 requested changes

2020-11-17 17:47 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.en.md
> +The default expiration date for cash payments is 30 days. If you want, you can change this date by sending the `date_of_expiration` field in the preference creation request. The configured date must
```suggestion
By default, the due date of a cash payment can vary between 5 and 30 days depending on the payment method you are using. If you want, you can change this date by sending the `date_of_expiration` field in the preference creation request. The configured date must be between 1 and 30 days from the preference creation date.
```

2020-11-17 17:47 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.es.md
> +Por defecto, la fecha de vencimiento para los pagos en efectivo es de 30 días. Si quieres, puedes cambiarla enviando el campo `date_of_expiration` en la solicitud de creación de la preferencia. La fe
```suggestion
Por defecto, la fecha de vencimiento de un pago en efectivo puede variar entre 5 y 30 días según el medio de pago estés utilizando. Si quieres, puedes cambiarla enviando el campo `date_of_expiration` en la solicitud de creación de la preferencia. La fecha configurada debe ser entre 1 y 30 días a partir de la fecha de creación de la preferencia de pago.
```

2020-11-17 17:47 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.pt.md
> +A data de expiração padrão para pagamentos em dinheiro é de 30 dias. Opcionalmente é possível alterar essa data enviando o campo `date_of_expiration` na requisição de criação da preferência. A data c
```suggestion
Por padrão, a data de vencimento para pagamentos em dinheiro pode variar entre 5 e 30 dias, dependendo do meio de pagamento que você está usando. Opcionalmente é possível alterar essa data enviando o campo `date_of_expiration` na requisição de criação da preferência. A data configurada deve estar entre 1 e 30 dias a partir da data de emissão.
```

2020-11-17 19:21 UTC, pamalv7 requested changes

2020-11-17 19:21 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.en.md
> +The default expiration date for cash payments is 30 days. If you want, you can change this date by sending the `date_of_expiration` field in the preference creation request. The configured date must
```suggestion
If you want, you can change the default due date of a cash payment by sending the `date_of_expiration` field in the preference creation request. The configured date must be between 1 and 30 days from the preference creation date.
```

2020-11-17 19:21 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.pt.md
> +A data de expiração padrão para pagamentos em dinheiro é de 30 dias. Opcionalmente é possível alterar essa data enviando o campo `date_of_expiration` na requisição de criação da preferência. A data c
```suggestion
Opcionalmente é possível alterar a data de vencimento por padrão para pagamentos em dinheiro enviando o campo `date_of_expiration` na requisição de criação da preferência. A data configurada deve estar entre 1 e 30 dias a partir da data de emissão.
```

2020-11-17 19:21 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/configurations.es.md
> +Por defecto, la fecha de vencimiento para los pagos en efectivo es de 30 días. Si quieres, puedes cambiarla enviando el campo `date_of_expiration` en la solicitud de creación de la preferencia. La fe
```suggestion
Si quieres, puedes cambiarla la fecha de vencimiento por defecto de un pago en efectivo enviando el campo `date_of_expiration` en la solicitud de creación de la preferencia. La fecha configurada debe ser entre 1 y 30 días a partir de la fecha de creación de la preferencia de pago.
```

2020-11-17 19:24 UTC, pamalv7 approved these changes

2020-11-17 19:24 UTC, SofiaMoralesGonzalez1992 approved these changes

2020-11-17 21:48 UTC, lamaralmp commented
Los cambios serán tomados en el PR #934 por el conflicto de la carpeta `/latest/` que no existe más.

2020-11-17 21:48 UTC, closed without merging

2020-11-18 12:17 UTC, SofiaMoralesGonzalez1992 approved these changes