[Feature] Checkout Pro Wallet landing page
mercadopago/devsite-docs pull request #904
Opened 2020-10-21 20:40 UTC by Kneehole

## Description
Se agrega nueva landing para Integración de Checkout Pro en modo billetera. Ademas de ello se agrega una card al final de la integración de Checkout API para invitar a que lo sumen a sus integraciones

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [x] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [x] New features were communicated in changelog.
- [ ] Requires translations.

2020-10-26 22:27 UTC, pamalv7 requested changes

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/goto-production.en.md
> +> [Registered users](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/configurations/#bookmark_accept_payments_from_registered_users_only)
```suggestion
> [Registered users](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-api/wallet-integration)
```

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/goto-production.es.md
> +> [Usuarios registrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/configurations/#bookmark_aceptar_pagos_únicamente_de_usuarios_registrados)
```suggestion
> [Usuarios registrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-api/wallet-integration)
```

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/goto-production.pt.md
> +> [Usuários cadastrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/configurations/#bookmark_aceitar_pagamentos_somente_de_usuários_cadastrados)
```suggestion
> [Usuários cadastrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/wallet-integration)
```

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/goto-production.pt.md
> +> Aceite pagamentos com a carteira Mercado Pago
Esto se nos va a dos lineas, ¿podríamos reducirlo?

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +Add in your integration the Checkout Pro wallet mode, so that **you receive payments only from Mercado Pago registered users with their cards and available balance.**
```suggestion
Add in your integration the Checkout Pro wallet mode, so that **you receive payments only from Mercado Pago registered users with their cards and available balance**.
```

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +Agrega en tu integración el Checkout Pro modo billetera, para que **recibas pagos únicamente de usuarios registrados en Mercado Pago, con sus tarjetas y dinero disponible.**
```suggestion
Agrega en tu integración el Checkout Pro modo billetera, para que **recibas pagos únicamente de usuarios registrados en Mercado Pago, con sus tarjetas y dinero disponible**.
```

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +Adicione na sua integração o Checkout Pro modo carteira, **para que você receba pagamentos somente de usuários cadastrados no Mercado Pago, com seus cartões e saldo disponível.**
```suggestion
Adicione na sua integração o Checkout Pro modo carteira, **para que você receba pagamentos somente de usuários cadastrados no Mercado Pago, com seus cartões e saldo disponível**.
```

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +> [Usuarios registrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-pro/configurations/#bookmark_aceptar_pagos_únicamente_de_usuarios_registrados)
¿No debería ir a integración? (ídem en/pt)

2020-10-26 22:27 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/integration.pt.md
> +> Aceite pagamentos com a carteira Mercado Pago
Esto se nos va a dos lineas, ¿podríamos reducirlo?

2020-10-27 03:13 UTC, Kneehole commented on guides/online-payments/checkout-api/goto-production.pt.md
> +> Aceite pagamentos com a carteira Mercado Pago
Quedamos a la espera de ver que nos comenta Gabi 👍

2020-10-27 03:16 UTC, Kneehole commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +> [Usuarios registrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-pro/configurations/#bookmark_aceptar_pagos_únicamente_de_usuarios_registrados)
Ahí revisé el journey, otra cosa que entendí para el traste 🤦

2020-10-27 03:22 UTC, Kneehole commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +> [Usuarios registrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-pro/configurations/#bookmark_aceptar_pagos_únicamente_de_usuarios_registrados)
ya lo actualicé!

2020-10-27 13:58 UTC, pamalv7 requested changes

2020-10-27 13:58 UTC, pamalv7 commented on guides/online-payments/checkout-api/goto-production.pt.md
> +> Aceite pagamentos com a carteira Mercado Pago
Me confirmo Gaby, sugiero el cambio!

2020-10-27 13:58 UTC, pamalv7 commented on guides/online-payments/checkout-api/goto-production.pt.md
> +> Aceite pagamentos com a carteira Mercado Pago
```suggestion
> Aceite a carteira Mercado Pago
```

2020-10-27 13:58 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +> Aceite pagamentos com a carteira Mercado Pago
```suggestion
> Aceite a carteira Mercado Pago
```

2020-10-27 14:06 UTC, pamalv7 requested changes

2020-10-27 14:06 UTC, pamalv7 commented on guides/online-payments/checkout-pro/latest/integration.pt.md
> +> Aceite pagamentos com a carteira Mercado Pago
```suggestion
> Aceite a carteira Mercado Pago
```

2020-10-27 14:06 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +> [Usuarios registrados](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/online-payments/checkout-pro/configurations/#bookmark_aceptar_pagos_únicamente_de_usuarios_registrados)
¡Perfecto!

2020-10-27 14:33 UTC, pamalv7 requested changes

2020-10-27 14:33 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +![Checkout-Wallet](/images/web-payment-checkout/cho-wallet-landing.png)
```suggestion
----[mla, mlm, mlc, mco, mpe, mlu]----
![Checkout-Wallet](/images/web-payment-checkout/cho-wallet-landing.png)
------------
----[mlb]----
![Checkout-Wallet](/images/web-payment-checkout/cho-wallet-landing-pt.png)
------------
```

2020-10-28 02:30 UTC, pamalv7 approved these changes

2020-10-28 12:45 UTC, Juanii95 approved these changes

2020-10-28 13:45 UTC, merged