Fature/suscriptions info update
mercadopago/devsite-docs pull request #910
Opened 2020-10-28 20:52 UTC by diemartinezmeli

## Description
Se agrega  informacion de suscripciones al changelog para ES - EN - PT
Se quita warning de suscripciones que mencionaba una limitacion que ya fue superada.

2020-11-02 20:40 UTC, Juanii95 approved these changes

2020-11-03 05:09 UTC, pamalv7 requested changes

2020-11-03 05:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +### 30 de octubre
Actualizar fecha a 5 de noviembre que es la subida.

2020-11-03 05:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +### October 30th
Actualizar fecha a 5 de noviembre que es la subida.

2020-11-03 05:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +### 30 de outubro
Actualizar fecha a 5 de noviembre que es la subida.

2020-11-03 13:14 UTC, diemartinezmeli commented on guides/resources/changelog/current-year.es.md
> +### 30 de octubre
Hola Pam, se actualizó título del mes y fecha del cambio

2020-11-03 13:14 UTC, diemartinezmeli commented on guides/resources/changelog/current-year.en.md
> +### October 30th
Hola Pam, se actualizó título del mes y fecha del cambio

2020-11-03 13:14 UTC, diemartinezmeli commented on guides/resources/changelog/current-year.pt.md
> +### 30 de outubro
Hola Pam, se actualizó título del mes y fecha del cambio

2020-11-03 13:26 UTC, bacarvalho approved these changes

2020-11-03 19:09 UTC, pamalv7 requested changes

2020-11-03 19:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +## November 2020
```suggestion
----[mlm, mla, mlb]----
## November 2020
```

2020-11-03 19:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +## Noviembre 2020
```suggestion
----[mlm, mla, mlb]----
## Noviembre 2020
```

2020-11-03 19:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +## Novembro 2020
```suggestion
----[mlm, mla, mlb]----
## Novembro 2020
```

2020-11-03 19:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +
```suggestion
------------

```

2020-11-03 19:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.es.md
> +
```suggestion
------------

```

2020-11-03 19:09 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +
```suggestion
------------

```

2020-11-03 20:38 UTC, pamalv7 approved these changes

2020-11-04 13:50 UTC, merged