[WIP][Feature] CHO Api wallet landing improvements
mercadopago/devsite-docs pull request #929
Opened 2020-11-13 18:44 UTC by Kneehole

## Description
Buscamos mejorar la landing generada para el modo billetera de Checkout Pro en la sección de Checkout API. Para ello vamos a agregar los snippets requeridos para hacer la integración con la configuración especifica para el soporte de modo billetera.
 
El brief de contenidos se puede ver en este [documento](https://docs.google.com/document/d/1d4r4Ue463WyJsHCI_UgofMbmvVGuR5kGdyzf2Qjjl2k/edit#) en la sección "Apartado técnico"

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [x] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-11-24 20:18 UTC, pamalv7 requested changes

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +The wallet mode works by adding the `purpose` attribute to the preference.
```suggestion
The wallet mode works by adding the _purpose_ attribute to the preference.
```
Nos rompe el snippet la cita de código.

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +The wallet mode works by adding the `purpose` attribute to the preference.
```suggestion
The wallet mode works by adding the _purpose_ attribute to the preference.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +The wallet mode works by adding the `purpose` attribute to the preference.
```suggestion
The wallet mode works by adding the _purpose_ attribute to the preference.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +The wallet mode works by adding the `purpose` attribute to the preference.
```suggestion
The wallet mode works by adding the _purpose_ attribute to the preference.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +The wallet mode works by adding the `purpose` attribute to the preference.
```suggestion
The wallet mode works by adding the _purpose_ attribute to the preference.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +The wallet mode works by adding the `purpose` attribute to the preference.
```suggestion
The wallet mode works by adding the _purpose_ attribute to the preference.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +El modo billetera funciona agregando el atributo `purpose` en la preferencia.
```suggestion
El modo billetera funciona agregando el atributo _purpose_ en la preferencia.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +El modo billetera funciona agregando el atributo `purpose` en la preferencia.
```suggestion
El modo billetera funciona agregando el atributo _purpose_ en la preferencia.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +El modo billetera funciona agregando el atributo `purpose` en la preferencia.
```suggestion
El modo billetera funciona agregando el atributo _purpose_ en la preferencia.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +El modo billetera funciona agregando el atributo `purpose` en la preferencia.
```suggestion
El modo billetera funciona agregando el atributo _purpose_ en la preferencia.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +El modo billetera funciona agregando el atributo `purpose` en la preferencia.
```suggestion
El modo billetera funciona agregando el atributo _purpose_ en la preferencia.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.es.md
> +El modo billetera funciona agregando el atributo `purpose` en la preferencia.
```suggestion
El modo billetera funciona agregando el atributo _purpose_ en la preferencia.
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/test-integration/
```suggestion
> [Pruebas](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/test-integration/)
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.en.md
> +> [Tests](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-pro/test-integration/
```suggestion
> [Tests](http://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/online-payments/checkout-pro/test-integration/)
```

2020-11-24 20:18 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +Você deve integrar o [Checkout Pro](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/introduction) configurado como [modo carteira](https://www.mercadopag
```suggestion
Você deve integrar o [Checkout Pro](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/introduction) configurado como [modo carteira](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-pro/configurations#bookmark_aceitar_pagamentos_somente_de_usuários_cadastrados) para adicionar a carteira do Mercado Pago no seu site.
```

2020-11-25 18:52 UTC, pamalv7 requested changes

2020-11-25 18:52 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +O modo carteira funciona adicionando o atributo `purpose` na preferência.
```suggestion
O modo carteira funciona adicionando o atributo _purpose_ na preferência.
```

2020-11-25 18:52 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +O modo carteira funciona adicionando o atributo `purpose` na preferência.
```suggestion
O modo carteira funciona adicionando o atributo _purpose_ na preferência.
```

2020-11-25 18:52 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +O modo carteira funciona adicionando o atributo `purpose` na preferência.
```suggestion
O modo carteira funciona adicionando o atributo _purpose_ na preferência.
```

2020-11-25 18:52 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +O modo carteira funciona adicionando o atributo `purpose` na preferência.
```suggestion
O modo carteira funciona adicionando o atributo _purpose_ na preferência.
```

2020-11-25 18:52 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +O modo carteira funciona adicionando o atributo `purpose` na preferência.
```suggestion
O modo carteira funciona adicionando o atributo _purpose_ na preferência.
```

2020-11-25 18:52 UTC, pamalv7 commented on guides/online-payments/checkout-api/wallet-integration.pt.md
> +O modo carteira funciona adicionando o atributo `purpose` na preferência.
```suggestion
O modo carteira funciona adicionando o atributo _purpose_ na preferência.
```

2020-11-25 19:10 UTC, pamalv7 approved these changes

2020-11-25 19:45 UTC, elvisjhonataoliveira approved these changes

2020-11-25 19:46 UTC, merged