fix/VTEX-CHOPRO_MODAL_WB-PT/ES
mercadopago/devsite-docs pull request #941
Opened 2020-11-24 17:04 UTC by douglas-cruz

Fix de emergencia para destacar el Checkout Pro Modal y Wallet en Vtex.

2020-11-25 12:48 UTC, adfonseca commented on guides/plugins/unofficial/vtex.pt.md
> +> Caso as condições de pagamento MercadoPagoPro e MercadoPagoWallet não estiverem disponíveis para adicioná las, certifique em sua loja de aplicativos da VTEX que o App Mercado Pago Payment APP estej
```suggestion
> Caso as condições de pagamento MercadoPagoPro e MercadoPagoWallet não estiverem disponíveis para adicioná-las, certifique em sua loja de aplicativos da VTEX que o App Mercado Pago Payment APP esteja instalado ou solicite a instalação pela equipe VTEX sob demanda através de ticket no [Support VTEX](https://support.vtex.com/).
```

2020-11-25 14:18 UTC, lamaralmp commented on guides/plugins/unofficial/vtex.pt.md
> +<!-- -->
```suggestion

<br>
```

2020-11-25 14:19 UTC, lamaralmp commented on guides/plugins/unofficial/vtex.pt.md
> +<!-- -->
Essa nota quebrou, sugiro usar a quebra de linha conforme suggestion
![image](https://user-images.githubusercontent.com/37806526/100239342-1009ec00-2f10-11eb-970d-24387ecc0fb8.png)

2020-12-01 16:39 UTC, pamalv7 requested changes

2020-12-01 16:39 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +### Configuração do meio de pagamento Mercado Pago
```suggestion
### Condição de pagamento Mercado Pago
```

2020-12-01 16:39 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +### Configuração do meio de pagamento Mercado Pago Pro
```suggestion
### Condição de pagamento Mercado Pago Pro
```

2020-12-01 16:39 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +**O comprador finalizará o pagamento no ambiente do Mercado Pago via formulário web modal** diretamente em sua loja.
```suggestion
**O comprador finalizará o pagamento no Mercado Pago via formulário web modal** diretamente em sua loja.
```

2020-12-01 16:39 UTC, pamalv7 commented on guides/plugins/unofficial/vtex.pt.md
> +### Configuração do meio de pagamento Mercado Pago Wallet
```suggestion
### Condição de pagamento Mercado Pago Wallet
```

2020-12-02 14:57 UTC, pamalv7 approved these changes

2020-12-02 19:52 UTC, merged