New NodeJS version
mercadopago/devsite-docs pull request #952
Opened 2020-12-03 14:50 UTC by NicholasPedroso

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-12-09 14:44 UTC, pamalv7 requested changes

2020-12-09 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.pt.md
> +### 7 de novembro
```suggestion
### 7 de dezembro
```

2020-12-09 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +- Add `statement_descriptor` option to Preferences
```suggestion
```

2020-12-09 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +- Credentials now can be set dynamically
```suggestion
```

2020-12-09 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +
```suggestion
```

2020-12-09 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +
```suggestion
```

2020-12-09 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +- Credentials now can be set dynamically
No está en los otros idiomas.

2020-12-09 14:44 UTC, pamalv7 commented on guides/resources/changelog/current-year.en.md
> +- Add `statement_descriptor` option to Preferences
No está en los otros idiomas.

2020-12-09 22:38 UTC, pamalv7 approved these changes

2020-12-10 13:27 UTC, elvisjhonataoliveira approved these changes

2020-12-10 21:50 UTC, merged