Add guide to MercadoPago JS V2
mercadopago/devsite-docs pull request #960
Opened 2020-12-09 17:24 UTC by NicholasPedroso

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-12-09 19:17 UTC, pamalv7 requested changes

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +Saiba como instalar a **nova versão beta do SDK MercadoPago.js para a integração da Checkout Transparente.**
```suggestion
Saiba como instalar a **nova versão beta do SDK MercadoPago.js para a integração da ----[mlb]---- Checkout Transparente ------------ ----[mla, mlm, mpe, mco, mlu, mlc]---- Checkout API ------------**.
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +
```suggestion
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +A nova versão **otimiza sua integração com a inclusão do uso da funcionalidade CardForm** que obtém e valida todos os dados necessários para realizar o pagamento sem ter que adicionar passos extras.
```suggestion
A nova versão **otimiza sua integração com a inclusão do uso da funcionalidade CardForm que obtém e valida todos os dados necessários** para realizar o pagamento sem ter que adicionar passos extras. 
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +No caso de não desejar utilizar a nova funcionalidade CardForm, você pode manter  os recursos básicos da versão antiga. Verifique a [referência técnica](https://github.com/mercadopago/sdk-js/) para s
```suggestion
No caso de não desejar utilizar a nova funcionalidade CardForm, você pode manter os recursos básicos da versão antiga. Verifique a [referência técnica](https://github.com/mercadopago/sdk-js/) para saber quais mudanças você precisa fazer e confira os novos nomes dos parâmetros.
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +<br>
```suggestion
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +
```suggestion
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +<br>
```suggestion
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +
```suggestion
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Configure as credenciais
```suggestion
### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Configure as credenciais
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +1. Inclui MercadoPago.js
```suggestion
### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Inclui MercadoPago.js
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Configura las credenciales
```suggestion
### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Configura las credenciales
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +Inicialize a biblioteca com a [Public Key](https://www.mercadopago.com.br/developers/panel/credentials) da conta que estiver integrando para que possamos identificá-la ao conectar com Mercado Pago.
```suggestion
Inicialize a biblioteca com a [Public Key](FAKER][CREDENTIALS][URL]) da conta que estiver integrando para que possamos identificá-la ao conectar com Mercado Pago.
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Atualize seu formulário de pagamento
```suggestion
### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Atualize seu formulário de pagamento
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +Agora, **você apenas deve inicializar nosso CardForm relacionando o ID de cada campo do formulário com os atributos correspondentes, e a biblioteca será responsável por preencher, obter e validar tod
```suggestion
Agora, **você apenas deve inicializar nosso CardForm relacionando o ID de cada campo do formulário com os atributos correspondentes, e a biblioteca será responsável por preencher, obter e validar todos os dados necessários no momento de confirmar o pagamento**.
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +
```suggestion
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +> Requisitos para integrar
```suggestion
----[mlb]----
> Integrar Checkout Transparente com cartão
------------
----[mla, mlm, mpe, mco, mlu, mlc]----
> Integrar Checkout API com cartão
------------
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +> Conheça todos os requisitos necessários para começar a integrar.
```suggestion
> Construa e configure sua própria experiência de pagamentos.
```

2020-12-09 19:17 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +> [Requisitos previos](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/previous-requirements/)
```suggestion
----[mlb]----
> [Integrar Checkout Transparente do Mercado Pago para cartão](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/receiving-payment-by-card/)
------------
----[mla, mlm, mpe, mco, mlu, mlc]----
> [Integrar Checkout API do Mercado Pago para cartão](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/online-payments/checkout-api/receiving-payment-by-card/)
------------
```

2020-12-09 20:03 UTC, pamalv7 requested changes

2020-12-09 20:03 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +> NOTE
```suggestion
> GIT
```

2020-12-09 20:03 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +> NOTE
```suggestion
> GIT
```

2020-12-09 20:03 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.en.md
> +> NOTE
```suggestion
> GIT
```

2020-12-09 21:24 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +Conoce cómo instalar la **nueva versión beta de la SDK MercadoPago.js para la integración de ----[mlb]---- Checkout Transparente ------------ ----[mla, mlm, mpe, mco, mlu, mlc]---- Checkout API -----
```suggestion
----[mlb]----
Conoce cómo instalar la **nueva versión beta de la SDK MercadoPago.js para la integración de Checkout Transparente**. 
------------ 
----[mla, mlm, mpe, mco, mlu, mlc]---- 
Conoce cómo instalar la **nueva versión beta de la SDK MercadoPago.js para la integración de Checkout API**. 
------------ 
```

2020-12-09 21:24 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +Saiba como instalar a **nova versão beta do SDK MercadoPago.js para a integração da ----[mlb]---- Checkout Transparente ------------ ----[mla, mlm, mpe, mco, mlu, mlc]---- Checkout API ------------**
```suggestion
----[mlb]----
Saiba como instalar a **nova versão beta do SDK MercadoPago.js para a integração da Checkout Transparente**.
------------ 
----[mla, mlm, mpe, mco, mlu, mlc]---- 
Saiba como instalar a **nova versão beta do SDK MercadoPago.js para a integração da Checkout API**.
------------ 
```

2020-12-09 22:36 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +Inicialize a biblioteca com a [Public Key](FAKER][CREDENTIALS][URL]) da conta que estiver integrando para que possamos identificá-la ao conectar com Mercado Pago.
```suggestion
Inicialize a biblioteca com a [Public Key]([FAKER][CREDENTIALS][URL]) da conta que estiver integrando para que possamos identificá-la ao conectar com Mercado Pago.
```

2020-12-09 22:39 UTC, pamalv7 approved these changes

2020-12-10 12:59 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.en.md
> +
```suggestion

<br>

```

2020-12-10 12:59 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +
```suggestion

<br>

```

2020-12-10 12:59 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +
```suggestion

<br>

```

2020-12-10 13:26 UTC, elvisjhonataoliveira approved these changes

2020-12-10 13:54 UTC, nicolassalvanes approved these changes

2020-12-10 13:54 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +Conoce cómo instalar la **nueva versión beta de la SDK MercadoPago.js para la integración de Checkout Transparente**.
Descartaron decir "Conoce cómo actualizar a la nueva versión..." ?

2020-12-10 13:54 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +Si no quieres utilizar la nueva funcionalidad CardForm, puedes mantener las características básicas de la versión antigua. Revisa las [referencias técnicas](https://github.com/mercadopago/sdk-js/) pa
CardForm al ser un término técnico y en inglés no lo querríamos resaltar como si fuese código? -> `CardForm`

2020-12-10 13:54 UTC, nicolassalvanes commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +> Encuentra información sobre los distintos atributos en la [referencia técnica](https://github.com/mercadopago/sdk-js).
@pamalv7 una pavada, pero seamos consistentes en poner las URL siempre con o sin / al final. Más arriba tenemos la misma URL con / al final.

Esto en general para todos los links (nuestros y externos). Voy a consultar a la gente de SEO si hay alguna preferencia sobre que opción elegir (yo prefiero sin) 😄

2020-12-10 14:08 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +Conoce cómo instalar la **nueva versión beta de la SDK MercadoPago.js para la integración de Checkout Transparente**.
Nunca lo planteamos creo 😂

2020-12-10 14:08 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +Si no quieres utilizar la nueva funcionalidad CardForm, puedes mantener las características básicas de la versión antigua. Revisa las [referencias técnicas](https://github.com/mercadopago/sdk-js/) pa
Es un buen punto. Creo que en este caso no aplica porque lo queremos traer más como nombre de funcionalidad, como "marca".

2020-12-10 14:08 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +> Encuentra información sobre los distintos atributos en la [referencia técnica](https://github.com/mercadopago/sdk-js).
Es una pavada importante. 
Bueno, vamos sin por el momento entonces. 

¡Gracias!

2020-12-10 14:08 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.es.md
> +Si no quieres utilizar la nueva funcionalidad CardForm, puedes mantener las características básicas de la versión antigua. Revisa las [referencias técnicas](https://github.com/mercadopago/sdk-js/) pa
```suggestion
Si no quieres utilizar la nueva funcionalidad CardForm, puedes mantener las características básicas de la versión antigua. Revisa las [referencias técnicas](https://github.com/mercadopago/sdk-js) para ver qué cambios necesitas hacer y conocer los nuevos nombres de los parámetros. 
```

2020-12-10 14:08 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.en.md
> +If you don't want to use the new CardForm feature, you can keep the basic characteristics of the previous version. Check the [technical reference](https://github.com/mercadopago/sdk-js/) to see what
```suggestion
If you don't want to use the new CardForm feature, you can keep the basic characteristics of the previous version. Check the [technical reference](https://github.com/mercadopago/sdk-js) to see what changes you need to make and to know the new names of the parameters.
```

2020-12-10 14:08 UTC, pamalv7 commented on guides/online-payments/checkout-api/guide-mercadopagojs-v2.pt.md
> +No caso de não desejar utilizar a nova funcionalidade CardForm, você pode manter os recursos básicos da versão antiga. Verifique a [referência técnica](https://github.com/mercadopago/sdk-js/) para sa
```suggestion
No caso de não desejar utilizar a nova funcionalidade CardForm, você pode manter os recursos básicos da versão antiga. Verifique a [referência técnica](https://github.com/mercadopago/sdk-js) para saber quais mudanças você precisa fazer e confira os novos nomes dos parâmetros.
```

2020-12-10 21:47 UTC, merged