feature/cambiosInstoreGenerales
mercadopago/devsite-docs pull request #976
Opened 2020-12-15 12:45 UTC by juanseferrari2

## Description
In few word, describe what’s your Pull Request about.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-12-21 15:35 UTC, lamaralmp commented on guides/in-person-payments/qr-code/introduction.pt.md
> +> Caso seu modelo não necessite de integração com sistema de ponto de venda, você pode consultar todas as informações disponíveis em [gerar QR do pagina web do Mercado Pago](https://www.mercadopago.c
```suggestion
> Caso seu modelo não necessite de integração com sistema de ponto de venda, você pode consultar todas as informações disponíveis em [geração de QR pelo painel do Mercado Pago](https://www.mercadopago.com.br/developers/pt/guides/in-person-payments/qr-code/integrations-front/).
```

2020-12-22 12:26 UTC, pamalv7 requested changes

2020-12-22 12:26 UTC, pamalv7 commented on guides/in-person-payments/qr-code/introduction.en.md
> +> If your model does not require integration with a point of sale system, you can consult all the information available in [generate QR from the Mercado Pago web page](https://www.mercadopago.com.ar/
```suggestion
> If your model does not require integration with a point of sale system, you can consult all the information available in [generate QR from the Mercado Pago panel](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/in-person-payments/qr-code/integrations-front).
```

2020-12-22 12:26 UTC, pamalv7 commented on guides/in-person-payments/qr-code/introduction.es.md
> +> Si tu modelo no requiere de una integración con un sistema de punto de venta,  puedes consultar toda la información disponible en [generar QR desde la página de Mercado Pago](https://www.mercadopag
```suggestion
> Si tu modelo no requiere de una integración con un sistema de punto de venta,  puedes consultar toda la información disponible en [generar QR desde el panel de Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/in-person-payments/qr-code/integrations-front). 
```

2020-12-22 12:26 UTC, pamalv7 commented on guides/in-person-payments/qr-code/introduction.pt.md
> +> Caso seu modelo não necessite de integração com sistema de ponto de venda, você pode consultar todas as informações disponíveis em [geração de QR pelo painel do Mercado Pago](https://www.mercadopag
```suggestion
> Caso seu modelo não necessite de integração com sistema de ponto de venda, você pode consultar todas as informações disponíveis em [geração de QR pelo painel do Mercado Pago](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/in-person-payments/qr-code/integrations-front).
```

2020-12-22 12:26 UTC, pamalv7 commented on guides/in-person-payments/qr-code/qr-attended-part-b.es.md
> +## Video explicativo
Quitar

2020-12-22 16:19 UTC, pamalv7 approved these changes

2020-12-22 17:48 UTC, merged