Feature/mprc 5646 released money
mercadopago/devsite-docs pull request #980
Opened 2020-12-18 20:53 UTC by ccamargov-meli

## Description
Dev-site implementation for new `release-report` for all sites and translations. Includes implementation of dynamic domains for urls, using [FAKER][URL][DOMAIN]

### Issue involved
- [MPRC-5737](https://mercadolibre.atlassian.net/browse/MPRC-5737)

### Checklist:
Before sending your contribution, please specify the following: 

- [ ] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

2020-12-21 18:55 UTC, pamalv7 requested changes

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.en.md
> +> LEFT_BUTTON_RECOMMENDED_ES
```suggestion
> LEFT_BUTTON_RECOMMENDED_EN
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.en.md
> +> [How to use this report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/how-to-use/)
```suggestion
> [How to use this report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/how-to-use/)
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.en.md
> +> RIGHT_BUTTON_REQUIRED_ES
```suggestion
> RIGHT_BUTTON_REQUIRED_EN
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.en.md
> +> [Generate your report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/generate/)
```suggestion
> [Generate your report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/generate/)
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.pt.md
> +> Como usar o relatório
¿Quedan diferentes?

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.en.md
> +> LEFT_BUTTON_RECOMMENDED_ES
```suggestion
> LEFT_BUTTON_RECOMMENDED_EN
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.en.md
> +> [How to use the report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/how-to-use/)
```suggestion
> [How to use the report](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/released-money/how-to-use/)
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.en.md
> +> RIGHT_BUTTON_REQUIRED_ES
```suggestion
> RIGHT_BUTTON_REQUIRED_EN
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.en.md
> +> [Generate your reports](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/release-money/generate/)
```suggestion
> [Generate your reports](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/en/guides/manage-account/reports/release-money/generate/)
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.es.md
> +Genera el reporte de ----[mla]---- liquidaciones ------------ ----[mlm, mlb, mlc, mco, mlu, mpe]---- liberaciones ------------ cada vez que necesites conciliar el detalle del dinero liberado entre do
```suggestion
Genera el reporte de ----[mla]---- Liquidaciones ------------ ----[mlm, mlb, mlc, mco, mlu, mpe]---- Liberaciones ------------ cada vez que necesites conciliar el detalle del dinero liberado entre dos fechas. Podrás saber cuándo se hizo cada transacción, en qué concepto y por qué monto, incluyendo los casos de bloqueo y desbloqueo. 
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.es.md
> +# ¿Qué es el Reporte de ----[mla]---- Liquidaciones ------------ ----[mlm, mlb, mlc, mco, mlu, mpe]---- Liberaciones ------------?
```suggestion
# ¿Qué es el reporte de ----[mla]---- Liquidaciones ------------ ----[mlm, mlb, mlc, mco, mlu, mpe]---- Liberaciones ------------?
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.pt.md
> +# O que é o Relatório de ----[mla]---- Liquidaçoes ------------ ----[mlm, mlb, mlc, mco, mlu, mpe]---- Liberações ------------?
```suggestion
# O que é o relatório de ----[mla]---- Liquidaçoes ------------ ----[mlm, mlb, mlc, mco, mlu, mpe]---- Liberações ------------?
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.pt.md
> +> LEFT_BUTTON_RECOMMENDED_ES
```suggestion
> LEFT_BUTTON_RECOMMENDED_PT
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.pt.md
> +> [Como usar o relatório](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/released-money/how-to-use/)
```suggestion
> [Como usar o relatório](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/manage-account/reports/released-money/how-to-use/)
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.pt.md
> +> RIGHT_BUTTON_REQUIRED_ES
```suggestion
> RIGHT_BUTTON_REQUIRED_PT
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.pt.md
> +> [Gere seus relatórios](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/es/guides/manage-account/reports/release-money/generate/)
```suggestion
> [Gere seus relatórios](https://www.mercadopago[FAKER][URL][DOMAIN]/developers/pt/guides/manage-account/reports/release-money/generate/)
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/how-to-use.pt.md
> +### Próximos passos
```suggestion
---

### Próximos passos
```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/generate.es.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/generate.en.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/generate.pt.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.en.md
> +
```suggestion
---

### Next steps

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.pt.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/glossary.es.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/how-to-use.en.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/how-to-use.es.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/how-to-use.pt.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.en.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.es.md
> +
```suggestion
---

```

2020-12-21 18:55 UTC, pamalv7 commented on guides/manage-account/reports/released-money/introduction.pt.md
> +
```suggestion
---

```

2020-12-21 20:37 UTC, ccamargov-meli commented on guides/manage-account/reports/released-money/generate.en.md
> +| Currency | <br/> Local (basada en el país donde esté registrada la cuenta de Mercado Pagobased on the country where the Mercado Pago account is registered) <br/> <br/> |
Está en inglés y en español, procedo a eliminar la parte en español.

2020-12-21 21:39 UTC, ccamargov-meli reviewed
Done.

2020-12-22 18:41 UTC, pamalv7 approved these changes

2020-12-22 18:46 UTC, merged